### ISSUE TITLE
DateTime function bug in Chrome with some locales

### ISSUE THREAD

**Issue by RollingTL** [intlify/vue-i18n-next#1002]
### Reporting a bug?

#d function returns wrong date representation for certain locales in Chrome. Firefox and Safari work properly.

$d function should return:
**2022 ж. 5 мамыр, бейсенбі**
instead of:
**Thursday, May 5, 2022**
for locale **kk**. 

Other minor languages behave inconsistently too, f.e. az. 

### **Chrome**
<img width="646" alt="Screen Shot 2022-05-05 at 13 36 30" src="https://user-images.githubusercontent.com/16714526/166881149-fc3f1f33-96dd-42fd-baf8-b33aceb816b8.png">

### Expected behavior

$d function should return:
2022 ж. 5 мамыр, бейсенбі
for locale kk. Other minor languages behave inconsistently too, f.e. az. 

### **Safari**
<img width="646" alt="Screen Shot 2022-05-05 at 13 37 11" src="https://user-images.githubusercontent.com/16714526/166880992-0e3885d6-0572-4c53-944d-965ccbe8fbd7.png">

or

### **FireFox**
<img width="646" alt="Screen Shot 2022-05-05 at 13 36 47" src="https://user-images.githubusercontent.com/16714526/166881109-ad97dae2-c733-4352-98c6-5ecc85065317.png">

### Reproduction

https://codesandbox.io/s/vue-i18n-9-dates-espu09?file=/index.html

`<div class="mark">{{ $d(new Date(), 'long', 'az') }}</div>`

### System Info

```shell
MacOS Big Sur. 
SandBox, i18n Vue template
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/intlify/vue-i18n-next/blob/master/.github/CONTRIBUTING.md)
- [X] Read the [Documentation](https://vue-i18n.intlify.dev/)
- [X] Check that there isn't [already an issue](https://github.com/intlify/vue-i18n-next/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/intlify/vue-i18n-next/discussions)
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by kazupon** [comment]
Thank you for your reporting!
Could you confirm the vanilla JavaScript using `Intl.DateTimeForamt`, please?
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DateTimeFormat

if you will get the same issue, it is chrome issue.
