### ISSUE TITLE
Option allowComposition does not work as expected

### ISSUE THREAD

**Issue by kuba108** [intlify/vue-i18n-next#1013]
### Reporting a bug?

When using option allowComposition: true, still can't get translations in setup().
I use legacy: true (because App is not fully migrated to composition API).
All code is in SFC component

```
import { useI18n } from 'vue-i18n'

setup() {
    const { t } = useI18n()
    console.log(t('cart'))

    useHead({
      title: t('cart'),
    })
},

<i18n>
{
  "cs": {
    "cart": "Nákupní košík",
  }
}
</i18n>
```

**localization.js file**

```
import { createI18n } from 'vue-i18n/index'

// import i18n resources
import translations from '../locales/translations.json'

const lang = process.env.VUE_APP_LOCALE

export const i18n = createI18n({
  locale: lang,
  allowComposition: true,
  messages: {
    [lang]: translations,
  },
})
```

Thanks for help or direction.

### Expected behavior

I would expect that switching on the option allowComposition, it should load local messages from `<i18n>` even with legacy: true mode. I cannot migrate all files in whole app at once, too dangerous.

This works fine:
`<h1 class="h2 mb-3 mb-sm-4 mb-md-5 mb-lg-6">{{ $t('cart') }}</h1>`

### Reproduction

When more info needed, I will create public repo with new app. 

### System Info

```shell
System:
    OS: macOS 12.3.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 442.30 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 17.9.0 - /opt/homebrew/bin/node
    Yarn: 1.22.18 - /opt/homebrew/bin/yarn
    npm: 8.5.5 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 101.0.4951.64
    Chrome Canary: 102.0.5005.0
    Firefox: 99.0.1
    Safari: 15.4
  npmPackages:
    @intlify/core-base: ^9.1.7 => 9.1.7
    @intlify/vue-i18n-loader: ^4.2.0 => 4.2.0
    @vue/cli-plugin-babel: ^5.0.0-beta.3 => 5.0.0-beta.3
    @vue/cli-plugin-eslint: ^5.0.0-beta.4 => 5.0.0-beta.4
    @vue/cli-service: ^5.0.0-beta.3 => 5.0.0-beta.3
    @vue/compiler-sfc: ^3.2.6 => 3.2.6
    @vue/test-utils: ^2.0.0-rc.17 => 2.0.0-rc.17
    @vue/vue3-jest: ^27.0.0-alpha.4 => 27.0.0-alpha.4
    vue: ^3.2.31 => 3.2.31
    vue-cli-plugin-sitemap: ^2.3.0 => 2.3.0
    vue-cli-plugin-svg: ^0.2.1 => 0.2.1
    vue-eslint-parser: ^7.11.0 => 7.11.0
    vue-facebook-login-component-next: ^1.0.4 => 1.0.4
    vue-i18n: ^9.1.10 => 9.1.10
    vue-inline-svg: ^3.0.0-beta.3 => 3.0.0-beta.3
    vue-loader: ^17.0.0 => 17.0.0
    vue-loading-overlay: ^4.0 => 4.0.4
    vue-qrcode: ^1.0.0 => 1.0.0
    vue-router: ^4.0.11 => 4.0.11
    vue-svg-sprite: ^2.2.0 => 2.2.0
    vue3-google-map: ^0.8.2 => 0.8.2
    vuex: ^4.0.2 => 4.0.2
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/intlify/vue-i18n-next/blob/master/.github/CONTRIBUTING.md)
- [X] Read the [Documentation](https://vue-i18n.intlify.dev/)
- [X] Check that there isn't [already an issue](https://github.com/intlify/vue-i18n-next/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/intlify/vue-i18n-next/discussions)
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by kazupon** [comment]
Thank you for your reporting!

`allowComposiyion` options is supported at `v9.2.0-beta.31`
https://github.com/intlify/vue-i18n-next/releases/tag/v9.2.0-beta.31

You need to use the v9.2 beta version

Thanks!
