### ISSUE TITLE
Doesn't work under the Suspense component

### ISSUE THREAD

**Issue by SunnyCrypto** [intlify/vue-i18n-next#1018]
### Reporting a bug?

<img width="886" alt="image" src="https://user-images.githubusercontent.com/59635374/171189507-60315f6d-ccb5-4005-aa8e-dea977ef097f.png">

```bash
Uncaught (in promise) TypeError: Cannot set properties of null (setting '__VUE_I18N__')
```

### Expected behavior

Should work under the `Suspense` component

### Reproduction

App.vue

```vue
<template>
  <Suspense>
    <!-- component with nested async dependencies -->
    <router-view />
    <!-- loading state via #fallback slot -->
    <template #fallback>
      Loading...
    </template>
  </Suspense>
</template>
```

The error disappears after removing the `Suspense` component

```vue
<template>
   <router-view />
</template>
```

### System Info

```shell
System:
    OS: macOS 10.15.7
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 53.09 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 16.8.0 - /usr/local/bin/node
    Yarn: 1.22.17 - ~/.yarn/bin/yarn
    npm: 7.21.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 102.0.5005.61
    Edge: 101.0.1210.53
    Firefox: 100.0.2
    Safari: 15.5
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/intlify/vue-i18n-next/blob/master/.github/CONTRIBUTING.md)
- [X] Read the [Documentation](https://vue-i18n.intlify.dev/)
- [X] Check that there isn't [already an issue](https://github.com/intlify/vue-i18n-next/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/intlify/vue-i18n-next/discussions)
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by kazupon** [comment]
Thank you for your reporting!

I've tried to reproduce using your reporting codes.
However, I could not reproduce it.

Could you give us minimum reproduction codes, please?
