### ISSUE TITLE
Locale change only changes language in sibling components, not parent components.

### ISSUE THREAD

**Issue by LouisVA** [intlify/vue-i18n-next#1019]
### Reporting a bug?

Hi,

In short:
Changing the language in a component changes the language in sibling components but not in any other component.

My setup is an Express backend with a Vue 3 front-end where I am using Composition API + SFC + vite. I am using `vue-i18-next` and `vite-plugin-vue-i18n` which adds <i18n> custom blocks for local translations in SFC.

So some configuration:
in vite.config.js:
```
return defineConfig({
        plugins: [
            vue(),
            vueI18n({
                // if you want to use Vue I18n Legacy API, you need to set `compositionOnly: false`
                // compositionOnly: false,
                defaultSFCLang: "json",
                include: [
                    path.resolve(__dirname, "./src/locales/en.json"),
                    path.resolve(__dirname, "./src/locales/nl.json"),
                    path.resolve(__dirname, "./src/locales/de.json"),
                ],
            }),
        ]
```

in main.js

```

import App from "./App.vue";

import en from "./locales/en.json";
import nl from "./locales/nl.json";
import de from "./locales/de.json";

const i18n = createI18n({
    legacy: false, // necessary for the composition API
    locale: "de", // set locale
    fallbackLocale: "en", // set fallback locale
    availableLocales: ["en", "nl", "de"],
    messages: {
        en: en,
        nl: nl,
        de: de,
    },
    globalInjection: true,
});

const app = createApp(App);
// I've also tried what is in the guide, but doesn't change anything for me:
// const app = Vue.createApp(App,{
//     setup() {
//       const { t } = VueI18n.useI18n() // call `useI18n`, and spread `t` from  `useI18n` returning
//       return { t } // return render context that included `t`
//     }
//   })


app.use(i18n);
app.mount("#app");

```

Basically in every component I am using translations from en.json/nl.json/de.json and LOCAL translations. Like custom block translations from the `vite-plugin-vue-i18n` library. That means every component has this:

```
<template>
<div class="field col-12">
    <div class="text-2xl font-bold">{{ t("title") }}</div>
</div>
</template>

<script setup>
import { useI18n } from "vue-i18n";
const { t } = useI18n({ usescope: "local" });
</script>

<i18n lang="json">
{
    "en": { "title": "foo bar"},
    "nl": {"title": "foo bar"},
    "de": {"title": "foo bar"}
}
</i18n>
```

So, because I am using this custom block `<i18n>` in combination with translations from en/de/nl.json, I need to import the t function from use `useI18n` because if I use the `$i18n.t` then only translations from en/de/nl.json work (part of the global scope) and the ones in `<i18n>` are ignored.

So far this works. However when I do a locale change, I have issues that I can't solve.

There are two ways to change the locale, but none actually change the language EVERYWHERE.

OPTION 1 (only local scope)
(Dropdown html event is a PrimeVue element)

```
<template>
  <Dropdown
        v-model="locale"
        :options="availableLocales.map((locale) => ({ code: locale, name: languages[locale] }))"
        optionLabel="name"
        optionValue="code"
    />
  </template>
  
<script setup>
import { useI18n } from "vue-i18n";
const { t, locale, availableLocales } = useI18n({ useScope: "local" });

const languages = { nl: "Nederlands", en: "English", de: "Deutsch" };
</script>
```
This will only change the language in this component as expected.

OPTION 2 (using $i18n from globalInjection)
```
<template>
  <Dropdown
        v-model="$i18n.locale"
         :options="$i18n.availableLocales.map((locale) => ({ code: locale, name: languages[locale] }))"
        optionLabel="name"
        optionValue="code"
    />
  </template>
  
<script setup>
import { useI18n } from "vue-i18n";
const { t, } = useI18n({ usescope: "local" });

const languages = { nl: "Nederlands", en: "English", de: "Deutsch" };
</script>
```
With this way, when I change the language, the language of this component changes and the language of SIBLING components change. But all the other components including even the parent component do not change??? It is very weird.

When I try v-model="$root.$i18n.locale" then the exact same happens.

The structure of the app is 
app
---> mainView.vue
------>userSettingsModal.vue
--------->userProfileTab.vue        <- contains the language switch
--------->userOtherTab.vue
--------->userOther2Tab.vue
------>adminSettingsModal.vue
--------->Admin1Tab.vue   
--------->Admin2Tab.vue
--------->Admin3Tab.vue
------>routerView

Basically changing the language in userProfileTab.vue changes the language in userProfileTab.vue/userOtherTab.vue/userOther2Tab.vue and also Admin1Tab/Admin2Tab/Admin3Tab but not in userSettingsModal.vue, adminSettingsModal.vue (which contain headers with localization text for the Tabs) , mainView.vue and routerView

I can also verify that in the components where the language does NOT change, I am using both en.json/de.json/nl.json as `<i18n>` translations. Both are not updated according to the locale change.

Anyone help me with this maze of a configuration. The documentation is confusing to me as there's a section on SFC, a section on Composition API and then there is the `vite-plugin-vue-i18n` plugin with it's custom blocks.

You might ask why I want en.json/nl.json/de.json and the `<i18n>`. Basically the files contain shares translations, the custom blocks contain messages specific to the component. I know there's a sharedMessages possibility too, I have not tried it though. I do feel there's more issues with this setup than I am aware of currently.

### Expected behavior

The locale should be updated everywhere in the app

### Reproduction

See in reporting bug

### System Info

```shell
System:
    OS: Windows 10 10.0.19044
    CPU: (12) x64 AMD Ryzen 5 5500U with Radeon Graphics
    Memory: 474.18 MB / 7.35 GB
  Binaries:
    Node: 16.13.1 - C:\Program Files\nodejs\node.EXE
    npm: 8.1.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (101.0.1210.53)
    Internet Explorer: 11.0.19041.1566
```

### Additional context

"dependencies": {
                "axios": "^0.27.2",
                "pinia": "^2.0.14",
                "primeflex": "^3.2.0",
                "primeicons": "^5.0.0",
                "primevue": "^3.12.6",
                "vue": "^3.2.25",
                "vue-i18n": "^9.1.10",
                "vue-router": "^4.0.15"
            },
            "devDependencies": {
                "@intlify/vite-plugin-vue-i18n": "^3.4.0",
                "@rushstack/eslint-patch": "^1.1.0",
                "@vitejs/plugin-vue": "^2.3.3",
                "@vue/eslint-config-prettier": "^7.0.0",
                "eslint-plugin-vue": "^8.2.0",
                "sass": "^1.50.0",
                "sass-loader": "^10.2.1",
                "vite": "^2.9.9"
            }

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/intlify/vue-i18n-next/blob/master/.github/CONTRIBUTING.md)
- [X] Read the [Documentation](https://vue-i18n.intlify.dev/)
- [X] Check that there isn't [already an issue](https://github.com/intlify/vue-i18n-next/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/intlify/vue-i18n-next/discussions)
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by kazupon** [comment]
close, so to comment at github discussion
https://github.com/intlify/vue-i18n-next/discussions/1016#discussioncomment-2862299
