### ISSUE TITLE
$t get global scope translation when using vue-i18n-bridge in a local scope component

### ISSUE THREAD

**Issue by LasyIsLazy** [intlify/vue-i18n-next#1038]
### Reporting a bug?

vue-i18n info:
- version 8.x
- composition mode
- vue-i18n-bridge

I have set `messages` in `i18n` component options, but `$t()` in template get a global translation.

### Expected behavior

In `vue-i18n@9.x`, using `$t()` in components with local scope will get a local translation.

### Reproduction

https://codesandbox.io/embed/vue-2-playground-forked-xh9c4v?fontsize=14&hidenavigation=1&theme=dark

### System Info

```shell
System:
    OS: macOS 12.4
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 1.59 GB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 14.16.1 - ~/.nvm/versions/node/v14.16.1/bin/node
    npm: 8.5.5 - ~/.nvm/versions/node/v14.16.1/bin/npm
  Browsers:
    Chrome: 102.0.5005.115
    Chrome Canary: 105.0.5137.0
    Firefox: 86.0.1
    Safari: 15.5
  npmPackages:
    @vue/cli-plugin-babel: ~4.5.13 => 4.5.17 
    @vue/cli-plugin-typescript: ~4.5.13 => 4.5.17 
    @vue/cli-service: ~4.5.13 => 4.5.17 
    @vue/composition-api: ^1.4.9 => 1.4.9 
    vue: ^2.6.11 => 2.6.14 
    vue-class-component: ^7.2.3 => 7.2.6 
    vue-i18n: 8.26.7 => 8.26.7 
    vue-i18n-bridge: ^9.2.0-beta.34 => 9.2.0-beta.34 
    vue-property-decorator: ^9.1.2 => 9.1.2 
    vue-template-compiler: ^2.6.11 => 2.6.14
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/intlify/vue-i18n-next/blob/master/.github/CONTRIBUTING.md)
- [X] Read the [Documentation](https://vue-i18n.intlify.dev/)
- [X] Check that there isn't [already an issue](https://github.com/intlify/vue-i18n-next/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/intlify/vue-i18n-next/discussions)
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by kazupon** [comment]
Thank you for your reporting!

[As commented by docs]([12de54f](https://github.com/intlify/vue-i18n-next/commit/12de54f846193e9b45beb0d769857d647569c439)), This is limitation.
`$t` is global scope, when we use the Composition API mode in vue-i18n-bridge

You can workaround with `useI18n` with `useScope: 'local'` and `messages` option in component:

```vue
<template>
  <div class="hello">
    <h2>Component</h2>
    {{ $i18n.locale }} {{ t("message.hello") }}
  </div>
</template>

<script lang="ts">
import { defineComponent } from "@vue/composition-api";
import { useI18n } from "vue-i18n-bridge";
export default defineComponent({
  setup() {
    const { t } = useI18n({
      inheritLocale: true,
      useScope: 'local',
      messages: {
        en: {
          message: {
            hello: "local, en",
          },
        },
        ja: {
          message: {
            hello: "local ja",
          },
        },
      },
    };
    return { t };
  },
});
</script>
```

Thanks!
