### ISSUE TITLE
[Feature Request] make vue-i18n-bridge support Vue 2.7

### ISSUE THREAD

**Issue by kingyue737** [intlify/vue-i18n-next#1052]
### Clear and concise description of the problem

I'm trying to migrate my project to Vue 2.7. It works like a charm for me, using Vue 2.6 + `vue-i18n-bridge` + `unplugin-vue-i18n`. But after I upgrade to Vue2.7, the following error is thrown in components with i18n custom block: 
```
Cannot read properties of undefined (reading '__i18n')
```
Reproduction:
https://stackblitz.com/edit/vitejs-vite-elfdtq

### Suggested solution

Maybe depends on `vue-demi` instead of `@vue/composition-api` to support both Vue 2.6 and 2.7?

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/intlify/vue-i18n-next/blob/master/.github/CONTRIBUTING.md)
- [X] Read the [Documentation](https://vue-i18n.intlify.dev/)
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by kazupon** [comment]
Vue 2.7 custom block handling process is almost same Vue 3 with `@vitejs/plugin-vue2`, so you don’t need configure `bridge: true` in `@intlify/unplugin-vue-i18n`

Thanks!

**Comment by kingyue737** [comment]
@kazupon I've tried before. It throws different errors if I remove `bridge:true` in plugin:

```
"TypeError: Cannot read properties of undefined (reading 'beforeMount')"
```

```
"TypeError: Cannot read properties of undefined (reading 't')"
```
