### ISSUE TITLE
Cannot parse message with multiple parameters with only space in between

### ISSUE THREAD

**Issue by gogoscrum** [intlify/vue-i18n-next#1055]
### Reporting a bug?

When formatting a message has multiple parameters like this "%{nickname} %{action} issue %{code}", it will cause the browser stopped response. If I add some letter between the parameters, or remove the space between the parameters, then it will work. 

### Expected behavior

It should work, as my code used to work fine in Vue2. I just upgrade to Vue3 and this piece of code was broken now.

### Reproduction

This should be a problem of vue-i18n

### System Info

```shell
"vue-i18n": "^9.1.10", "vue": "^3.2.37"
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/intlify/vue-i18n-next/blob/master/.github/CONTRIBUTING.md)
- [X] Read the [Documentation](https://vue-i18n.intlify.dev/)
- [X] Check that there isn't [already an issue](https://github.com/intlify/vue-i18n-next/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/intlify/vue-i18n-next/discussions)
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by xfq** [comment]
I have the same issue. You can change `locale` from `ja` to `en` in https://codepen.io/xfq/pen/RwMRYPy to see the issue.
