### ISSUE TITLE
Interpolations in production mode does not work

### ISSUE THREAD

**Issue by gewisser** [intlify/vue-i18n-next#1059]
### Reporting a bug?

In dev mode, interpolation works as expected. Interpolation does not work in production mode.

**In dev mode:**
![image](https://user-images.githubusercontent.com/5417292/178742718-d3061808-a3e6-4374-bf3a-e9d262ce94c9.png)

**In prod mode:**

![image](https://user-images.githubusercontent.com/5417292/178743228-bf434a87-78a5-4147-8c40-e578f47863bb.png)

**translate:**

![image](https://user-images.githubusercontent.com/5417292/178743633-a624297c-7158-4e29-9c54-4f91d9ca8f57.png)

**template:**

![image](https://user-images.githubusercontent.com/5417292/178743918-0db1b615-5bc5-4252-857a-01d0c8cbb8c5.png)

### Expected behavior

In production, interpolation works the same way as in dev mode.
![image](https://user-images.githubusercontent.com/5417292/178742718-d3061808-a3e6-4374-bf3a-e9d262ce94c9.png)

### Reproduction

Create a quasar project with vue-i18n integration enabled. Install the latest version of vue-i18n `(9.2.0-beta.37)`. Create a translation with named interpolation and build the project `quasar build`

### System Info

```shell
System:
    OS: Windows 10 10.0.19044
    CPU: (12) x64 Intel(R) Xeon(R) CPU E5-2678 v3 @ 2.50GHz
    Memory: 42.90 GB / 63.84 GB
  Binaries:
    Node: 16.14.2 - C:\Program Files\nodejs\node.EXE
    npm: 8.9.0 - ~\AppData\Roaming\npm\npm.CMD
  Browsers:
    Chrome: 103.0.5060.114
    Edge: Spartan (44.19041.1266.0), Chromium (103.0.1264.49)
    Internet Explorer: 11.0.19041.1566
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/intlify/vue-i18n-next/blob/master/.github/CONTRIBUTING.md)
- [X] Read the [Documentation](https://vue-i18n.intlify.dev/)
- [X] Check that there isn't [already an issue](https://github.com/intlify/vue-i18n-next/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/intlify/vue-i18n-next/discussions)
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

quasarframework/quasar#13951

**Comment by gewisser** [comment]
Need to add: `runtimeOnly: false`


```javascript
      vitePlugins: [
        [
          "@intlify/vite-plugin-vue-i18n",
          {
            // if you want to use Vue I18n Legacy API, you need to set `compositionOnly: false`
            // compositionOnly: false,

            runtimeOnly: false,
            // you need to set i18n resource including paths !
            include: path.resolve(__dirname, "./src/i18n/**"),
          },
        ],
      ],
```

**Comment by tofi86** [comment]
We had the same issue and I can confirm that @gewisser's solution works.

Even better with `runtimeOnly: ctx.dev` as noted by @gewisser in https://github.com/quasarframework/quasar/issues/13951

**Comment by klastarnstrom** [comment]
It is true that `runtimeOnly: false` can solve this problem. However, we are forced to be CSP-compliant and while it solves the problem with interpolation, it violates CSP. 

Is there another way to solve this and remaining CSP compliant?

**Comment by 13uraksahin** [comment]
I should not be forced to compromise on runtimeOnly and I also need to stay CSP compliant as mentioned above. and if I am not wrong there is still no fix with the beta updates up to 9.3.0.beta-17. So, I think this should be opened and fixed again @kazupon.

**Comment by nicooprat** [comment]
Seems to work without CSP violations when setting `allowDynamic: false`:

```js
VueI18nPlugin({
  allowDynamic: false, // Prevents CSP violation with `new Function`
  runtimeOnly: false, // Keeps translations interpolation
}),
```

Of course we lose the ability to have functions as translations but we don't use them fortunately.

This is a workaround but an official solution would still be better...

**Comment by nicooprat** [comment]
We couldn't find any working workaround, so we had to revert our whole migration to `vue-i18n-bridge`. @kazupon I saw you just reopened the issue, any idea if this is something expected to be fixed?

PS. the special `@` character was another deal breaker even if we found an acceptable workaround with some performances penalties; It would be great to be able to "choose" new features because we were pretty happy with v8 but are forced to migrate to v9 to update to Vue 3.

Anyway, thanks for your work ;)

**Comment by benlind** [comment]
I was able to solve this (getting translation interpolations without having to add "unsafe-eval" to my CSP) thanks to [kazupon's comment](https://github.com/intlify/vue-i18n-next/issues/1457#issuecomment-1627764486) in #1457:

1. Upgrade to `"vue-i18n": "9.3.0-beta.24",`
2. Upgrade to `"@intlify/unplugin-vue-i18n": "^0.12.2",`
3. Pass `jitCompilation: true` in my vite.config.ts:

```ts
    vueI18nPlugin({
      // This is necessary in order to use i18n parameter interpolation without
      // having to put "unsafe-eval" in our CSP:
      // https://github.com/intlify/vue-i18n-next/issues/1457
      jitCompilation: true,
    }),
```

**Comment by nicooprat** [comment]
For the record, the `@intlify/unplugin-vue-i18n` plugin is **not required** (we dynamically serve translations through an API for instance), you can also add define: { __INTLIFY_JIT_COMPILATION__: true } in vite.config.ts.

**Comment by codersjj** [comment]
> I was able to solve this (getting translation interpolations without having to add "unsafe-eval" to my CSP) thanks to [kazupon's comment](https://github.com/intlify/vue-i18n-next/issues/1457#issuecomment-1627764486) in #1457:
> 
> 1. Upgrade to `"vue-i18n": "9.3.0-beta.24",`
> 2. Upgrade to `"@intlify/unplugin-vue-i18n": "^0.12.2",`
> 3. Pass `jitCompilation: true` in my vite.config.ts:
> 
> ```ts
>     vueI18nPlugin({
>       // This is necessary in order to use i18n parameter interpolation without
>       // having to put "unsafe-eval" in our CSP:
>       // https://github.com/intlify/vue-i18n-next/issues/1457
>       jitCompilation: true,
>     }),
> ```

Thank you for @benlind's solution.
Now we can upgrade `@intlify/unplugin-vue-i18n` to v3+. In this version, the `jitCompilation` option defaults to `true`.
See: https://github.com/intlify/bundle-tools/tree/main/packages/unplugin-vue-i18n#jitcompilation

**Comment by kazupon** [comment]
close by jitCompilation

**Comment by chrissyast** [comment]
> I was able to solve this (getting translation interpolations without having to add "unsafe-eval" to my CSP) thanks to [kazupon's comment](https://github.com/intlify/vue-i18n-next/issues/1457#issuecomment-1627764486) in #1457:

> 3. Pass `jitCompilation: true` in my vite.config.ts:
> 
> ```ts
>     vueI18nPlugin({
>       // This is necessary in order to use i18n parameter interpolation without
>       // having to put "unsafe-eval" in our CSP:
>       // https://github.com/intlify/vue-i18n-next/issues/1457
>       jitCompilation: true,
>     }),
> ```

Is there an equivalent to this config using Quasar?

**Comment by chrissyast** [comment]
> Is there an equivalent to this config using Quasar?
Managed to achieve this by doing the following...
```
//quasar.config.js
       
      build: {
            rawDefine: {
                __INTLIFY_JIT_COMPILATION__ : true
            }
      }
```
