### ISSUE TITLE
Random "SyntaxError: Must be called at the top of a `setup` function" message while navigating back through pages

### ISSUE THREAD

**Issue by NathanAP** [intlify/vue-i18n-next#1063]
### Reporting a bug?

Hi!

I'm developing an application, but sometimes I get this error while navigating back to a page:

![Screenshot_3](https://user-images.githubusercontent.com/12821171/179310156-c1ad6885-1384-402b-9a43-a27dbc7a625c.png)

as you can see, it says that my i18n is being called outside `setup` which is not true:

![Screenshot_2](https://user-images.githubusercontent.com/12821171/179310188-cdda4b40-873e-43f9-81ee-b3d3e152619e.png)

Actually this is a bit strange because it is not happening in every single attempt, it seems to be something when I'm using the navigator back arrow 🤔

Maybe I'm doing something wrong when calling my `useI18n({ useScope: 'global' })`?

### Expected behavior

No errors when navigating back through pages.

### Reproduction

Let me know if I need to provide more info :)

### System Info

```shell
System:
    OS: Windows 10 10.0.19044
    CPU: (8) x64 Intel(R) Core(TM) i7-9700KF CPU @ 3.60GHz
    Memory: 6.49 GB / 15.92 GB
  Binaries:
    Node: 16.14.0 - C:\Program Files\nodejs\node.EXE
    npm: 8.13.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 103.0.5060.114
    Edge: Spartan (44.19041.1266.0), Chromium (103.0.1264.49)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    @intlify/vite-plugin-vue-i18n: ^3.4.0 => 3.4.0
    @vitejs/plugin-vue: ^2.3.0 => 2.3.3
    vite: ^2.9.0 => 2.9.14
    vue: ^3.2.33 => 3.2.37
    vue-axios: ^3.4.1 => 3.4.1
    vue-cli-plugin-vuetify: ~2.4.8 => 2.4.8
    vue-i18n: ^9.1.9 => 9.1.10
    vue-router: ^4.0.14 => 4.1.2
    vuetify: ^3.0.0-beta.0 => 3.0.0-beta.5
    vuetify-loader: ^2.0.0-alpha.0 => 2.0.0-alpha.9
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/intlify/vue-i18n-next/blob/master/.github/CONTRIBUTING.md)
- [X] Read the [Documentation](https://vue-i18n.intlify.dev/)
- [X] Check that there isn't [already an issue](https://github.com/intlify/vue-i18n-next/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/intlify/vue-i18n-next/discussions)
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by jvrsolis** [comment]
same i am getting the error in a watch function that is within a composable that is used within a base layout setup script

**Comment by kazupon** [comment]
Thank you for your reporting!

Unfortunately, We could not reproduce this issue. 😞 
We need minimum reproduction codes to resolve this issue.
Could you give it to us, please? 🙏

**Comment by NathanAP** [comment]
> Thank you for your reporting!
> 
> Unfortunately, We could not reproduce this issue. 😞 We need minimum reproduction codes to resolve this issue. Could you give it to us, please? 🙏

TBH it is a really really random error 😥 Last Friday I got it like 3 times in a row, but this week I could no reproduce it anymore. I did updated my packages this week so maybe it got fixed? I believe @jvrsolis could compare his versions with mine or add more of his info to help us?

**Comment by jvrsolis** [comment]
Ok i was able to solve it by using using
```
  const { availableLocales, locale: currentLocale, t, messages: currentMessages } = useI18n({ useScope: 'global'});
```

at the top of a composable rather than 
```
  const { t } = useI18n();
```
or other similar statements in a watch in the same composable. I would get the error when the watch was triggered after a reload.

**Comment by jooy2** [comment]
+1 I have the same symptoms.

Unfortunately, I haven't been able to pinpoint exactly where this is happening.
Neither the above solution nor the package update solved it.

**Here is my sample project:**
https://github.com/jooy2/vutron

It is a combination of `Electronjs`+`vue` and uses `Vue3` and composition api+esm. In the case of Vue, I configured it through `<script setup>`.

Open the file `src/renderer/components/screen/MainScreen.vue`,
1. Uncomment all commented lines
2. Delete disabled button properties with label: `menu.change-language`
3. Run the app: `npm run dev`

I hope I can get any hints. Thank you.

**Comment by NathanAP** [comment]
Is there any chance this is just occuring in dev?

I don't remember getting this error frequently as before anymore, but I remember that I got into it once last week. Maybe its some situation like going back to a page before it loads? Or maybe <Suspense> is having some impact? Maybe something with Vuetify?

**Comment by HipyCas** [comment]
I am having the same issue in a Ionic project with Vue 3. It worked the last time I used the code, but for some reason now it stopped working and I can't guess why :cry:

**Comment by kazupon** [comment]
close in-activity

**Comment by 6XGate** [comment]
I just encountered this issue in the setup function of a component. It happens due to getting `null` with `getCurrentInstance()`. For me it was related to upgrading `vue-demi` to `0.14.0`. This seemed to have caused some version inconsistency between all packages using `vue-demi` including `vue-i18n-bridge`. It even broke dependencies not reliant on `vue-demi`, such as Vuetify.

If you encounter this issue and have `vue-demi` as a direct dependency (or devDependency), try moving back to `0.13`.

**Comment by nikneym** [comment]
Issue persists, I've also tried the following:
```ts
const { t } = useI18n({ useScope: "global" });
```

**Comment by aasen** [comment]
I get this error when using i18n within a pinia store.

**Comment by wcheek** [comment]
Same here. Can't use the `useI18n` composable in a pinia store without `SyntaxError`.

**Comment by TimurNazarov** [comment]
Following worked for me..
1. Wherever you create a i18n instance - export it afterwards(if not already)
2. import it to your pinia store
3. You can use it as i18n.global.t

**Comment by bmm54** [comment]
I'am Having the same issue here when using vue-i18n inside ts files

i was able to fix it temporally

> main.ts

`const i18n = createI18n({
  legacy: false,
  locale: storedLang || 'en',
  fallbackLocale: 'en',
  messages: {
    en,
    fr,
    ar
  },
})

export default i18n;` 

> in the designated file

`import i18n from '@/main'
`
`i18n.global.t('auth.phoneNumberExists')`

**Comment by posti85** [comment]
> in the designated file
> 
> ```
> import i18n from '@/main' 
> 
> i18n.global.t('keywrodHere')
> ```

The code runs, but TypeScript returns an error: `This expression is not callable.
  Each member of the union type 'ComposerTranslation<LocaleMessages<VueMessageType>...`  :/
