### ISSUE TITLE
unable to load messages with error  Type 'Record<string, LocaleMessageDictionary<string>>' is not assignable to type 'Record<string, LocaleMessageDictionary<VueMessageType>>'.

### ISSUE THREAD

**Issue by dev-kr2020** [intlify/vue-i18n-next#108]
code 
*******
import { createI18n, LocaleMessages } from 'vue-i18n'

function loadLocaleMessages (): LocaleMessages {
  const locales = require.context('./locales', true, /[A-Za-z0-9-_,\s]+\.json$/i)
  const messages: LocaleMessages = {}
  locales.keys().forEach(key => {
    const matched = key.match(/([A-Za-z0-9-_]+)\./i)
    if (matched && matched.length > 1) {
      const locale = matched[1]
      messages[locale] =  locales(key)
    }
  })
  return messages
}

const i18n = createI18n({
  
  locale: process.env.VUE_APP_I18N_LOCALE || 'en',
  fallbackLocale: process.env.VUE_APP_I18N_FALLBACK_LOCALE || 'en',
  messages: loadLocaleMessages()
  
})

export default i18n;
****************
error
*********
 Type 'Record<string, LocaleMessageDictionary<string>>' is not assignable to type 'Record<string, LocaleMessageDictionary<VueMessageType>>'.
  Index signatures are incompatible.
    Type 'LocaleMessageDictionary<string>' is not assignable to type 'LocaleMessageDictionary<VueMessageType>'.
    20 |   locale: process.env.VUE_APP_I18N_LOCALE || 'en',
    21 |   fallbackLocale: process.env.VUE_APP_I18N_FALLBACK_LOCALE || 'en',
  > 22 |   messages: loadLocaleMessages()
       |   ^^^^^^^^
    23 |   
    24 | })
**********

**Comment by kazupon** [comment]
This issue is reoslved with #110 

You can add `VueMessageType` that is defined with `vue-i18n-next`

```ts
import { createI18n, LocaleMessages, VueMessageType } from 'vue-i18n'

function loadLocaleMessages() {
  const locales = require.context('./locales', true, /[A-Za-z0-9-,\s]+.json$/i)
  const messages: LocaleMessages<VueMessageType> = {}
  locales.keys().forEach(key => {
    const matched = key.match(/([A-Za-z0-9-]+)./i)
    if (matched && matched.length > 1) {
      const locale = matched[1]
      messages[locale] = locales(key)
    }
  })
  return messages
}
```

**Comment by dev-kr2020** [comment]
Great .. thanks..

**Comment by dev-kr2020** [comment]
build error is remove but there is no error or unable to use {{ t('message.hello') }}. Since createApp is taking standard config, not able to have setup() as mentioned in example
code 
****************
import { createApp } from 'vue'
import i18n from '@/i18n'
import App from './App.vue'
import './registerServiceWorker'
import router from './router'
import store from './store'

createApp(App).use(store).use(i18n).use(router).mount('#app')
***************

**Comment by kazupon** [comment]
Thank you for your feedback.

Could you provide reproduction minimum codes, please?

**Comment by dev-kr2020** [comment]
using Vue/CLI - Vue3, created project with store and router. added vue-i18n-next to it
main.ts
*********
import { createApp } from 'vue'
import i18n from '@/i18n'
import App from './App.vue'
import './registerServiceWorker'
import router from './router'
import store from './store'

createApp(App).use(store).use(i18n).use(router).mount('#app')
*************
i18n.ts
****************
import { createI18n, LocaleMessages, VueMessageType } from 'vue-i18n'

function loadLocaleMessages() {
  const locales = require.context('./locales', true, /[A-Za-z0-9-,\s]+.json$/i)
  const messages: LocaleMessages<VueMessageType> = {}
  locales.keys().forEach(key => {
    const matched = key.match(/([A-Za-z0-9-]+)./i)
    if (matched && matched.length > 1) {
      const locale = matched[1]
      messages[locale] = locales(key)
    }
  })
  return messages
}
************
and add {{ t('message.hello') }} in app.ts just to test.. page itself is not showing and now error is throwing.

**Comment by kazupon** [comment]
> and add {{ t('message.hello') }} in app.ts just to test.

sorry, I could not find the `app.ts`.
generally, `t` is implemented in `<template>`.
I guess that you are not running `useI18n` in the `setup` function of `App.vue`.

**Comment by dev-kr2020** [comment]
here is the app.ts
***********
<template>
  <div id="nav">
    <router-link to="/">Home</router-link> |
    <router-link to="/about">About</router-link>
  </div>
  <router-view/>
</template>

<style lang="scss">
#app {
  font-family: Avenir, Helvetica, Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  text-align: center;
  color: #2c3e50;
}

#nav {
  padding: 30px;

  a {
    font-weight: bold;
    color: #2c3e50;

    &.router-link-exact-active {
      color: #42b983;
    }
  }
}
</style>
**************

**Comment by dev-kr2020** [comment]
do we have vue CLI plugin?

**Comment by dev-kr2020** [comment]
Below is the repository -code - only vue3 with i18n works but with ion it do not 
https://github.com/dev-kr2020/sample-vue3-i18n

https://github.com/dev-kr2020/sample-ionicvue3-i18n

getting following error
Uncaught (in promise) TypeError: _ctx.t is not a function
    at eval (eval at ./node_modules/cache-loader/dist/cjs.js?!./node_modules/babel-loader/lib/index.js!./node_modules/vue-loader-v16/dist/templateLoader.js?!./node_modules/cache-loader/dist/cjs.js?!./node_modules/vue-loader-v16/dist/index.js?!./src/views/Tabs.vue?vue&type=template&id=6a83f7b8&bindings={"ellipse":"setup","square":"setup","triangle":"setup"} (app.js:1054), <anonymous>:41:160)

**Comment by kazupon** [comment]
sorry, vue-cli-plugin-i18n cannot not support for Vue 3 yet.

**Comment by dev-kr2020** [comment]
thanks buddy..

**Comment by scalingapps** [comment]
@kazupon what about:
```
  datetimeFormats: any // DateTimeFormats<?????>
  numberFormats: any // NumberFormats<????>
```
