### ISSUE TITLE
Custom directive messages don't update when changing locale

### ISSUE THREAD

**Issue by anatolykopyl** [intlify/vue-i18n-next#1083]
When updating `locale.value`, the change is not reflected inside custom `v-t` directives until a rerender occurs.

### Expected behavior

Every element with `v-t` updates it's value when the locale is changed.

### Reproduction

https://github.com/anatolykopyl/vue-i18n-next-issue-reproduction

### System Info

```shell
System:
    OS: macOS 13.0
    CPU: (8) arm64 Apple M1
    Memory: 70.58 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.15.0 - ~/.nvm/versions/node/v16.15.0/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 8.9.0 - ~/.nvm/versions/node/v16.15.0/bin/npm
    Watchman: 2022.07.04.00 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome Canary: 106.0.5197.0
    Firefox: 101.0.1
    Safari: 16.0
  npmPackages:
    @vitejs/plugin-vue: ^3.0.0 => 3.0.1 
    vite: ^3.0.0 => 3.0.2 
    vue: ^3.2.37 => 3.2.37 
    vue-i18n: 9 => 9.1.10 
    vue-tsc: ^0.38.4 => 0.38.9
```

### Additional context

This does not affect translations made with the `useI18n` `t` function, they stay updated.

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/intlify/vue-i18n-next/blob/master/.github/CONTRIBUTING.md)
- [X] Read the [Documentation](https://vue-i18n.intlify.dev/)
- [X] Check that there isn't [already an issue](https://github.com/intlify/vue-i18n-next/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/intlify/vue-i18n-next/discussions)
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by kazupon** [comment]
Thank you for your reporting!
I've just confirmed this issue.
I'll try to fix it!
