### ISSUE TITLE
'unplugin-vue-i18n/messages' is imported by nuxt/dist/server but could not be resolved – treating it as an external dependency.

### ISSUE THREAD

**Issue by jonmes** [intlify/vue-i18n-next#1085]
### Reporting a bug?

Could not resolve import 
**"@intlify/unplugin-vue-i18n/messages"** in ...nuxt/dist/server/server.mjs 
using exports defined in **/node_modules/@intlify/unplugin-vue-i18n/package.json**. 
'**@intlify/unplugin-vue-i18n/messages**' is imported by .nuxt/dist/server/server.mjs, but could not be resolved – treating it as an external dependency.

### Expected behavior

In dev mode **@intlify/unplugin-vue-i18n/messages** the package automatically imports the messages created in the locales folder, but while building a ssr in nuxt 3 the builder couldn't resolve the **messages** file, and treating it as an external dependency.
I was expecting that the builder would import @intlify/unplugin-vue-i18n/messages, so I can find the messages in built ssr file.

### Reproduction

[Link](https://github.com/jonmes/Nuxt3-Metadata) to github repo that show how i implement it. to see the bug just uncomment [this line](https://github.com/jonmes/Nuxt3-Metadata/blob/main/plugins/i18n.js#L4)GitHub

### System Info

```shell
### Package
{
  "private": true,
  "scripts": {
    "build": "nuxt build",
    "dev": "nuxt dev",
    "generate": "nuxt generate",
    "preview": "nuxt preview"
  },
  "devDependencies": {
    "@intlify/unplugin-vue-i18n": "^0.4.0",
    "nuxt": "3.0.0-rc.5",
    "vue-i18n": "^9.1.10"
  },
  "dependencies": {
    "@vee-validate/i18n": "^4.6.2",
    "petite-vue-i18n": "^9.2.0-beta.39",
    "vee-validate": "^4.6.2"
  }
}


### nuxt.config.ts
import { defineNuxtConfig } from "nuxt";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "url";
import VueI18nPlugin from "@intlify/unplugin-vue-i18n/vite";

// https://v3.nuxtjs.org/api/configuration/nuxt.config
export default defineNuxtConfig({
  vite: {
    plugins: [
      // VueI18nPlugin.vite({ /* options */ }),
      VueI18nPlugin({
        include: [
          resolve(dirname(fileURLToPath(import.meta.url)), "./locales/*.json"),
        ],
      }),
    ],
  },
});
```

### Screenshot

![image](https://user-images.githubusercontent.com/59283322/180746648-1794342f-55dc-4e1f-a7b9-511eaf961406.png)

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/intlify/vue-i18n-next/blob/master/.github/CONTRIBUTING.md)
- [X] Read the [Documentation](https://vue-i18n.intlify.dev/)
- [X] Check that there isn't [already an issue](https://github.com/intlify/vue-i18n-next/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/intlify/vue-i18n-next/discussions)
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by kazupon** [comment]
Duplicated this issue
https://github.com/intlify/bundle-tools/issues/145

Thank you for your reporting!

**Comment by jonmes** [comment]
my bad I haven't properly configured the build transpiler.
`  build: {
    transpile: ["@intlify/unplugin-vue-i18n"],
  },`
now it generates perfectly using the code above.
