### ISSUE TITLE
i18n.global.t raises a warning

### ISSUE THREAD

**Issue by giolf** [intlify/vue-i18n-next#1102]
### Reporting a bug?

if you use i18n instance in composition mode and outside the setup function like:
```
import { i18n } from '@/i18n'
...
i18n.global.t('header.pageTitle')
```
you get the following warning:

> Argument types do not match parameters 

My config about i18n instance is the following:
```
import { createI18n } from 'vue-i18n'
import it from '@/i18n/locales/it.json'

type MessageSchema = typeof it

export const i18n = createI18n<[MessageSchema], 'it', false>({
  fallbackLocale: 'it',
  globalInjection: false,
  legacy: false,
  locale: 'it',
  messages: { it }
})
```

### Expected behavior

It should not alert any kind of warning

### Reproduction

Is not required a reproduction, just use the `t` function with the `i18n` instance outside the setup function as i mentioned in the example.

### System Info

```shell
System:
    OS: macOS 12.5
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 66.00 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 12.16.1 - ~/.nvm/versions/node/v12.16.1/bin/node
    npm: 6.13.4 - ~/.nvm/versions/node/v12.16.1/bin/npm
  Browsers:
    Chrome: 103.0.5060.134
    Safari: 15.6
  npmPackages:
    @intlify/eslint-plugin-vue-i18n: ^2.0.0 => 2.0.0
    @intlify/vite-plugin-vue-i18n: ^5.0.1 => 5.0.1
    @vitejs/plugin-vue: ^2.3.3 => 2.3.3
    @vue/eslint-config-typescript: ^10.0.0 => 10.0.0
    @vue/test-utils: ^2.0.0 => 2.0.0
    vite: ^2.9.9 => 2.9.9
    vite-plugin-vue-type-imports: ^0.2.0 => 0.2.0
    vitest: ^0.12.9 => 0.12.9
    vue: ^3.2.36 => 3.2.36
    vue-i18n: ^9.2.0-beta.40 => 9.2.0-beta.40
    vue-router: ^4.0.15 => 4.0.15
    vue-tsc: ^0.29.8 => 0.29.8
```

### Screenshot

![image](https://user-images.githubusercontent.com/6743233/182405287-2004ac63-d6d9-4629-9076-d50cae786e98.png)

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/intlify/vue-i18n-next/blob/master/.github/CONTRIBUTING.md)
- [X] Read the [Documentation](https://vue-i18n.intlify.dev/)
- [X] Check that there isn't [already an issue](https://github.com/intlify/vue-i18n-next/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/intlify/vue-i18n-next/discussions)
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by kazupon** [comment]
Thank you for your reporting!
I've tried reproduction from reporting info at VSCode.
But, Unfortunately I could not reproduce this issue.

We need more minimum repro repo in VSCode.
Could you give it to us, please? 🙏

**Comment by giolf** [comment]
Hi @kazupon  
Thank you for you reply. 

I figured out in the meanwhile that if i do this:
```
import { i18n } from '@/i18n'
const { t } = i18n.global

t('header.pageTitle.notFound')
```

it works. 
![image](https://user-images.githubusercontent.com/6743233/182959113-ea40b810-9efa-4ca5-b347-f33d10146bd7.png)

**Comment by giolf** [comment]
my bad it works now, I simply had a wrong setup in my IDE.  (i was accidentally ignoring the `node_modules` folder)
