### ISSUE TITLE
$t 超过3个第四个复数不展示

### ISSUE THREAD

**Issue by ht-sauce** [intlify/vue-i18n-next#1103]
### Reporting a bug?

demo
test: '1 | 2 | 3 | 4 | 5'
$t('test', 4)
output： 3
Should output： 4

### Expected behavior

Should output： 4

### Reproduction

null

### System Info

```shell
null
```

### Validations

- [ ] Read the [Contributing Guidelines](https://github.com/intlify/vue-i18n-next/blob/master/.github/CONTRIBUTING.md)
- [ ] Read the [Documentation](https://vue-i18n.intlify.dev/)
- [x] Check that there isn't [already an issue](https://github.com/intlify/vue-i18n-next/issues) that reports the same bug to avoid creating a duplicate.
- [x] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/intlify/vue-i18n-next/discussions)
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by xfq** [comment]
Would you please provide a minimal reproducible example of the bug ([like this](https://codepen.io/xfq/pen/gOeexyj))?

请问是否可以创建一个最小的、可重现的示例？[比如这个](https://codepen.io/xfq/pen/gOeexyj)。

**Comment by ht-sauce** [comment]
> Would you please provide a minimal reproducible example of the bug ([like this](https://codepen.io/xfq/pen/gOeexyj))?
> 
> 请问是否可以创建一个最小的、可重现的示例？[比如这个](https://codepen.io/xfq/pen/gOeexyj)。

Thank you. This is my example
https://codepen.io/ht-sauce/pen/dymmVdj

**Comment by kazupon** [comment]
THank you for your reporting!
Unfortunately, it does not support plurals, such as mapping numbers. 
For such use cases, you need to define your rules with custom pluralization.

Thanks!
