### ISSUE TITLE
Calling tm(key) emits error "TS2589: Type instantiation is excessively deep and possibly infinite."

### ISSUE THREAD

**Issue by JulianSchoenbaechler** [intlify/vue-i18n-next#1119]
### Reporting a bug?

With Typescript v4.7, the call to [tm(key)](https://vue-i18n.intlify.dev/api/composition.html#tm-key) in the composition API sometimes results in a type error being thrown:
```
error TS2589: Type instantiation is excessively deep and possibly infinite.
```

I can't seem to reproduce it consistently, so my only way of dealing with this for the moment is by sprinkling `@ts-ignore`'s through my codebase.

### Expected behavior

Correct type processing of the Vue I18n composition API.

### Reproduction

```html
<div class="container">
  <p v-for="line in tm('lines')">
    {{ rt(line) }}
  </p>
</div>
```

### System Info

```shell
System:
    OS: Windows 10 10.0.19043
    CPU: (8) x64 Intel(R) Core(TM) i7-3770K CPU @ 3.50GHz
    Memory: 8.24 GB / 15.94 GB
  Binaries:
    Node: 18.7.0 - C:\Program Files\nodejs\node.EXE
    npm: 8.15.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (104.0.1293.47)
    @vue/tsconfig: ^0.1.3 => 0.1.3
    vite: ^3.0.5 => 3.0.5
    vue: ^3.2.37 => 3.2.37
    vue-i18n: ^9.2.2 => 9.2.2
    vue-tsc: ^0.40.0 => 0.40.0
    typescript: ~4.7.4 => 4.7.4
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/intlify/vue-i18n-next/blob/master/.github/CONTRIBUTING.md)
- [X] Read the [Documentation](https://vue-i18n.intlify.dev/)
- [X] Check that there isn't [already an issue](https://github.com/intlify/vue-i18n-next/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/intlify/vue-i18n-next/discussions)
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by horans** [comment]
> error TS2589: Type instantiation is excessively deep and possibly infinite.

same error when trying to use i18n in plain js(outside component) with `const { t } = i18n.global`

**Comment by Fuzzyma** [comment]
> same error when trying to use i18n in plain js(outside component) with const { t } = i18n.global

Same here

**Comment by matzeso** [comment]
This has a Need More Info tag - anything in particular you are looking for? 
Our pipelines are also failing on `const { t } = i18n.global` with the
```
Type instantiation is excessively deep and possibly infinite.
```
error.

**Comment by chimpydev** [comment]
Is this resolved?
I'm having this every fckg time
<img width="397" alt="image" src="https://user-images.githubusercontent.com/86309030/185569370-77a8974e-948a-4a20-83dc-1f71ad08b9cf.png">

**Comment by Kruptein** [comment]
Upgrading from `9.1.10` to `9.2.2` causes this issue for me with `i18n.global.t`

**Comment by ll60** [comment]
> Upgrading from `9.1.10` to `9.2.2` causes this issue for me with `i18n.global.t`

我也遇到了相同的问题，降级后，解决了，十分感谢

**Comment by luisdeka** [comment]
> Upgrading from `9.1.10` to `9.2.2` causes this issue for me with `i18n.global.t`

For me the 2 versions throw same error

**Comment by popadicbranislav** [comment]
Same issue - `"vue-i18n": "^9.2.2"`
Volar TypeScript version: `4.8.4`


```ts
// i18n.ts
import { createI18n } from 'vue-i18n'

// Import locales
const messages = Object.fromEntries(
  Object.entries(
    import.meta.glob<{ default: any }>('../locales/*.y(a)?ml', { eager: true }))
    .map(([key, value]) => {
      const yaml = key.endsWith('.yaml')
      return [
        key.slice(key.lastIndexOf('/') + 1, yaml ? -5 : -4),
        value.default,
      ]
    }),
)

const i18n = createI18n({
  legacy: false,
  locale: 'en',
  messages,
})

export const { t } = i18n.global

export default i18n
```

Usage of `t` outside of vue component files:
```ts
// some.ts
import { t } from '../i18n'

const text = t('example')
//                   ^ - Type instantiation is excessively deep and possibly infinite. ts(2589)
```
Error:
**Type instantiation is excessively deep and possibly infinite.** _ts(2589)_

**Comment by antoniogiroz** [comment]
Hello!

I was the same type issue and I've solved casting the messages files to `I18nOptions['message']` type:

```ts
import type { I18nOptions } from 'vue-i18n';
import { createI18n } from 'vue-i18n';

const messages = Object.fromEntries(
  Object.entries(import.meta.glob<{ default: unknown }>(`./locales/*.json`, { eager: true })).map(([key, value]) => [
    key.slice(10, -5),
    value.default,
  ])
) as I18nOptions['messages'];

const i18n = createI18n({
  locale: 'en',
  messages,
});

export default i18n;
```

I hope it helps you!

**Comment by IceTea233** [comment]
> I'm still experiencing this issue with v9.9.1, using `tm` with messages imported directly from JSON files via import. Can this be reopened?

Still encounter the same problem with v10.0.8. Not sure if it is proper but I finally workaround like below:
```vue
<li v-for="(hint, i) in tm('notes') as VueMessageType" :key="i">
  {{ rt(hint) }}
</li>
```
I didn't investigate in but I guessed that `tm` was not able to assume the structure of the object imported from JSON files. You need to either use local-scope messages like the [documentation](https://vue-i18n.intlify.dev/api/composition.html#tm-key) mentioned, or add type assertion by yourself.

**Comment by EDM115** [comment]
@IceTea233 thank you, this fixed it 🫶
