### ISSUE TITLE
Usage outside of vue components

### ISSUE THREAD

**Issue by FrankSingh** [intlify/vue-i18n-next#113]
### vue & vue-i18n version
ex:
- vue: 3.0.0-rc.10
- vue-i18n: 9.0.0-beta.1

Hi, is it possible to use vue-i18n outside of regular vue components? I'm trying to set the document title inside my router file.

What I tried so far is to import "useI18n" and pass the same options I used to call "createI18n". Like this:
```
import { useI18n } from 'vue-i18n'
import { i18nOptions } from '@/plugins/i18n'
const { t } = useI18n(i18nOptions)
```

All I got so far where "createCompileError/createI18nError"
![image](https://user-images.githubusercontent.com/26551709/93093053-85e81080-f6a0-11ea-9df2-2cf8b2c631ff.png)

Thank you for your work and help :)

**Comment by syuilo** [comment]
I have same issue.
It would be nice if methods such as `$t` were provided in an i18n instance. e.g.

``` ts
import { createI18n } from 'vue-i18n';

const i18n = createI18n({
	...
});

console.log(i18n.$t('foo', { bar: 'buzz' }));
```

**Comment by kazupon** [comment]
> Hi, is it possible to use vue-i18n outside of regular vue components? I'm trying to set the document title inside my router file.
> 
> What I tried so far is to import "useI18n" and pass the same options I used to call "createI18n". Like this:

@FrankSingh 
Thank you for your feedback!

`useI18n` is **only available in the `setup` of Compsition API.

For use outside of component, it makes use of the `composer` which is referred to in the `global` property of the `i18n` instance created by `createI18n`.

About detail `composer`, see the API docs:
https://github.com/intlify/vue-i18n-next/blob/master/docs/vue-i18n.composer.md

**Comment by kazupon** [comment]
@syuilo 
> It would be nice if methods such as `$t` were provided in an i18n instance. e.g.

Unfortunately, in vue-i18n-next and later versions (v9.0.0), APIs provided by vue-i18n@v8.x, such as `$t`, are not available outside of components.

Inside the component, they can be used by specifying the `legacy: true` option of `createI18n`.

For use outside of component, it makes use of the composer which is referred to in the `global` property of the i18n instance created by `createI18n`.

**Comment by FrankSingh** [comment]
```js
import { i18n } from '@/plugins/i18n'
const { t } = i18n.global
```

works like a charm. Thank you @kazupon 

Closing this issue :)
