### ISSUE TITLE
类型实例化过深，且可能无限

### ISSUE THREAD

**Issue by muchenfine** [intlify/vue-i18n-next#1133]
### Reporting a bug?

类型实例化过深，且可能无限

### Expected behavior

类型实例化过深，且可能无限

### Reproduction

类型实例化过深，且可能无限

### System Info

```shell
类型实例化过深，且可能无限
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/intlify/vue-i18n-next/blob/master/.github/CONTRIBUTING.md)
- [X] Read the [Documentation](https://vue-i18n.intlify.dev/)
- [X] Check that there isn't [already an issue](https://github.com/intlify/vue-i18n-next/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/intlify/vue-i18n-next/discussions)
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by kazupon** [comment]
close in-activity
thanks!
