### ISSUE TITLE
How to use it in TS files, and in Pinia

### ISSUE THREAD

**Issue by muchenfine** [intlify/vue-i18n-next#1134]
### Clear and concise description of the problem

How to use it in TS files, and in Pinia

### Suggested solution

How to use it in TS files, and in Pinia

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/intlify/vue-i18n-next/blob/master/.github/CONTRIBUTING.md)
- [X] Read the [Documentation](https://vue-i18n.intlify.dev/)
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by realityfilter** [comment]
We habe the same problem. How to access the global instance from pinia. Any help appreciated.

**Comment by kazupon** [comment]
This issue should be asked at github disicussions
so, close
