### ISSUE TITLE
`beforeDestroy` has been renamed to `beforeUnmount`

### ISSUE THREAD

**Issue by 1ncounter** [intlify/vue-i18n-next#114]
### vue & vue-i18n version
- vue: 3.0.0-beta.14
- vue-i18n: 9.0.0-beta.1

### Steps to reproduce

export const i18n = createI18n({
  locale: 'zh-cn',
  legacy: true,
....

### What is Expected?
[Vue warn]: `beforeDestroy` has been renamed to `beforeUnmount`.

**Comment by exoego** [comment]
Could you fill "what is actual behavior" field ?

**Comment by kazupon** [comment]
Fixed in #115. I'll release soon.

**Comment by kazupon** [comment]
I've just released vue-i18n@v9.0.0-beta.2
https://github.com/intlify/vue-i18n-next/releases/tag/v9.0.0-beta.2

please check it!

**Comment by kazupon** [comment]
close due to in-activity.
