### ISSUE TITLE
How is internationalization used in TS

### ISSUE THREAD

**Issue by muchenfine** [intlify/vue-i18n-next#1146]
### Clear and concise description of the problem

If the Server internationalization takes effect
How is internationalization used in TS
```
<script setup lang="ts">

import { useI18n } from 'vue-i18n';
const { t } = useI18n();
const options = [       props: { label: t('server')    } ];

</script>


```

### Suggested solution

If the Server internationalization takes effect
How is internationalization used in TS
```
<script setup lang="ts">

import { useI18n } from 'vue-i18n';
const { t } = useI18n();
const options = [       props: { label: t('server')    } ];

</script>


```

### Alternative

If the Server internationalization takes effect

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/intlify/vue-i18n-next/blob/master/.github/CONTRIBUTING.md)
- [X] Read the [Documentation](https://vue-i18n.intlify.dev/)
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by kazupon** [comment]
Thank you for your feedback.

About server side rendering,  vue-i18n has already supported it.
if you would mean back-end integration, we already have an example here:
https://github.com/intlify/vue-i18n-next/tree/master/examples/backend

Thanks
