### ISSUE TITLE
If $t params are undefined

### ISSUE THREAD

**Issue by martinlundin** [intlify/vue-i18n-next#1155]
### Reporting a bug?

When using a variable as a param to the $t() function it works good until the variable is undefined. Then there is an error:
`Uncaught (in promise) SyntaxError: Invalid argument `

### Expected behavior

In previous versions this was handled by the function.

### Reproduction

I made a JSFiddle here https://jsfiddle.net/rxn13fa7/4/
Its the "undefined" on row 28 that creates the error. Remove it and it works fine.

### System Info

```shell
See JSFiddle
```

### Additional context

The current solution I do is making a wrapping function like this
`
translate (key) {
      return key ? this.$t(key) : ''
}
`

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/intlify/vue-i18n-next/blob/master/.github/CONTRIBUTING.md)
- [X] Read the [Documentation](https://vue-i18n.intlify.dev/)
- [X] Check that there isn't [already an issue](https://github.com/intlify/vue-i18n-next/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/intlify/vue-i18n-next/discussions)
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by kazupon** [comment]
This is not a bug, but expected behavior.
vue-i18n raises the following error:
```
vue@3:1839 Uncaught SyntaxError: Invalid argument
    at createCompileError (vue-i18n@9:323:21)
    at createI18nError (vue-i18n@9:3669:14)
    at Object.t (vue-i18n@9:4645:29)
    at Proxy.$t (vue-i18n@9:5826:49)
    at eval (eval at compileToFunction (vue@3:16563:20), <anonymous>:11:57)
    at renderList (vue@3:4446:18)
    at Proxy.render (eval at compileToFunction (vue@3:16563:20), <anonymous>:9:68)
    at renderComponentRoot (vue@3:2459:18)
    at ReactiveEffect.componentUpdateFn [as fn] (vue@3:7510:48)
    at ReactiveEffect.run (vue@3:538:21)```
```

`Invalid argument` is outputting that message because there is a problem with the `$t` argument.

Thanks!

**Comment by r4mbo7** [comment]
Thanks for reporting this.

You can override the global `$t` function in your app this way:
```js
// $t(undefined) raises a runtime error (→ white screen)
// this plugin override the $t to prevent this
export const i18nPluginExtended = {
  install: (app) => {
    // override the globally available $t() method
    app.config.globalProperties.$t = (key) => {
      if (key === null || key === undefined) {
        console.error("Missing key in $t");
        return "";
      }

      return i18n.global.t(key);
    };
  },
};
```
Then 
```
app.use(i18n);
app.use(i18nPluginExtended);
```

It would be nice for `vue-i18n` to have a config for logging parsing error instead of throwing exception imho.
