### ISSUE TITLE
import I18nT from vue-i18n

### ISSUE THREAD

**Issue by TwT-L** [intlify/vue-i18n-next#1171]
### Clear and concise description of the problem

I'm trying to use `<i18n-t>` in web components
```vue
<script setup>
import { ref } from 'vue';
import { useI18n } from 'vue-i18n';
const { t } = useI18n();
defineProps({
  msg: String,
});

const count = ref(0);
</script>

<template>
  <div class="">
    <h1>banner</h1>
    <h2>{{ msg }}</h2>

    <div class="card">
      <button type="button" @click="count++">count is {{ count }}</button>
      <p>
        Edit
        <code>components/HelloWorld.vue</code> to test HMR
      </p>
    </div>

    <p>
      Check out
      <a href="https://vuejs.org/guide/quick-start.html#local" target="_blank"
        >create-vue</a
      >, the official Vue + Vite starter
    </p>
    <div>{{ t('description') }}</div>
    <i18n-t keypath="tagComponent">
      <template #text>
        <span class="font-color green"> 我的 </span>
      </template>
    </i18n-t>
  </div>
</template>
```
but warning shows `Failed to resolve component: i18n-t`

### Suggested solution

```
<script setup>
import { I18nT } from 'vue-i18n'

```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/intlify/vue-i18n-next/blob/master/.github/CONTRIBUTING.md)
- [X] Read the [Documentation](https://vue-i18n.intlify.dev/)
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by Ininit** [comment]
you can use import { Translation as I18nT } from 'vue-i18n'

**Comment by TwT-L** [comment]
> Translation

thanks for your reply.

but still shows a warning
![image](https://user-images.githubusercontent.com/93702913/190617723-0fc849bc-5097-46f0-8457-401d1262f925.png)

here is my [code on stackblitz](https://stackblitz.com/edit/vitejs-vite-h2rjan?file=src/libs/banner.ce.vue)

**Comment by TwT-L** [comment]
> you can use import { Translation as I18nT } from 'vue-i18n'

thanks for your reply.

but still shows a warning
![image](https://user-images.githubusercontent.com/93702913/190617723-0fc849bc-5097-46f0-8457-401d1262f925.png)

here is my [code on stackblitz](https://stackblitz.com/edit/vitejs-vite-h2rjan?file=src/libs/banner.ce.vue)

**Comment by ccqgithub** [comment]
> you can use import { Translation as I18nT } from 'vue-i18n'

直接这样，Volar 类型提示有问题。

**Comment by kazupon** [comment]
close in-activity
thanks!
