### ISSUE TITLE
Slot unwork in Production Environment

### ISSUE THREAD

**Issue by lilawliet** [intlify/vue-i18n-next#1179]
### Reporting a bug?

Probrem: display in the **development environment Correctly**, but slot-content **doesn't parse in production environment**.

en.json:
![image](https://user-images.githubusercontent.com/12482690/192109965-a4796372-fe67-4530-b573-311f0d148665.png)

index.vue:
![image](https://user-images.githubusercontent.com/12482690/192109943-8bb97f9e-d81e-40d8-ad37-e97a4c51551b.png)

vite.config.ts: (Various configurations have been tried)
![image](https://user-images.githubusercontent.com/12482690/192109959-3f7b5699-2020-4509-90b9-1b244c9dcdff.png)

i18n.index.vue:
![image](https://user-images.githubusercontent.com/12482690/192109994-dab6afa3-ebdd-4692-808a-1e80036392d0.png)

Dev : 
![image](https://user-images.githubusercontent.com/12482690/192110042-c1bb7406-5bf1-4365-bed8-ca9bbcccec5b.png)

Prod:
![image](https://user-images.githubusercontent.com/12482690/192110053-3a48c2eb-c7db-4d70-a557-18dbd2e809a9.png)

### Expected behavior

Production environment configuration Helper Docs.

### Reproduction

none

### System Info

```shell
System:
    OS: Windows 10 10.0.22000
    CPU: (16) x64 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz
    Memory: 5.70 GB / 15.75 GB
  Binaries:
    Node: 16.15.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.18 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.11.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22000.120.0), Chromium (105.0.1343.50)
    Internet Explorer: 11.0.22000.120
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/intlify/vue-i18n-next/blob/master/.github/CONTRIBUTING.md)
- [X] Read the [Documentation](https://vue-i18n.intlify.dev/)
- [X] Check that there isn't [already an issue](https://github.com/intlify/vue-i18n-next/issues) that reports the same bug to avoid creating a duplicate.
- [x] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/intlify/vue-i18n-next/discussions)
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by lilawliet** [comment]
- [ ] Solved the problem without using a plugin

![image](https://user-images.githubusercontent.com/12482690/192137788-2fbac067-2fc8-4113-b6ed-644ff699bec8.png)

**Comment by kazupon** [comment]
Thank you for your reporting!
Sorry, my late response.

Unfortunately, I could not this issue.
So, We need more reproruction minimue code.
Could you give us your github repo or stackbliz please? 🙏

**Comment by kazupon** [comment]
Close due to in-activity
If you would have issue, please give us to **minimual** reproduction codes with github repo or stackbliz as new issue.

Thanks!
