### ISSUE TITLE
i18n block not working in Vue 3 with options API

### ISSUE THREAD

**Issue by RuneClaeys** [intlify/vue-i18n-next#1186]
### Reporting a bug?

The i18n custom block in SFC doesn't work in Vue 3 when using the "older" options API.

The global translations are working, but the local translations aren't.

### Expected behavior

I expect my local translations to work when using the block

### Reproduction

https://stackblitz.com/edit/vitejs-vite-qoza92?file=src/App.vue

### System Info

```shell
System:
    OS: Linux 5.0 undefined
    CPU: (4) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.17.0 - /usr/local/bin/npm
  npmPackages:
    @intlify/vite-plugin-vue-i18n: ^6.0.3 => 6.0.3 
    @vitejs/plugin-vue: ^3.1.0 => 3.1.0 
    @vue/compiler-sfc: ^3.2.39 => 3.2.39 
    vite: ^3.1.3 => 3.1.3 
    vue: ^3.2.39 => 3.2.39 
    vue-i18n: ^9.2.2 => 9.2.2 
    vue-tsc: ^0.40.13 => 0.40.13
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/intlify/vue-i18n-next/blob/master/.github/CONTRIBUTING.md)
- [X] Read the [Documentation](https://vue-i18n.intlify.dev/)
- [X] Check that there isn't [already an issue](https://github.com/intlify/vue-i18n-next/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/intlify/vue-i18n-next/discussions)
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by waldemarennsaed** [comment]
Facing the same issue - any workaround yet?

**Comment by Adnan-kreiker** [comment]
I'm also facing the same issue, but with `vue 2.7` and `i18n-bridge`. I found a hack around it by doing the follwoing in main.ts:

```
const app =  createApp(
  {
    router,
    store,
    i18n,
    vuetify,
    beforeCreate() {
      this.customT = function(input: string) {
        const { t } = useI18n()
        return t(input)
      }
      Vue.prototype.$t = this.customT
    },
    render: (h: CreateElement) => h(App)
  }).mount('#app')
```

@kazupon Could you please provide suggestions to solve this issue in a non-hacky way?

**Comment by kazupon** [comment]
Sorry, I'm currently busy with another developments. Please wait. 🙏

**Comment by SebastianMelinat** [comment]
Can confirm that @Adnan-kreiker 's workaround works, except for translations with substrings (something like `Foo {bar}`). To get them to work I made the hack a bit hackier:

```
    beforeCreate () {
      this.customT = function (...input: unknown[]) {
        const { t } = useI18n()
        // Causes error TS2556: A spread argument must either have a tuple type or be passed to a rest parameter.
        // @ts-ignore
        return t(...input)
      }
      Vue.prototype.$t = this.customT
    }
```

**Comment by waldemarennsaed** [comment]
> Can confirm that @Adnan-kreiker 's workaround works, except for translations with substrings (something like `Foo {bar}`). To get them to work I made the hack a bit hackier:
> 
> ```
>     beforeCreate () {
>       this.customT = function (...input: unknown[]) {
>         const { t } = useI18n()
>         // Causes error TS2556: A spread argument must either have a tuple type or be passed to a rest parameter.
>         // @ts-ignore
>         return t(...input)
>       }
>       Vue.prototype.$t = this.customT
>     }
> ```

Love it! Thanks!
@kazupon any plans on tackling this bug soon?

**Comment by semiaddict** [comment]
I am also experiencing the same issue with vue-i18n `v9.2.2` and @intlify/unplugin-vue-i18n `v0.12.0`.
I keep getting `[intlify] Not found '...' key in 'fr' locale messages.` for all local messages in SFCs.

Here's a new repro: https://stackblitz.com/edit/vue3-vite-starter-v4kumr?file=vite.config.js,src%2Fmain.js,src%2FApp.vue

**Comment by semiaddict** [comment]
If using [@intlify/unplugin-vue-i18n](https://github.com/intlify/bundle-tools/tree/main/packages/unplugin-vue-i18n) with vite, it seems that you need to set `compositionOnly` to false in the vueI18n vite plugin options (see https://github.com/intlify/bundle-tools/tree/main/packages/unplugin-vue-i18n#compositiononly) to make it work with the legacy/options API.

**Comment by beda42** [comment]
> If using [@intlify/unplugin-vue-i18n](https://github.com/intlify/bundle-tools/tree/main/packages/unplugin-vue-i18n) with vite, it seems that you need to set `compositionOnly` to false in the vueI18n vite plugin options (see https://github.com/intlify/bundle-tools/tree/main/packages/unplugin-vue-i18n#compositiononly) to make it work with the legacy/options API.


This works for me as well. Thanks!

**Comment by kazupon** [comment]
If you use the legacy API style (options API), you must set `compositionOnly` to false when you are using vite and unplugin-vue-i18n.

If you are using another environment, please open a new issue.

Thanks!
