### ISSUE TITLE
Invalid Translation Component Typing Error

### ISSUE THREAD

**Issue by lostncg** [intlify/vue-i18n-next#1199]
### Reporting a bug?

Problem:
Using the Translation component correctly, but the linter warns the typing error for this component.

![image](https://user-images.githubusercontent.com/11206864/195852046-b82a8aca-883d-4aec-ab1e-f20b9d4f83a0.png)

### Expected behavior

Show the component typings correctly

```ts
export declare const Translation: new () => {
  $props: {
            keypath: string;
            plural?: number | string;
       
            tag?: keyof HTMLElementTagNameMap;
            locale?:string;
            scope?: "parent" | "global";
            i18n?: I18n; // this line could be wrong
        };
  $slots: {
      [x: string]: (arg: {
          Component: VNode;
      }) => VNode[];
  };
};
```

![image](https://user-images.githubusercontent.com/11206864/195856862-fcbd4594-20a9-4939-96e4-6f5d14786edf.png)

### Reproduction

Reproducible repo: [vitejs-vite-zv2s54.zip](https://github.com/intlify/vue-i18n-next/files/9786437/vitejs-vite-zv2s54.zip)

### System Info

```shell
System:
    OS: macOS 12.5
    CPU: (10) x64 Apple M1 Pro
    Memory: 18.43 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
Binaries:
    Node: 14.20.0 - ~/.nvm/versions/node/v14.20.0/bin/node
    npm: 8.15.0 - ~/.nvm/versions/node/v14.20.0/bin/npm
Browsers:
    Chrome: 106.0.5249.119
    Safari: 15.6
```

### Validations

- [x] Read the [Contributing Guidelines](https://github.com/intlify/vue-i18n-next/blob/master/.github/CONTRIBUTING.md)
- [X] Read the [Documentation](https://vue-i18n.intlify.dev/)
- [X] Check that there isn't [already an issue](https://github.com/intlify/vue-i18n-next/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/intlify/vue-i18n-next/discussions)
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by kazupon** [comment]
duplicate issue as #1244
