### ISSUE TITLE
When building with ASTRO getting error with @intlify/shared

### ISSUE THREAD

**Issue by demiro** [intlify/vue-i18n-next#1205]
### Reporting a bug?

When trying to use the vue-i18n inside ASTRO it works fine in dev mode... but when I am trying to build and creating static resources, I get an error:

`[commonjs--resolver] Failed to resolve entry for package "@intlify/shared". The package may have incorrect main/module/exports specified in its package.json: No known conditions for "." entry in "@intlify/shared" package
file: C:/DEVELOPMENT/_MY/dhw-astro/node_modules/.pnpm/vue-i18n@9.3.0-beta.6_vue@3.2.41/node_modules/vue-i18n/dist/vue-i18n.cjs.js
transforming (16) node_modules\.pnpm\@intlify+core-base@9.3.0-beta.6\node_modules\@intlify\core-base\dist\core-base.esm-browser.js error   Failed to resolve entry for package "@intlify/shared". The package may have incorrect main/module/exports specified in its package.json: No known conditions for 
"." entry in "@intlify/shared" package
  File:
    C:/DEVELOPMENT/_MY/dhw-astro/node_modules/.pnpm/vue-i18n@9.3.0-beta.6_vue@3.2.41/node_modules/vue-i18n/dist/vue-i18n.cjs.js
  Stacktrace:
Error: Failed to resolve entry for package "@intlify/shared". The package may have incorrect main/module/exports specified in its package.json: No known conditions for "." entry in "@intlify/shared" package
    at packageEntryFailure (file:///C:/DEVELOPMENT/_MY/dhw-astro/node_modules/.pnpm/vite@3.1.8_sass@1.55.0/node_modules/vite/dist/node/chunks/dep-4da11a5e.js:34841:11)
    at resolvePackageEntry (file:///C:/DEVELOPMENT/_MY/dhw-astro/node_modules/.pnpm/vite@3.1.8_sass@1.55.0/node_modules/vite/dist/node/chunks/dep-4da11a5e.js:34836:9)
    at tryNodeResolve (file:///C:/DEVELOPMENT/_MY/dhw-astro/node_modules/.pnpm/vite@3.1.8_sass@1.55.0/node_modules/vite/dist/node/chunks/dep-4da11a5e.js:34584:20)
    at Object.resolveId (file:///C:/DEVELOPMENT/_MY/dhw-astro/node_modules/.pnpm/vite@3.1.8_sass@1.55.0/node_modules/vite/dist/node/chunks/dep-4da11a5e.js:34357:28)
    at file:///C:/DEVELOPMENT/_MY/dhw-astro/node_modules/.pnpm/rollup@2.78.1/node_modules/rollup/dist/es/shared/rollup.js:22710:40

 ELIFECYCLE  Command failed with exit code 1.`

### Expected behavior

I would expect the dist folder to be created without any issues

### Reproduction

- install astro
- add vue-i18n and @intlify/vite-plugin-vue-i18n
- setup i18n.js in root
`import messages from '@intlify/vite-plugin-vue-i18n/messages'
import { createI18n } from 'vue-i18n'

const i18n = createI18n({
  legacy: false,
  locale: 'en',
  fallbackLocale: 'en',
  globalInjection: true,
  messages,
})

export default i18n`

- set astro.config.mjs
`import path from 'path'
import { fileURLToPath, URL } from 'node:url'
import Components from 'unplugin-vue-components/vite'
import AutoImport from 'unplugin-auto-import/vite'
import VueI18n from '@intlify/vite-plugin-vue-i18n'
import Vue from '@vitejs/plugin-vue'

import Icons from 'unplugin-icons/vite'
import IconsResolver from 'unplugin-icons/resolver'
import {
  defineConfig
} from 'astro/config';

// https://astro.build/config
import vue from "@astrojs/vue";

// https://astro.build/config
import tailwind from "@astrojs/tailwind";

const __dirname = path.resolve();

// https://astro.build/config
export default defineConfig({
  integrations: [vue({ appEntrypoint: '/src/pages/_app' }), tailwind()],
  vite: {
    plugins: [
      VueI18n({
        include: path.resolve(__dirname, './src/locales/**'),
      }),
      Components({
        extensions: ['vue'],
        include: [/\.vue$/, /\.vue\?vue/],
        dts: 'src/components.d.ts',
        resolvers: [IconsResolver({})],
      }),
      // https://github.com/antfu/unplugin-auto-import
      AutoImport({
        imports: [
          'vue',
          'vue-router',
          'vue-i18n',
          'vue/macros',
        ],
        dts: 'src/auto-imports.d.ts',
      }),
      Icons({
        compiler: 'vue3',
        autoInstall: true,
      }),
    ],
    resolve: {
      alias:{
        '@': fileURLToPath(new URL('./src', import.meta.url)),
        'vue-i18n': 'vue-i18n/dist/vue-i18n.cjs.js'
      },
    },
    css: {
      preprocessorOptions: {
        scss: {
          // example : additionalData: `@import "./src/design/styles/variables";`
          // dont need include file extend .scss
          additionalData: `@import "./src/assets/styles/_variables.scss";`,
        },
      },
    },
  }
});`

### System Info

```shell
System:
    OS: Windows 10 10.0.19044
    CPU: (40) x64 Intel(R) Xeon(R) CPU E5-2640 v4 @ 2.40GHz     
    Memory: 52.79 GB / 63.89 GB
  Binaries:
    Node: 18.11.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.19.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 106.0.5249.119
    Edge: Spartan (44.19041.1266.0), Chromium (106.0.1370.47)   
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    @intlify/vite-plugin-vue-i18n: 7.0.0-beta.4 => 7.0.0-beta.4 
    @vitejs/plugin-vue: ^3.1.2 => 3.1.2
    @vue/tsconfig: ^0.1.3 => 0.1.3
    vite: ^3.1.8 => 3.1.8
    vue: ^3.2.30 => 3.2.41
    vue-i18n: 9.3.0-beta.6 => 9.3.0-beta.6
    vue-router: ^4.1.5 => 4.1.5
    vue3-mq: ^3.1.3 => 3.1.3


"dependencies": {
    "@astrojs/tailwind": "^2.1.1",
    "@astrojs/vue": "^1.2.0",
    "astro": "^1.5.1",
    "tailwindcss": "^3.0.24",
    "vue": "^3.2.30",
    "vue-router": "^4.1.5",
    "vue3-mq": "^3.1.3"
  },
  "devDependencies": {
    "@babel/core": "^7.0.0-0",
    "@iconify/json": "^2.1.124",
    "@intlify/vite-plugin-vue-i18n": "7.0.0-beta.4",
    "@tailwindcss/typography": "^0.5.7",
    "@types/i18n": "^0.13.4",
    "@types/lodash": "^4.14.186",
    "@types/node": "^18.11.3",
    "@vitejs/plugin-vue": "^3.1.2",
    "@vue/tsconfig": "^0.1.3",
    "sass": "^1.55.0",
    "unplugin-auto-import": "^0.11.2",
    "unplugin-icons": "^0.14.12",
    "unplugin-vue-components": "^0.22.8",
    "vite": "^3.1.8",
    "vue-i18n": "9.3.0-beta.6"
  }
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/intlify/vue-i18n-next/blob/master/.github/CONTRIBUTING.md)
- [X] Read the [Documentation](https://vue-i18n.intlify.dev/)
- [X] Check that there isn't [already an issue](https://github.com/intlify/vue-i18n-next/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/intlify/vue-i18n-next/discussions)
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by kazupon** [comment]
related #1521 

I have only used astro for hello world
I heard that astro use the vite.
vue-i18n provides unplugin-vue-i18n as a plugin for vite.
vue-i18n v9.3 and unplugin-vue-i18n can be used to resolve module dependencies.

so close

**Comment by igorms-pro** [comment]
same here.. why this is closed?

**Comment by Cryszon** [comment]
Here's how I fixed `ReferenceError: __VUE_PROD_DEVTOOLS__ is not defined` error when running `astro build`:

```js
export default defineConfig({
  vite: {
    plugins: [
      VueI18nPlugin({
        ssr: true, // <- Add this
      }),
    ],
  },
});
```
