### ISSUE TITLE
Input a non-existent key with no error when using in typescript

### ISSUE THREAD

**Issue by Sweet-KK** [intlify/vue-i18n-next#1210]
### Reporting a bug?

```
// en.json
const en = {
  'Doc': 'Document',
}

// use
import { useI18n } from 'vue-i18n'
const { t } = useI18n()
t('hi')  // no error
```

### Expected behavior

I expect to be able to prompt all keys and corresponding value when typing. And show error when typing a non-existent key. 

### Reproduction

```
// en.json
const en = {
  'Doc': 'Document',
}

// use
import { useI18n } from 'vue-i18n'
const { t } = useI18n()
t('hi')  // no error
```

### System Info

```shell
System:
    OS: macOS 12.2.1
    CPU: (8) x64 Apple M1
    Memory: 38.32 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.18.3 - ~/.nvm/versions/node/v12.18.3/bin/node
    Yarn: 1.22.5 - ~/.yarn/bin/yarn
    npm: 6.14.6 - ~/.nvm/versions/node/v12.18.3/bin/npm
  Browsers:
    Chrome: 107.0.5304.62
    Safari: 15.3
  npmPackages:
    @vitejs/plugin-basic-ssl: ^0.1.2 => 0.1.2 
    @vitejs/plugin-legacy: ^2.2.0 => 2.2.0 
    @vitejs/plugin-vue: ^3.1.2 => 3.1.2 
    @vitejs/plugin-vue-jsx: ^2.0.1 => 2.0.1 
    @vue/compiler-sfc: ^3.2.40 => 3.2.40 
    @vue/eslint-config-typescript: ^11.0.2 => 11.0.2 
    vite: ^3.1.6 => 3.1.6 
    vite-plugin-babel-import: ^2.0.5 => 2.0.5 
    vite-plugin-html: ^3.2.0 => 3.2.0 
    vite-plugin-style-import: ^2.0.0 => 2.0.0 
    vite-plugin-svg-icons: ^2.0.1 => 2.0.1 
    vite-plugin-windicss: ^1.8.8 => 1.8.8 
    vue: 3.2.40 => 3.2.40 
    vue-i18n: 9 => 9.2.2 
    vue-router: 4.1.5 => 4.1.5 
    vuedraggable-es: ^4.1.1 => 4.1.1
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/intlify/vue-i18n-next/blob/master/.github/CONTRIBUTING.md)
- [X] Read the [Documentation](https://vue-i18n.intlify.dev/)
- [X] Check that there isn't [already an issue](https://github.com/intlify/vue-i18n-next/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/intlify/vue-i18n-next/discussions)
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by kazupon** [comment]
vue-i18n is designed to work with the assumption that the key specified in t is dynamically built by programatically.
Therefore, it does not generate type errors for keys that do not currently exist in the typescript.

This is a specification.

Thanks!
