### ISSUE TITLE
Format number in counter interpolation using composition API

### ISSUE THREAD

**Issue by paul-thebaud** [intlify/vue-i18n-next#1229]
### Clear and concise description of the problem

Hello,

With the removal of `tc`, it is currently not possible to differentiate the value used for count interpolation than the value interpolated in the translation when using `t`.

With version 8 it was possible thanks to `tc`:
```javascript
const count = 1500:
const formattedCount = new Intl.NumberFormat('fr_FR').format(count);

i18n.tc('count-of-something', count, { count: formattedCount });
```

### Suggested solution

Multiple solutions are available IMO:

- Bring `tc` back in composition API (and not only legacy)
- Update `t` to support differentiation between count and interpolated values

### Alternative

I didn't found any alternative for now.

### Additional context

This may be related to #1090

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/intlify/vue-i18n-next/blob/master/.github/CONTRIBUTING.md)
- [X] Read the [Documentation](https://vue-i18n.intlify.dev/)
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by kamilcglr** [comment]
Hello @paul-thebaud, I'm experiencing the same issue. Did you find an alternative solution?

**Comment by paul-thebaud** [comment]
HI @kamilcglr,
After searching in the source of the package and history, looks like this feature is already available since a while...
My bad. It does not look documented indeed.

For anyone searching issues for this feature, it can also be used in composition API using the same arguments:

```typescript
const i18n = useI18n();

const count = 10e9;
const formattedCount = new Intl.NumberFormat('fr').format(count);

i18n.t('count.something',  { n: formattedCount }, count);
```

Thanks @kamilcglr for helping me on this. Closing as the feature is already available.
