### ISSUE TITLE
Is not possible to use <i18n-t> with monorepo

### ISSUE THREAD

**Issue by leandrogehlen** [intlify/vue-i18n-next#1230]
### Reporting a bug?

I have created a monorepo project where the `core` package depends `vue-i18n` and the messages are defined in `web` package that depends of `core`.

https://github.com/leandrogehlen/vue-i18n-monorepo

in core package using 
```vue
<template>
  <WelcomeItem>
    <template #icon>
      <DocumentationIcon />
    </template>
    <!-- this works fine --> 
    <template #heading>{{ t("documentation") }}</template>

    <!-- this IS NOT WORKING -->
    <i18n-t keypath="officialDocContent" tag="div">
      <template #link>
        <a href="https://vuejs.org/" target="_blank" rel="noopener">
          {{ t("officialDoc") }}
        </a>
      </template>
    </i18n-t>
  </WelcomeItem>
</template>
```
the following error happens:

![image](https://user-images.githubusercontent.com/1750751/202263866-2fa9e699-7d5c-4325-b6b3-5cfeb9345792.png)

### Expected behavior

The message will be translated without errors

### Reproduction

- Clone repository: https://github.com/leandrogehlen/vue-i18n-monorepo.git
- `npm install`
- `npm run dev`

### System Info

```shell
System:
    OS: Windows 10 10.0.22000
    CPU: (8) x64 Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz
    Memory: 7.29 GB / 19.83 GB
  npmPackages:
    @intlify/unplugin-vue-i18n: ^0.8.0 => 0.8.0 
    @rushstack/eslint-patch: ^1.1.4 => 1.2.0 
    @types/node: ^16.11.68 => 16.18.3 
    @vitejs/plugin-vue: ^3.1.2 => 3.2.0 
    @vue-i18n-monorepo/core: file:../core => 0.0.1 
    @vue/eslint-config-prettier: ^7.0.0 => 7.0.0 
    @vue/eslint-config-typescript: ^11.0.0 => 11.0.2 
    @vue/tsconfig: ^0.1.3 => 0.1.3 
    eslint: ^8.22.0 => 8.27.0 
    eslint-plugin-vue: ^9.3.0 => 9.7.0 
    npm-run-all: ^4.1.5 => 4.1.5 
    prettier: ^2.7.1 => 2.7.1 
    vite: ^3.1.8 => 3.2.4 
    vue-i18n: ^9.2.2 => 9.2.2
    vue-tsc: ^1.0.8 => 1.0.9
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/intlify/vue-i18n-next/blob/master/.github/CONTRIBUTING.md)
- [X] Read the [Documentation](https://vue-i18n.intlify.dev/)
- [X] Check that there isn't [already an issue](https://github.com/intlify/vue-i18n-next/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/intlify/vue-i18n-next/discussions)
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by kazupon** [comment]
Thank you for your reporting!
Sorry for my late reply.

Unfortunately, I could not reproduce this issue.
If you can see this issue again, please give us your minimal repo or update it!

Thanks!
