### ISSUE TITLE
v9.0.0-beta.3 published on latest tag

### ISSUE THREAD

**Issue by deraw** [intlify/vue-i18n-next#124]
### vue & vue-i18n version

- vue-i18n: 9.0.0-beta.3

### What is actually happening?

Hi!

I think there was an error in the publication of the version `9.0.0-beta.3`, it was published on the `latest` tag!

**Comment by kazupon** [comment]
Thank you for your reporting!
I've just fixed version 8.21.1 !
Thanks!
