### ISSUE TITLE
RangeError: Value (ctx) => {const { normalize: _normalize } = ctx;return _normalize(["currency"])} out of range for Intl.NumberFormat options property style

### ISSUE THREAD

**Issue by NathanAP** [intlify/vue-i18n-next#1247]
### Reporting a bug?

Hi!

I'm trying to use `vue-i18n` and `vite-plugin-vue-i18n` in my code with `n` to "translate" my currency data.

My JSON file has this structure: 
```json
"pt-BR": {
    "currency": {
        "style": "currency",
        "currency": "BRL",
        "currencyDisplay": "symbol"
    }
}
```

when I use `console.log` in my `json` files that are imported, all of them are like this:
![image](https://user-images.githubusercontent.com/12821171/203836566-ea7cc90d-c6aa-4836-bd65-a1e5d317b48e.png)

Here is the problem
```js
import { useI18n } from 'vue-i18n'
const { t, n } = useI18n({ useScope: 'global' })

const testT = t('currency.currency') // this returns 'BRL'
const testN = n(100, 'currency') // this throws an error
```
![image](https://user-images.githubusercontent.com/12821171/203836884-689369bf-7ff7-4421-bea1-727ce42d99ec.png)

I think thats a bug because I can use `t` but I can't use `n` and I feel that is really odd that my imported `json` files has that `(ctx => { ... }` value. Is there something I could to to fix it?

### Expected behavior

My `testN` variable should be `R$ 100.00` just like my `testT` variable is `BRL`.

### Reproduction

Let me know if I need to reproduce somewhere. I think that my description is concise enough.

### System Info

```shell
System:
    OS: Linux 5.15 Manjaro Linux
    CPU: (8) x64 Intel(R) Core(TM) i7-9700KF CPU @ 3.60GHz
    Memory: 9.15 GB / 15.54 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 19.0.1 - /usr/bin/node
    Yarn: 1.22.19 - /var/lib/snapd/snap/bin/yarn
    npm: 8.19.2 - /usr/bin/npm
  Browsers:
    Firefox: 107.0
  npmPackages:
    @intlify/vite-plugin-vue-i18n: ^6.0.1 => 6.0.3 
    @vitejs/plugin-basic-ssl: ^0.1.2 => 0.1.2 
    @vitejs/plugin-vue: ^3.1.0 => 3.2.0 
    vite: ^3.1.3 => 3.2.4 
    vite-plugin-vuetify: ^1.0.0-alpha.17 => 1.0.0 
    vue: ^3.2.39 => 3.2.45 
    vue-advanced-cropper: ^2.8.3 => 2.8.6 
    vue-axios: ^3.4.1 => 3.5.2 
    vue-cli-plugin-vuetify: ~2.5.8 => 2.5.8 
    vue-google-maps-community-fork: ^0.1.4 => 0.1.6 
    vue-i18n: ^9.2.2 => 9.2.2 
    vue-router: ^4.1.5 => 4.1.6 
    vuetify: ^3.0.0 => 3.0.1
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/intlify/vue-i18n-next/blob/master/.github/CONTRIBUTING.md)
- [X] Read the [Documentation](https://vue-i18n.intlify.dev/)
- [X] Check that there isn't [already an issue](https://github.com/intlify/vue-i18n-next/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/intlify/vue-i18n-next/discussions)
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by NathanAP** [comment]
Hmmmm I guess I figured it out... I cannot just import my currency data like I do with the default translate data.

**Comment by kazupon** [comment]
Thank you for your reporting!

`n` and `$n` use `numberFormats` option of `createI18n`.
`t` and `$t` use `messages` option of `createI18n`.

So you need to specify the following in `createI18n`.

```js
import { createI18n } from 'vue-i18n'

// something locale messages from json
import ptBR from './locales/pt-BR.json'

const i18n = createI18n({
  legacy: false,
  locale: "pt-BR",
  messages: {
    "pt-BR": ptBR,
  },
  numberFormats: {
    "pt-BR": {
      currency: {
        style: "currency",
        currency: "BRL",
        currencyDisplay: "symbol",
      },
    },
  },
});
```

Thanks!

**Comment by NathanAP** [comment]
This seems like a limitation. I cant put my `numberFormats` inside my `import ptBR from './locales/pt-BR.json'` because it gives that error in the title, so I guess this should be in docs.
