### ISSUE TITLE
TypeError: i18n[TranslateVNodeSymbol] is not a function

### ISSUE THREAD

**Issue by DamianGlowala** [intlify/vue-i18n-next#1248]
### Reporting a bug?

When using the `<i18n-t>` component in Nuxt 3, the following error occurs:

![image](https://user-images.githubusercontent.com/48835293/203983935-5f5077dc-b951-4288-a188-e307c3bc2381.png)
![image](https://user-images.githubusercontent.com/48835293/203984463-532294cd-11a7-4cc9-85d9-9fa238f9b4a9.png)
![image](https://user-images.githubusercontent.com/48835293/203984078-263339ac-f27b-48dd-bc07-cec92b64671c.png)

### Expected behavior

n/a

### Reproduction

n/a

### System Info

```shell
System:
    OS: Windows 10 10.0.22000
    CPU: (16) x64 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz
    Memory: 8.21 GB / 31.73 GB
  Binaries:
    Node: 16.17.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.19.3 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22000.120.0), Chromium (107.0.1418.56)
    Internet Explorer: 11.0.22000.120
  npmPackages:
    vue-kinesis: ^2.0.5 => 2.0.5 
    vue-tippy: ^6.0.0-alpha.65 => 6.0.0-alpha.65 
    vue3-popper: ^1.5.0 => 1.5.0
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/intlify/vue-i18n-next/blob/master/.github/CONTRIBUTING.md)
- [X] Read the [Documentation](https://vue-i18n.intlify.dev/)
- [X] Check that there isn't [already an issue](https://github.com/intlify/vue-i18n-next/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/intlify/vue-i18n-next/discussions)
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by kazupon** [comment]
Thank you for your reporting!

Unfortunately, I could not reproduce this issue.
I seem that is occured in windows. 🤔 
(I don't have windows machine ...)

**Comment by dargmuesli** [comment]
Here you go, a reproduction: https://stackblitz.com/edit/github-a5wazj-4ptzyu?file=app.vue

**Comment by dargmuesli** [comment]
I guess the **Symbol** used to index `i18n` for the `translateVNode` and created at `makeSymbol('__translateVNode')` is not the same on client side as on server side?

**Comment by Solant** [comment]
Same issue here, looks like this issue can be reproduced when you have localized component, and use `i18n-t` component with parent scope, when i use `scope="global"` there is no issue

**Comment by kazupon** [comment]
Thank all your reporting!
this issue requires bundle optimize in nuxtjs/i18n. So that's nuxtjs/i18n issue, not a vue-i18n-next issue.

**Comment by kazupon** [comment]
I've just moved it to nuxtjs/i18n issue
https://github.com/nuxt-modules/i18n/issues/1713

Thanks!

**Comment by aautcq** [comment]
I was having the same error as @Solant using `vue-i18n-next` in a pure Vue.js project, and fixed it using the `i18n` prop of the `<i18n-t>` component, like so:

```vue
<template>
  <!-- ... -->
  <i18n-t
    keypath="path"
    :i18n="useI18n({ inheritLocale: true, useScope: 'local' })"
    >
    <!-- ... -->
  </i18n-t>
  <!-- ... -->
</template>

<script setup>
import { useI18n } from 'vue-i18n';

// ...
</script>

<i18n>
{
  "en": {
    "path": "My content"
  },
  "fr": {
    "path": "Mon contenu"
  }
}
</i18n>
```

The issue seems to be coming from the fallback value of the `i18n` prop.
