### ISSUE TITLE
error: Invalid token in placeholder: '$

### ISSUE THREAD

**Issue by xlz26296** [intlify/vue-i18n-next#127]
### vue & vue-i18n version
ex:
- vue: 3.0.0-0
- vue-i18n: 9.0.0-beta.3

### Reproduction Link
https://jsfiddle.net/x0o2cL67/

### Steps to reproduce
How to output 'xxx: { $100, $xxx }' string directly, some scenarios need to output special characters.

### What is Expected?
Output string with no error.

### What is actually happening?
![image](https://user-images.githubusercontent.com/34787386/94354583-18c87800-00af-11eb-8b4f-869167ceb623.png)

**Comment by kazupon** [comment]
Thank you for your feedback!!
sorry, lately my reply.

Related #118 
`@`,  `{`, `}` and `$` characters is special characters since vue-i18n-next in message syntax.

You can avoid it to use **literal interpolation**.

```
"请问如何输出字符串，如何关闭默认的格式化：{'{'} {'$'}100, {'$'}xxx {'}’}"
```
https://jsfiddle.net/9zdL8vak/

**Comment by kazupon** [comment]
or
```
"请问如何输出字符串，如何关闭默认的格式化：{'{ $100, $xxx }’}"
```

**Comment by xlz26296** [comment]
thanks, It would be nice to be able to close the parse placeholder directly, so that you can upgrade directly from ```vue-i18n``` to``` vue-i18n-next``` without any changes.

Could you consider supporting placeholder switches?
```
createI18n({
  parsePlaceholder: false
})
```
