### ISSUE TITLE
in 'nuxt3' && 'tailwind' ,have  '[ERROR] [plugin vite:dep-pre-bundle] Failed to resolve entry for package "@intlify/shared".'

### ISSUE THREAD

**Issue by rain-hsiang** [intlify/vue-i18n-next#1270]
### Reporting a bug?

install `nuxt3`
`pnpm dlx nuxi init project-name `
`pnpm install`
install `i18n` && `@intlify/unplugin-vue-i18n`
[i18n](https://vue-i18n.intlify.dev/guide/integrations/nuxt3.html#localize-your-nuxt-3-application)
install `tailwind`
[tailwind](https://tailwindcss.com/docs/guides/nuxtjs#3)
error:
`✘ [ERROR] [plugin vite:dep-pre-bundle] Failed to resolve entry for package "@intlify/shared". The package may have incorrect main/module/exports specified in its package.json: No known conditions for "." entry in "@intlify/shared" package`

### Expected behavior

use (`i18n` && `@intlify/unplugin-vue-i18n` ) && tailwind in nuxt3

### Reproduction

demo: https://gitee.com/rain-hsiang20221113/nuxt3-i18n-tailwind

### System Info

```shell
`
  System:
    OS: macOS 12.6
    CPU: (8) arm64 Apple M1
    Memory: 485.75 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.18.1 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.19.2 - /usr/local/bin/npm
  Browsers:
    Chrome: 108.0.5359.124
    Safari: 16.0
  npmPackages:
    @intlify/unplugin-vue-i18n: ^0.8.1 => 0.8.1 
    vue-i18n: ^9.2.2 => 9.2.2 
`
```

### Screenshot

...

### Additional context

...

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/intlify/vue-i18n-next/blob/master/.github/CONTRIBUTING.md)
- [X] Read the [Documentation](https://vue-i18n.intlify.dev/)
- [X] Check that there isn't [already an issue](https://github.com/intlify/vue-i18n-next/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussions](https://github.com/intlify/vue-i18n-next/discussions)

**Comment by kazupon** [comment]
Thank you for your feedback!

vue-i18n depend on some deps, so `@intlify/shared` is one of these.
If you would to use vue-i18n with nuxt plugin instead of nuxtjs/i18n, you will need to resolve those dependencies.

You can check to the following code in nuxtjs/i18n
https://github.com/nuxt-modules/i18n/blob/next/src/alias.ts

This issue is not a vue-i18n issue. Therefore, I’l l close it.

Thanks!
