### ISSUE TITLE
Named interpolation doesn't work when app is built

### ISSUE THREAD

**Issue by Polm90** [intlify/vue-i18n-next#1278]
### Reporting a bug

I'm using named interpolation to print some strings.
During the app development (while running `npm dev`) everything is worked as expected.
However, if I build the app (using `npm build`) the named interpolation is not replaced anymore, so I can see the values between the { not been replaced.

### Expected behavior

The { } part should be reploaced

### Reproduction

Here is my template:

```html
<template>
  <main class="page-w container-center">
    <div class="wrapper-text item-center">
      <h1 class="title">{{$t("start_page.title")}}</h1>
      <div class="text-v">{{$t('start_page.content', {starTag: "test"})}}</div>
    </div>
  </main>
</template>
```

This is the json file:

```json
{
  "start_page": {
    "title": "Welcome!",
    "content": "Hello {starTag}",
  },
}
```

### System Info

I'm using:
```shell
node 19.3.0
npm 9.2.0
vite 4.0.4
vue 3.2.45 (with composition api, SFC)
vue-i18n 9.2.2
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/intlify/vue-i18n-next/blob/master/.github/CONTRIBUTING.md)
- [X] Read the [Documentation](https://vue-i18n.intlify.dev/)
- [X] Check that there isn't [already an issue](https://github.com/intlify/vue-i18n-next/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussions](https://github.com/intlify/vue-i18n-next/discussions)

**Comment by velly** [comment]
Naming fomating has problem in build production?

I have the same issue while using format.

Locale string:
  "unlock.imnot": "I'm not {fullName}.",

Usage:
  <span>{{ $t("unlock.imnot", { fullName: authStore.user.fullname }) }}</span>

This works well in development mode:  vite
Fails when vite build.

I'm using:

vite 4.0.3
vue 3.2.45 (with composition api, SFC)
vue-i18n: 9.2.2

any critical bug of i18n vite build?

**Comment by Polm90** [comment]
> Naming fomating has problem in building production?
> 
> ## I have the same issue while using formatting.
> Locale string: "unlock.imnot": "I'm not {fullName}.",
> 
> Usage: {{ $t("unlock.imnot", { fullName: authStore.user.fullname }) }}
> 
> ## This works well in development mode:
> Output: I'm not Velly.
> Fails when vite build.
> Output: I'm not {fullName}.
> I'm using: vite 4.0.3 vue 3.2.45 (with composition api, SFC) vue-i18n: 9.2.2
> 
> I18n Configuration: import { createI18n } from "vue-i18n"; import { defaultLocale } from "@/config/locale"; import messages from "@/locales";
> 
> export default createI18n({ locale: defaultLocale, fallbackWarn: false, missingWarn: false, legacy: false, fallbackLocale: defaultLocale, messages, });
> 
> After my checking. I think it's the critical issue of @intlify/unplugin-vue-i18n, ^0.8.1.
> 
> I works well after i disable the Plugin。 import VueI18nPlugin from "@intlify/unplugin-vue-i18n/vite"; // VueI18nPlugin({ // include: resolve( // dirname(fileURLToPath(import.meta.url)), // "./path/to/src/locales/**" // ), // }),

Have you opened the issue on the unplugin-vue-i18n repository?
Since simply removing the plugin is not an option, have you found another workaround?

**Comment by velly** [comment]
> > After my checking. I think it's the critical issue of @intlify/unplugin-vue-i18n, ^0.8.1.
> > I works well after i disable the Plugin。 import VueI18nPlugin from "@intlify/unplugin-vue-i18n/vite"; // VueI18nPlugin({ // include: resolve( // dirname(fileURLToPath(import.meta.url)), // "./path/to/src/locales/**" // ), // }),
> 
> Have you opened the issue on the unplugin-vue-i18n repository? Since simply removing the plugin is not an option, have you found another workaround?

Yes, I may do that. 
Regarding to my solution, I used TS + vite to manage the translations now.

**Comment by ivan-trusov** [comment]
I have similar issue with syntax error in production build when using named interpolation. Setting runtimeOnly: false in plugin options helps.

**Comment by Polm90** [comment]
Found that we need to use the option `runtimeOnly: false` in the unplugin-vue-i18n configuration.
So we can close this as it's not a bug

**Comment by Gidoont** [comment]
It's not an option for a webextension - disabling this option breaks the whole thing with the following message:

> EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'".

**Comment by BasilaryGroup** [comment]
Doesn't work for me in a production release. With or with `runtimeOnly: false`.

```
node 16.18.1
npm 8.19.2
vite 4.0.4
vue 3.2.45
vue-i18n 9.2.2
```

```json
{
  "organization-last-updated": "Last updated {0} on {1}"
}
```
