### ISSUE TITLE
How to load messages asynchronously?

### ISSUE THREAD

**Issue by ux-engineer** [intlify/vue-i18n-next#129]
Could there be an example for loading messages asynchronously?

I've made logic for that, but am still debugging why my code is not working...

**Comment by ux-engineer** [comment]
Here are parts of my setup:

In `@/@types/index.ts`:
```ts
export * from './locales.d';
```

In `@/@types/locales.d.ts`

```ts
import supportedLocales from '@/../config/i18n/suppported-locales';

export type LocaleKey = keyof typeof supportedLocales;

export type LocaleObject = {
  code: LocaleKey;
  name: string;
};

export type LanguageJson = Record<string, unknown>;

export type CustomLocaleMessages = {
  [locale in LocaleKey]: {
    [key: string]: Record<string, string>;
  } & {
    validation?: Record<string, unknown>;
  };
}
```

In `./config/i18n/supported-locales.ts`
```ts
export default {
  'en-GB': 'In English',
  ...
};
```

In `src/i18n/index.ts`:
```ts
import { ref, Ref } from 'vue';
import { createI18n, useI18n } from 'vue-i18n';

import type { LocaleKey } from '@/@types';

import { getStartingLocale, getSupportedLocales, persistChosenLocale } from './util';

// Get initial locale from locale storage, or browser's locale if we are supporting
export const initialLocale = getStartingLocale();

// Execute factory function
const i18n = createI18n({
  locale: initialLocale,
  fallbackLocale: process.env.VUE_APP_I18N_FALLBACK_LOCALE,
  messages: {},
});

const loadedLanguages: LocaleKey[] = [];
const isLoadingLocale: Ref<boolean> = ref(false);

// Method for setting and persisting language choice
const setI18nLanguage = (locale: LocaleKey) => {
  const i18nInstance = useI18n();

  i18nInstance.locale.value = locale as string;
  persistChosenLocale(locale);

  if (isLoadingLocale.value) {
    isLoadingLocale.value = false;
  }

  return locale;
};

// Load locale message asynchronously from a webpack-built named chunk
const loadLocaleMessagesAsync = async (locale: LocaleKey): Promise<LocaleKey> => {
  const i18nInstance = useI18n();

  if (loadedLanguages.length > 0 && i18nInstance.locale.value === locale) {
    return Promise.resolve(locale);
  }

  // If the language hasn't been loaded yet
  if (!loadedLanguages.includes(locale)) {
    isLoadingLocale.value = true;

    const messages = await import(/* webpackChunkName: "lang-[request]" */ `@/i18n/lang/${locale as string}.json`);

    i18nInstance.setLocaleMessage(locale as string, messages);

    loadedLanguages.push(locale);
  }

  return Promise.resolve(setI18nLanguage(locale));
};
```

In `main.ts`:
```ts
import { createApp } from 'vue';

// Import Core Libraries
import { i18n, loadLocaleMessagesAsync, initialLocale } from '@/i18n';

// Import Page Layout For Renderer
import DefaultLayout from '@/layouts/default.vue';

// Create App With Layout
const app = createApp(DefaultLayout);

// Install plugins
app.use(i18n);

// Mount to DOM
app.mount('#app');
```

**Am getting an error:**
```txt
chunk-vendors.js:79279 Uncaught (in promise) SyntaxError: Unexpeced error
    at createCompileError (chunk-vendors.js:79279)
    at createI18nError (chunk-vendors.js:81785)
    at useI18n (chunk-vendors.js:83045)
    at _callee$ (app.js:7007)
    at tryCatch (chunk-vendors.js:65779)
    at Generator.invoke [as _invoke] (chunk-vendors.js:66009)
    at Generator.next (chunk-vendors.js:65834)
    at asyncGeneratorStep (chunk-vendors.js:146)
    at _next (chunk-vendors.js:168)
    at chunk-vendors.js:175
```

**This happens when using `useI18n` method in `loadLocaleMessagesAsync` function, as it's not finding the instance:**
```ts
const i18nInstance = useI18n();
```

**Comment by kazupon** [comment]
Hi! 
Thank you for your feedback!

You're using dynamic import in `loadLocaleMessagesAsync` to dynamically load i18n locale messags, but would you like to manage these resources globally?

If so, you can use `global` property of the i18n instance created by `createI18n` instead of calling `useI18n`.

`useI18n` Currently, it only works in the `setup`.

**Comment by ux-engineer** [comment]
@kazupon I tried to search through the codebase and documentation but couldn't figure out which kind of modifications I'd need to do with this setup. Could give some examples?

**Comment by kazupon** [comment]
I've just added lazy loading example.
please check it!

**Comment by ux-engineer** [comment]
Thanks for this example @kazupon, which nicely touches also the topic of using locale route params.

Is there some specific reason for wrapping the initilization logic of i18n and router libraries into setup functions? Why not to just `export const i18n = createI18n({ ...` so it could be imported with object-destructuring directly from @/i18n file without needing to pass it to `setupRouter` function?

```js
const i18n = setupI18n()
const router = setupRouter(i18n)
```

**Comment by kazupon** [comment]
**The examples I added are just an example code for lazy-loading**.
In an actual project, it is not a good idea to use the examples as they are. You are implementing it for your use case.

>> Is there some specific reason for wrapping the initilization logic of i18n and router libraries into setup functions? Why not to just `export const i18n = createI18n({ ...` so it could be imported with object-destructuring directly from @/i18n file without needing to pass it to `setupRouter` function?

While wrapping it may indeed be useless, it is generally not a good idea to implement it as-is in the entry point, as it would make the code more complex.
Structuring each logic steps with it's own responsibility is good software design.

It may indeed be useful to use the bandler alias such as `@/i18n` in the path of an es import.
However, using it would be a technical liability in terms of maintenance later on, since the path resolution is done using the features of the bundler.
I think you should use the standard path of es modules.
