### ISSUE TITLE
_ctx.$t is not a function

### ISSUE THREAD

**Issue by Damon99999** [intlify/vue-i18n-next#1307]
### Reporting a bug?

`[Vue warn]: Property "$t" was accessed during render but is not defined on instance. 
  at <Condition> 
  at <App>
`

`Condition.vue:176 Uncaught (in promise) TypeError: _ctx.$t is not a function
    at Proxy._sfc_render (Condition.vue:176:24)
    at renderComponentRoot (chunk-U6IDEWU5.js?v=2ce80086:1930:39)
    at ReactiveEffect.componentUpdateFn [as fn] (chunk-U6IDEWU5.js?v=2ce80086:5654:26)
    at ReactiveEffect.run (chunk-U6IDEWU5.js?v=2ce80086:386:19)
    at instance.update (chunk-U6IDEWU5.js?v=2ce80086:5698:52)
    at callWithErrorHandling (chunk-U6IDEWU5.js?v=2ce80086:1373:32)
    at flushJobs (chunk-U6IDEWU5.js?v=2ce80086:1560:9)`

`const i18n = createI18n({
  legacy: false,
  globalInjection: true,
  locale,
  fallbackLocale: 'en',
  messages
})`

I tried to add this config 'globalInjection: true', but it not works

### Expected behavior

I hope that it works like normal

### Reproduction

n/a

### System Info

```shell
"vue": "^3.2.39",
"vue-i18n": "^9.2.2"
```

### Screenshot

![企业微信截图_16733415512667](https://user-images.githubusercontent.com/38937194/211509930-0fd215bb-5c81-4b8b-b28e-99d1aac01b87.png)
![企业微信截图_16733420418950](https://user-images.githubusercontent.com/38937194/211510059-cd3116fe-81b0-4ed7-9216-893c0b1df724.png)

### Additional context

I guess that it's maybe about the 'v-if' directive

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/intlify/vue-i18n-next/blob/master/.github/CONTRIBUTING.md)
- [X] Read the [Documentation](https://vue-i18n.intlify.dev/)
- [X] Check that there isn't [already an issue](https://github.com/intlify/vue-i18n-next/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussions](https://github.com/intlify/vue-i18n-next/discussions)

**Comment by kazupon** [comment]
Thank you for your reporting!

However, We need minimal reproduction codes with github repo or stackbliz.
could you give us that, please?
