### ISSUE TITLE
Pascal case variants of custom components

### ISSUE THREAD

**Issue by DamianGlowala** [intlify/vue-i18n-next#1312]
### Clear and concise description of the problem

Differentiating native components (dash case) from custom ones (pascal case) improves DX and makes it visually easier to distinguish one from the other. Could all the components be also available as the pascal case variant?

### Suggested solution

Given the `<i18n-t />` component, it would also be available as `<I18nT />`.

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/intlify/vue-i18n-next/blob/master/.github/CONTRIBUTING.md)
- [X] Read the [Documentation](https://vue-i18n.intlify.dev/)
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by kazupon** [comment]
I've just spported at v9.3.0-beta.16
I'm going to release nuxtjs/i18n edge version.

Thanks!

**Comment by DamianGlowala** [comment]
Thank you! Much appreciated. I'll give it a go soon :)
