### ISSUE TITLE
`i18n.global.t('xxxx')` 报错 TS2349: This expression is not callable.

### ISSUE THREAD

**Issue by WangJincheng4869** [intlify/vue-i18n-next#1314]
### Reporting a bug?

在TS文件中使用`i18n.global.t('messageBox.title.tip')`会报错，报错信息如下：
```
TS2349: This expression is not callable.   Each member of the union type 'ComposerTranslation<{}, string, RemoveIndexSignature<{ [x: string]: LocaleMessageValue<VueMessageType>; }>, never, never, never> | VueI18nTranslation<...>' has signatures, but none of those signatures are compatible with each other.
```
但是并不影响获取到内容，就是编辑器会报错

### Expected behavior

没有报错信息，可以正常使用

### Reproduction

https://github.com/WangJincheng4869/fanKuiWenJian/blob/02c03d249a138e7adf019f50b453f3a957a926bf/%60i18n.global.t('xxxx')%60%20%E6%8A%A5%E9%94%99%20TS2349%20This%20expression%20is%20not%20callable.zip

下载这个文件，解压后代码在src\hooks\feedback\use-message-box.ts中

### System Info

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Memory: 3.36 GB / 15.56 GB
  Binaries:
    Node: 18.12.1 - D:\Program Files\nodejs\node.EXE
    npm: 9.2.0 - D:\Users\jcwang\AppData\Roaming\npm\npm.CMD
  Browsers:
    Edge: Spartan (44.22621.1105.0), Chromium (109.0.1518.55)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    @intlify/unplugin-vue-i18n: ^0.8.1 => 0.8.1 
    @vitejs/plugin-vue: ^4.0.0 => 4.0.0 
    vite: ^4.0.4 => 4.0.4 
    vite-plugin-compression2: ^0.5.0 => 0.5.0 
    vue: ^3.2.45 => 3.2.45 
    vue-i18n: ^9.2.2 => 9.2.2 
    vue-router: ^4.1.6 => 4.1.6 
    vue-tsc: ^1.0.24 => 1.0.24
```

### Screenshot

![image](https://user-images.githubusercontent.com/41162158/213126913-6fa5aabd-7bf9-41f0-a621-a5de72a79a4a.png)
![image](https://user-images.githubusercontent.com/41162158/213127264-278e20e8-8d85-4cc0-bd7d-566373f310a5.png)

### Additional context

难道使用`i18n.global.t`需要什么特殊的配置吗？

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/intlify/vue-i18n-next/blob/master/.github/CONTRIBUTING.md)
- [X] Read the [Documentation](https://vue-i18n.intlify.dev/)
- [X] Check that there isn't [already an issue](https://github.com/intlify/vue-i18n-next/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussions](https://github.com/intlify/vue-i18n-next/discussions)

**Comment by WangJincheng4869** [comment]
虽然它在报错，但是程序可以正常运行，且能获取到值，如图所示：
![image](https://user-images.githubusercontent.com/41162158/213129046-7e890805-0437-4dc5-ae76-89792a457bb3.png)
![image](https://user-images.githubusercontent.com/41162158/213129106-e05c1912-0e03-47fe-b899-35cae8026292.png)

**Comment by duanmw** [comment]
+1 , 换成用useI18n里的t就可以
import { useI18n } from "vue-i18n";
const { t } = useI18n();

**Comment by duanmw** [comment]
> > +1 , 换成用useI18n里的t就可以 import { useI18n } from "vue-i18n"; const { t } = useI18n();
> 
> 但是useI18n()只能在stup中使用，这是个硬伤。太局限了
那就强行指定ts类型 i18n: I18n<object, object, object, string, false>;

**Comment by WangJincheng4869** [comment]
调用  `createI18n`  时传入泛型后正常 `createI18n<false>`
```ts
const i18n = createI18n<false>({
  legacy: false,
  locale: getStorageLocale(),
  fallbackLocale: "zh-CN",
  messages: localesConfigs
});
```
