### ISSUE TITLE
Using $t() with <i18n> block and Composition API not working (Vue 3)

### ISSUE THREAD

**Issue by KaliaJS** [intlify/vue-i18n-next#1318]
### Reporting a bug?

For large app, I want to use $t() localy inside my Single-File Components with custom block <i18n> to avoid importing each time and pages the composable useI18n().

```javascript
import { useI18n } from 'vue-i18n'
const { t } = useI18n()
```

$t() works well ONLY with global messages set globaly in ```createI18n()```.

```javascript
import messages from '@intlify/unplugin-vue-i18n/messages'

export const i18n = createI18n({
  locale: language.value,
  fallbackLocale: 'fr',
  messages,
})
```

Is it normal ? If so, is it possible to add this new feature?

### Expected behavior

That i18n takes into account the block <i18n> when i use $t()

### Reproduction

```javascript
<script setup>
import { useI18n } from 'vue-i18n'
const { t } = useI18n()
</script>

<template>
  $t('title') not working
  <div>{{ $t('title') }}</div>
  t('title') working
  <div>{{ t('title') }}</div>
</template>

<i18n>
fr:
  title: Commencez par entrer votre e-mail
en:
  title: Start by entering your email
</i18n>
```

### System Info

```shell
System:
    OS: macOS 12.6.2
    CPU: (8) x64 Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz
    Memory: 6.86 GB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.15.0 - /usr/local/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 8.5.5 - /usr/local/bin/npm
  Browsers:
    Chrome: 109.0.5414.87
    Firefox: 107.0
    Safari: 15.6.1
  npmPackages:
    @intlify/unplugin-vue-i18n: ^0.8.1 => 0.8.1 
    @vitejs/plugin-vue: ^3.2.0 => 3.2.0 
    @vue/test-utils: ^2.0.0-rc.21 => 2.0.0-rc.21 
    vite: ^3.2.4 => 3.2.4 
    vite-plugin-inspect: ^0.7.9 => 0.7.9 
    vite-svg-loader: ^3.6.0 => 3.6.0 
    vitest: ^0.25.2 => 0.25.2 
    vue: ^3.2.31 => 3.2.31 
    vue-dragscroll: ^3.0.1 => 3.0.1 
    vue-i18n: ^9.3.0-beta.11 => 9.3.0-beta.11 
    vue-router: 4 => 4.0.12
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/intlify/vue-i18n-next/blob/master/.github/CONTRIBUTING.md)
- [X] Read the [Documentation](https://vue-i18n.intlify.dev/)
- [X] Check that there isn't [already an issue](https://github.com/intlify/vue-i18n-next/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussions](https://github.com/intlify/vue-i18n-next/discussions)

**Comment by blackravenx** [comment]
Hi, if you want to use both "$t" and "t", set  `legacy: true` in `createI18n` params.

**Comment by KaliaJS** [comment]
@blackravenx Hi, I already tried and it doesn't work with <i18n> block as describe. Do you have an example to show me where it works (stackblitz) ?

**Comment by anikeef** [comment]
I have a similar problem using Vue 2.7 with vue-i18n-bridge. `legacy: true` doesn't solve the issue. Here is a reproduction link:

https://stackblitz.com/edit/vitejs-vite-chaof9?file=vite.config.js,src%2Fmain.js,src%2FApp.vue

When I change $t to t, the message is rendered properly. But $t doesn't catch neither global, nor local messages.

**Comment by ice-kylin** [comment]
Same problem.

**Comment by rdhainaut** [comment]
Same issue here.
I have the problem in a Vue 2.7 app + vue i18n bridge 
and 
in a Vue 3.3.2 app with Vue i18n v9.22.

It works partially (all global messages or all local messages but it s impossible to make work both at same time with legacy $t api)
My current workaround is to use composition api everywhere (it s a lot of import + useI18n()) but at least it works as expected

Note: because I use vite cli, i have installed following devDependencies
```
// package.json
"devDependencies": {
   // ...
    "@intlify/vue-i18n-loader": "^4.2.0",
    "vue-cli-plugin-i18n": "~2.3.2"
  }
 ```

and i have following config
```
// vue.config.js
const { defineConfig } = require('@vue/cli-service')
module.exports = defineConfig({
  pluginOptions: {
    i18n: {
      locale: 'en',
      fallbackLocale: 'en',
      localeDir: 'locales',
      enableLegacy: true,
      runtimeOnly: false,
      compositionOnly: true,
      fullInstall: true
    }
  }
})

```

**Comment by kazupon** [comment]
Thank you for your feedback.
This is the design philosophy of vue-i18n that `$t` cannot be used for local in the Composition API.

If you support this, then `$t` can be used both globally and locally, which is not possible if you want to use it with i18n custom blocks in SFC and we would to make some of them global.

Thanks!
