### ISSUE TITLE
Cannot read property '__disableEmitter' 

### ISSUE THREAD

**Issue by thisisablock** [intlify/vue-i18n-next#133]
### vue & vue-i18n version
- vue: 3.0.0
- vue-i18n: 9.0.0-beta.4

### What is actually happening?
On Beta 4 i get on a page change with vue-router@4.0.0-beta.12  an error

```
vueI18n.__disableEmitter && _vueI18n.__disableEmitter();
```

it related to 
```
      _vueI18n.__disableEmitter && _vueI18n.__disableEmitter();
```

On Beta 3 everything works fine

**Comment by kazupon** [comment]
I could not reproduce my environments ... 😞 
Could you provide minimum reproduction codes please?

**Comment by kazupon** [comment]
close due to in-activity

**Comment by holtwick** [comment]
I encounter the same problem with version 9.0.0. My projects use latest vite, vue3 and typescript. Everything worked fine until today. It is only triggered in certain circumstances for special routes. But it disappears if I don't use `i18n`.

<img width="524" alt="image" src="https://user-images.githubusercontent.com/49557/112813132-2c649380-907e-11eb-8cc4-6834df3df6c7.png">

```js
        beforeUnmount() {
            const instance = getCurrentInstance();
            /* istanbul ignore if */
            if (!instance) {
                throw createI18nError(22 /* UNEXPECTED_ERROR */);
            }
            /* istanbul ignore if */
            if (((process.env.NODE_ENV !== 'production') || __INTLIFY_PROD_DEVTOOLS__) && !false) {
                if (this.__emitter) {
                    this.__emitter.off('*', addTimelineEvent);
                    delete this.__emitter;
                }
                const _vueI18n = this.$i18n;
                _vueI18n.__disableEmitter && _vueI18n.__disableEmitter();
                delete this.$el.__INTLIFY__;
            }
            delete this.$t;
            delete this.$tc;
            delete this.$te;
            delete this.$d;
            delete this.$n;
            delete this.$tm;
            i18n.__deleteInstance(instance);
            delete this.$i18n;
        }
```

**Comment by holtwick** [comment]
It somehow seems to end up in the wrong context. The contents of `this` look like the properties of a component I use:

<img width="1413" alt="image" src="https://user-images.githubusercontent.com/49557/112814195-4e124a80-907f-11eb-9ec6-c547440d1ea4.png">

**Comment by holtwick** [comment]
Ok, the pages that cause issues use `<teleport>`. It works if I remove it. I consider this being a bug in either `vue3` or `i18n`. What do you think @kazupon ? Worth reopening the ticket?

**Comment by holtwick** [comment]
This seems to be related to a vue bug, in vue 3.0.7 everything works fine again.
