### ISSUE TITLE
Service Worker fails in dev if runtimeOnly flag is set to false

### ISSUE THREAD

**Issue by Polm90** [intlify/vue-i18n-next#1333]
### Reporting a bug?

If I configure the VueI18nPlugin with the runtimeOnly flag to false, I cannot run in dev mode a service worker injected with the vite-plugin-pwa plugin with strategy 'injectManifest'. I receive as error 'cannot use import statement outside a module'.

Setting the flag to true, everything works as expected.
However, with the flag set to true, the named interpolation is not working when the app is built. See this https://github.com/intlify/vue-i18n-next/issues/1278

### Expected behavior

I should be able to use the serviceworker properly.

### Reproduction

Custom service worker file:

```javascript
import` {precacheAndRoute} from 'workbox-precaching';

precacheAndRoute(self.__WB_MANIFEST);
```

vite.config.js plugins configuration:
```javascript
VueI18nPlugin({
			include: resolve(dirname(fileURLToPath(import.meta.url)), './src/locales/**'),
			runtimeOnly: false
		}),
		VitePWA({
			injectRegister: 'auto',
			registerType: 'prompt',
			devOptions: {
				enabled: true,
				type: 'module'
			},
			workbox: {
				globPatterns: ['**/*.{js,css,html,json,ico,svg,ttf,webmanifest}'],
			},
			srcDir: '',
			filename: 'custom-sw.js',
			strategies: 'injectManifest',
			includeAssets: ['favicon.ico', 'apple-icon-180.png', '**/*.{js,css,html,json,ico,svg,ttf,webmanifest}'],
			manifest: {
				//omitted
			}
		})
```

### System Info

```shell
vite: 4.1.1
vue: 3.2.47
node:  19.6.0
npm: 9.4.2
@intlify/unplugin-vue-i18n: 0.8.2
vue-i18n: 9.2.2
vite-plugin-pwa: 0.14.4
workbox-precaching: 6.5.4
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/intlify/vue-i18n-next/blob/master/.github/CONTRIBUTING.md)
- [X] Read the [Documentation](https://vue-i18n.intlify.dev/)
- [X] Check that there isn't [already an issue](https://github.com/intlify/vue-i18n-next/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussions](https://github.com/intlify/vue-i18n-next/discussions)

**Comment by kazupon** [comment]
From v9.3.0-beta.20, vue-i18n can be compile like JIT style.
so you can integrate back-end that has locale messages.
https://vue-i18n.intlify.dev/guide/advanced/optimization.html#jit-compilation
example is here
https://github.com/intlify/vue-i18n-next/tree/master/examples/backend
so close.
