### ISSUE TITLE
Composition API: Plurialization won't work with `formatFallbackMessages: true`

### ISSUE THREAD

**Issue by mrleblanc101** [intlify/vue-i18n-next#1338]
### Reporting a bug?

Hi, 
I have a small app, so I decided to use [Fallback interpolation](https://vue-i18n.intlify.dev/guide/essentials/fallback.html#fallback-interpolation) so my i18n key would be my default locale text.
Exemple: 
```js
// someComponent.vue
{{ $t('Résumé') }}

// en.json
{
    "Résumé": "Summary",
}
```
Output: 
```
English: 'Summary',
French: 'Résumé'
```

This worked great until I had to do plurialization.
Exemple 2:
```js
// someComponent.vue
{{ $t('Aucune entrée | {n} entrée | {n} entrées', 10) }}

// en.json
{
    "Aucune entrée | {n} entrée | {n} entrées": "No entries | {n} entry | {n} entries"
}
```
Output: 
```
English: '10 entries',
French: 'Aucune entrée | {n} entrée | {n} entrées'
```
In english it works, but it french the plurialization doesn't seem to work if `formatFallbackMessages` is set to `true`.

### Expected behavior

The fallback interpolation string should also be plurialized.

### Reproduction

.

### System Info

```shell
System:
    OS: macOS 13.2
    CPU: (8) arm64 Apple M1 Pro
    Memory: 64.19 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 19.6.0 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 9.4.0 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 109.0.5414.119
    Chrome Canary: 112.0.5606.0
    Firefox: 109.0.1
    Safari: 16.3
    Safari Technology Preview: 16.4
  npmPackages:
    vite-svg-loader: ^4.0.0 => 4.0.0
```

### Screenshot

![Capture d’écran, le 2023-02-19 à 16 37 44](https://user-images.githubusercontent.com/17392251/219976691-26d68784-fe34-4bf0-bcf0-9066c8e9b99d.png)
![Capture d’écran, le 2023-02-19 à 16 37 36](https://user-images.githubusercontent.com/17392251/219976692-02ebe909-becf-4124-aeda-1ee8dc5a0c17.png)

### Additional context
```js
    i18n: {
        strategy: 'prefix_except_default',
        defaultLocale: 'fr',
        langDir: 'i18n/',
        locales: [
            {
                code: 'fr',
                name: 'Français',
                iso: 'fr-CA',
                file: 'fr.json',
            },
            {
                code: 'en',
                name: 'English',
                iso: 'en-CA',
                file: 'en.json',
            },
        ],
        vueI18n: {
            legacy: false,
            fallbackWarn: false,
            missingWarn: false,
            formatFallbackMessages: true,
        },
    },
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/intlify/vue-i18n-next/blob/master/.github/CONTRIBUTING.md)
- [X] Read the [Documentation](https://vue-i18n.intlify.dev/)
- [X] Check that there isn't [already an issue](https://github.com/intlify/vue-i18n-next/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussions](https://github.com/intlify/vue-i18n-next/discussions)

**Comment by kazupon** [comment]
Hi!
Sorry for my reply lately.
(My day job has been hectic recently 💦 )

Could you give **minimal reproduction** with github repo or stackbliz plaese? 🙏

**Comment by mrleblanc101** [comment]
@kazupon My bad, I thought I linked to my project here:
https://github.com/mrleblanc101/neobigben
https://mrleblanc101.github.io/neobigben/
I'll post the stackblitz later tonight, creating it right now

**Comment by mrleblanc101** [comment]
@kazupon Here is the stackblitz: https://stackblitz.com/edit/nuxt-starter-kugtsg?file=app.vue
Maybe it's linked to the fact that it require me to define a `file: "fr.json"` in `nuxt.config.js` even I use [Fallback interpolation](https://vue-i18n.intlify.dev/guide/essentials/fallback.html#fallback-interpolation) which shouldn't require me to define the file since I keep it empty ? 🤔

**Comment by kazupon** [comment]
Hi!
I noticed that your nuxt.config.ts has settings incorrectly.

When you have specified `legacy: true`, vue-i18n will work in composition API mode. In that case, you need to set `fallbackFormat`, not `formatFallbackMessages`.

The option names for vue-i18n composition API mode and legacy API mode are different.
See here for details.
https://vue-i18n.intlify.dev/guide/advanced/composition.html#mapping-between-vuei18n-instance-and-composer-instance

Thanks!

**Comment by mrleblanc101** [comment]
@kazupon Indeed, thanks.
I think the doc could be clearer.
I'm indeed using `<script setup>`, but this was in a template block, so I did not think to look there.

**Comment by mrleblanc101** [comment]
@kazupon Shouldn't there be a TypeScript or runtime warning to prevent people from using legacy vlaue when `legacy` is set to `false` and vice-versa ?

**Comment by kazupon** [comment]
>Shouldn't there be a TypeScript or runtime warning to prevent people from using legacy value when legacy is set to false and vice-versa ?

Indeed, I'll register as new issue it.

**Comment by mrleblanc101** [comment]
@kazupon It work with `yarn dev`, but not with `yarn generate && yarn preview`.
![2023-03-07 13 53 15](https://user-images.githubusercontent.com/17392251/223522729-6575f212-e76c-4cea-bf33-3480792eaf9b.gif)
![2023-03-07 13 52 49](https://user-images.githubusercontent.com/17392251/223522731-9100f659-7e4b-4a24-a0ca-387ecee1ccd2.gif)

**Comment by mrleblanc101** [comment]
@kazupon Did i miss something ?

**Comment by jraez** [comment]
Hello,
I had a very similar issue: interpolation and pluralization were not working on build, until I found is deactivated by default when using vue vite.

You have to set `runtimeOnly: false` ; https://github.com/intlify/vite-plugin-vue-i18n/issues/91

Hope it helps!
