### ISSUE TITLE
`fallbackFormat` doesn't work in production

### ISSUE THREAD

**Issue by mrleblanc101** [intlify/vue-i18n-next#1352]
### Reporting a bug?

Nuxt config:
```
    i18n: {
        strategy: 'prefix_except_default',
        defaultLocale: 'fr',
        langDir: 'i18n/',
        locales: [
            {
                code: 'fr',
                name: 'Français',
                iso: 'fr-CA',
                file: 'fr.json',
            },
            {
                code: 'en',
                name: 'English',
                iso: 'en-CA',
                file: 'en.json',
            },
        ],
        vueI18n: {
            legacy: false,
            fallbackWarn: false,
            missingWarn: false,
            fallbackFormat: true,
        },
    },
```

Input:
```
// someComponent.vue
{{ $t('Aucune entrée | {n} entrée | {n} entrées', 10) }}

// en.json
{
    "Aucune entrée | {n} entrée | {n} entrées": "No entries | {n} entry | {n} entries"
}
```

Output:
```
// yarn dev
English: '10 entries',
French: '10 entrées'

// yarn generate && yarn preview
// production build on github pages won't work either
English: '10 entries',
French: 'Aucune entrée | {n} entrée | {n} entrées'
```

See for more info #1338

### Expected behavior

The string should be plurialized when using `yarn generate` with a production build.

### Reproduction

`yarn dev` will work.
`yarn generate && yarn preview` won't
https://stackblitz.com/edit/nuxt-starter-kugtsg?file=app.vue,nuxt.config.ts

### System Info

```shell
System:
    OS: macOS 13.2.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 48.19 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.19.1 - ~/.nvm/versions/node/v16.19.1/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.19.3 - ~/.nvm/versions/node/v16.19.1/bin/npm
  Browsers:
    Chrome: 111.0.5563.64
    Chrome Canary: 113.0.5648.0
    Firefox: 110.0
    Safari: 16.3
    Safari Technology Preview: 16.4
  npmPackages:
    vite-svg-loader: ^4.0.0 => 4.0.0
    vue-draggable-next: ^2.1.1 => 2.1.1
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/intlify/vue-i18n-next/blob/master/.github/CONTRIBUTING.md)
- [X] Read the [Documentation](https://vue-i18n.intlify.dev/)
- [X] Check that there isn't [already an issue](https://github.com/intlify/vue-i18n-next/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussions](https://github.com/intlify/vue-i18n-next/discussions)

**Comment by kazupon** [comment]
Hi!
Sorry for late reply.
I've checked this issue.
This issue is bug.
So, I'll work on this issue.

**Comment by mrleblanc101** [comment]
Any update ?

**Comment by mrleblanc101** [comment]
@kazupon Any alternative in the meantime ?

**Comment by mrleblanc101** [comment]
@kazupon I recently opened the project again and update all dependency and this seem to be fixed now, so i'll close.
Thanks
