### ISSUE TITLE
Integrating with Vue Router for localizing route paths structure

### ISSUE THREAD

**Issue by ux-engineer** [intlify/vue-i18n-next#136]
@kazupon made an example for implementing locale string as the root route param i.e. `/en/home`: https://github.com/intlify/vue-i18n-next/commit/a7d2147f7a0430c8cbeeb4a77395bda9d20462ad

Which gave me an idea of opening a feature request and discussion about this specific need, which in my mind would seem a great enhancement and a quite possibly real need for some projects.

How can we localize full route paths? Like `/en/home` -> `/sv/hem`?

Is there actually need for this, or would there be some downsize like with SEO? Perhaps some webstores would find it especially useful to be able to localize their product page urls?

Are there some ready solutions for this already? Could or should it be a feature with this library?

How to actually implement this?

**Comment by kazupon** [comment]
related issue comment 
https://github.com/intlify/vue-i18n-next/issues/129#issuecomment-703787843

As for vue-router's path structure, it is beyond the scope of vue-i18n's obligations.
Providing localizing with vue-i18n and vue-router should consider your project in its own use case.
vue-i18n simply provides i18n.
