### ISSUE TITLE
HTML detected error

### ISSUE THREAD

**Issue by artrayd** [intlify/vue-i18n-next#1377]
### Reporting a bug?

Can't deploy on Netlify, getting this error:

[unplugin-vue-i18n]  Detected HTML in ""

### Expected behavior

Should be able to deploy

### Reproduction

Install Nuxt3, add i18n, use HTML

### System Info

```shell
System:
    OS: macOS 12.6
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 59.67 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.19.1 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.19.3 - /usr/local/bin/npm
  Browsers:
    Chrome: 112.0.5615.137
    Edge: 112.0.1722.58
    Safari: 16.0
  npmPackages:
    vue-gtag-next: ^1.14.0 => 1.14.0 
    vue-i18n: ^9.3.0-beta.17 => 9.3.0-beta.17 
    vuefire: ^3.1.0 => 3.1.0
```

### Additional context

It worked in the beginning, but after updating and reinstalling all packages it stopped to work.

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/intlify/vue-i18n-next/blob/master/.github/CONTRIBUTING.md)
- [X] Read the [Documentation](https://vue-i18n.intlify.dev/)
- [X] Check that there isn't [already an issue](https://github.com/intlify/vue-i18n-next/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussions](https://github.com/intlify/vue-i18n-next/discussions)

**Comment by kazupon** [comment]
Thank you for your reporting!
This issues is same [nuxt i18n issue](https://github.com/nuxt-modules/i18n/issues/1991)

You can install edge channel version.
Please try it!

Thanks!
