### ISSUE TITLE
Overriding the locale on a per-translation basis does not work

### ISSUE THREAD

**Issue by RuneClaeys** [intlify/vue-i18n-next#1389]
### Reporting a bug?

The locale is set to 'nl'. But I wan't to show a specific translation in a different language. But the translations remains the global locale.

Input:

```html
<span>{{ $t('welcome',  { locale: 'fr' }) }}</span>
```

Output:

```
Welkom
```

### Expected behavior

Input:

```html
<span>{{ $t('welcome',  { locale: 'fr' }) }}</span>
```

Output:

```
Bienvenue
```

### Reproduction

https://stackblitz.com/edit/vitejs-vite-9xprcm?file=src/App.vue

### System Info

```shell
System:
    OS: macOS 13.2.1
    CPU: (10) arm64 Apple M2 Pro
    Memory: 944.75 MB / 32.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 18.14.2 - /opt/homebrew/opt/node@18/bin/node
    npm: 9.5.0 - /opt/homebrew/opt/node@18/bin/npm
  Browsers:
    Chrome: 112.0.5615.137
    Firefox: 112.0.1
    Safari: 16.3
  npmPackages:
    vite: ^4.3.3 => 4.3.3 
    vitest: ^0.29.2 => 0.29.2 
    vue: ^3.2.45 => 3.2.47 
    vue-i18n: ^9.2.2 => 9.2.2
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/intlify/vue-i18n-next/blob/master/.github/CONTRIBUTING.md)
- [X] Read the [Documentation](https://vue-i18n.intlify.dev/)
- [X] Check that there isn't [already an issue](https://github.com/intlify/vue-i18n-next/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussions](https://github.com/intlify/vue-i18n-next/discussions)

**Comment by codeflorist** [comment]
Check out  #1356 regarding this topic and a current workaround.

**Comment by mtdvlpr** [comment]
I've got a similar problem. I'm using the correct workaround listed by @codeflorist. But I get the warning that the translation is not listed in the locale I'm specifying. I think it has to do with the fact that locales are lazy-loaded. Is there a way to translate in a different locale while keeping lazy-loading enabled?

**Comment by kazupon** [comment]
Thank you for your reporting!

If you want to use only locale for a specific part, you can work around it by using the following workaround mentioned in the feature request issue that x has opened.

```ts
t('message.key', 1, { locale: 'fr' })
```

`t` (or `$t`) I/F is designed for vue-i18n v8 and frequency of use. Cases where the locale is different for a specific part are rare.

The I/F of this function is subject to breaking change, so we will re-design the API in a future version to make it easier to use.

Thanks!
