### ISSUE TITLE
Edge version info in docs

### ISSUE THREAD

**Issue by olemarius** [intlify/vue-i18n-next#1390]
### Clear and concise description of the problem

It's unclear to me what Edge version is, and could not find any information in GH issues, discussions or changelog. 

### Suggested solution

Add explanation in docs

https://vue-i18n.intlify.dev/guide/installation.html#edge-version

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/intlify/vue-i18n-next/blob/master/.github/CONTRIBUTING.md)
- [X] Read the [Documentation](https://vue-i18n.intlify.dev/)
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by aaronransley** [comment]
@olemarius It appears that the edge version is listed on npm, just in case you needed a workaround:
https://www.npmjs.com/package/vue-i18n?activeTab=versions

**Comment by olemarius** [comment]
Aha so it's "bleeding-edge" :-) I was thinking maybe it had something to do with Vercel Edge or similar
