### ISSUE TITLE
Inconsistent TM return type in dev and build environment

### ISSUE THREAD

**Issue by VeselyJan92** [intlify/vue-i18n-next#1397]
### Reporting a bug?

Message compilation / rendering works differently on dev and release version. 

`tm` returns `object` instead of `array`. 
```
<template>

  <h1>{{ t("simple_key") }}</h1>

  <h2>v-for</h2>
  <div v-for="item in tm('items')">
    <p>{{ rt(item.name)}}</p>
  </div>

  <h2>map</h2>
  <p>
    Works only for: yarn run dev
    <br>
    Does not work for: yarn run build && yarn run start
  </p>

  <div v-for="name in mappedItems">
    <p>{{ name}}</p>
  </div>
  
</template>

<script setup>

const {t, tm, rt} = useI18n();

const mappedItems = tm('items').map(item => rt(item.name))

</script>
```

```
export default defineI18nConfig(async () => {
    return {
      legacy: false,
 
      messages: {
        cs: await getLocale('cs'),
        de: await getLocale('en'),
      }
    }
  })
  
  async function getLocale(locale: string) {
    return {
        simple_key: "header",
        items:[
            { name: "item 1"},
            { name: "item 2"},
            { name: "item 3"}
        ]
    };
  }
```

### Expected behavior

`tm` returns iterable `array` not `object` 

### Reproduction

https://github.com/VeselyJan92/i18n-nuxt-bug/blob/master/pages/index.vue

### System Info

```shell
- Operating System: Linux
- Node Version:     v19.8.1
- Nuxt Version:     3.4.3
- Nitro Version:    2.4.0
- Package Manager:  yarn@1.22.19
- Builder:          vite
- User Config:      components, modules, i18n
- Runtime Modules:  @nuxtjs/i18n@8.0.0-beta.11-28059008.d1499b6
- Build Modules:    -
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/intlify/vue-i18n-next/blob/master/.github/CONTRIBUTING.md)
- [X] Read the [Documentation](https://vue-i18n.intlify.dev/)
- [X] Check that there isn't [already an issue](https://github.com/intlify/vue-i18n-next/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussions](https://github.com/intlify/vue-i18n-next/discussions)

**Comment by kazupon** [comment]
Thank you for your reporting!
Sorry for my late reply! 🙇 

I've checked your minimal codes with simple vue-i18n v9 + vite, not use nuxt-i18n
This isssue is nuxt i18n module bug.
So, I'll re-open https://github.com/intlify/vue-i18n-next/issues/1415, and close this issue

Thanks!
