### ISSUE TITLE
[Vue 2.7][vite] Can't use special characters in translation message

### ISSUE THREAD

**Issue by YanZaytsev** [intlify/vue-i18n-next#1412]
### Reporting a bug?

I have a custom block with translations:
```json
<i18n>
{
  "en": {
    "hello": "Use varible like this: {{UTC}}"
  }
}
</i18n>
```

I want it to be displayed as is. But I had an error from `unplugin-vue-i18n`: Not allowed nest placeholder. To display curly braces I tried using literal interpolation as suggested in the [docs](https://vue-i18n.intlify.dev/guide/essentials/syntax.html#literal-interpolation). And so I changed the translation  to:  "Use varible like this: {'{{'}UTC{'}}'}". But in the interface I see this message with symbols that are used to escape special characters (like curly braces in my case):
![image](https://github.com/intlify/bundle-tools/assets/11797469/15026876-9051-44bd-90e6-f58d8ccfd993)

### Expected behavior

I want the possibility to escape special characters

### Reproduction

https://stackblitz.com/edit/vitejs-vite-masrj4?file=package.json,vite.config.ts,src%2Fmain.ts,src%2FApp.vue,src%2Fi18n.ts&terminal=dev

### Issue Package

unplugin-vue-i18n

### System Info

```shell
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 7.17.0 - /usr/local/bin/npm
  npmPackages:
    vite: ^3.1.0 => 3.1.0 
    vue: ^2.7.10 => 2.7.10 
    vue-i18n: ^8.27.2 => 8.27.2
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/intlify/bundle-tools/blob/main/.github/contributing.md).
- [X] Read the README
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/intlify/bundle-tools/discussions).

**Comment by kazupon** [comment]
close, vue 2.x is EOL
