### ISSUE TITLE
Custom Formatter

### ISSUE THREAD

**Issue by mydnic** [intlify/vue-i18n-next#1432]
### Clear and concise description of the problem

If translations are coming from a backend in a specific format, you'd want to use a Custom Formatter (as it was possible in previous version).

My backend returns the translations in Laravel format :  `Good morning, :first_name` 

In the current version it's not possible to handle because apparently, [custom formatters where removed](https://vue-i18n.intlify.dev/guide/migration/breaking.html#remove-custom-formatter).

### Suggested solution

Either put the Custom Formatters back into the package, or instruct developers on how to achieve this.

### Additional context

I'm currently migrating our Nuxt2 application to Nuxt3. It's a non-ssr, static Nuxt app that consumes an external Back End via API.

In Nuxt2 + nuxt-i18n v6, I was able to build my own custom formatter that was really simple:
```javascript
interpolate (message, values) {
    if (values) {
        let resolved = message
        Object.keys(values).forEach((variable) => {
            resolved = resolved.replace(':' + variable, values[variable])
        })
        return [resolved]
    }
    return [message]
}
```

I'm now using `"@nuxtjs/i18n": "^8.0.0-beta.11"`
But with this nuxt3 compatible version of the package, Custom Formatters are gone ? It looks like I'm **obligated** to use `Good morning, {first_name}` interpolation format. But as I don't have any control on the translations keys in the Backend, it'll never work.

This is the only hard wall I'm facing while upgrading from nuxt2 to nuxt3

What would be the solution here ?

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/intlify/vue-i18n-next/blob/master/.github/CONTRIBUTING.md)
- [X] Read the [Documentation](https://vue-i18n.intlify.dev/)
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by kazupon** [comment]
close. This feature was supported with #1497

**Comment by mydnic** [comment]
@SamuelWei yes the documentation here https://vue-i18n.intlify.dev/guide/advanced/format.html explains how.

The warning saying that it may be removed in the future is a bit scary though..

**Comment by SamuelWei** [comment]
@mydnic Awesome, would you be so kind to share a snippet on how you implemented it?

**Comment by SamuelWei** [comment]
I was able to achive this, but only using the composition API

```js
function messageCompiler (message) {
  if (typeof message === 'string') {
    return (ctx) => {
      if (!ctx.values) {
        return [message];
      }
      Object.keys(ctx.values).forEach(key => {
        // Use Laravel syntax :placeholder instead of {placeholder}
        message = message.replace(`:${key}`, ctx.values[key]);
      });

      return message;
    };
  }
}
```
