### ISSUE TITLE
Pluralization not workin after built.

### ISSUE THREAD

**Issue by andersonAlmeida** [intlify/vue-i18n-next#1439]
### Reporting a bug?

Using composition API mode renders the full term instead the right slice. For instance, if I have a term like that `adult: 'Adult | Adults'` when I build the app the page renders `Adult | Adults`. In dev mode  it runs fine.

```
//  config
import { boot } from "quasar/wrappers";
import { createI18n } from "vue-i18n";
import messages from "src/i18n";

export default boot(({ app }) => {
  const i18n = createI18n({
    locale: "en-US",
    legacy: false,
    messages,
  });

  // Set i18n instance on app
  app.use(i18n);
});
```

```
<template>
  <q-page class="flex flex-center">
    {{ t("general.adult", 2) }}

    <img
      alt="Quasar logo"
      src="~assets/quasar-logo-vertical.svg"
      style="width: 200px; height: 200px"
    />
  </q-page>
</template>

<script setup>
import { useI18n } from "vue-i18n";

const { t } = useI18n();
</script>
```

### Expected behavior

To render the right plural. Ex: `t('adult', 2)`  renders `Adults`.

### Reproduction

https://github.com/andersonAlmeida/vue-i18n-plural

### System Info

```shell
System:
    OS: macOS 13.4
    CPU: (8) arm64 Apple M1
    Memory: 66.11 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.16.0 - ~/.nvm/versions/node/v16.16.0/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.11.0 - ~/.nvm/versions/node/v16.16.0/bin/npm
  Browsers:
    Chrome: 114.0.5735.133
    Safari: 16.5
  npmPackages:
    @intlify/vite-plugin-vue-i18n: ^3.3.1 => 3.4.0 
    vue: ^3.0.0 => 3.3.4 
    vue-i18n: ^9.0.0 => 9.2.2 
    vue-router: ^4.0.0 => 4.2.2
```

### Screenshot

![Captura de Tela 2023-06-22 às 18 44 00](https://github.com/intlify/vue-i18n-next/assets/2407499/c6e6fde5-a073-4aee-aa9f-b12efcafa0ba)
![Captura de Tela 2023-06-22 às 18 50 07](https://github.com/intlify/vue-i18n-next/assets/2407499/941b983d-f7f9-499a-8fbd-b4737e4db77e)

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/intlify/vue-i18n-next/blob/master/.github/CONTRIBUTING.md)
- [X] Read the [Documentation](https://vue-i18n.intlify.dev/)
- [X] Check that there isn't [already an issue](https://github.com/intlify/vue-i18n-next/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussions](https://github.com/intlify/vue-i18n-next/discussions)

**Comment by AnthonyRuelle** [comment]
Same problem here
it's really very blocking, it's supposed to go into production soon but this bug will stop me

Issue already exist #1428 
Up @kazupon  :)

**Comment by kazupon** [comment]
Hi!
Thank you for your reporting!

I've just checked your repository.
`@intlify/vite-plugin-vue-i18n` is not support `js` / `ts` format for resources.
You need use `json` or `yaml` or `json5`.

if you would like to use these format, you need to use `@intlify/unplugin-vue-i18n`.
BWT, `@intlify/vite-plugin-vue-i18n` will not support near the future and that is maintain phase.
I would recommend to use `@intlify/unplugin-vue-i18n`.
See the docs here: https://github.com/intlify/bundle-tools/tree/main/packages/unplugin-vue-i18n

Thanks!

**Comment by AllbusDoubledoor** [comment]
Setting `runtimeOnly: false` solved the problem.
<img width="668" alt="image" src="https://github.com/user-attachments/assets/77929ee2-43b5-4a90-b4a4-e96292140d03">
