### ISSUE TITLE
Module parse failed: Unexpected token

### ISSUE THREAD

**Issue by lyokth0241** [intlify/vue-i18n-next#1459]
### Reporting a bug?

Module parse failed: Unexpected token (1316:23)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|     if (shared.isString(source)) ;
|     else {
>         if (source.loc?.source) {
|             return source.loc.source;
|         }

### Expected behavior

don't have any question 

### Reproduction

|     if (shared.isString(source)) ;
|     else {
>         if (source.loc?.source) {
|             return source.loc.source;
|         }

 @ ./node_modules/@intlify/core-base/index.js 6:19-50
 @ ./node_modules/vue-i18n/dist/vue-i18n.mjs
 @ ./src/i18n/index.js
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://192.168.31.67:8081&sockPath=/sockjs-node (webpack)/hot/dev-server.js ./src/main.js

### System Info

```shell
--
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/intlify/vue-i18n-next/blob/master/.github/CONTRIBUTING.md)
- [X] Read the [Documentation](https://vue-i18n.intlify.dev/)
- [X] Check that there isn't [already an issue](https://github.com/intlify/vue-i18n-next/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussions](https://github.com/intlify/vue-i18n-next/discussions)

**Comment by kazupon** [comment]
Thank you for your reporting!

We need your minimal reproduction code.
Could you give us it, please ?

**Comment by kazupon** [comment]
close in-activity
if you have still issue, please open as new issue with minimal reproduction!

Thanks!

**Comment by JoedsonGabriel** [comment]
![image](https://github.com/intlify/vue-i18n-next/assets/45566621/483e0cd8-4397-4816-9f71-48ced1a90050)


Isso aconteceu comigo ao fazer upgrade da versão node 16.20.0 para 16.20.2

Veja que na versão 16.20.2 não ocorre o problema.
