### ISSUE TITLE
Typo in documentation when referring to translation component

### ISSUE THREAD

**Issue by AdrianAbramczyk** [intlify/vue-i18n-next#1475]
### Reporting a bug?

In the documentation https://vue-i18n.intlify.dev/api/component.html#translation
File: packages/vue-i18n-core/src/components/Translation.ts

The translation component is referred to as `i18n`

### Expected behavior

The documentation should refer to the translation component as `i18n-t`

### Reproduction

https://vue-i18n.intlify.dev/api/component.html#translation

### System Info

```shell
/
```

### Screenshot

![image](https://github.com/intlify/vue-i18n-next/assets/72611719/952eb6fd-2a3a-47a4-80fa-04505887d681)

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/intlify/vue-i18n-next/blob/master/.github/CONTRIBUTING.md)
- [X] Read the [Documentation](https://vue-i18n.intlify.dev/)
- [X] Check that there isn't [already an issue](https://github.com/intlify/vue-i18n-next/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussions](https://github.com/intlify/vue-i18n-next/discussions)

**Comment by kazupon** [comment]
Thank you for your reporting!
This issue is good first issue for open-source contribution.
If you have the time, you can contribute it! :)
