### ISSUE TITLE
v9.3.0 Pre-Release names do not follow common Semantic Versioning and cause tools to think there is a new (old) version `9.3.0-beta.14-77e850b` available

### ISSUE THREAD

**Issue by sceee** [intlify/vue-i18n-next#1481]
### Reporting a bug?

On npm, there is `9.3.0-beta.14-77e850b` published for `vue-i18n`. This is an older pre-release which is actually a lot older than the current published v9.3.0 pre-release (`9.3.0-beta.25`).

But because of the different formats of the pre-releases, tools like Renovate that follow Semver for package updates consider `9.3.0-beta.14-77e850b` to be "newer" than `9.3.0-beta.25` thus try to "update" from the installed `9.3.0-beta.25` to `9.3.0-beta.14-77e850b` (which is obviously wrong).

I _think_ this is because of [SemVer item 11.4.4](https://semver.org/#spec-item-11) ("A larger set of pre-release fields has a higher precedence than a smaller set, if all of the preceding identifiers are equal.").

### Expected behavior

Pre-Release names follow a common SemVer format so that tools following SemVer can correctly identify the newest pre-release.

### Reproduction

Have a project, install `vue-i18n` `^9.3.0-beta.25` and run Renovate against it. Renovate suggests to update from `9.3.0-beta.25` to `9.3.0-beta.14-77e850b` even though the latter is way older.

### System Info

```shell
n/a
```

### Additional context

This partially relates to #1445 .

Probably it is already fixed as the last releases on npm are now on a common format (..., 9.3.0-beta.23, 9.3.0-beta.24, 9.3.0-beta.25) and the issue is only that there is still the old pre-release available.
Then it would automatically be resolved from 9.3.1 or 9.4.0 onwards.

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/intlify/vue-i18n-next/blob/master/.github/CONTRIBUTING.md)
- [X] Read the [Documentation](https://vue-i18n.intlify.dev/)
- [X] Check that there isn't [already an issue](https://github.com/intlify/vue-i18n-next/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussions](https://github.com/intlify/vue-i18n-next/discussions)

**Comment by DJ-caddev** [comment]
NPM installs BETA 14 too when doing `npm update`.

**Comment by dacoto97** [comment]
Try to install directly beta.26
```
npm install vue-i18n@9.3.0-beta.26
```
Then install update package.json and install all dependencies again
```
"vue-i18n": "^9.3.0-beta.26",
```
![CleanShot 2023-08-26 at 01 30 40](https://github.com/intlify/vue-i18n-next/assets/16915053/c47809ac-6356-4e71-882b-2202cca25241)

**Comment by kazupon** [comment]
This is a mistake for my vue-i18n edge channel (canary) release.
sorry ...

That version is released as vue-i18n-edge now.
https://www.npmjs.com/package/vue-i18n-edge

**Comment by kazupon** [comment]
I believe this issue will go away when vue-i18n v9.3 is released.
