### ISSUE TITLE
import {createI18n} from "vue-i18n"; throw typescript error

### ISSUE THREAD

**Issue by ramseyfeng** [intlify/vue-i18n-next#1512]
### Reporting a bug?

trying to import the vue-i18n as below in a vite vue3 project:

`import {createI18n} from "vue-i18n";`

<img width="1007" alt="image" src="https://github.com/intlify/vue-i18n-next/assets/2835062/047b5d76-8e05-4e85-9b9f-b4312e605ac5">

### Expected behavior

vue3 project typescript import vue-i18n successfuly without throwing an error.

### Reproduction

`import {createI18n} from "vue-i18n";`

### System Info

```shell
"vite": "^4.4.9",
"typescript": "5.2.2"
    "vue": "^3.3.4",
"vue-i18n": "9.3.0-beta.27"
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/intlify/vue-i18n-next/blob/master/.github/CONTRIBUTING.md)
- [X] Read the [Documentation](https://vue-i18n.intlify.dev/)
- [X] Check that there isn't [already an issue](https://github.com/intlify/vue-i18n-next/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussions](https://github.com/intlify/vue-i18n-next/discussions)

**Comment by ntomka** [comment]
```SH
error TS7016: Could not find a declaration file for module 'vue-i18n'. '/srv/www/assets/node_modules/vue-i18n/dist/vue-i18n.esm-bundler.js' implicitly has an 'any' type.
  There are types at '/srv/www/assets/node_modules/vue-i18n/dist/vue-i18n.d.ts', but this result could not be resolved when respecting package.json "exports". The 'vue-i18n' library may need to update its package.json or typings.

3 import { createI18n } from 'vue-i18n';
```

**Comment by ramseyfeng** [comment]
It seems resolved after restarting intellij

**Comment by ntomka** [comment]
I'm sorry, but this is not the solution for me. :)

```
Could not find a declaration file for module 'vue-i18n'. '/node_modules/vue-i18n/dist/vue-i18n.esm-bundler.js' implicitly has an 'any' type.
  There are types at '/node_modules/vue-i18n/dist/vue-i18n.d.ts', but this result could not be resolved when respecting package.json "exports". The 'vue-i18n' library may need to update its package.json or typings.ts(7016)
```

I use vscode.

**Comment by ntomka** [comment]
It must have been something with the configuration of version 9.2.2. I just upgraded to 9.3.0 and the bug is gone.

**Comment by BenceSzalai** [comment]
Right. `types` were missing from `exports` in `package.json` in `v9.2.2`, but it is there in `v9.3.0`. This issue did not affect those using `moduleResolution` set to `node`, but once it is set to `nodenext` the `exports` are respected.
