### ISSUE TITLE
syntaxError: 11

### ISSUE THREAD

**Issue by lmjgyy** [intlify/vue-i18n-next#1514]
### Reporting a bug?

OS: windows
mode: electron production(development environment does not appear)
version:  9.2.2
description:  The string with "|" is incorrectly translated as 11。the string is `文件名称不能以.开头，且不能包含特殊字符\\/:*?"<>|`
![CleanShot 2023-09-01 at 14 38 08](https://github.com/intlify/vue-i18n-next/assets/53996952/31c22685-04ac-4246-b9db-8b7f5b094e0a)
![CleanShot 2023-09-01 at 14 38 57](https://github.com/intlify/vue-i18n-next/assets/53996952/b29ead5c-11d8-4c71-8a63-4031059ba2e2)

### Expected behavior

Correct translation

### Reproduction

can't provide

### System Info

```shell
windows 32/Electron 21.4.4/ vue 3.2.37 / vue-i18n 9.2.2
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/intlify/vue-i18n-next/blob/master/.github/CONTRIBUTING.md)
- [X] Read the [Documentation](https://vue-i18n.intlify.dev/)
- [X] Check that there isn't [already an issue](https://github.com/intlify/vue-i18n-next/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussions](https://github.com/intlify/vue-i18n-next/discussions)

**Comment by lmjgyy** [comment]
Even using unicode characters for "|" results in an error

**Comment by kazupon** [comment]
Thank you for your reporting!

`|` is special character.
https://vue-i18n.intlify.dev/guide/essentials/syntax.html#special-characters

so, it's used by vue-i18n message format.
if you want to use it, you need to avoid with using literal interpolation.
https://vue-i18n.intlify.dev/guide/essentials/syntax.html#literal-interpolation

Thanks!
