### ISSUE TITLE
Module parse failed: Unexpected token (1316:23)

### ISSUE THREAD

**Issue by JoedsonGabriel** [intlify/vue-i18n-next#1526]
### Reporting a bug?

This happened to me when upgrading from node version 16.20.0 to 16.20.2

![image](https://github.com/intlify/vue-i18n-next/assets/45566621/45255a24-5c1f-4af9-b409-b00092a1b6a0)

See that in version 16.20.0 the problem does not occur.

### Expected behavior

Build production with node v16.20.2

### Reproduction

just use the version node 16.20.2 

### System Info

```shell
-+ssssssssssssssssssyyssss+-         OS: Ubuntu 22.04.2 LTS x86_64 
    .ossssssssssssssssssdMMMNysssso.       Host: VivoBook_ASUSLaptop X513EAN_X5 
   /ssssssssssshdmmNNmmyNMMMMhssssss/      Kernel: 6.2.0-31-generic 
  +ssssssssshmydMMMMMMMNddddyssssssss+     Uptime: 1 hour, 41 mins 
 /sssssssshNMMMyhhyyyyhmNMMMNhssssssss/    Packages: 2754 (dpkg), 5 (flatpak),  
.ssssssssdMMMNhsssssssssshNMMMdssssssss.   Shell: bash 5.1.16 
+sssshhhyNMMNyssssssssssssyNMMMysssssss+   Resolution: 1920x1080, 1920x1080 
ossyNMMMNyMMhsssssssssssssshmmmhssssssso   DE: GNOME 42.9 
ossyNMMMNyMMhsssssssssssssshmmmhssssssso   WM: Mutter 
+sssshhhyNMMNyssssssssssssyNMMMysssssss+   WM Theme: Adwaita 
.ssssssssdMMMNhsssssssssshNMMMdssssssss.   Theme: Yaru-blue-dark [GTK2/3] 
 /sssssssshNMMMyhhyyyyhdNMMMNhssssssss/    Icons: Yaru-blue [GTK2/3] 
  +sssssssssdmydMMMMMMMMddddyssssssss+     Terminal: terminator 
   /ssssssssssshdmNNNNmyNMMMMhssssss/      CPU: 11th Gen Intel i7-1165G7 (8) @  
    .ossssssssssssssssssdMMMNysssso.       GPU: Intel TigerLake-LP GT2 [Iris Xe 
      -+sssssssssssssssssyyyssss+-         Memory: 4731MiB / 7628MiB
```

### Screenshot

![image](https://github.com/intlify/vue-i18n-next/assets/45566621/9fa14c6d-ea39-424a-8741-a1c0e22634a1)

### Additional context

issue with the same problem: 
https://github.com/intlify/vue-i18n-next/issues/1459

```
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file

|     if (shared.isString(source)) ;
|     else {
>         if (source.loc?.source) {
|             return source.loc.source;
|         }
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/intlify/vue-i18n-next/blob/master/.github/CONTRIBUTING.md)
- [X] Read the [Documentation](https://vue-i18n.intlify.dev/)
- [X] Check that there isn't [already an issue](https://github.com/intlify/vue-i18n-next/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussions](https://github.com/intlify/vue-i18n-next/discussions)

**Comment by JoedsonGabriel** [comment]
### Fiz um ajuste que resolveu o problema paleativamente.

**package.json**

Antes:
```
"vue-i18n": "^9.2.2",
```

Depois:
```
"vue-i18n": "9.2.2",
```

**Comment by kazupon** [comment]
Thank you for your reporting!

> After:
> ```
> "vue-i18n": "9.2.2",
> ```

This is 9.3.0, right? 😅 
If it is 9.2.2, please upgrade to 9.3.0 and see if you can reproduce it.And you would give us your reproduction. 🙏

**Comment by mityaua** [comment]
> Thank you for your reporting!
> 
> > After:
> > ```
> > "vue-i18n": "9.2.2",
> > ```
> 
> This is 9.3.0, right? 😅 If it is 9.2.2, please upgrade to 9.3.0 and see if you can reproduce it.And you would give us your reproduction. 🙏

Unfortunately same with 9.3.0
![Screenshot 2023-09-07 160127](https://github.com/intlify/vue-i18n-next/assets/20481332/6d83a5e5-8534-46af-a3fd-fee8fb225c8e)

**Comment by axof3873** [comment]
I've ran into the same error with version `9.3.0` Rolling back to `9.2.2` also fixed the problem.

```
Module parse failed: Unexpected token (1309:23)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|     if (shared.isString(source)) ;
|     else {
>         if (source.loc?.source) {
|             return source.loc.source;
|         }

 @ ./node_modules/@intlify/core-base/index.js 6:19-50
 @ ./node_modules/vue-i18n/dist/vue-i18n.mjs
 @ ./node_modules/cache-loader/dist/cjs.js??ref--15-0!./node_modules/babel-loader/lib!./node_modules/ts-loader??ref--15-2!./node_modules/cache-loader/dist/cjs.js??ref--1-0!./node_modules/vue-loader-v16/dist??ref--1-1!./src/App.vue?vue&type=script&lang=ts&setup=true
 @ ./src/App.vue?vue&type=script&lang=ts&setup=true
 @ ./src/App.vue
 @ ./src/main.ts
 @ multi (webpack)-dev-server/client?http://192.168.2.250:8080/&sockPath=/sockjs-node (webpack)/hot/dev-server.js ./src/main.ts
 ```

**Comment by kazupon** [comment]
Hi!

We need minimal reproduction.
We are providing starter.

- Reproduction mininal starter: https://stackblitz.com/edit/vitejs-vite-gfrx6w
- Reproduction starter with unpluguin-vue-i18n: https://stackblitz.com/edit/vitejs-vite-jnecup

Could you give your minimal reproduction please? 🙏

**Comment by kirangurung2023** [comment]
Followed 
https://cli.vuejs.org/core-plugins/babel.html
https://stackoverflow.com/questions/67068107/vue-config-js-transpiledependencies-is-not-work

For us adding this config in vue.config.js did the trick .

  transpileDependencies: [
    '@intlify'
  ],

**Comment by kazupon** [comment]
close in-activity
if you have still issue, please you can open a new issue with your minimal reproduction.

thanks!
