### ISSUE TITLE
vue-i18n-bridge 9.3.0 peer dependency warning

### ISSUE THREAD

**Issue by kingyue737** [intlify/vue-i18n-next#1529]
### Reporting a bug?

Add `vue-i18n-bridge@9.3.0` will also add `@vue/composition-api` as its dependency which conflicts with `vue@2.7`.

```
 WARN  Issues with peer dependencies found
.
└─┬ vue-i18n-bridge 9.3.0
  └─┬ @vue/composition-api 1.7.2
    └── ✕ unmet peer vue@">= 2.5 < 2.7": found 2.7.14 
```

### Expected behavior

No dependency warning

### Reproduction

https://stackblitz.com/edit/vitejs-vite-fjumap

### System Info

```shell
System:
    OS: Linux 5.0 undefined
    CPU: (6) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 16.20.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.4.2 - /usr/local/bin/npm
    pnpm: 8.6.10 - /usr/local/bin/pnpm
  npmPackages:
    vite: ^4.4.9 => 4.4.9 
    vue: 2.7.14 => 2.7.14 
    vue-i18n-bridge: ^9.3.0 => 9.3.0
```

### Screenshot

![image](https://github.com/intlify/vue-i18n-next/assets/40021217/7dac193c-d050-47db-a098-a0c533a97747)

### Additional context

Run `pnpm update` or add whatever dependency will show the warning

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/intlify/vue-i18n-next/blob/master/.github/CONTRIBUTING.md)
- [X] Read the [Documentation](https://vue-i18n.intlify.dev/)
- [X] Check that there isn't [already an issue](https://github.com/intlify/vue-i18n-next/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussions](https://github.com/intlify/vue-i18n-next/discussions)

**Comment by kazupon** [comment]
Thank you for reporting!

Hmm, 🤔 
vue-i18n-bridge is defining `@vue/composition-api` as `optionalDependencies`.
https://github.com/intlify/vue-i18n-next/blob/1124ef852d9a6c1b13da90369c6705cd8edcf74a/packages/vue-i18n-bridge/package.json#L48C4-L49

peerDependencies of vue-demi might be having an effect.
https://github.com/vueuse/vue-demi/blob/main/package.json#L39

As the workaround, you can overrides with package manager.
example for pnpm:

```json
  "pnpm": {
    "overrides": {
      "@vue/composition-api": "<1.7.0"
    }
  },
```

**Comment by kingyue737** [comment]
It seems that `optionalDependencies` are installed by default without `--no-optional` 
https://pnpm.io/cli/install#--no-optional

Use `peerDependenciesMeta` like what `vue-demi` does may be a better way https://github.com/vueuse/vue-demi/blob/80b8e939134c4d8e9457bd97235a46712ea0988a/package.json#L44
