### ISSUE TITLE
TypeScript error: Cannot find name 'MessageFunctionInternal'

### ISSUE THREAD

**Issue by SAMERkab** [intlify/vue-i18n-next#1533]
### Reporting a bug?

When using Vue I18n 9 with Vuetify and TypeScript, the following error message is output after running `npm run build`:
```
node_modules/@intlify/core-base/dist/core-base.d.ts:645:77 - error TS2304: Cannot find name 'MessageFunctionInternal'.

645 export declare type MessageFunction<T = string> = MessageFunctionCallable | MessageFunctionInternal<T>;
                                                                                ~~~~~~~~~~~~~~~~~~~~~~~


Found 1 error in node_modules/@intlify/core-base/dist/core-base.d.ts:645
```

The problem doesn't occur when using `npm run dev`.

### Expected behavior

A project using Vuetify and Vue I18n should build successfully.

### Reproduction

Run:
```sh
npm create vuetify
# Project name: ... vuetify-project
# Which preset would you like to install? » Essentials (Vuetify, VueRouter, Pinia)
# Use TypeScript? ... Yes
# Would you like to install dependencies with yarn, npm, or pnpm? » npm
cd ./vuetify-project
npm install vue-i18n@9
```
then add 
```ts
import { createI18n } from 'vue-i18n'
```
to `src/plugins/index.ts` and run `npm run build`.

Link to reproduction repo: https://stackblitz.com/edit/vitejs-vite-nei8kc?file=src%2Fplugins%2Findex.ts

### System Info

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (12) x64 AMD Ryzen 5 5500U with Radeon Graphics
    Memory: 1.14 GB / 7.31 GB
  Binaries:
    Node: 18.17.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - C:\Program Files\nodejs\yarn.CMD
    npm: 9.8.1 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.7.4 - C:\Program Files\nodejs\pnpm.CMD
  Browsers:
    Edge: Spartan (44.22621.2134.0), Chromium (116.0.1938.69)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    @vitejs/plugin-vue: ^4.0.0 => 4.3.4
    @vue/eslint-config-typescript: ^11.0.0 => 11.0.3
    vite: ^4.2.0 => 4.4.9
    vite-plugin-vuetify: ^1.0.0 => 1.0.2
    vue: ^3.2.0 => 3.3.4
    vue-i18n: ^9.3.0 => 9.3.0
    vue-router: ^4.0.0 => 4.2.4
    vue-tsc: ^1.2.0 => 1.8.10
    vuetify: ^3.0.0 => 3.3.15
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/intlify/vue-i18n-next/blob/master/.github/CONTRIBUTING.md)
- [X] Read the [Documentation](https://vue-i18n.intlify.dev/)
- [X] Check that there isn't [already an issue](https://github.com/intlify/vue-i18n-next/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussions](https://github.com/intlify/vue-i18n-next/discussions)

**Comment by masumbillah** [comment]
I'm facing same error message when create build. 
![image](https://github.com/intlify/vue-i18n-next/assets/5412179/3535642a-c872-45ff-a07c-a90b8e369eab)

**Comment by kazupon** [comment]
Thank you for your reporting!

Unfortunately, We need your minimal reproduction, so we cannot debug it ...

Could you give us your minimal reproduction please? 🙏 

Issue guideline is saying:

https://github.com/intlify/vue-i18n-next/issues/new?assignees=&labels=Status%3A+Review+Needed&projects=&template=bug-report.yml

>Please use a template below to create a minimal reproduction, and provide to us your issue cases
>👉 Reproduction mininal starter
>👉 Reproduction starter with unpluguin-vue-i18n

**Comment by masumbillah** [comment]
Thanks @kazupon  for reply.
