### ISSUE TITLE
lazy-loading example not work with vite 4.4.9/4.4.10

### ISSUE THREAD

**Issue by KANekT** [intlify/vue-i18n-next#1575]
### Reporting a bug?

example
https://github.com/intlify/vue-i18n-next/tree/master/examples/lazy-loading/vite

if I use vite 4.4.9/4.4.10 - in prod build not load lang files (work in dev mode)

for vite 4.4.8 it work in prod

### Expected behavior

-

### Reproduction

-

### System Info

```shell
System:
    OS: macOS 14.0
    CPU: (8) arm64 Apple M2
    Memory: 55.48 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.18.0 - /usr/local/bin/node
    npm: 10.1.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 117.0.5938.132
    Safari: 17.0
  npmPackages:
    @intlify/eslint-plugin-vue-i18n: ^2.0.0 => 2.0.0 
    @intlify/unplugin-vue-i18n: ^1.4.0 => 1.4.0 
    @intlify/vue-devtools: ^9.5.0 => 9.5.0 
    @vitejs/plugin-legacy: ^4.1.1 => 4.1.1 
    @vitejs/plugin-vue: ^4.4.0 => 4.4.0 
    @vue/eslint-config-typescript: ^12.0.0 => 12.0.0 
    vite: 4.4.9 => 4.4.9 
    vue: ^3.3.4 => 3.3.4 
    vue-advanced-cropper: ^2.8.8 => 2.8.8 
    vue-cal: ^4.8.1 => 4.8.1 
    vue-i18n: ^9.4.1 => 9.4.1 
    vue-observe-visibility: ^2.0.0-alpha.1 => 2.0.0-alpha.1 
    vue-router: ^4.2.5 => 4.2.5 
    vue-tsc: ^1.8.15 => 1.8.15
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/intlify/vue-i18n-next/blob/master/.github/CONTRIBUTING.md)
- [X] Read the [Documentation](https://vue-i18n.intlify.dev/)
- [X] Check that there isn't [already an issue](https://github.com/intlify/vue-i18n-next/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussions](https://github.com/intlify/vue-i18n-next/discussions)

**Comment by ankanlim** [comment]
We are having the same issue. Is anybody able to look into this?

**Comment by kazupon** [comment]
I've just updated lazy-loading example.
please check it.
