### ISSUE TITLE
useI18n with 'local' scope in custom hooks can't resolve messages when using in component with custom blocks.

### ISSUE THREAD

**Issue by notzheng** [intlify/vue-i18n-next#1583]
### Reporting a bug?

useI18n with 'local' scope in custom hooks can't resolve messages when using in component with custom blocks.

### Expected behavior

it can resolve 'tip' message correctly.

### Reproduction

https://stackblitz.com/edit/vitejs-vite-nw7gas?file=src%2FApp.vue

### System Info

```shell
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  npmPackages:
    @intlify/unplugin-vue-i18n: ^1.4.0 => 1.4.0 
    @vitejs/plugin-vue: ^4.2.3 => 4.4.0 
    typescript: ^5.0.2 => 5.2.2 
    vite: ^4.4.8 => 4.4.11 
    vue: ^3.3.4 => 3.3.4 
    vue-i18n: ^9.5.0 => 9.5.0 
    vue-tsc: ^1.8.8 => 1.8.16
```

### Screenshot

![CleanShot 2023-10-07 at 14 43 42](https://github.com/intlify/vue-i18n-next/assets/13414731/9f95d151-a9d2-4eaa-b012-4e1a2f6e7537)

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/intlify/vue-i18n-next/blob/master/.github/CONTRIBUTING.md)
- [X] Read the [Documentation](https://vue-i18n.intlify.dev/)
- [x] Check that there isn't [already an issue](https://github.com/intlify/vue-i18n-next/issues) that reports the same bug to avoid creating a duplicate.
- [x] Check that this is a concrete bug. For Q&A open a [GitHub Discussions](https://github.com/intlify/vue-i18n-next/discussions)

**Comment by brachkow** [comment]
Same issue there

**Comment by notzheng** [comment]
> Same issue there

This is my temporary solution, create a custom hooks:

```typescript
import { useI18n } from 'vue-i18n'

export const useLocalScopeI18n = (messages) => {
  const fns = useI18n({
    useScope: 'local',
    messages
  })

  /** @fix https://github.com/intlify/vue-i18n-next/issues/1583 */
  Object.entries(messages).forEach(([key, value]) => {
    fns.mergeLocaleMessage(key, value)
  })

  return fns
}
```

**Comment by kazupon** [comment]
Thank you for your reporting!

You seem to be calling `useI18n` with `useTip`. You are already calling `useI18n` in `<script setup>` in `App.vue`.
vue-i18n is not supposed to be called multiple times in Vue components in `setup`.
`useI18n` returns a `Composer` instance. You need to configure your composable with the `mergeLocaleMessage` or `t` that the instance exports.

Thanks!
