### ISSUE TITLE
Pass fallback translation as argument to `$t()`

### ISSUE THREAD

**Issue by BobbieGoede** [intlify/vue-i18n-next#1586]
### Clear and concise description of the problem

Let's say I am rendering the following message `$t('home.title')`, but this translation is loaded from an API. If the translation is not found at this key, the key itself `"home.title"` will be displayed. 

It would be nice to be able to provide a fallback translation at the function call to ensure a user friendly message is displayed.

### Suggested solution

It would be great to pass a fallback translation in the `$t()` function:

```ts
$t(key: string, fallbackText: string)
```

Using the scenario described above the usage would look like this: `$t('home.title', 'Homepage title')`, the user sees `"Homepage title"` if the translation is not found at that key, was unable to be loaded, or is empty.

### Additional context

This proposal was requested downstream at https://github.com/nuxt-modules/i18n/issues/2309. I have rewritten the description to clearly describe the feature and match the issue template.

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/intlify/vue-i18n-next/blob/master/.github/CONTRIBUTING.md)
- [X] Read the [Documentation](https://vue-i18n.intlify.dev/)
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by kazupon** [comment]
It is already provided as an API.
The following API is overloaded for `t` exported with `useI18n`, and it be the same for `$t`.

`(key: Key | ResourceKeys | number, defaultMsg: string, options?: TranslateOptions<Locales>): string;`
https://vue-i18n.intlify.dev/api/composition.html#key-key-resourcekeys-number-defaultmsg-string-options-translateoptions-locales-string
