### ISSUE TITLE
Unexpected token error

### ISSUE THREAD

**Issue by pclokcer** [intlify/vue-i18n-next#1604]
### Reporting a bug?

[https://prnt.sc/Vo77iKYxFMo5](url)

that is problem `?`

how can I fix ?

### Expected behavior

```js
if ('source' in source.loc) {
  return source.loc.source;
}
```

### System Info

```shell
node -v => 18.18.2
```

### Screenshot

https://prnt.sc/Vo77iKYxFMo5

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/intlify/vue-i18n-next/blob/master/.github/CONTRIBUTING.md)
- [X] Read the [Documentation](https://vue-i18n.intlify.dev/)
- [X] Check that there isn't [already an issue](https://github.com/intlify/vue-i18n-next/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussions](https://github.com/intlify/vue-i18n-next/discussions)

**Comment by christian-benseler-farm** [comment]
Same problem here.
