### ISSUE TITLE
[v9.6.4] Suppressing automatic locale fallback with `!` causes redundant `console.warn`s for missing keys

### ISSUE THREAD

**Issue by shengslogar** [intlify/vue-i18n-next#1626]
### Reporting a bug?

Thanks for a wonderful library!

`{ locale: 'en-US!' }` causes the library to `console.warn` about falling back to `en-US` for all translation keys, and appears to perform a redundant resolution step for missing keys.

### Expected behavior

`{ locale: 'en-US!' }` should be identical to `{ locale: 'en-US' }`, except with no fallback strategy, and no fallback-related `console.warn` logs should be present, [as detailed in the docs](https://vue-i18n.intlify.dev/guide/essentials/fallback.html#explicit-fallback-with-one-locale):

> To suppress the automatic fallback, add the postfix exclamation mark `!`, for example `de-DE!`

The final translation output is as expected, but the steps to get there are not.

### Reproduction

[StackBlitz repro](https://stackblitz.com/edit/vitejs-vite-msts1m?file=src%2Fmain.ts)

Open up browser developer tools to view console logs.

### System Info

```shell
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
Binaries:
    Node: 18.18.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.4.2 - /usr/local/bin/npm
    pnpm: 8.9.2 - /usr/local/bin/pnpm
npmPackages:
    @vitejs/plugin-vue: ^4.2.3 => 4.3.4 
    vite: ^4.4.9 => 4.4.9 
    vue: ^3.3.4 => 3.3.4 
    vue-i18n: ^9.6.4 => 9.6.4 
    vue-tsc: ^1.8.8 => 1.8.10
```

### Screenshot

![Screenshot of StackBlitz repro with developer tools opened to console logs. Four warning logs are circled for the "Test missing" key: fall back with en-US, not found in en-US, fall back with en-US, not found in en-US.](https://github.com/intlify/vue-i18n-next/assets/4350009/60a3b52a-7f1d-4dec-8236-c4b65816000e)

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/intlify/vue-i18n-next/blob/master/.github/CONTRIBUTING.md)
- [X] Read the [Documentation](https://vue-i18n.intlify.dev/)
- [X] Check that there isn't [already an issue](https://github.com/intlify/vue-i18n-next/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussions](https://github.com/intlify/vue-i18n-next/discussions)

**Comment by kazupon** [comment]
duplicate #1641
