### ISSUE TITLE
Export message merging utilities or move to shared

### ISSUE THREAD

**Issue by BobbieGoede** [intlify/vue-i18n-next#1634]
### Clear and concise description of the problem

We redefine/reimplement message merging in `@nuxtjs/i18n`, to prevent bugs and keep things stable it would be beneficial to make the message merging available for packages downstream. 

### Suggested solution

Either export the relevant utility functions from `vue-i18n` or maybe these can be moved to `@intlify/shared` instead?

### Additional context

I'm pretty sure there is a bug in the message merging in `@nuxtjs/i18n`

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/intlify/vue-i18n-next/blob/master/.github/CONTRIBUTING.md)
- [X] Read the [Documentation](https://vue-i18n.intlify.dev/)
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by kazupon** [comment]
@BobbieGoede 

>Either export the relevant utility functions from vue-i18n or maybe these can be moved to @intlify/shared instead?

I think it should be moved to `@intlify/shared`
You can push the PR :)
