### ISSUE TITLE
Suggestion: Do not use so many component properties

### ISSUE THREAD

**Issue by michaelzangl** [intlify/vue-i18n-next#164]
While I agree that using t() and d() and so on as helpers is useful, most of the properties added by useI18n are not required to be directly on the component. Especially, since they may clash with other properties and cause unexpected behavior when new ones are added later.

Those methods should be fine (people using single letter variables can be punished 😈):
```
d
n
t
tm
```

I suggest to move all those properties to a new i18n wrapper object, so that they need to be accessed using `this.i18n.availableLocales`:
```
availableLocales:Array[4]
datetimeFormats:Object (Computed)
escapeParameter:false
fallbackFormat:false
fallbackLocale:"en" (Computed)
fallbackRoot:true
fallbackWarn:true
getDateTimeFormat:ƒ getDateTimeFormat(locale)
getLocaleMessage:ƒ getLocaleMessage(locale)
getMissingHandler:ƒ getMissingHandler()
getNumberFormat:ƒ getNumberFormat(locale)
getPostTranslationHandler:ƒ getPostTranslationHandler()
id:3
inheritLocale:true
isGlobal:false
locale:"de" (Computed)
mergeDateTimeFormat:ƒ mergeDateTimeFormat(locale, format)
mergeLocaleMessage:ƒ mergeLocaleMessage(locale, message)
mergeNumberFormat:ƒ mergeNumberFormat(locale, format)
messages:Object (Computed)
missingWarn:true
modifiers:Object (empty)
numberFormats:Object (Computed)
pluralRules:undefined
setDateTimeFormat:ƒ setDateTimeFormat(locale, format)
setLocaleMessage:ƒ setLocaleMessage(locale, message)
setMissingHandler:ƒ setMissingHandler(handler)
setNumberFormat:ƒ setNumberFormat(locale, format)
setPostTranslationHandler:ƒ setPostTranslationHandler(handler)
warnHtmlMessage: true
```

**Comment by kazupon** [comment]
Thank you for your feedback!

This is vue-i18n-next bad example of what I'm currently offering ...  
I'll fix the examples code.

In general, when using the Compostion API, the style of use of Compostion API is to spread syntax the necessary functions and properties in `setup`, and return them as the render context, as shown below:

```js
setup () {
  const { t, locale } = useI18n({
    // something options
  }

  // somthing todo 
  // …

  return {
    t,
    locale
  }
}
```
