### ISSUE TITLE
My doubts about the architecture of vue-i18n-next

### ISSUE THREAD

**Issue by basvanmeurs** [intlify/vue-i18n-next#166]
I was looking for i18n in vue-next and had a look at vue-i18n-next. But to be honest it doesn't look very flexible, and it left me in confusion. I doubt if it is usable at all for me.

Vue-i18n-next seems just a static bucket of translations. You create it once, provide it a list of messages and then use it everywhere. But..
* What if you want to load the translations later, using an API call? 
* Or even add new translations on the fly?
* Are translations reactive at all?
* How would you create a reusable component, shared by multiple projects, carrying its own translations?

It does not make sense to me that you declare all messages in one place anyway.
Apps are usually divided into a component hierarchy. Components are meant to be independent. That's why nowadays you specify CSS within your vue SFC file. It makes sense to specify your translations within the component as well. And just like CSS inherits from the parent, it would be nice to inherit translations from the parent as well. It would be annoying to have to redeclare certain translations over and over within your app. And this pattern should allow you to override a translation in a sub component when needed. Maybe it should also support overriding translations of a reusable component by the parent.

I don't see any example covering this, and the library doesn't seem to allow chaining messages or date/number formats or something like it. Am I missing something?

**Comment by ducmerida** [comment]
@basvanmeurs maybe you need to check the [current version documentation](https://kazupon.github.io/vue-i18n/) because I see that documentation for this "next" version still pending (you can see the TODOs at the end of the Readme)

**Comment by psychonetic** [comment]
@basvanmeurs a lot of those things you have mentioned are already included in the project. Especially creating the translations in the components (https://kazupon.github.io/vue-i18n/guide/sfc.html#basic-usage) itself.
Regardless that you can do that, I think it's pretty hard to maintain translations in sfc. But this is something you may should try for yourself.
