### ISSUE TITLE
mutil call for useI18n not work

### ISSUE THREAD

**Issue by littleboarx** [intlify/vue-i18n-next#1689]
### Reporting a bug?

see: https://codesandbox.io/p/sandbox/vue3-i18n-forked-dpjcp4?file=%2Fsrc%2FApp.vue%3A22%2C1

### Expected behavior

t1 and t2 should work together

### Reproduction

see playground

### System Info

```shell
there's a front code sandbox
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/intlify/vue-i18n-next/blob/master/.github/CONTRIBUTING.md)
- [X] Read the [Documentation](https://vue-i18n.intlify.dev/)
- [X] Check that there isn't [already an issue](https://github.com/intlify/vue-i18n-next/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussions](https://github.com/intlify/vue-i18n-next/discussions)

**Comment by kazupon** [comment]
Thank you for your reporting!

vue-i18n doesn’t expect multiple calls to `useI18n` in the setup lifecycle. Because of the internal use of `inject/provie`.

Thanks
