### ISSUE TITLE
The README file in this repo has some bad links - [404:NotFound]

### ISSUE THREAD

**Issue by MrCull** [intlify/vue-i18n-next#169]
The README file in this repo has some bad links - [404:NotFound]

Status code [404:NotFound] - Link: https://github.com/intlify/vue-i18n-next/blob/master/examples/legacy/composition/translation.html
Status code [404:NotFound] - Link: https://github.com/intlify/vue-i18n-next/blob/master/examples/legacy/compostion/datetime-format.html
Status code [404:NotFound] - Link: https://github.com/intlify/vue-i18n-next/blob/master/docs/vue-i18n.md

This was found by an new experimental hobby project that I have just created: https://github.com/MrCull/GitHub-Repo-ReadMe-Dead-Link-Finder
If this has been in any way helpful then please consider giving the above Repo a Star.

p.s. the link given in the Issue template is also bad:
- Read the docs: https://github.com/intlify/vue-i18n/blob/master/README.md

**Comment by kazupon** [comment]
Thanks! I've stared you repo!
fixed with #170
