### ISSUE TITLE
Inconsistent behaviour with $te and $t regarding nested message notation

### ISSUE THREAD

**Issue by Lehren** [intlify/vue-i18n-next#1703]
### Reporting a bug?

Hi, I've noticed that `$te` will not see a translation exists if the message key contains periods and it is not in nested form in the messages object, but `$t` will translate the message correctly regardless. 
Example:

```
messages: {
"example.message": "Example message"
}
```

`$te('example.message')` : `false`
`$t('example.message')`: `'Example message'`

### Expected behavior

`$te` should see the message exists if it exists in the messages object, because clearly it can be translated correctly anyway by `$t`

### Reproduction

[Code sandbox](https://codesandbox.io/p/sandbox/dreamy-sun-h35j42?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clrhixfkv00063b6hres3sxvd%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clrhixfkv00023b6h9iejp5cm%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clrhixfkv00033b6hzibhvt6u%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clrhixfkv00053b6h2g0lf1pf%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clrhixfkv00023b6h9iejp5cm%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clrhixfku00013b6hwa4t5365%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clrhiyxat004j3b6h6ix5sjrw%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A4%252C%2522startColumn%2522%253A1%252C%2522endLineNumber%2522%253A85%252C%2522endColumn%2522%253A10%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252Fcomponents%252FHelloWorld.vue%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clrhixfkv00023b6h9iejp5cm%2522%252C%2522activeTabId%2522%253A%2522clrhiyxat004j3b6h6ix5sjrw%2522%257D%252C%2522clrhixfkv00053b6h2g0lf1pf%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clrhixfkv00043b6hgpjgxyz6%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clrhixfkv00053b6h2g0lf1pf%2522%252C%2522activeTabId%2522%253A%2522clrhixfkv00043b6hgpjgxyz6%2522%257D%252C%2522clrhixfkv00033b6hzibhvt6u%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clrhixfkv00033b6hzibhvt6u%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

### System Info

```shell
System:
    OS: Linux 6.1 Debian GNU/Linux 12 (bookworm) 12 (bookworm)
    CPU: (2) x64 AMD EPYC
    Memory: 784.07 MB / 2.01 GB
    Container: Yes
    Shell: Unknown
  Binaries:
    Node: 20.9.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.8.1 - /usr/local/bin/npm
    pnpm: 8.10.2 - /usr/local/share/npm-global/bin/pnpm
  npmPackages:
    @vue/cli-plugin-babel: ~4.5.0 => 4.5.6 
    @vue/cli-plugin-eslint: ~4.5.0 => 4.5.6 
    @vue/cli-service: ~4.5.0 => 4.5.6 
    @vue/compiler-sfc: ^3.0.0-0 => 3.0.0 
    vue: 3.2.45 => 3.2.45 
    vue-i18n: 9.9.0 => 9.9.0
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/intlify/vue-i18n-next/blob/master/.github/CONTRIBUTING.md)
- [X] Read the [Documentation](https://vue-i18n.intlify.dev/)
- [X] Check that there isn't [already an issue](https://github.com/intlify/vue-i18n-next/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussions](https://github.com/intlify/vue-i18n-next/discussions)

**Comment by dg-mann** [comment]
Hi @Lehren, 

there are two things i figured out:

1. $te checking in the 'en-US' locale where no translation is defined. Similarly, $t also checks 'en-US' but will use the fallback 'en' if no translation is found. To resolve this, you could set the default locale to 'en'
2. Additionally, $te won't work with the flat key annotation like "example.message". So the resulting snippet is: 


```
const i18n = createI18n({
  locale: "en",
  messages: {
    en: {
      example: {
        message: "Example message",
      },
    },
  },
});
```

Hope that helps!

**Comment by kazupon** [comment]
Thank you for your reporting!

As already mentioned, If you want to use keys in object path format, you must specify `flatJson: true` to createI18n. That will flatten the message inside vue-i18n.

Thanks
