### ISSUE TITLE
Linked messages cannot support non-nested syntax

### ISSUE THREAD

**Issue by fuping685** [intlify/vue-i18n-next#1719]
### Reporting a bug?

It works fine when I use nested syntax
```
const messages = {
  en: {
    message: {
      hello: 'Hello',
      hello_link: '@:message.hello'
    }
  }
}

<div>{{ $t('message.hello_link') }}</div> // Hello
```

It shows nothing when I use non-nested syntax
```
const messages = {
  en: {
    'message.hello': 'Hello',
    'message.hello_link': '@:message.hello'
  }
}

<div>{{ $t('message.hello_link') }}</div> // Nothing is shown
```

### Expected behavior

It works normally in version 8.x

### Reproduction

N/A

### System Info

```shell
N/A
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/intlify/vue-i18n-next/blob/master/.github/CONTRIBUTING.md)
- [X] Read the [Documentation](https://vue-i18n.intlify.dev/)
- [X] Check that there isn't [already an issue](https://github.com/intlify/vue-i18n-next/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussions](https://github.com/intlify/vue-i18n-next/discussions)

**Comment by kazupon** [comment]
Thank you for your reporting!

when you use the key of object path, you need to put `flatJson: true`  to `createI18n`.
Then vue-i18n will flatten the `message`.

Thanks!
