### ISSUE TITLE
Incorrect tm return type

### ISSUE THREAD

**Issue by MalkovVladimir** [intlify/vue-i18n-next#1772]
### Reporting a bug?

[Example from documentation](https://vue-i18n.intlify.dev/api/composition.html#tm-key) not working correctly. tm - returns `numer` type when you try to iterate via array

<img width="741" alt="image" src="https://github.com/intlify/vue-i18n-next/assets/22113671/8bb2a8a9-769a-416a-aeaa-b8e6fc3a0320">

### Expected behavior

`content` variable type should be 
```typescript
type Example = {
  title: 'Title1',
  paragraphs: Array[...],
}
```

### Reproduction

To reproduce it, go to [stackblitz](https://stackblitz.com/edit/vitejs-vite-a7xyzm?file=src%2FApp.vue) and run `yarn build`

<img width="399" alt="image" src="https://github.com/intlify/vue-i18n-next/assets/22113671/2aaf928d-543e-4513-92fb-7fe8e4d69cac">

### System Info

```shell
System:
    OS: macOS 12.5
    CPU: (10) arm64 Apple M1 Pro
    Memory: 136.16 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.2.0 - /usr/local/bin/node
    Yarn: 1.22.21 - /usr/local/bin/yarn
    npm: 8.9.0 - /usr/local/bin/npm
    bun: 1.0.18 - ~/.bun/bin/bun
  Browsers:
    Chrome: 123.0.6312.59
    Safari: 15.6
  npmPackages:
    @vitejs/plugin-basic-ssl: ^1.1.0 => 1.1.0 
    @vitejs/plugin-vue: ^5.0.3 => 5.0.4 
    vite: ^5.1.0 => 5.1.3 
    vite-svg-loader: ^5.1.0 => 5.1.0 
    vue: ^3.4.15 => 3.4.19 
    vue-i18n: ^9.10.2 => 9.10.2 
    vue-router: ^4.2.5 => 4.2.5 
    vue-tg: ^0.4.0 => 0.4.0 
    vue-tsc: ^1.8.27 => 1.8.27
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/intlify/vue-i18n-next/blob/master/.github/CONTRIBUTING.md)
- [X] Read the [Documentation](https://vue-i18n.intlify.dev/)
- [X] Check that there isn't [already an issue](https://github.com/intlify/vue-i18n-next/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussions](https://github.com/intlify/vue-i18n-next/discussions)

**Comment by kazupon** [comment]
Thank you!
This issue has duplicate #1686, so close

Thanks!
