### ISSUE TITLE
Warning: [vue-i18n] Not found parent composer. use the global composer. 

### ISSUE THREAD

**Issue by ivansieder** [intlify/vue-i18n-next#179]
## Steps done:
- installed latest vue version
- installed latest vue-i18n beta version

### vue & vue-i18n version
- vue 3.0.2
- vue-i18n: 9.0.0-beta.6

### Reproduction link
https://codesandbox.io/s/stupefied-nightingale-5kv28?file=/src/App.vue

When using the functional components (no matter if with or without named slots), a warning comes up in the application stating "[vue-i18n] Not found parent composer. use the global composer.". Now I'm not quiet sure if this is something that should be fixed or if it's something to be expected and if so, why does this warning shows up?

**Comment by kazupon** [comment]
Thank you for your feedback!

This warning is to be expected.
`<i18n-t>` component is generally used in SFC.
The i18n scope (composer) that `<i18n-t>` component refers to should be enabled in the component where it is used.

In the traditional API style of vue-i18n@v8.x (called legacy API), the scope is enabled by setting the resource with locale messages in the `messages` options of `i18n` or i18n custom block.
For Composition API, the locale messages are set and enabled scope by the `messages` option of `useI18n` in `setup`.

I've checked your code.

In the `App.vue`, there doesn't seem to be a call to `useI18n` in the `setup`, or `i18n` component options.
As a result, vue-i18n prints a warning like this one.

**Comment by ivansieder** [comment]
Thank you for the feedback. So the proper way to do this would be to use the useI18n in each Component and just return the needed messages, is that correct?

**Comment by kazupon** [comment]
If you have the locale messages defined by SFC, you need to have `useI18n` specify it in the `messages` options.

If you intentionally want to localize them with global scope locale messages (as specified in the `messages` options` of `createI18n`), there is no need to localize them on a per-component basis.

I'm working on vue-i18n-next (vue-i18n@v9) documentation for the release.
Built-in components such as the `<i18n-t>` component will be described with scope. :)

Note: 
that warning will be output development only, not output for production.

**Comment by ivansieder** [comment]
Thank you very much! So just to get it right: If I define messages in global scope, I can ignore the warning from <i18n-t>, <i18n-d> and <i18n-n>?

**Comment by kazupon** [comment]
yes! that's right!

**Comment by ivansieder** [comment]
Thank you very much and keep up the awesome work!
