### ISSUE TITLE
Guide leads to a 404

### ISSUE THREAD

**Issue by thany** [intlify/vue-i18n-next#1803]
### Reporting a bug?

On the homepage, the Guide link leads to a 404

### Expected behavior

Display the installation guide, I suppose. Probably [this one](https://github.com/intlify/vue-i18n-next/blob/master/docs/guide/installation.md)

### Reproduction

https://vue-i18n.intlify.dev/guide/

### System Info

```shell
Not relevant
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/intlify/vue-i18n-next/blob/master/.github/CONTRIBUTING.md)
- [X] Read the [Documentation](https://vue-i18n.intlify.dev/)
- [X] Check that there isn't [already an issue](https://github.com/intlify/vue-i18n-next/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussions](https://github.com/intlify/vue-i18n-next/discussions)

**Comment by kazupon** [comment]
Thank you for your reporting!

How did you get to that link?
I would it if you could tell us the source of the link. 🙏

**Comment by thany** [comment]
Sorry yea, I just clicked the top navigation. I thought it was obvious because that is (seemingly) the only entrypoint to the getting started guides. Thanks for fixing!
