### ISSUE TITLE
[vue-i18n] Object Spread { ...options } in VueI18n Next not supported by all Browsers

### ISSUE THREAD

**Issue by d3orn** [intlify/vue-i18n-next#184]
Greetings, 
Thanks a lot for your work!

VueI18n is using some object spread operations which are not converted to <ES2018.

### vue & vue-i18n version
- vue: 3.0.0
- vue-i18n: 9.0.0-beta.6

### What is Expected?
The final product (node_module dist build) might want to take into consideration to target older versions (not supporting object spread) as well.

This can be for Example found in 

- vue-i18n.cjs.js: Unexpected token (1137:52)
- vue-i18n.global.js: Unexpected token (1516:54)

and other places.

Thanks a lot for reaching out and if there is something I can do to fix this, might be a babel config I am forgetting, please let me know

**Comment by kazupon** [comment]
related #331

**Comment by jiangjunfeng98** [comment]
hi，This line of code is missing

https://github.com/intlify/vue-i18n-next/blob/a1ac943deeeb2bf5131a14d38f24545a5399605a/packages/vue-i18n/src/i18n.ts#L626

**Comment by kazupon** [comment]
Oh, Good catch! 😂 
Thanks!
I've just fixed #454
I'll release v9.1.5 later

**Comment by jiangjunfeng98** [comment]
你好，9.1.5大概什么时候发布呢？我急需修复 `Object Spread` 在 Edge（<79）的展示问题 

Baidu Translate：

Hello, when will 9.1.5 be released? I urgently need to fix the display problem of 'object spread' in edge (< 79). Thanks

**Comment by jiangjunfeng98** [comment]
你好，9.1.5大概什么时候发布呢？我急需修复 `Object Spread` 在 Edge（<79）的展示问题 

Baidu Translate：

Hello, when will 9.1.5 be released? I urgently need to fix the display problem of  'object spread'  in edge (< 79). Thanks

**Comment by kazupon** [comment]
I've just released it.
please check it!

**Comment by jiangjunfeng98** [comment]
it's ok. thanks
