### ISSUE TITLE
can't change local 

### ISSUE THREAD

**Issue by Alymbek** [intlify/vue-i18n-next#186]
### vue & vue-i18n version
"vue": "^3.0.2",
"vue-i18n": "^9.0.0-beta.6",
"@intlify/vue-i18n-loader": "^2.0.0-beta.1",

### Steps to reproduce
as mentioned here - https://kazupon.github.io/vue-i18n/guide/locale.html

		methods: {
			changeLanguage: function (language) {
				this.$root.$i18n.locale = language;
			},
		},
### What is Expected?
all  messages should change to selected local

### What is actually happening?
doesn't change

**Comment by Alymbek** [comment]
![ky](https://user-images.githubusercontent.com/2016702/98824773-1d71a180-244d-11eb-9966-3a2b4b8b5c63.PNG)

from I18n Resource Inspector I can see empty Global Scope, and all Local Scopes with messages.

seems like local scope doen't merge with global scope?

can somebody provide detailed gide for this version pls?
all info about previous version which is frustrating us.

**Comment by Alymbek** [comment]
![ru](https://user-images.githubusercontent.com/2016702/98825332-cae4b500-244d-11eb-9443-24aa1fb7065b.PNG)

this is for some local component messages

**Comment by kazupon** [comment]
I’m writing the document now.
It's still a WIP, but you can read this document
https://vue-i18n-next.intlify.dev/

**Comment by Alymbek** [comment]
@kazupon , thank you for reply!
will check tomorrow.

**Comment by Alymbek** [comment]
hi, dear @kazupon .

thank you for official manual!

I have few questions:
1. I just follow https://vue-i18n-next.intlify.dev/essentials/scope.html#local-scope-2 to make global changing locales, but can't use it from component - how to embed/link/ref global instance of i18n from main.js to other separate vuejs components?

2. inheritance of locales work from root to children, not in the opposite direction. How to import components locales to global scope?

**Comment by Alymbek** [comment]
with below code I can change only Local Scope messages:

	methods: {
			changeLanguage: function (language) {
				this.$i18n.locale = language;
		}
	}

CAn't find global instance from components

**Comment by Alymbek** [comment]
I guess there are wrong code sample in Notice:

![miss](https://user-images.githubusercontent.com/2016702/98917732-2c586280-24e6-11eb-98b2-347661f9f108.PNG)

**Comment by kazupon** [comment]
Sorry bad document …
I’ve fixed docs.
You can use `$root.$i18n.locale`.

**Comment by Alymbek** [comment]
![root](https://user-images.githubusercontent.com/2016702/99177812-644de880-2726-11eb-9456-351777661618.PNG)
hi, dear @kazupon .
in this case I'm getiing error: Uncaught ReferenceError: $root is not defined
see att.ss.

**Comment by Alymbek** [comment]
can get value from this.$root.$i18n.locale.
but changing this value doesn't change locales on page.

**Comment by kazupon** [comment]
@Alymbek 
Thank you for your feedback!
Hmm...  🤔 
Could you give me minimum reproduction codes with GitHub rep, please? 🙏

**Comment by Alymbek** [comment]
Hi, dear @kazupon .
Pls check it here - https://github.com/Alymbek/vue3-i18n-next

It is standard Vue-3 app generated by vue-cli with your library only

**Comment by Alymbek** [comment]
language changing proceed here - https://github.com/Alymbek/vue3-i18n-next/blob/master/src/pages/layout/components/Language.vue

**Comment by Alymbek** [comment]
hi, dear @kazupon .
any news?

**Comment by kazupon** [comment]
Thank you for your repo!

The vue-i18n architecture has been redesigned for Vue 3. As a result, 
I've found a case where I can't change the global scope locale via `this.$root.$i18n`.
To solve this problem, I'm going to do `$$i18n` to make the global scope referenceable.

I'll add `$$i18n` to access to the global scope.
I'll add `$$i18n` to access to the global scope, which is provided by both the Legacy mode and Composition mode.

Examples of the use of the legacy mode and composition mode are as follows:

## Legacy mode

```js
method: {
  changeLocale(locale) {
    this.$$i18n.locale = locale
  }
}
```


## Composition mode

### explicit 

script:

```js
setup() {
  const { locale, t } = useI18n() // return global scope composer

  // something todo ...
  // 

  return { locale, t }
}
```

template:

```html
<form>
  <select v-modle="locale>
    <option value="ja">ja</option>
    <option value="en">en</option>
  </select>
</form>
<p>{{ t('msg') }}</p>
```

### implicit

use `$$i18n` in template:

```html
<form>
  <select v-modle="$$i18n.locale">
    <option value="ja">ja</option>
    <option value="en">en</option>
  </select>
</form>
<p>{{ $t('msg') }}</p>
```

In the composition mode, `$$i18n` and `$t` (other `$t`, `$d`, and `$tm`) are inejcted to component as prop and function of global scope.

@Alymbek 
What do you think about this?

**Comment by Alymbek** [comment]
I'm going crazy with migration from vue2 to vue3, and from $ to $$ will make me crazy more...

No other simple solution? Need to make request to vue3 developer with this issue.

But all up to you, as you are Shogun of this library!

Waiting new release from you!

**Comment by Alymbek** [comment]
hi, dear @kazupon .

I just update to latest `9.0.0-beta.7`, but still can't change global scope.

So, how we can do it? Can you provide some example based on my repo pls?

**Comment by kazupon** [comment]
I've just fixed. 
You can install 9.0.0-beta.8

**Comment by Alymbek** [comment]
thank you, dear @kazupon !

now it is working well as expected:

**Comment by kazupon** [comment]
Enjoy! Happy! Coding! :)

**Comment by Alymbek** [comment]
thank you!

I just update  https://github.com/Alymbek/vue3-i18n-next.
you can refer as sample and testing.
