### ISSUE TITLE
About display problems after changing language

### ISSUE THREAD

**Issue by FlyFishCode** [intlify/vue-i18n-next#189]
### vue & vue-i18n version
- vue: 3.0.0-alpha.10
- vue-i18n: 9.0.0-alpha.0

### Steps to reproduce
After switching languages

![image](https://user-images.githubusercontent.com/37266998/99135267-79f6db80-265c-11eb-8507-4f5e42315b84.png)
![image](https://user-images.githubusercontent.com/37266998/99135301-9b57c780-265c-11eb-916a-08d36e8b212a.png)

### What is Expected?
After switching languages, the fields selected in the drop-down box are not changed to the corresponding language
### What is actually happening?
After switching languages, the field selected in the drop-down box is changed to the corresponding language

ps:
Did I use it wrong? thank you

**Comment by Alymbek** [comment]
hi, @FlyFishCode .

1) update to "vue": "^3.0.2"and  "vue-i18n": "^9.0.0-beta.6" (I'm using https://www.npmjs.com/package/npm-check-updates, to keep all updated).

2) where your messages was declared? see here - https://vue-i18n-next.intlify.dev/essentials/scope.html#local-scope

I guess in SFC, in this case use **legacy: true** option. See here - https://github.com/intlify/vue-i18n-next/issues/183

For SFC see here - https://vue-i18n-next.intlify.dev/advanced/sfc.html#basic-usage

If still getting issue pls show screenshot of web-browser's dev-tool log tab. 
More details - https://developers.google.com/web/tools/chrome-devtools

**Comment by Alymbek** [comment]
Was fixed in `9.0.0-beta.8`

see here - https://github.com/intlify/vue-i18n-next/issues/186

**Comment by kazupon** [comment]
close due to in-activity
if you have the issue, you can open new issue!
