### ISSUE TITLE
Uncaught ReferenceError: exports is not defined

### ISSUE THREAD

**Issue by lqsong** [intlify/vue-i18n-next#209]
### vue & vue-i18n version
ex:
- vue: 3.0.4
- vue-i18n: v9.0.0-beta.9

### What is actually happening?

![image](https://user-images.githubusercontent.com/22975974/101122394-615f5d00-362d-11eb-8174-564095f537a7.png)

**Comment by Daniel-Kao** [comment]
same here, any solutions?

**Comment by kazupon** [comment]
fixed with #211

**Comment by lqsong** [comment]
> same here, any solutions?

Should be this version of the BUG, waiting to be fixed！

**Comment by kazupon** [comment]
I've fixed and relesed v9.0.0-beta.10.
you can check it!
