### ISSUE TITLE
[vite] ignored dynamic import(`./locales/${locale}.js`) in /@/i18n.ts.

### ISSUE THREAD

**Issue by mzl1988** [intlify/vue-i18n-next#210]
![image](https://user-images.githubusercontent.com/11645762/101129233-33354980-363c-11eb-889f-5d3f2cf62394.png)
[vite] ignored dynamic import(`./locales/${locale}.js`) in /@/i18n.ts.

**Comment by kazupon** [comment]
Thank you for your feedback!

I seem that it's vite problem, not a vue-i18n problem. 🤔 
Vite follows the specification of es imports and imports.
It's up to vite's implementation whether or not it supports the dynamic import of typescript.
