### ISSUE TITLE
Dynamic Language Change

### ISSUE THREAD

**Issue by Failip420** [intlify/vue-i18n-next#215]
is it possible to dynamically change language?
I would like to press a button to toggle the language between english and swedish for example
how can i do it?

**Comment by Alymbek** [comment]
hi, dear @Failip420 .
please check it here - https://github.com/intlify/vue-i18n-next/issues/186

**Comment by kazupon** [comment]
@Alymbek is as mentioned.
Please read document together.
https://vue-i18n-next.intlify.dev/
