### ISSUE TITLE
Datetime Formatting  Not found 'short' key in 'en' locale message

### ISSUE THREAD

**Issue by albertcito** [intlify/vue-i18n-next#220]
I created a [basic example](https://github.com/albertcito/vue-i18n-temp) with Vue3 and vue-i18n-next (`^9.0.0-beta.10`) I followed the [ instruction](https://vue-i18n-next.intlify.dev/essentials/datetime.html#basic-usage) and I reviewed the example [date-time file](https://github.com/intlify/vue-i18n-next/blob/master/examples/composition/datetime.html) but in any case I'm no able to display the date in my view with the `d` function. I just return this message:

`Not found 'short' key in 'en' locale messages.`

I don't know what I'm doing wrong or maybe it's an issue. The main files are (the [repo here](https://github.com/albertcito/vue-i18n-temp)): 

main.ts
```typescript 
const i18n = createI18n({
    legacy: false,
    dateTimeFormats: {
      en: {
        short: {
          year: 'numeric',
          month: 'short',
          day: 'numeric',
        },
        long: {
          year: 'numeric',
          month: 'short',
          day: 'numeric',
          weekday: 'short',
          hour: 'numeric',
          minute: 'numeric',
        },
      },
    },
    locale: 'en',
    fallbackLocale: 'en',
    messages: {
      en: {
        message: {
          hello: 'hello world',
        },
      },
    },
  });

createApp(App)
    .use(router)
    .use(i18n)
    .mount('#app')
```

Vue file
```vue
<h1>
      Current time: "{{ d(new Date(), 'short') }}"
</h1>
...
<script lang="ts">
export default defineComponent({
  name: 'App',
  setup() {
    const { d } = useI18n();
    return {
      d,
    };
  },
});
</script>
```

**Comment by kazupon** [comment]
Thank you for your reporting!

I found typo.

> dateTimeFormats

the bellow is correct.

> datetimeFormats

**Comment by tiltec** [comment]
This seems to be a breaking change, in v8 spelling was 'dateTimeFormats': https://github.com/intlify/vue-i18n-next/blob/master/docs-old/guide/datetime.md

Should I open a new issue to add this to https://vue-i18n-next.intlify.dev/guide/migration/breaking.html?

**Comment by kazupon** [comment]
Indeed, you're right.
This would be a breaking change.
I'll update the documentation.
