### ISSUE TITLE
Syntax Error: TypeError: vue_i18n_1.friendlyJSONstringify is not a function

### ISSUE THREAD

**Issue by Alymbek** [intlify/vue-i18n-next#232]
### vue & vue-i18n version
```
"vue": "^3.0.4",
"vue-i18n": "^9.0.0-beta.12",
"@intlify/vue-i18n-loader": "^2.0.0-beta.2",
```

### Reproduction Link

https://github.com/Alymbek/vue3-i18n-next

### Steps to reproduce
standard
### What is Expected?
should work
### What is actually happening?
getting error message:
`Syntax Error: TypeError: vue_i18n_1.friendlyJSONstringify is not a function`

![error](https://user-images.githubusercontent.com/2016702/102175082-43f58300-3eb8-11eb-8035-e3bffad5fcef.PNG)

**Comment by kazupon** [comment]
Sorry, I'm working on vue-i18n-loader
https://github.com/intlify/vue-i18n-loader/pull/141

Please, a little waiting!

**Comment by Alymbek** [comment]
hi, dear @kazupon !

no issue, pls take your time.

**Comment by kazupon** [comment]
I've just releasd out.
You nedd to install the below versions:

- `vue-i18n`: 9.0.0-beta.15
- `@intlify/vue-i18n-loader`: 2.0.0-beta.3

**Comment by Alymbek** [comment]
thank you, dear @kazupon !

I can confirm - in latest versions it is working as expected.
