### ISSUE TITLE
vue binding expression cannot be translated

### ISSUE THREAD

**Issue by softboy99** [intlify/vue-i18n-next#241]
the following editor-options cannot be translated:      
`<dx-item
        data-field="rememberMe"
        editor-type="dxCheckBox"
        :editor-options="{ text: `$t('login_form.Remember_me')`, elementAttr: { class: 'form-text' } }"
 >`

**Comment by kazupon** [comment]
I could not reproduce vue binding expression issue.
This is not  vue-i18n issue, so close it.

If you can resolve this issue, you can open a new issue with minimum  reproduction codes and error message.
