### ISSUE TITLE
Unable to parse linked message with parentheses

### ISSUE THREAD

**Issue by ota-meshi** [intlify/vue-i18n-next#244]
### vue & vue-i18n version
- @intlify/message-compiler: 9.0.0-beta.10

### Reproduction Link

In format-explorer:

http://localhost:8080/#%7B%22src%22%3A%22%40%3A(interpolation.path)%22%7D

### Steps to reproduce

Parse the following message.

```
@:(interpolation.path)
```

### What is Expected?

I expected to generate a link with `interpolation.path` as the key. I think I was able to parse it in version 8.

### What is actually happening?

The parses will fail. Is this a feature that was intentionally removed?

**Comment by kazupon** [comment]
>The parses will fail. Is this a feature that was intentionally removed?

Yeah! This is intentionally breaking change.
In Vue I18n v9 or later, brackets are no longer needed as the message format compiler allows you to handle named, list, and literal interpolations.

https://vue-i18n-next.intlify.dev/migration/breaking.html#remove-brackets-grouping-for-linkekd-messages

**Comment by ota-meshi** [comment]
Thank you for letting me know! Sorry, I missed the migration guide.
I'm working on change to use `@intlify/message-compiler` with `eslint-plugin-vue-i18n`.
However, I've found that it doesn't parse well if the user uses an older version of the message format, so I'll consider what to do with this. 
I close this issue. Thank you!

**Comment by kazupon** [comment]
@ota-meshi 
Thanks!

If you would like to API (e.g parser) that you want something (e.g. token included at AST), you can contribution or discussion. 😉
