### ISSUE TITLE
Because message compiler isn't included.

### ISSUE THREAD

**Issue by Brouilles** [intlify/vue-i18n-next#249]
`The message format compilation is not supported in this build. Because message compiler isn't included. You need to pre-compilation all message format. So translate function return 'login.rememberMe'.` 
 
 In Electron application.

**Comment by nicojmb** [comment]
in beta.15 all translations fails for me.

**Comment by Brouilles** [comment]
@nicojmb Yes, it's since the beta.15. But rollback (with clean node_module) don't work.

**Comment by kazupon** [comment]
Thank you for your feedback!
Sorry, bad vue-i18n-next documentation.

vue-i18n locale messages & i18n custom block will be pre-compiled from vue-i18n@9.0.0-beta.15 for performance optimization & CSP support.
This is not yet reflected in the documentation, you can check the differences in the provided packages here.
https://github.com/intlify/vue-i18n-next/blob/master/docs/installation.md#explanation-of-different-builds

(The provided package is almost identical to Vue 3.)
https://v3.vuejs.org/guide/installation.html#release-notes

If you get a warning, the compiler is not included, only the runtime is provided.
In general, you need to use a loader/plugin such as vue-i18n-loader (a similar plugin will be provided for vite & rollup in near the future) configured for each bundler.
I'll support vue-cli-plugin-i18n soon.

**Comment by kazupon** [comment]
vue-i18n-loader latest docs here:
https://github.com/intlify/vue-i18n-loader#rocket-i18n-resource-pre-compilation

**Comment by kazupon** [comment]
if you cannot wait vue-cli-plugin-i18n next major version release, you can configure the below docs:
https://github.com/intlify/vue-i18n-next/blob/master/docs/advanced/sfc.md#vue-cli

**Comment by Brouilles** [comment]
Thanks for your help and time.

**Comment by anncwb** [comment]
@kazupon Does vite have related plugins? If not, I can only fix the version to beta.14

**Comment by kazupon** [comment]
I working on now :)

**Comment by nicojmb** [comment]
> if you cannot wait vue-cli-plugin-i18n next major version release, you can configure the below docs:
> https://github.com/intlify/vue-i18n-next/blob/master/docs/advanced/sfc.md#vue-cli

Hi, i tried to configure with this doc but messages are note traslated, ¿do you have any example how i configure?

> [intlify] Not found 'forms.validation.default' key in 'es' locale messages.

**Comment by tarkhil** [comment]
```
//import { createI18n } from "vue-i18n";
import { createI18n } from "vue-i18n/dist/vue-i18n.esm-bundler.js";
```
saved me, but this move is ugly and quite unclear documented

**Comment by kazupon** [comment]
close, due to I wrote docs here:
https://vue-i18n-next.intlify.dev/advanced/optimization.html#improve-performance-and-reduce-bundle-size-with-runtime-build-only

**Comment by Kameecoding** [comment]
link leads to 404

**Comment by kazupon** [comment]
https://vue-i18n-next.intlify.dev/guide/advanced/optimization.html#improve-performance-and-reduce-bundle-size-with-runtime-build-only
