### ISSUE TITLE
9.0.0-beta.15 regressions with simple setup (no JSON translations or i18n block)

### ISSUE THREAD

**Issue by cexbrayat** [intlify/vue-i18n-next#254]
### vue & vue-i18n version
ex:
- vue: 3.0.4
- vue-i18n: 9.0.0-beta.15

### Reproduction Link

https://github.com/cexbrayat/vue-cli-playground/pull/4

### Steps to reproduce

The application uses a very simple setup (no external file or <i18n> block):
```
const i18n = createI18n({
  locale: 'en',
  messages: {
    en: {
      hello: 'Hello i18n'
    }
  }
})
```

Run `yarn` and `yarn serve` to launch the application.
The translation is not displayed. 
Rollback to beta.14 and the translation is displayed again.

`yarn serve --mode production` is completely broken with beta.15: the application does not start and throws:
```
TypeError: s is not a function
    U core-base.esm-bundler.js:460
    D core-base.esm-bundler.js:344
    W vue-i18n.runtime.esm-bundler.js:570
    R vue-i18n.runtime.esm-bundler.js:536
    W vue-i18n.runtime.esm-bundler.js:570
```

### What is Expected?

For a simple setup as the one in the repro, with the messages not provided in an external file or in an <i18n> block, I would expect beta.15 to work as beta.14.

### What is actually happening?

In dev mode, the translations are not displayed with the following warnings:

```
You are running the esm-bundler build of vue-i18n. It is recommended to configure your bundler to explicitly replace feature flag globals with boolean literals to get proper tree-shaking in the final bundle. vue-i18n.runtime.esm-bundler.js:270
You are running a development build of vue-i18n.
Make sure to use the production build (*.prod.js) when deploying for production. vue-i18n.runtime.esm-bundler.js:284
[intlify] The message format compilation is not supported in this build. Because message compiler isn't included. You need to pre-compilation all message format. So translate function return 'hello'.
```

In pro mode, the application is broken.

**Comment by otabekoff** [comment]
This error also happening in my project. I created it today.
