### ISSUE TITLE
Lazy loading with vue-router fails

### ISSUE THREAD

**Issue by screets** [intlify/vue-i18n-next#259]
- vue: 3.0.4
- vue-i18n: 9.0.0-beta.16
- vue-router: 4.0.1

### Test repo Link
https://github.com/screets/_i18n-test

### Issues

I've followed both "examples" directory and documentation to apply vue-i18n and vue-router. The language has changed successfully when you do through "select" field found on the header.

- It does NOT work when you call website in another url (i.e. mydomain.com/tr/about)
- It gives fallback errors on browser console although it translate it

<img width="495" alt="Screen Shot 2020-12-23 at 12 08 09" src="https://user-images.githubusercontent.com/969912/102979812-a46b6c80-4517-11eb-8322-7687d664fbe0.png">

### What is Expected?

No browser errors and should work when you directly request page for another language (i.e. mydomain.com/tr/about)

Any help will highly appreciated!

**Comment by kazupon** [comment]
Thank you for your feedback!

Hmm, I ported it from the vue-i18n@v8 docs. 
https://kazupon.github.io/vue-i18n/guide/lazy-loading.html

But it seems that Vue 3 didn't take into account vue-router `beforeEach` navigation guard and vue rendering timing enough.

We need to improve the example code.  we should lazy load the i18n resource, set it to the i18n instance, and then render the component.

**Comment by PeterAlfredLee** [comment]
Hi @kazupon @screets 

I just pushed a fix #278 for this.
But the warnings still exist and I have no ideas about them. Maybe you have some ideas?

**Comment by screets** [comment]
Hey Intlify/vue-I18n-Next,

We got your help request!
One of our agents will respond to you, asap (usually in *1 business day*).

Note that we don't work on weekends.
However, if we release a major update recently, we are following the
issues.

For support questions, please also email us *s**creets API key* which is
required for support questions.
If you already included in your message, you don't need to do anything else.

Best,
screets
{#HS:1387745957-7764#}

**Comment by kazupon** [comment]
@PeterAlfredLee 
Thank you for your contribution!
I've just updated lazy-lading examples
https://github.com/intlify/vue-i18n-next/commit/09776ef63a317aadd75894ec92bbb137ddeac069

>But the warnings still exist and I have no ideas about them. Maybe you have some ideas?

I've fixed this issue.
Please check it!

**Comment by PeterAlfredLee** [comment]
LGTM

**Comment by screets** [comment]
Thank you for your update guys. It's working well for us too. 
Great job!
