### ISSUE TITLE
$d work only with one parameter

### ISSUE THREAD

**Issue by RollingTL** [intlify/vue-i18n-next#260]
### vue & vue-i18n version
- "vue": "^3.0.4",
- "vue-i18n": "^9.0.0-beta.15",

### Steps to reproduce
**main.js**
```
const dateTimeFormats = {
  'en-US': {
    short: {
      year: 'numeric',
      month: 'short',
      day: 'numeric'
    },
    long: {
      year: 'numeric',
      month: 'short',
      day: 'numeric',
      weekday: 'short',
      hour: 'numeric',
      minute: 'numeric'
    }
  },
  'kz-KZ':  // same as en-US
}

const i18n = createI18n({
  globalInjection: true,
  legacy: false,
  locale: 'en',
  fallbackLocale: 'en',
  availableLocales: [  'en', 'kz'],
  messages: messageDictionary(),
  dateTimeFormats // tried also dateTimeFormats: dateTimeFormats with same result
})

const app = createApp(App)
app.use(i18n)
```

**inside vue template**
```
{{ $d(new Date()}}  // outputs 23.12.2020
{{ $d(new Date(), 'long', 'en-US') }}  // outputs nothing
```

The problem I face is that - $d(new Date(), 'long', 'en-US') not working.

Also please help how to output date like 12 April 2020 (month name)
And  one more question - $d(new Date()  gives different date formats depending on locale, where can I ajust such formats? How does to know current locale without third param?

**Comment by RollingTL** [comment]
checked with "vue-i18n": "^9.0.0-beta.16" and get similar behaviour.

this.$d(new Date(), 'long') return empty line.

**Comment by kazupon** [comment]
Thank  you for your feedback!

I could find the typo.

> `dateTimeFormats` 

That is `datetimeFormats`.
You can check the API reference: https://vue-i18n-next.intlify.dev/api/composition.html#datetimeformats-2

**Comment by RollingTL** [comment]
Thank you

**Comment by BobbieGoede** [comment]
@jarkt 
This issue has been closed for years, please open a new issue with a minimal reproduction 🙏
