### ISSUE TITLE
can't get list of global availableLocales from component

### ISSUE THREAD

**Issue by Alymbek** [intlify/vue-i18n-next#270]
### vue & vue-i18n version
```
"vue": "^3.0.4",
"vue-i18n": "^9.0.0-beta.16",
"@intlify/vue-i18n-loader": "^2.0.0-beta.3",
```

### Reproduction Link

https://github.com/Alymbek/vue3-i18n-next/blob/master/src/pages/layout/components/Language.vue

### Steps to reproduce
Standard steps

### What is Expected?
Want to get a list of global `availableLocales ` from the component.

### What is actually happening?
Getting only `fallbackLocale` value, I guess.

**Comment by Alymbek** [comment]
I have used below code:

`this.$root.$i18n.availableLocales`

**Comment by kazupon** [comment]
Thank you for your feedback!

Hmm, 
If you use global scope in component, you cant get global `availableLocales` in it.

**Comment by Alymbek** [comment]
hi, dear @kazupon .
Happy New Year!

so, how can I get  global `availableLocales` in this case?

**Comment by kazupon** [comment]
@Alymbek 

You can check the components that is assiend global scope with using vue-devtools.
(You need to upgrade vue-i18n@v9.0.0-beta.18 & vue-devtools@6.0.0.beta.3)

The following is a screenshot of vue-devtools appearing the scopes of vue-i18n:

![image](https://user-images.githubusercontent.com/72989/103443016-559f9e80-4c9e-11eb-8bb5-f63da2cbb5a2.png)

In the component inspector, vue-i18n tags components that are assigned a **local scope** with `i18n (xxx scope)`.
Other than that label, components are assigned **global scope`. (In legacy mode).

Your Vue application is making in Vue I18n legacy mode (`legacy: true`). The `General` component has been assigned a global scope. (legacy mode) Your Vue application is running in legacy mode, and the `General` component has been assigned a global scope, which means it can be accecced on the component with `this.$i18n.availableLocale`.

**Comment by Alymbek** [comment]
thank you, dear @kazupon !
it is working with `this.$i18n.availableLocales`

PS. there is a typo in your sample code (`this.$i18n.availableLocale`)
