### ISSUE TITLE
Warnings not suppressed

### ISSUE THREAD

**Issue by SnosMe** [intlify/vue-i18n-next#281]
- vue: 3.0.5
- vue-i18n: 9.0.0-rc.1
- @intlify/vue-i18n-loader: 2.0.0-beta.4

### Reproduction Link
https://github.com/SnosMe/vue-i18n-warnings/

### Steps to reproduce

```js
createI18n({
  formatFallbackMessages: true,
  silentFallbackWarn: true,
  silentTranslationWarn: true,
  ...
})
```

SFC

```js
<i18n>
{
  "ru": {
    "Links: {0}": "Связи: {0}",
    "Hidden": "Скрытые"
  }
}
</i18n>
```

### What is Expected?

No warnings (as in v8).
I'm using raw English strings as keys and use `formatFallbackMessages`.

### What is actually happening?

`[intlify] Fall back to translate '..............' with root locale.`

Only when `<i18n>` block is added in SFC, warnings start to be logged.

**Comment by kazupon** [comment]
Thank you for your reporting!
Could you give us minimum reproduction coes, please? 🙏

**Comment by SnosMe** [comment]
I tried to create fresh repo and wasn't able to reproduce in it.
I'm still in the process of migrating my app to vue3, maybe there some conflict, so I'll try to finish migration first and then will let you know what was causing it.

Yet consider my suggestion from issue
> will be good if you provide base template on CodeSandbox that can be forked.

**Comment by SnosMe** [comment]
Also in fresh repo when I turned on warning it was saying `Fall back to translate '..............' with 'en' locale`, but in my app it's a `root` locale. Do you have any ideas about it, what is a root locale?

**Comment by SnosMe** [comment]
> wasn't able to reproduce in it

@kazupon Reproduced, just needed to use nested component.

https://github.com/SnosMe/vue-i18n-warnings/

**Comment by kazupon** [comment]
@SnosMe 
Thank you for your feedpack!

I try to check your repo!
