### ISSUE TITLE
example project examples/lazy-loading/vite runs fail on windows

### ISSUE THREAD

**Issue by PeterAlfredLee** [intlify/vue-i18n-next#286]
### vue & vue-i18n version
- vue: 3.0.4
- vue-i18n: 9.0.0-beta.16

### Reproduction Link

https://github.com/intlify/vue-i18n-next/tree/69ce8dc95af4222c8da45155f4a65e5e8d7ef37f/examples/lazy-loading/vite

### Steps to reproduce
run these on windows (Ubuntu don't have this issue)
```shell
yarn
yarn dev
```
access url `http://localhost:3000/`

### What is Expected?
example project's home page

### What is actually happening?
can't see anything and got this error in console:
>Uncaught SyntaxError: The requested module '/src/locales/en.yaml?import' does not provide an export named 'default'

**Comment by PeterAlfredLee** [comment]
This issue is caused by `vite-plugin-vue-i18n`,  and we can fix it by [vite-plugin-vue-i18n PR #45](https://github.com/intlify/vite-plugin-vue-i18n/pull/45)

**Comment by kazupon** [comment]
@PeterAlfredLee 
Thank you for your reporting!

I've just fixed and released!
https://github.com/intlify/vite-plugin-vue-i18n/releases/tag/v1.0.0-beta.12

Please check it!

**Comment by PeterAlfredLee** [comment]
Just tested on window10 and ubuntu20.04, everything looks good to me.
