### ISSUE TITLE
how to get messages form other component 

### ISSUE THREAD

**Issue by Alymbek** [intlify/vue-i18n-next#288]
### vue & vue-i18n version
```
"vue": "^3.0.4",
"vue-i18n": "^9.0.0-rc.1",
"@intlify/vue-i18n-loader": "^2.0.0-beta.4",
```

### Reproduction Link

https://github.com/Alymbek/vue3-i18n-next
### Steps to reproduce
I want to get messages from https://github.com/Alymbek/vue3-i18n-next/blob/master/src/pages/layout/Header.vue inside the other component https://github.com/Alymbek/vue3-i18n-next/blob/master/src/pages/layout/components/Language.vue **to avoid dublicating messages**
### What is Expected?
should be able to get messages from parent component at least
### What is actually happening?
can't get messages from parrent component

**Comment by kazupon** [comment]
Thank you for you feedback!

Unfortunately, vue-i18n-next or later, we can not get messages from parent, due to avoid the complexity of managing i18n locale messages, we do not expose the messages defined in the parent component as an API.

If you would like to not allow duplicate messages, you need to define them in the global scope.

**Comment by Alymbek** [comment]
I see...

thank you, dear @kazupon

**Comment by kazupon** [comment]
@Alymbek 
Alternatively, in legacy mode, you can use `sharedMessages`.
https://vue-i18n-next.intlify.dev/guide/essentials/local.html#shared-locale-messages-for-components

**Comment by Alymbek** [comment]
wow, that is great!
I'll try this option.

thank you again, dear @kazupon !

**Comment by DaveBagler** [comment]
@kazupon, if I want to use parent scope messages in a child component, do you see a problem with passing the `ComposerTranslation` function from the parent to the child as a property?

I tested it, and it appears to be working fine, but I just wanted to check in case there might be side effects of using `ComposerTranslation` as a property that I just haven't experienced yet.

**Comment by kazupon** [comment]
I think it's one of the good solutions, so it's i18n resources & i18n abstracted by props.
