### ISSUE TITLE
How to transpile v-i18n

### ISSUE THREAD

**Issue by 5upr3m0** [intlify/vue-i18n-next#292]
First of all, thx for your great library!
I always used your plugin for vue2, but I fail to get it work properly in vue3

### vue & vue-i18n version
- vue: 3.0.5
- vue-i18n: 9.0.0-rc.2

Could you give me some directions how to setup vue-18n for vue3? It seems I do not succeed in transpiling the library:

![Screenshot 2021-01-12 at 12 02 03](https://user-images.githubusercontent.com/69140399/104306285-0d6a5280-54ce-11eb-8d5c-f180bb633db0.png)
![Screenshot 2021-01-12 at 12 01 33](https://user-images.githubusercontent.com/69140399/104306310-14916080-54ce-11eb-914b-2f5f564726d8.png)

### vue.config.js
```
transpileDependencies: ['vue-i18n'],
```

**Comment by kazupon** [comment]
for vue-cli, I'm working on at vue-cli-plugin-i18n. coming soon. :)
https://github.com/intlify/vue-cli-plugin-i18n

**Comment by kazupon** [comment]
I've just released 2.0.0-beta
https://github.com/intlify/vue-cli-plugin-i18n/releases/tag/v2.0.0-beta.1
