### ISSUE TITLE
Error thrown from vue-devtools if missing translation during mounted

### ISSUE THREAD

**Issue by MiniGod** [intlify/vue-i18n-next#293]
### vue & vue-i18n version
- vue: 3.0.5
- vue-i18n: 9.0.0-rc.2

### Reproduction Link

Source: https://gist.github.com/MiniGod/0fbc8ac28913cf0a68cfbdf23c0995b9
View: http://bl.ocks.org/MiniGod/raw/0fbc8ac28913cf0a68cfbdf23c0995b9/

### Steps to reproduce
1. Open the link above to "view" the page
2. Make sure the Vue devtools has initialized
3. Reload the page
4. Wait 2 seconds and you see an error in the console

#### Reproduce from scratch
1. Another vue app has to be created on the page (can be empty)
2. Create a vue app with i18n in legacy mode
	1. Render must use `$t` with a key that is missing
	2. On mounted, update some data to make the component rerender
3. Continue from step 2 above

### What is Expected?
No thrown error, only a warning about missing translation.

### What is actually happening?
There is an error in the console thrown by Vue-Devtools.

```
Uncaught (in promise) TypeError: Cannot read property 'timelineEventMap' of undefined
    at registerTimelineEvent (backend.js:2055)
    at Object.addTimelineEvent (backend.js:2047)
    at Object.<anonymous> (backend.js:819)
    at Object.emit (<anonymous>:1:780)
    at DevtoolsPluginApiInstance.addTimelineEvent (backend.js:315)
    at addTimelineEvent (vue-i18n@next:4266)
    at vue-i18n@next:2718
    at Array.map (<anonymous>)
    at Object.emit (vue-i18n@next:2718)
    at handleMissing (vue-i18n@next:1940)
```

### Description
This is a very weird use-case that happened in our app, where we have multiple Vue apps on the same page.
I don't know if this a vue-i18n bug or a vue-devtools bug, but I was only able to reproduce it with vue-i18n, similar to how this bug happened in our app.

**Comment by kazupon** [comment]
Thank you for your reporting!

Hmm, 🤔 
I checked vue-devtools API usage at vue-i18n-next
I seem that is correctly usage.
At the error logs, I seem that problem with vue-devtools.

**Comment by kazupon** [comment]
close due to in-activity.

if you have still issue, you can open the new issue.
thanks!
