### ISSUE TITLE
Uncaught TypeError: obj.hasOwnProperty is not a function

### ISSUE THREAD

**Issue by MartB** [intlify/vue-i18n-next#305]
https://github.com/intlify/vue-i18n-next/blob/9e6f6ea3f068e1c467f1781fc264b1d9d37ba996/packages/message-resolver/src/index.ts#L336

This breaks for my app after updating to rc3, rc2 was fine.

Im using 
```
createI18n({
  messages: MESSAGES,
  locale: DEFAULT_LOCALE,
  fallbackLocale: DEFAULT_LOCALE,
})
```

with 
```
export const MESSAGES = {
  [Locales.EN]: enAPP,
  [Locales.DE]: deAPP,
}
```

The locale files contain normal json like this
```
{
  "tests": {
    "main": "Hello there general kenobi"
  }
}
```

Hopefully you can figure that out, any help appreciated.

Edit: reference screenshot for better understanding
![image](https://user-images.githubusercontent.com/4820905/105087015-20ff5580-5a9a-11eb-8467-fdb64c1e5f71.png)

**Comment by PeterAlfredLee** [comment]
Hi @MartB , Can you provide a repository link ? I'm trying to fix this issue.

**Comment by MartB** [comment]
@PeterAlfredLee thanks for working on fixing this so quickly.

You can use this test repository.
It is close to what im using at the moment.

https://github.com/MartB/i18n-bug

Thanks for your work :)

**Comment by PeterAlfredLee** [comment]
@MartB , Thank you for provide this test repository，just did some debug, and I think PR #306 will fix this.

And there is a workaround :
use `import en from "./locales/en.json";` instead of `import * as en from "./locales/en.json";` will also work.

Hope this would help.

**Comment by kazupon** [comment]
Close, so revert #294

About details, see the PR link: 
https://github.com/intlify/vue-i18n-next/pull/306
