### ISSUE TITLE
How use Single File Compoments

### ISSUE THREAD

**Issue by nicojmb** [intlify/vue-i18n-next#314]
- vue: 3.05
- vue-i18n: 9.0.0-rc.4

I've added a i18n block inside my component but developer console tellme "Key" not found

![image](https://user-images.githubusercontent.com/5610392/105606639-ded85b80-5d9a-11eb-9292-851b6a357a9c.png)

Component:
```
<template>
  <ion-page>
    <ion-content>
      <Form
        @submit="onSubmit"
        :validation-schema="formSchema"
        class="fullheight xc"
      >
        <ion-grid>
          <ion-row>
            <ion-col class="ion-text-center">
              <img src="../assets/img/logo.png" />
            </ion-col>
          </ion-row>
          <ion-row style="margin-top: 80px">
            <ion-col>
              <Field name="name" v-slot="{ errorMessage, field }">
                <ion-item :color="errorMessage ? 'danger' : ''">
                  <ion-label position="floating" style="font-size: 18px">{{
                    t("global.user")
                  }}</ion-label>
                  <ion-input
                    style="font-size: 40px"
                    required
                    clear-input="true"
                    autofocus="true"
                    v-bind="field"
                  ></ion-input>
                </ion-item>
                <ion-text color="danger">
                  <small>{{ errorMessage }}</small>
                </ion-text>
              </Field>
            </ion-col>
          </ion-row>
          <ion-row>
            <ion-col>
              <ion-button size="large" expand="full" type="submit">{{
                t("global.testing")
              }}</ion-button>
            </ion-col>
          </ion-row>
        </ion-grid>
      </Form>
    </ion-content>
  </ion-page>
</template>

<script lang="ts">
import {
  IonContent,
  IonInput,
  IonItem,
  IonLabel,
  IonButton,
  IonPage,
  IonGrid,
  IonRow,
  IonCol,
  IonText,
} from "@ionic/vue";
import { defineComponent } from "vue";
import { useI18n } from "vue-i18n";
import { useRouter } from "vue-router";
import { Field, Form } from "vee-validate";
import { object, string } from "yup";

import { useUserStore } from "@/stores/user";

export default defineComponent({
  name: "LoginPage",
  components: {
    IonContent,
    IonInput,
    IonItem,
    IonLabel,
    IonButton,
    IonPage,
    IonGrid,
    IonRow,
    IonCol,
    IonText,
    Field,
    Form,
  },
  setup() {
    const { t } = useI18n();

    const router = useRouter();

    const userStore = useUserStore();

    const formSchema = object().shape({
      name: string().required().min(6),
    });

    const onSubmit = (values: any) => {
      userStore.name = values.name;
      userStore.isLoggedIn = true;
      router.replace({ name: "Home" });
    };

    return {
      t,
      onSubmit,
      formSchema,
    };
  },
});
</script>
<i18n>
                                                                                                       
{
  "es": {
    "global": { 
      "testing" :  "Global testing wroks!!!"
      },
  }
}
</i18n>
```

The others translations (in json file) works great!

my main.ts

![image](https://user-images.githubusercontent.com/5610392/105606697-2e1e8c00-5d9b-11eb-8a6d-02a994a54e1d.png)

**Comment by kazupon** [comment]
Thank you for feedback!

From your code example, it seems to me that vue-i18n-next works with global scope.

If there is no option, like `useI18n()`, it works with **global scope**. vue-i18n-next or later version,  i18n custom blocks default to a per-component **local scope**.

So if you have defined i18n custom blocks with locale messages, you should be able to resolve the following

- Specify `useI18n` with `useScope: 'local'`.
- Add the `global` attribute to the i18n custom block

About details, you can see the docs:
- global scope: https://vue-i18n.intlify.dev/guide/advanced/composition.html#global-scope
- local scope: https://vue-i18n.intlify.dev/guide/advanced/composition.html#local-scope

The `useScope: 'local'` option is not mentioned in the docs, so I will write it. 😉

**Comment by nicojmb** [comment]
thanks @kazupon, but I don't understand, what should I do? 

adding global in the custom block doesn't work, i try variouscombinations but do not work

**Comment by nicojmb** [comment]
Hi again, in my firtst example the code now works perfect.

Before it doesn't work because I was missing the vue.config.js part (not need to add "local" or "global" in any place).

![image](https://user-images.githubusercontent.com/5610392/105993422-b015fa00-60a6-11eb-8386-78592a4b5f2a.png)

**Comment by kazupon** [comment]
I'm relieved to hear that. 
enjoy, vue3 & vue-i18n-next coding :)
