### ISSUE TITLE
vue-i18n-next is not backward compatible

### ISSUE THREAD

**Issue by MBurchard** [intlify/vue-i18n-next#315]
### vue & vue-i18n version
- vue: 3.0.5
- vue-i18n: 9.0.0-rc.4

### Steps to reproduce

- create a vue 3 project using vue-cli
- add i18n by `vue add i18n@next` and use legacy mode
- create a component and add both local and global translation

```javascript
// src/locales/de.json
{
  "fromGlobal": "Ein globales Hallo Welt"
}
// src/locales/en.json
{
  "fromGlobal": "A global Hello World"
}
```

```vue
<template>
  <div>
    <p>{{ $t('fromGlobal') }}</p>
    <p>{{ $t('fromLocal') }}</p>
    <select v-model="$i18n.locale">
      <option value="de">de</option>
      <option value="en">en</option>
    </select>
  </div>
</template>
...

<i18n lang="yml" locale="de">
fromLocal: Ein lokales Hallo Welt
</i18n>

<i18n lang="yml" locale="en">
fromLocal: A local Hello World
</i18n>
```

Starting with default English

![grafik](https://user-images.githubusercontent.com/4256302/105638437-e10de900-5e72-11eb-82f7-1cb5d7b86038.png)

Switch to German

![grafik](https://user-images.githubusercontent.com/4256302/105638450-f71ba980-5e72-11eb-92a8-40a10c940917.png)

### What is Expected?
Both areas, so local and the global should switch to the chosen language

### What is actually happening?
The global area stays in English

### Additional comments.
I also tried to work with the non legacy mode

```typescript
   setup() {
     const {t, locale} = useI18n({
       inheritLocale: true,
       useScope: 'global',
     })
     return {t, locale}
   },
```

And I played around with different scopes like local or global.

I was unable to achieve, that a global translation and a local translation is used in combination and the language switch works as expected.

**Comment by PeterAlfredLee** [comment]
Hi @MBurchard , Maybe you can try use `global` scope in `i18n custom blcok` and `useI18n`. 
I just tested with these codes, and it work.

App.vue
```vue
<template>
  <div>
    <p>{{ t('fromGlobal') }}</p>
    <p>{{ t('fromLocal') }}</p>
    <select v-model="locale">
      <option value="de">de</option>
      <option value="en">en</option>
    </select>
  </div>
</template>

<i18n global lang="yml" locale="de">
  fromLocal: Ein lokales Hallo Welt
</i18n>

<i18n global lang="yml" locale="en">
  fromLocal: A local Hello World
</i18n>

<script>
import { defineComponent } from "vue"
import { useI18n } from 'vue-i18n'

export default defineComponent({
  name: 'App',
  setup() {
    const { t, locale } = useI18n({ useScope: 'global' })
    return { t, locale }
  }
})
</script>
```

main.ts
```typescript
import { createApp } from 'vue'
import App from './App.vue'
import { createI18n } from 'vue-i18n'

const i18n = createI18n({
  legacy: false,
  locale: 'en',
  fallbackLocale: 'en',
  messages: {
    en: {
      fromGlobal: "A global Hello World"
    },
    de: {
      fromGlobal: "Ein globales Hallo Welt"
    }
  }
})

const app = createApp(App)
app.use(i18n)
app.mount('#app')
```

**Comment by kazupon** [comment]
@MBurchard 
Thank you for your reporting!

> ### What is actually happening?
> The global area stays in English

This behavior is correct.

You have defined a local scope in your i18n custom block. Therefore, changing the locale with `$i18n.locale` will change the locale in that component.

If you want to change the locale globally, you can use `$root.$i18n.locale` to change the locale for all components.
