### ISSUE TITLE
Fallback does not fallbacks if locale option is an empty string

### ISSUE THREAD

**Issue by scapodicasa** [intlify/vue-i18n-next#328]
### vue & vue-i18n version
- vue: 3.0.5
- vue-i18n: 9.0.0-rc.4

### Steps to reproduce

Setup i18n in this way:

```js
const i18n = {
    locale: '',
    fallbackLocale: 'en',
    messages: {/* my translations */},
};

createI18n(i18n);

createApp({
...
})
.use(i18n)
.mount('#app');

```

### What is Expected?

Fallback to 'en' locale.

### What is actually happening?

Displaying messages placeholders.

**Comment by PeterAlfredLee** [comment]
@scapodicasa  
Seems this issue is relate to this [code](https://github.com/intlify/vue-i18n-next/blob/0bf2d2feef42285fc8a5d42214a65ba5df0c993c/packages/core-base/src/context.ts#L361), `''` is a special value here that will be ignore.

I just tested it, it work well if you don't use `''` as `locale` value, you can use `' '` or anything else. 
Hope this helps you.

**Comment by PeterAlfredLee** [comment]
@kazupon  I'm wonder why we check `''` in this [code](https://github.com/intlify/vue-i18n-next/blob/0bf2d2feef42285fc8a5d42214a65ba5df0c993c/packages/core-base/src/context.ts#L361), should we remove it ?

**Comment by scapodicasa** [comment]
> @scapodicasa
> Seems this issue is relate to this [code](https://github.com/intlify/vue-i18n-next/blob/0bf2d2feef42285fc8a5d42214a65ba5df0c993c/packages/core-base/src/context.ts#L361), `''` is a special value here that will be ignore.
> 
> I just tested it, it work well if you don't use `''` as `locale` value, you can use `' '` or anything else.
> Hope this helps you.

Thanks for the reply, I fixed my code. I wanted to report the behaviour because it looks a bit strange to me: if I put a `' '` or `null` or `undefined` as locale it fallbacks, with `''` it does not.

**Comment by kazupon** [comment]
@PeterAlfredLee 

> @kazupon I'm wonder why we check `''` in this [code](https://github.com/intlify/vue-i18n-next/blob/0bf2d2feef42285fc8a5d42214a65ba5df0c993c/packages/core-base/src/context.ts#L361), should we remove it ?

This is bug from v8.x.
https://github.com/kazupon/vue-i18n/blob/f78c1fc1f3137935e57735df20aef83f16dd68cf/src/index.js#L569

That should be fallback.

Could you fix this issue? 🙏 
I've been busy lately preparing my speak slides for Vuejs Amsterdam. 😓

**Comment by PeterAlfredLee** [comment]
@kazupon 
>Could you fix this issue? 🙏

Glad to help, just push #330 to fix this issue, and add a test.

>I've been busy lately preparing my speak slides for Vuejs Amsterdam.

Cheers, look forward to your speech!
