### ISSUE TITLE
IE SCRIPT1028 error

### ISSUE THREAD

**Issue by MarsCaiWORD** [intlify/vue-i18n-next#331]
![image](https://user-images.githubusercontent.com/14837356/106431764-b5a98080-64a8-11eb-8e4a-e1df3296f817.png)
![image](https://user-images.githubusercontent.com/14837356/106431784-ba6e3480-64a8-11eb-86f4-645d63a0302f.png)

**Comment by Alymbek** [comment]
hi, dear @kazupon .

I'm also confirm this issue.

after half-day investigation I got link to your library.

all working in Chrome, but in IE and Edge getting blank and empty page with this error message in Console..

please check my old git repository - https://github.com/Alymbek/vue3-i18n-next

**Comment by Alymbek** [comment]
it is working without this error message if I delete/comment your library in `main.js `file

**Comment by Alymbek** [comment]
I guess some babel configuration is required...

**Comment by Alymbek** [comment]
if you update https://github.com/Alymbek/vue3-i18n-next/blob/main/vue.config.js file to : 


```
module.exports = {
	configureWebpack: {
		optimization: {
			runtimeChunk: 'single',
			splitChunks: {
				chunks: 'all',
				maxInitialRequests: Infinity,
				minSize: 0,
				cacheGroups: {
					vendor: {
						test: /[\\/]node_modules[\\/]/,
						name(module) {
							// get the name. E.g. node_modules/packageName/not/this/part.js
							// or node_modules/packageName
							const packageName = module.context.match(
								/[\\/]node_modules[\\/](.*?)([\\/]|$)/
							)[1];

							// npm package names are URL-safe, but some servers don't like @ symbols
							return `npm.${packageName.replace('@', '')}`;
						},
					},
				},
			},
		},
	},
};
```

you can get error location in your library file.

**Comment by Alymbek** [comment]
with this configurations I'm getting error in Edge at the `./node_modules/vue-i18n/dist/vue-i18n.esm-bundler.js`.

but in IE in the `"./node_modules/vue/dist/vue.runtime.esm-bundler.js":`

**Comment by MarsCaiWORD** [comment]
@Alymbek  Thanks for the detailed explanation , Maybe need bable node_modules but this configuration is a bit troublesome

**Comment by Alymbek** [comment]
so, now we can ignor error in IE, because of this - https://github.com/vuejs/vue-cli/issues/6255

and concentrate on Edge...

**Comment by kazupon** [comment]
@Alymbek @MarsCaiWORD 
Thank you for your feedback!

IE11 support for vue-i18n-next is as mentioned in the comments of the vue-cli issue.

In Vue Official Blog, Vue 3 will support IE 11.
https://blog.vuejs.org/posts/hello-2021.html

vue-i18n-next is dependent on IE11 support for Vue 3.

As well as Vue 3, vue-i18n-next will be released once v9 is released, so we will provide IE11 compatibility build.

**Comment by Alymbek** [comment]
thank you for info, dear @kazupon.

what about Edge support?

**Comment by kazupon** [comment]
related vue RFCs for IE11
https://github.com/vuejs/rfcs/pull/294

If this RFC is adopted, vue-i18n will follow vue as well.

**Comment by kazupon** [comment]
https://github.com/vuejs/rfcs/pull/294
Vue.js has decided to adopt the IE 11 drop RFC.

vue-i18n is a library for Vue.js.
In accordance with Vue.js policy, we will not support IE11 in vue-i18n.
