### ISSUE TITLE
vite:legacy built got SyntaxError: Unexpected identifier

### ISSUE THREAD

**Issue by sayuti-daniel** [intlify/vue-i18n-next#344]
### vue & vue-i18n version

- vue: 3.0.5
- vue-i18n: 9.0.0-rc.6

### Reproduction Link

https://github.com/sayuti-daniel/vue-i18n-repro-android-5

### Steps to reproduce

```bash
npm run build
npm run serve
```

Visit http://locahost:5000
I used https://www.ldplayer.net/:
- Android 5.1 version
- Chrome Mobile WebView version: 52.0.2743.

### What is Expected?

Page rendered correctly with translations

### What is actually happening?

Blank page with `SyntaxError: Unexpected identifier` error caused by:

```js
function __msg__ (ctx) {
  const { [object Set]: _[object Set] } = ctx
  return _normalize([
    "Hello World!"
  ])
}
```

I used `vite@2.0.0-beta.67` with `@vitejs/plugin-legacy@2.0.0-beta.67` to build the project and notice [this line](https://github.com/intlify/vue-i18n-next/blob/v9.0.0-rc.6/packages/message-compiler/src/transformer.ts#L92) is the root cause which is being transpiled to:

```js
ast.helpers = [].concat(context.helpers);
```

Replacing it with `Array.from` can fix the issue.

```diff
-  ast.helpers = [...context.helpers]
+  ast.helpers = Array.from(context.helpers)
```

**Comment by tbtalbottjr** [comment]
I am unable to update past vue-i18n@9.0.0-rc6 due to the following error when calling this.$t(...)

VM2538:4 Uncaught (in promise) ReferenceError: _normalize is not defined
    at __msg__ (eval at compileToFunction (core-base.esm-bundler.js:269), <anonymous>:4:3)
    at evaluateMessage (core-base.esm-bundler.js:494)
    at translate (core-base.esm-bundler.js:350)
    at vue-i18n.esm-bundler.js:339
    at wrapWithDeps (vue-i18n.esm-bundler.js:302)
    at Object.t (vue-i18n.esm-bundler.js:339)
    at Object.t (vue-i18n.esm-bundler.js:812)
    at Proxy.$t (vue-i18n.esm-bundler.js:1636)

Any thoughts on what I need to look for as the cause?
