### ISSUE TITLE
TypeError: _ctx.$t is not a function when using $t in child component

### ISSUE THREAD

**Issue by boussadjra** [intlify/vue-i18n-next#350]
### vue & vue-i18n version
- vue: 3.0.0
- vue-i18n: 9.0.0-rc.7

### Reproduction Link

https://github.com/boussadjra/vue3-tailwind2

### Steps to reproduce

I added a file named [`i18n.ts`](https://github.com/boussadjra/vue3-tailwind2/blob/main/src/i18n.ts) next to [`main.ts`](https://github.com/boussadjra/vue3-tailwind2/blob/main/src/main.ts) which contains the following snippet :

```
import { createI18n } from "vue-i18n";

const i18n = createI18n({
  legacy: false,
  locale: "ja",
  messages: {
    en: {
      message: {
        language: "English",
        greeting: "Hello !"
      }
    },
    ar: {
      message: {
        language: "العربية",
        greeting: "السلام عليكم"
      }
    },
    es: {
      message: {
        language: "Español",
        greeting: "Hola !"
      }
    }
  }
});
export default i18n;
```
 then I imported the file inside `main.ts` and use it  : 

```
...
import i18n from './i18n'
let root = app.use(i18n).use(store).use(router).mount('#app')
```

then I added the following snippet to [`home.vue`](https://github.com/boussadjra/vue3-tailwind2/blob/main/src/views/Home.vue)  : 

```
<h2>{{ $t("message.greeting", {}, { locale: "en" }) }}</h2>
```

### What is Expected?

Render the message **Hello !**

### What is actually happening?

but this is giving the following error : 

>Uncaught (in promise) TypeError: _ctx.$t is not a function
    at Proxy.render (Home.vue?bb51:2)

**Comment by danielpetrica** [comment]
Hi, I think this may be similar to my issue, I found out that to have the global $t injected like on previous version I neet to pass 
`globalInjection: true,` in the createI18n() function options.

So your `i18n.ts ` may look like this: 

```
import { createI18n } from "vue-i18n";

const i18n = createI18n({
  legacy: false,
  locale: "ja",
  globalInjection: true,
  messages: {
    en: {
      message: {
        language: "English",
        greeting: "Hello !"
      }
    },
    ar: {
      message: {
        language: "العربية",
        greeting: "السلام عليكم"
      }
    },
    es: {
      message: {
        language: "Español",
        greeting: "Hola !"
      }
    }
  }
});
export default i18n;
```

**Comment by boussadjra** [comment]
Wow it works like charm, thank you very very much

**Comment by danielpetrica** [comment]
@boussadjra I'm glad it worked. 
This may be useful in the future. I found out that $t is not available everywhere (like inside other .ts files) but if you add this function to the i18n file you can import it and use it to translate strings: 
```
// file: i18n.ts
/**
 * it's ugly but we can use this to translate strings inside js code
 * @param key
 */
export const translate = (key: string) => {
    if (!key) {
        return '';
    }
    return i18n.global.t(key);
};
```

```
// another .ts file
import { translate } from 'path to i18n file'
...
console.log(translate('message.languge'))
```

**Comment by boussadjra** [comment]
Thank you for this hint, but I think we could do : 

```
declare module '@vue/runtime-core' {
  interface ComponentCustomProperties {
    $t: i18n.global.t;
  }
}

```

**Comment by osahene** [comment]
How do I resolve the same issue in a js file?

**Comment by oscyp** [comment]
@danielpetrica for me `this.$t` works inside component definition.

**Comment by hks2002** [comment]
Vue3 and vue-i18n-next sample, it could works as bellow:
```
<template>
  <q-page class="flex flex-center">
    <img alt="Quasar logo" src="/imgs/logo.svg" />
    <div>{{ t("success") }}</div>
  </q-page>
</template>

<script>
import { defineComponent } from "vue";
import { useI18n } from "vue-i18n";

export default defineComponent({
  name: "PageIndex",
  setup() {
    const { t } = useI18n();
    return {
      t,
    };
  },
});
</script>
```
* import `useI18n`:
```
import { useI18n } from "vue-i18n";
```
* define function in `setup()`:
```
const { t } = useI18n();
```
* using `t` in the template:
```
<div>{{ t("success") }}</div>
```

**Comment by dybxin** [comment]
how to use t("") in <script></script>

**Comment by dybxin** [comment]
if i only use in *.js file and not setup() how to use i18n?

**Comment by gwen1230** [comment]
Hi ! I have same issue but with $tc. I pass globalInjection to true, $t is available but not $tc.

**Comment by danielpetrica** [comment]
> Hi ! I have same issue but with $tc. I pass globalInjection to true, $t is available but not $tc.

Hi from what i can see the plurarization has been integrated in `t()`when using composition api [https://vue-i18n.intlify.dev/guide/advanced/composition.html#pluralization](https://vue-i18n.intlify.dev/guide/advanced/composition.html#pluralization)

**Comment by gwen1230** [comment]
> > Hi ! I have same issue but with $tc. I pass globalInjection to true, $t is available but not $tc.
> 
> Hi @gwen1230 from what i can see the plurarization has been integrated in `t()`when using composition api https://vue-i18n.intlify.dev/guide/advanced/composition.html#pluralization

Yes I saw that and it works with composition API. But with global injection, $t is like the old $t, and $tc doesn't seem to exist.

**Comment by ronaldoqj** [comment]
@danielpetrica Thank you very much.
You saved my life.

**Comment by brainafesoh** [comment]
Hello guys. I instead get this error when using  i18n custom blocks in single file components. Using @danielpetrica's solution clears the error but the translation is not read from the i18n custom block.
Any tips please?

**Comment by danielpetrica** [comment]
Hi @brainafesoh,  unfortunately English is not my first language and I didn’t understand your use case. Can you please explain your use case and maybe provide an example so we can help you better?

**Comment by brainafesoh** [comment]
Ok in fact I'm trying to use single file component based translations (as described here: https://vue-i18n.intlify.dev/guide/advanced/sfc.html) and I am using vite.

However, after adding necessary configs to my `vite.config.ts` file, I get error `Uncaught (in promise) TypeError: _ctx.$t is not a function`

Just for some context here are some code snippets that summarize my current dev environment; Thanks for helping.

- Article.vue file
```
<template>
<div>{{ $t("stepHeading_1") }}</div>
</template>

<i18n>
{
  "en": {
    "stepHeading_1": "General Information"
  },
  "fr": {
    "stepHeading_1": "Informations Générales"
  }
}
</i18n>

<script lang="ts" src="./article.component.ts"></script>
```

- vite.config.ts file
```
import vue from "@vitejs/plugin-vue";
import { resolve } from "path";
import { defineConfig } from "vite";
import vueI18n from "@intlify/vite-plugin-vue-i18n";

export default defineConfig({
  resolve: {
    alias: {
      "@": resolve(__dirname, "src"),
    },
  },
  plugins: [vue(), vueI18n({})],
});
```

- article.component.ts file
```
import { Options, Vue } from "vue-class-component";

@Options({})
class Article extends Vue {}
export default Article;
```

- main.ts file
```
// mouting point for the whole app
import App from "@/App.vue";
import "@/assets/styles/index.css";
// styles
import "@fortawesome/fontawesome-free/css/all.min.css";
import { createApp } from "vue";
import { createI18n } from "vue-i18n";
import { createRouter, createWebHistory } from "vue-router";
import { routes } from "./routes";

const router = createRouter({
  history: createWebHistory(),
  routes,
});

// Create VueI18n instance with options
const i18n = createI18n({
  locale: "fr", // set locale
  fallbackLocale: "en", // set fallback locale
});

createApp(App).use(router).use(i18n).mount("#app");
```

- Package.json file
```
{
  "dependencies": {
    "@fortawesome/fontawesome-free": "5.15.3",
    "@headlessui/vue": "^1.4.1",
    "@popperjs/core": "2.9.1",
    "@tailwindcss/forms": "0.2.1",
    "ag-grid-community": "^26.0.0",
    "ag-grid-vue3": "^26.0.0",
    "chart.js": "2.9.4",
    "core-js": "3.9.1",
    "tslib": "^2.3.1",
    "vue": "^3.0.5",
    "vue-class-component": "^8.0.0-0",
    "vue-i18n": "^9.2.0-beta.6",
    "vue-router": "4.0.5"
  },
  "devDependencies": {
    "@intlify/vite-plugin-vue-i18n": "^2.4.0",
    "@types/node": "^16.9.6",
    "@vitejs/plugin-vue": "^1.3.0",
    "@vue/compiler-sfc": "^3.0.5",
    "autoprefixer": "^10.3.2",
    "eslint": "^7.32.0",
    "eslint-config-prettier": "^8.3.0",
    "eslint-plugin-vue": "^7.16.0",
    "postcss": "^8.3.6",
    "prettier": "2.3.2",
    "tailwindcss": "^2.2.7",
    "typescript": "^4.3.2",
    "vite": "^2.4.4",
    "vue-tsc": "^0.2.2"
  }
}
```

**Comment by danielpetrica** [comment]
@brainafesoh I don't know the plugin enough to find whats wrong. 
The only thing comming to my mind if you have problems with $t is: have you tried to add `globalInjection: true,` to the `createI18n({
  locale: "fr", // set locale
  fallbackLocale: "en", // set fallback locale
});` block?

**Comment by laoshaw** [comment]
Spent 6 hours today until I arrived here for this magic "globalInjection: true," Thanks!

**Comment by Korak-997** [comment]
> Hi, I think this may be similar to my issue, I found out that to have the global $t injected like on previous version I neet to pass `globalInjection: true,` in the createI18n() function options.
> 
> So your `i18n.ts ` may look like this:
> 
> ```
> import { createI18n } from "vue-i18n";
> 
> const i18n = createI18n({
>   legacy: false,
>   locale: "ja",
>   globalInjection: true,
>   messages: {
>     en: {
>       message: {
>         language: "English",
>         greeting: "Hello !"
>       }
>     },
>     ar: {
>       message: {
>         language: "العربية",
>         greeting: "السلام عليكم"
>       }
>     },
>     es: {
>       message: {
>         language: "Español",
>         greeting: "Hola !"
>       }
>     }
>   }
> });
> export default i18n;
> ```

I had same Issue Your solution works perfectly :) thanks BRO !

**Comment by terwer** [comment]
> Hi, I think this may be similar to my issue, I found out that to have the global $t injected like on previous version I neet to pass `globalInjection: true,` in the createI18n() function options.
> 
> So your `i18n.ts ` may look like this:
> 
> ```
> import { createI18n } from "vue-i18n";
> 
> const i18n = createI18n({
>   legacy: false,
>   locale: "ja",
>   globalInjection: true,
>   messages: {
>     en: {
>       message: {
>         language: "English",
>         greeting: "Hello !"
>       }
>     },
>     ar: {
>       message: {
>         language: "العربية",
>         greeting: "السلام عليكم"
>       }
>     },
>     es: {
>       message: {
>         language: "Español",
>         greeting: "Hola !"
>       }
>     }
>   }
> });
> export default i18n;
> ```

Thanks very much,it works.

**Comment by jbiddulph** [comment]
I just tried this: adding in: globalInjection: true,
I am still getting the error: 

Uncaught (in promise) TypeError: _ctx.$t is not a function
    at Proxy._sfc_render (home.vue:11:50)

home.vue

line 11 col 50 is at the $
{{ $t("home.listen") }}

**Comment by danielpetrica** [comment]
@jbiddulph can you please add a copy of the configuration you used? 
Also what version of the plugin and vue.js are you using?

**Comment by jbiddulph** [comment]
package.json:

`{
  "name": "music",
  "version": "0.0.0",
  "scripts": {
    "dev": "vite",
    "build": "vite build",
    "preview": "vite preview --port 4173",
    "test:unit": "vitest --environment jsdom",
    "test:e2e": "start-server-and-test preview http://localhost:4173/ 'cypress open --e2e'",
    "test:e2e:ci": "start-server-and-test preview http://localhost:4173/ 'cypress run --e2e'",
    "lint": "eslint . --ext .vue,.js,.jsx,.cjs,.mjs --fix --ignore-path .gitignore"
  },
  "dependencies": {
    "@vee-validate/rules": "^4.6.2",
    "firebase": "^8.10.1",
    "howler": "^2.2.3",
    "pinia": "^2.0.16",
    "vee-validate": "^4.5.8",
    "vue": "^3.2.37",
    "vue-i18n": "^9.2.2",
    "vue-router": "^4.1.2",
    "zod": "^3.10.0-beta.1"
  },
  "devDependencies": {
    "@rushstack/eslint-patch": "^1.1.0",
    "@vitejs/plugin-vue": "^3.0.1",
    "@vue/eslint-config-prettier": "^7.0.0",
    "@vue/test-utils": "^2.0.2",
    "autoprefixer": "^10.4.7",
    "cypress": "^10.3.0",
    "eslint": "^8.5.0",
    "eslint-plugin-cypress": "^2.12.1",
    "eslint-plugin-vue": "^9.0.0",
    "jsdom": "^20.0.0",
    "postcss": "^8.4.14",
    "prettier": "^2.5.1",
    "start-server-and-test": "^1.14.0",
    "tailwindcss": "^3.1.6",
    "vite": "^3.0.1",
    "vitest": "^0.18.1"
  }
}
`

**Comment by jbiddulph** [comment]
anyone?

**Comment by ilovepixelart** [comment]
@danielpetrica @jbiddulph having similar issue but with a different spin)
Setup is vue2 codebase + vite + @vue/compat + vue3 with compatibility set to 2, and boostrap-vue
On initial render of the page all good $t('some.translation') works but for components that are rendered conditional using v-if TypeError: _ctx.$t is not a function

**Comment by J2A2B** [comment]
Hi, I have a similar problem when I try to unit test my component :
"vue-i18n": "^9.2.2",
"vite": "^3.2.4",
"vitest": "^0.25.3",

It's working on my dev environment but not when I try to test with :

```
components/__tests__/Header.spec.ts > Header > renders properly
TypeError: _ctx.$t is not a function
```

**Comment by amitchaudhary140** [comment]
Same, it is not working in unit test.

**Comment by stevereinke** [comment]
There is no solution yet, isn't it?

**Comment by juandanielc0** [comment]
Hi! try using i18n.global.t(key) instead of i18n.t(key)

**Comment by devinRex** [comment]
In vue3, if I use h function in setup，like this:
`
import { h } from 'vue';
const node = createApp({ render: () => h(component)});
const detailDiv = document.createElement('div');
node.mount(detailDiv);
`
in this case, _ctx.$t is not exist.

**Comment by marko3190** [comment]
Working solution for me:

main.js file
```
import i18n from './i18n'
const app = createApp(App)

app.config.globalProperties.$t = i18n.global.t
```

and i18n is just a:
```
const i18n = createI18n({
  locale: currentLang,
  fallbackLocale: fallbackLanguage,
  messages: {}
})

export default i18n
```

**Comment by Sheng08** [comment]
> Working solution for me:
> 
> main.js file
> 
> ```
> import i18n from './i18n'
> const app = createApp(App)
> 
> app.config.globalProperties.$t = i18n.global.t
> ```
> 
> and i18n is just a:
> 
> ```
> const i18n = createI18n({
>   locale: currentLang,
>   fallbackLocale: fallbackLanguage,
>   messages: {}
> })
> 
> export default i18n
> ```

I had the same problem, and your solution resolved it perfectly! Thanks so much! 👍
