### ISSUE TITLE
"Incorrect Locale Provided" when using current locale - datetimeFormats

### ISSUE THREAD

**Issue by arxpw** [intlify/vue-i18n-next#355]
### Reproduction Link
https://gist.github.com/arxpw/82e854dd0ff97a7e1ff2f84c9ebfa600

### Steps to reproduce
Use a name of any currently used locale
Translate via the date d() method from usei18n in a vue template.

### What is Expected?
To use the valid date time formats from the current locale name

### What is actually happening?
```
runtime-dom.esm-bundler-9a9d7b5a.js:1664 RangeError: Incorrect locale information provided
```

Is this because underscores are not properly valid for the names of a locale, or is this something else?

**Comment by kazupon** [comment]
Thank you for your feedback!

> Is this because underscores are not properly valid for the names of a locale, or is this something else?

Yes! You can use BCP 47 format of locale.
https://tc39.es/ecma402/#sec-isstructurallyvalidlanguagetag

The Functions exported with `d` or `n` from the method `useI18n` cannot use underscore format for locale, so it used internally ecma-402 API.

Thanks!
