### ISSUE TITLE
Named interpolation with underscore in json file

### ISSUE THREAD

**Issue by Kameecoding** [intlify/vue-i18n-next#371]
The following error is shown if the external json file with the messages has underscore in the interpolation.

`Syntax Error: Final loader (./node_modules/@intlify/vue-i18n-loader/lib/index.js) didn't return a Buffer or String`

```
{
"excluded": "{_field} with the same value already exists.",
}

```
Causes the error.

```
{
"excluded": "{field} with the same value already exists.",
}

```

is fine

**Comment by kazupon** [comment]
Thank you for your reporting!

This is bug of message compiler.
I'll try to fix!
