### ISSUE TITLE
tm composition API function return a proxy instead of an array or object

### ISSUE THREAD

**Issue by dsolay** [intlify/vue-i18n-next#375]
### vue & vue-i18n version
ex:
- vue: 3.0.6
- vue-i18n: 9.0.0

### Reproduction Link
Use  https://github.com/intlify/vite-vue-i18n-starter

### Steps to reproduce
given this locale
```
{
  "en": {
    "hello": "Hello Vue I18n 9.0 🌏!",
    "count": "count is: {count}",
    "docs": {
      "vue-i18n": "Vue I18n v9 Documentation",
      "vite-plugin": "Vite Plugin Vue I18n Documentation"
    },
    "recommended": "Recommended setup"
  },
  "ja": {
    "hello": "こんにちは Vue I18n 9.0 🌏！",
    "count": "カウントは{count}です",
    "docs": {
      "vue-i18n": "Vue I18n v9 ドキュメント",
      "vite-plugin": "Vite プラグイン Vue I18n ドキュメント"
    },
    "recommended": "推奨セットアップ"
  }
}
```
I want access to "docs" object, so I use the "tm" function

```
const { tm } = useI18n();
console.log(tm("docs"));
```

### What is Expected?
I want to get the following object

```
"docs": {
      "vue-i18n": "Vue I18n v9 Documentation",
      "vite-plugin": "Vite Plugin Vue I18n Documentation"
}
```

### What is actually happening?

I am getting the following output on the console

![2021-03-03_00:33:31_1912x1026](https://user-images.githubusercontent.com/22564820/109763785-364ac200-7bb8-11eb-9c61-534e6e5ac2cf.png)

**Comment by kazupon** [comment]
Thank you for your feedback!

`tm` is assumed to be used in template as bellow:

```vue
<li v-for="msg in tm('messages')">
  <p>{{ msg }}</p>
</li>
```

`tm` will return a reactive value. If you change the `locale`, `tm` will reactively return the value corresponding to the locale.

if you hope raw object, you can use `toRaw` reactive API.
https://v3.vuejs.org/api/basic-reactivity.html#toraw

Thanks!
