### ISSUE TITLE
$t(key) api should not compile pluralized messages

### ISSUE THREAD

**Issue by Jesseyx** [intlify/vue-i18n-next#376]
### vue & vue-i18n version
ex:
- vue: 3.0.5
- vue-i18n: 9.0.0

### Reproduction Link

See [https://codepen.io/yaoxcode/pen/JjbZRvW](https://codepen.io/yaoxcode/pen/JjbZRvW)

### What is Expected?
Messages should not be plural when using `$t(key)` api

### What is actually happening?
The message was truncated. It should show as `hello world | test`

**Comment by kazupon** [comment]
Thank you for your reporting.

`|` is special character from v9.
You can use literal interpolation.
about details, see here:
https://vue-i18n.intlify.dev/guide/essentials/syntax.html#special-characters
