### ISSUE TITLE
What is the point of the "legacy" property?

### ISSUE THREAD

**Issue by reverb051** [intlify/vue-i18n-next#377]
This is more of a question, but it could also be a potential bug. I read the official docs and guides, but still couldn't find the answer. I was trying to create the custom pluralization function for another language, when I noticed that the  `pluralizationRules` property didn't do anything.
Then I realized that I set the `legacy` property to `false`, so the Composition API requires the `pluralRules` property instead of `pluralizationRules`. So I changed the property name and everything works. But in the process of trying to find why the custom pluralization doesn't work I figured out that I can use the composition API even when the `legacy` property is `true`. 

The guide says that we need to set `legacy` to `false` so that we can use the `useI18n` composer. However, from my experience, composition API components with `useI18n` still work when I don't set this to `legacy`. 

Is this intended behaviour? What is the point of the `legacy` property? Instead of setting the `legacy` to `false` and `globalInjection` to `true`, I can just completely ignore these two properties and still use the Vue i18n plugin in composition API and options API components together in the same project. 

### What is Expected?

It is expected that the `useI18n` composer function is not available if `legacy` is not set to `false`.

### What is actually happening?

`useI18n` composer is still available and we can translate composition API components without the `legacy` property set to `false`

**Comment by pavelzemek** [comment]
@kazupon Please add a note to https://vue-i18n.intlify.dev/guide/essentials/pluralization.html#custom-pluralization that `pluralRules` has to be used when `legacy: false`.
