### ISSUE TITLE
formatFallbackMessages does not work when translation key is nested

### ISSUE THREAD

**Issue by PaddyLock** [intlify/vue-i18n-next#378]
### vue & vue-i18n version
ex:
- vue: 2.6.11
- vue-i18n: 8.23.0

### Steps to reproduce

Following the documentation here - http://kazupon.github.io/vue-i18n/guide/fallback.html#fallback-interpolation

### What is Expected?

My locale files are structured like this

`
const messages = {
  ja: {
    headings : {
        'Hello, world!': 'こんにちは、世界!'
    }
  }
}
`

If I use formatFallbackMessages: true

const i18n = new VueI18n({
  locale:  'en',
  fallbackLocale: 'en',
  formatFallbackMessages: true
});

I expect

<p>{{ $t('headings.The weather today is {condition}!', { condition: 'sunny' }) }}</p>

to render

<p>The weather today is sunny!</p>

### What is actually happening?

What is rendered is

headings.The weather today is sunny!

**Comment by reverb051** [comment]
I tried the same exact thing you did and it worked. I also used the nested translation key.
Can you check the rest of your code, maybe something is wrong there? Your $t example here seems perfectly fine

**Comment by kazupon** [comment]
Thank you for your reporting!

This repository issue is for Vue I18n v9.
About Vue I18n v8.x, Please report here:
https://github.com/kazupon/vue-i18n/issues

Thanks!
