### ISSUE TITLE
_this.$t is not a function in my ts codes

### ISSUE THREAD

**Issue by xjw181221** [intlify/vue-i18n-next#379]
in my ts codes:
title: string = this.$t("login.title");  i get error in my chrome console:
_this.$t is not a function in my ts codes

But in  html, this is ok:
<span>{{ $t("login.title") }} title</span>

**Comment by kazupon** [comment]
Thanks for filing the issue!

Please follow the [Issue Reporting Guidelines](https://github.com/intlify/vue-i18n-next/blob/master/.github/CONTRIBUTING.md#vue-i18n-contributing-guide) and provide a minimal JSFiddle or JSBin or CodeSandbox containing a set of reproducible steps that can lead to the behavior you described.

Thanks!
