### ISSUE TITLE
When I call a create I18n method, how to locale and messages the types of properties by typescript constraints

### ISSUE THREAD

**Issue by zzqgithb** [intlify/vue-i18n-next#382]
The distinguished author has already participated in the createI18n method, how should I inform typescript, of the locale and messages types defined in my project.

Like, I'd like to define the attributes in the messages by interface, and if so, is this also supported in mergeLocaleMessage and other ways.

I looked through the document, tried some methods, did not achieve the desired results.

thinks

![image](https://user-images.githubusercontent.com/24291786/109954351-3663d280-7d1c-11eb-8af0-fc7d2d5625f2.png)
![image](https://user-images.githubusercontent.com/24291786/109954939-df123200-7d1c-11eb-834f-4545831770b3.png)
![image](https://user-images.githubusercontent.com/24291786/109954786-b4c07480-7d1c-11eb-8fc5-c1e978443e5e.png)

**Comment by kazupon** [comment]
Thank you for your feedback!

I would like to know what your use cases.
Do you mean you want to use the i18n instance created by createI18n outside of the Vue component?

**Comment by zzqgithb** [comment]
Thanks for the reply!
in other words, I used it in vue components compositionApi, Now I want to define clearly the type of parameters in mergeLocaleMessage method, not the (locale：Locale,message：LocaleMessageDictionary<Message>)
What should I do!
Thanks.
![Uploading image.png…]()
