### ISSUE TITLE
ISO 8601 format validation bug

### ISSUE THREAD

**Issue by RollingTL** [intlify/vue-i18n-next#383]
- `vue`: 3.0.7 
 - `vue-i18n`: 9.0.0 

Application is normally working in Firefox and Chrome but fails to work in Safari 14

The code casing error
<template>
<div>
{{ $d('2021-02-26 12:58:58', 'long') }}
</div>
</template>

Error message:
Unhandled Promise Rejection: SyntaxError: The argument provided is not a valid ISO date string

**Comment by kazupon** [comment]
Thank you for your reporting!

You can use strictly ISO 8601 format.
https://en.wikipedia.org/wiki/ISO_8601

e.g.
```
2021-02-26T12:58:58
```

However, there is bug in the ISO 8601 format validation of vue-i18n.
I’ll try to fix it. 😉

**Comment by RollingTL** [comment]
People please fix this bug, or whatever it is!
I have no skill to do it myself, but the solution seems very easy - just one regular expression adding T instead of space when receiving $d function argument would do.

**Comment by PeterAlfredLee** [comment]
Hi @kazupon 

> However, there is bug in the ISO 8601 format validation of vue-i18n.

I'm testing with Chrome and it works well. Could you make the problem more clear? I will try to fix this. :-)

**Comment by kazupon** [comment]
- chrome: 
![image](https://user-images.githubusercontent.com/72989/119803141-22460080-bf1a-11eb-80c7-c16c96832f61.png)
- safari
![image](https://user-images.githubusercontent.com/72989/119803190-2ffb8600-bf1a-11eb-8448-f97cbc6145d2.png)

Formats without `T` will not work in safari. We need it to work in major browsers.
