### ISSUE TITLE
TS build error

### ISSUE THREAD

**Issue by bobohuochai** [intlify/vue-i18n-next#390]
- `vue`: 3.0.7
 - `vue-i18n`: 9.0.0

**Screenshots**
lerna ERR! yarn run build stdout:
$ tsc -b .
../../node_modules/@intlify/core-base/dist/core-base.d.ts(526,26): error TS2430: Interface 'SpecificDateTimeFormatOptions' incorrectly extends interface 'DateTimeFormatOptions'.
  Types of property 'localeMatcher' are incompatible.
    Type '"lookup" | "best-fit" | undefined' is not assignable to type '"lookup" | "best fit" | undefined'.
      Type '"best-fit"' is not assignable to type '"lookup" | "best fit" | undefined'.

**Comment by kazupon** [comment]
Fixed with #417
