### ISSUE TITLE
Unexpected token '...'. Expected a property name.

### ISSUE THREAD

**Issue by Zenquan** [intlify/vue-i18n-next#393]
**Reporting a bug?**
 - I tried to install `@babel/plugin-proposal-object-rest-spread`, but it didn't solve the problem

**Module versions (please complete the following information):**
 - `vue`: 3.05
 - `vue-i18n`: 9.0.0
 -  ios 11.2 iPhoneX Safari 

**Reproduction Link**
A minimal JSBin, JSFiddle, Codepen, CodeSandbox, or a GitHub reprository that can reproduce the bug.

You can use reproduction CodeSandbox template: https://codesandbox.io/s/vue-i18n-test-jbeg9

**To Reproduce**
ex:
1. npm run serve
2. open 0.0.0.0:8080 in Simulator (Xcode) ios11.2 Device iPhoneX
3. see error by safari console

**Screenshots**
![截屏2021-03-12 下午2 36 58](https://user-images.githubusercontent.com/38183707/110902234-7dffe500-8340-11eb-8737-7696a73875c8.png)

**Comment by kazupon** [comment]
related #184
