### ISSUE TITLE
tm dosen't return locaMessageValue but an empty object when matching a language that is not exist locally even if used fallbackLocale 

### ISSUE THREAD

**Issue by calvinxie001** [intlify/vue-i18n-next#399]
**Module versions (please complete the following information):**
 - `vue`: 3.x
 - `vue-i18n`: 9.x

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/17590085/111470621-05938c80-8763-11eb-88ff-d3dc39ee90da.png)

**Additional context**

I hope that return localMessageValue which I have pointed to at fallbackLocale when matching a language that does not exist  but an empty object.What I need as follow

![image](https://user-images.githubusercontent.com/17590085/111471907-61124a00-8764-11eb-8199-7038eecbbe97.png)

**Comment by kazupon** [comment]
Thank you for your reporing!

Unfotunately, I could not reproduce this issue.
Could you provide minmum production code, please?

**Comment by calvinxie001** [comment]
sure, firstly, I make a global configuration just like that:
```
export const i18n = createI18n({
    locale: 'en', 
    messages, 
    fallbackLocale: 'cn',
    legacy: false, 
    formatFallbackMessages: true
})
```
Then, I code the vue-i18n  in SPA  composition api  ,
```
import { useI18n } from 'vue-i18n'
const MESSAGES = {
  cn: {
     text: '你好 世界'
  },
  ja: {
   text: 'こんにちは世界'
 }
}
setup () {
       const { t, tm } = useI18n({
            messages: MESSAGES
        })
   onMounted(async() => {
            console.log(tm('text'))  //  return {}  
        })
    return {
     tm
   }
}
      
```
THANKS

**Comment by kazupon** [comment]
Thank you for your more info.

I could reproduce this issue.
this is a bug. 🐛 

I'll try to fix it. 😉

**Comment by calvinxie001** [comment]
it's not working in my project. could you show me an example. @kazupon
