### ISSUE TITLE
Pipe in $t breaks translation

### ISSUE THREAD

**Issue by JBtje** [intlify/vue-i18n-next#401]
**Module versions (please complete the following information):**
 - `vue`: 3.0.7
 - `vue-i18n`: 9.0.0

**Reproduction Link**
https://codesandbox.io/s/vue-i18n-9-template-forked-pfxh8
https://github.com/JBtje/LaravelSPABoilerplate (See footer tekst)

**To Reproduce**
ex:
1. Go to https://codesandbox.io/s/vue-i18n-9-template-forked-pfxh8

**Expected behavior**
`message.hello` should show `hello | world!` However it shows `hello `. All text after the pipe is removed.
Note that `$t` is used, not `$tc`.

**Additional context**
Escaping the pipline symbol does not solve the problem. As far as I could find in the docs the pipeline should be usable within `$t`

**Comment by kazupon** [comment]
Thank you for your reporting!

The pipeline character is a special character from v9.
if you want to appear it as a message, you need to use literal interpolation.
https://vue-i18n.intlify.dev/guide/essentials/syntax.html#special-characters

e.g.
```
hello {'|'} world!
```

Thanks!
