### ISSUE TITLE
Does vue-i18n-next support both vue 2 and vue 3?

### ISSUE THREAD

**Issue by dougalg** [intlify/vue-i18n-next#405]
**Is your feature request related to a problem? Please describe.**
It would be nice to ease the transition to intlify/vue-i18n-next if users of Vue 2 didn't have to do both the Vue 2 to 3 migration AND the intlify migration at once. 

**Describe the solution you'd like**
Ideally, Vue 2 users could migrate intlify first, and get comfortable with the composition api, and then switch to Vue 3. I don't know if this is possible, but would something like [Vue Demi](https://github.com/vueuse/vue-demi) make this possible for this project?

Thanks for all the great work!

**Comment by kazupon** [comment]
You can use `vue-i18n-composable`.
https://github.com/intlify/vue-i18n-composable

`vue-i18n-composable` does not have all the same APIs as vue-i18n v9, but it should have a minimal set of APIs.

**Comment by dougalg** [comment]
Interesting! Thanks a lot, I will take a look.

**Comment by kazupon** [comment]
close
if you have anything issue, you can open new issue.

if you have anything questions, you can open the disccusion as Q & A
https://github.com/intlify/vue-i18n-next/discussions

Thanks!
