### ISSUE TITLE
typesafe translate?

### ISSUE THREAD

**Issue by rainmanhhh** [intlify/vue-i18n-next#407]
key of t() is a string (eg.: `t('foo.bar')`)
I can get message functions by `useI18n().locale.messages` (eg.: `foo.bar` in which bar is a function)
Is it possible to translate like
```
const msgFunc = useI18n().locale.messages
msgFunc.foo.bar() // how to get context?
```
or
```
const msgFunc = useI18n().locale.messages
trans(msgFunc.foo.bar) // how to get context?
```

**Comment by kazupon** [comment]
Thank you for your feedback.

Unfortunately, We doesn’t allow to use directly Message functions in VueI18n 😞 
It's designed to be used with the VueI18n runtime in mind.

I would like to know more about why you want to call and translate directly.
I'd like to know more about it for future reference, if you don't mind. 🙏

**Comment by rainmanhhh** [comment]
because I want make my app typesafe. t('foo.bar') is obviously not (no auto-completion in IDE and no compile error if I pass a wrong key)

**Comment by kazupon** [comment]
Thank you for your reply!

You are right, vue-i18n still needs to be improved for typescript.
I’ll improve the typesafe (auto complition) in key parameter in the future.

I'll also improve around the type parameter.
https://github.com/intlify/vue-i18n-next/issues/382
