### ISSUE TITLE
Uncaught (in promise) TypeError: Cannot read property '__disableEmitter' of undefined

### ISSUE THREAD

**Issue by mits87** [intlify/vue-i18n-next#412]
Hi, 

I've just installed the latest version of vue-i18n-next and I have a big problem because it does it work correctly with vue-router. Exactly the same bug like we can find here: https://github.com/intlify/vue-i18n-next/issues/253

Some people suggested to use `NODE_ENV=production` but I can't do that based on fact I'm using different .env files for different environments. Also based on **NODE_ENV** I'm attaching some extra functionality. So this is not solution.

**Version & libraries:**
I'm using these version of libraries:

```
"dependencies": {
    "@vueuse/core": "^4.6.2",
    "core-js": "^3.9.1",
    "register-service-worker": "^1.7.2",
    "vue": "^3.0.2",
    "vue-i18n": "^9.0.0",
    "vue-router": "^4.0.5",
    "vuex": "^4.0.0"
  },
```

**The behaviour:**
When I'm trying to change page (using vue-router) I get those errors:

```
vue-i18n.esm-bundler.js?47e2:1672 Uncaught (in promise) TypeError: Cannot read property '__disableEmitter' of undefined
    at Proxy.beforeUnmount (vue-i18n.esm-bundler.js?47e2:1672)
    at callWithErrorHandling (runtime-core.esm-bundler.js?5c40:154)
    at callWithAsyncErrorHandling (runtime-core.esm-bundler.js?5c40:163)
    at Array.hook.__weh.hook.__weh (runtime-core.esm-bundler.js?5c40:1957)
    at invokeArrayFns (shared.esm-bundler.js?9ff4:470)
    at unmountComponent (runtime-core.esm-bundler.js?5c40:4819)
    at unmount (runtime-core.esm-bundler.js?5c40:4731)
    at Object.remove (runtime-core.esm-bundler.js?5c40:5125)
    at unmount (runtime-core.esm-bundler.js?5c40:4755)
    at unmountChildren (runtime-core.esm-bundler.js?5c40:4859)
```
<img width="1289" alt="Screenshot 2021-03-28 at 19 36 04" src="https://user-images.githubusercontent.com/605186/112761735-fe8b3a80-8ffc-11eb-886c-6d07c2c9ef3e.png">

Someone has still a similar problem?

**Comment by kazupon** [comment]
Thank you for your reporting!

I tried to reproduce this issue.
Unfortunately, I could not reproduce...

The below issue minimul repo:
https://github.com/kazupon/vue-i18n-next-issue-412

I need the component structure information from the `App` root and the following information for each component to solve this problem.

- whether use i18n custom block
- or, whetheruse  i18n options 
- or, not use both 

Could you give us the component info and structure, please? 🙏

**Comment by jiangjunfeng98** [comment]
vue 3.0.7 is work

```json
"vue": "3.0.7",
"vue-i18n": "^9.0.0"
```

**Comment by ota-meshi** [comment]
Are you using `<teleport>`?
If so, it may be related to a bug in vue v3.0.9.
https://github.com/vuejs/vue-next/issues/3497

There is no `$i18n` property on the second call of beforeUnmount.

**Comment by holtwick** [comment]
Oh, @ota-meshi  and @jiangjunfeng98 why didn't i see your comments earlier, it could have saved my morning ;) I came to the same conclusions. Vue 3.0.7 works and it is related to `<teleport>`. See my debug comment here: https://github.com/intlify/vue-i18n-next/issues/133

**Comment by mits87** [comment]
@ota-meshi and @jiangjunfeng98 Yes, I'm using `<teleport>` in my project  and I changed my VUE version to `vue 3.0.7` but the problem still exists there 👎 

In a few hours I will try to prepare some sandbox version of that problem.

**Comment by holtwick** [comment]
@mits87 did you check which version is really installed using `npm ls vue`? Often it is not corresponding to the one in `package.json`. Try `npm i vue@3.0.7` to force update.

**Comment by mits87** [comment]
ohh, you are right. The `npm ls vue` still displayed 3.0.9. 
So it means we are waiting for bug fix from here https://github.com/vuejs/vue-next/issues/3497

**Comment by shqyking** [comment]
I encountered same problem and my Vue version is 3.0.7(double checked with `npm ls vue`).  I didn't use `<teleport>` anywhere in the codebase, but maybe some library that I use is using the `<teleport>`. kazupon/vue-i18n#1168  above is opened by me.

**Comment by ota-meshi** [comment]
It works fine with the newly released vue v3.0.10.

**Comment by antonio-wundermart** [comment]
We have the same issue, in particular we are using this stack: 
vue3, vite, primevue (ui framework) and vue-i18n. 
In the latest versions of Primevue they use heavily teleports, which cause the aforementioned error when we change route. 
We solved downgrading primevue to an older version which doesn't rely on teleport, but this is not optimal at all. We are considering to move out from vue-i18n since we want also to start using teleport as well for our components.

**Comment by ota-meshi** [comment]
You need to use `vue@3.0.10` or later.

**Comment by antonio-wundermart** [comment]
> You need to use `vue@3.0.10` or later.

Thanks, you are right, I cannot replicate it anymore after upgraded vue and cleaned my caches.

**Comment by kazupon** [comment]
This issue was caused by a bug in Vue. This problem does not occur after `vue@3.0.10`, so it is closed.

Thank you for your feedback!

**Comment by ldsenow** [comment]
I am on Vue 3.2.25, however, the issue is still happening.

![image](https://user-images.githubusercontent.com/177045/167850209-ef2b74c5-39cd-408c-b0eb-58524e1afd21.png)
