### ISSUE TITLE
Example for lazy loading locales

### ISSUE THREAD

**Issue by samuveth** [intlify/vue-i18n-next#428]
Is there any example project for lazy loaded locales with vue3 + typescript? The example [here](https://vue-i18n-next.intlify.dev/guide/advanced/lazy.html) leaves me with a lot of questions

**Comment by PeterAlfredLee** [comment]
@samuveth 
Are you looking for this ? 
https://github.com/intlify/vue-i18n-next/tree/master/examples/lazy-loading/vite

**Comment by samuveth** [comment]
> @samuveth 
> Are you looking for this ? 
> https://github.com/intlify/vue-i18n-next/tree/master/examples/lazy-loading/vite

Yes, many thanks!

**Comment by kazupon** [comment]
Happy coding :)
