### ISSUE TITLE
CDN problems

### ISSUE THREAD

**Issue by Darkade** [intlify/vue-i18n-next#437]
- `vue@v2.6.12`
- `vue-i18n@9.1.0` 

I'm having two issues

1. The CDN link that appears in the documentation is broken. To reproduce just go to the link https://unpkg.com/vue-i18n/dist/vue-i18n

![image](https://user-images.githubusercontent.com/4106546/113921178-4bb09e80-97ab-11eb-940a-89ed987f693f.png)

**Comment by kazupon** [comment]
Thank you for your reporting!

Sorry, I could understand what you are mean about it. 
This is a problem with the v8.x documentation.
I have updated the correct CDN link.
https://kazupon.github.io/vue-i18n/installation.html

Please check it!

Thanks!
