### ISSUE TITLE
Syntax Error: no such file or directory, open '/app/node_modules/vue-i18n/dist/vue-i18n.esm.js'

### ISSUE THREAD

**Issue by v-dale** [intlify/vue-i18n-next#448]
**Reporting a bug?**
Hi
I'm getting this error when I try to use i18n with vue 3. I tried the previous version, got the same error
I get: 
- error  in ./node_modules/vue-i18n/dist/vue-i18n.esm.js
- Syntax Error: no such file or directory, open '/app/node_modules/vue-i18n/dist/vue-i18n.esm.js'

**Module versions (please complete the following information):**
 - `vue`: 3.x
 - `vue-i18n`: 9.x

**Reproduction Link**
don't have reproduction link

**To Reproduce**
npm install vue-i18n@next

**Expected behavior**
it should just work

**Comment by kazupon** [comment]
Thank you for your reporting!
I could not reproduce this issue.

Could you provide a minimum reproduction code with GitHub repo, please?

**Comment by v-dale** [comment]
Thanks for your reply
I faced this issue when I installed the package and npm dev was running. I restarted it and the issue was resolved. 

Thanks a lot

**Comment by elzodxon** [comment]
Hello, I am having the same issue on     `"vue-i18n": "^9.2.2"` this version. How can I resolve it?
