### ISSUE TITLE
Hot reloading locales in single file components is not working

### ISSUE THREAD

**Issue by SI-IC** [intlify/vue-i18n-next#456]
Hello. Please help.
Everything is working perfect. But after hot reloading I get keys from locale `<i18n>` tag instead of values. In console I see messages like:
![image](https://user-images.githubusercontent.com/78099231/114685014-26c3aa80-9d1a-11eb-8684-74a23de1e840.png)

What can I do to fix it?
Thanks in advance.

**Comment by kazupon** [comment]
Thank you for your reporting!
But, We need more information.

Please understand the guideline.
https://github.com/intlify/vue-i18n-next/blob/master/.github/CONTRIBUTING.md#general-guidelines

You would like to re-option as new issues.
Thanks!

**Comment by NikitaIT** [comment]
This is what has happened every time since I created an empty project with vue-cli.
![46](https://user-images.githubusercontent.com/16810067/124777291-64625900-df40-11eb-9cba-b1b6fc358fc0.gif)
