### ISSUE TITLE
Incorrect type declaration file in vue-i18n@9.1.5

### ISSUE THREAD

**Issue by gedzeppelin** [intlify/vue-i18n-next#458]
Hello, in the latest version (9.1.5) of this package, the vue-i18n.d.ts file has been generated incorrectly with the following code:

`declare module '@vue/runtime-core' { ... }`

Due to this, all 'vue' and 'vue-i18n ' module exports become unusable. The current type declaration file can be seen [here (jsdelivr)](https://cdn.jsdelivr.net/npm/vue-i18n@9.1.5/dist/vue-i18n.d.ts).

**Module versions:**
 - `vue`: 3.0.11
 - `vue-i18n`: 9.1.5

Thanks in advance.

**Comment by bobohuochai** [comment]
The same problem.

**Comment by kazupon** [comment]
yeah, that's is breaking ...
I'll try to fix it now.
