### ISSUE TITLE
不兼容vite 中ts 模板的引入

### ISSUE THREAD

**Issue by wushijiang13** [intlify/vue-i18n-next#462]
**Reporting a bug?**
 - Try to search for your issue, it may have already been answered or even fixed in the development branch.
 - Check if the issue is reproducible with the latest version of Vue I18n. If you are using a pre-release, please indicate the specific version you are using.
 - For bugs that involves build setups, you can create a reproduction repository with steps in the .github/CONTRIBUTING.md
 - If your issue is resolved but still open, don’t hesitate to close it. In case you found a solution by yourself, it could be helpful to explain how you fixed it.

**Module versions (please complete the following information):**
 - `vue`: 3.0.5
 - `vue-i18n`: ^9.1.5

**Reproduction Link**
A minimal JSBin, JSFiddle, Codepen, CodeSandbox, or a GitHub reprository that can reproduce the bug.

You can use reproduction CodeSandbox template: https://codesandbox.io/s/vue-i18n-9-template-h28c0

**To Reproduce**
ex:
1.在vue-i18n.d.ts 中并未暴露createI18n函数。
2.import {createI18n}  from  'vue-i18n' 提示error

**Expected behavior**
对ts 导入进行兼容。并将相关函数暴露在vue-i18n.d.ts 文件中以便导致

**Screenshots**
![image](https://user-images.githubusercontent.com/38801556/114963074-83e86900-9e9e-11eb-8b01-62db619cebbc.png)
![image](https://user-images.githubusercontent.com/38801556/114963113-982c6600-9e9e-11eb-97ff-1a070d5e4882.png)

**Additional context**
no

**Comment by wushijiang13** [comment]
请将
![image](https://user-images.githubusercontent.com/38801556/114963819-23f2c200-9ea0-11eb-8d88-b49194b6a63f.png)中函数暴露出来

**Comment by kazupon** [comment]
Hi! Thank you for your reporting!

I seem you use vue-i18n v9.1.5
That version type definition is broken. You can see #458

Could you check the vue-i18n version and upgrade?

**Comment by wushijiang13** [comment]
好的，已经解决，谢谢

**Comment by wushijiang13** [comment]
![image](https://user-images.githubusercontent.com/38801556/114980929-ca9a8b00-9ebf-11eb-8505-9924e7e5e380.png)
Is the assignment here a deep copy? My vuex status has been updated but has not been monitored and modified

**Comment by wushijiang13** [comment]
> 你好！感谢您的举报！
> 
> 我似乎您使用的是vue-i18n v9.1.5，
> 该版本类型定义已损坏。你可以看到[＃458](https://github.com/intlify/vue-i18n-next/issues/458)
> 
> 您可以检查vue-i18n安装的版本并升级吗？
Thank you. I have solved the above problem, but I have to introduce it here
![image](https://user-images.githubusercontent.com/38801556/115003784-b9aa4380-9ed8-11eb-8eb0-98bbb766fe7f.png)
Is the assignment here a deep copy? My vuex status has been updated but has not been monitored and modified

**Comment by kazupon** [comment]
The `locale` options of `createI18n` pass by value.
For this reason, we will copy the value of state in Vuex.
If you want to make the `locale` reactive to the Vuex state, you need to pass it to the `locale` via `global` of the `createI18n` generated i18n instance using `computed`, `watch`, `watchEffect`, and so on.

See the detail:
https://vue-i18n.intlify.dev/ja/api/general.html#global

I seem that you have solved the problem that mold does not solve.

This is not the place to ask questions, this is a GitHub Issue.
You can ask about the question in the [Vue.js Discord](https://vue-land.js.org/) or [GitHub Discussions](https://github.com/intlify/vue-i18n-next/discussions).

Thanks

**Comment by wushijiang13** [comment]
> 按值传递的`locale`选项`createI18n`。
> 因此，我们将在Vuex中复制state的值。
> 如果你想使`locale`反应到Vuex状态，你需要它传递给`locale`通过`global`的的`createI18n`使用产生的国际化实例`computed`，`watch`，`watchEffect`，等等。
> 
> 查看详细信息：[https](https://vue-i18n.intlify.dev/ja/api/general.html#global) :
> [//vue-i18n.intlify.dev/ja/api/general.html#global](https://vue-i18n.intlify.dev/ja/api/general.html#global)
> 
> 我似乎您已经解决了模具无法解决的问题。
> 
> 这不是问问题的地方，这是GitHub问题。
> 您可以在[Vue.js Discord](https://vue-land.js.org/)或[GitHub Discussions中](https://github.com/intlify/vue-i18n-next/discussions)询问有关该问题的[信息](https://vue-land.js.org/)。
> 
> 谢谢

Okay, thanks for your reply. This is a great help to me~
