### ISSUE TITLE
_vueI18n can be undefined and throw error in __DEV__

### ISSUE THREAD

**Issue by m0ksem** [intlify/vue-i18n-next#476]
**Module versions (please complete the following information):**
 - `vue`: 3.0.5
 - `vue-i18n`: 9.1.6

**Reproduction Link**
https://github.com/m0ksem/vue-i18n-render-error

Look at List.vue component. It renders the Separator component from the slot, where $i18n = undefined for some reason.

Probably you need to add a simple undefined check.

**Screenshots**
**Current behavior**
![image](https://user-images.githubusercontent.com/23530004/115861281-4bff9980-a43b-11eb-9db1-8fe265c80651.png)

Probably you should just check for undefined.

```ts
const _vueI18n: VueI18nInternal<
          Messages,
          DateTimeFormats,
          NumberFormats
        > = this.$i18n
        if (_vueI18n) {
          _vueI18n.__disableEmitter && _vueI18n.__disableEmitter()
        }
        
        delete this.$el.__VUE_I18N__
      }
```
in packages/vue-i18n/src/mixin.ts:133

**Comment by kazupon** [comment]
related #412
I think that issue is same!

**Comment by m0ksem** [comment]
Yes. The error message looks different, but it is the same issue. 

I still get this issue. I upgraded Vue to 3.0.11 in the reproduction repo. So #412 should be reopened.

**Comment by kazupon** [comment]
I checked your repro codes and debugged your code.

I think this is bug of Vue
I have confirmed that the beforeUnmount occurs twice in your code as well.

I hope You should send an issue to vue-next along with your code.
