### ISSUE TITLE
$n ignores formatting options

### ISSUE THREAD

**Issue by johannesstricker** [intlify/vue-i18n-next#481]
`$n` seems to ignore formatting options.
```javascript
$n(1.234234, { maximumFractionDigits: 2 }); // -> returns 1.234 instead of 1.23
```

**Module versions (please complete the following information):**
 - `vue`: 3.0.11
 - `vue-i18n`: 9.1.6

**Reproduction Link**
https://codesandbox.io/s/vue-i18n-9-template-forked-45g0k

**Expected behavior**
Since `maximumFractionDigits: 2` is specified, the number should be formatted with 2 decimals. Instead it shows the default 3 decimals.

**Comment by PeterAlfredLee** [comment]
Hi, @johannesstricker 

This might be a configuration error. See this Link: https://codesandbox.io/s/vue-i18n-9-template-forked-2gxxq
If you add these config
```js
numberFormats: {
  en: {
	decimal: {
	  maximumFractionDigits: 2
	}
  },
  ja: {
	decimal: {
	  maximumFractionDigits: 2
	}
  }
}
```
and call `$n` like this : 
```html
<p>{{ $n(1.123123, "decimal") }}</p>
```
everything works fine.

Also, if you want to overwrite the `maximumFractionDigits`, you can call `$n` like this:
```html
<p>{{ $n(1.123123, "decimal", {maximumFractionDigits: 5}) }}</p>
```

Hope this help.

**Comment by johannesstricker** [comment]
Thank you, that did work 👍  I was really confused because there was no need to specify the number format in v8 and the docs are not really explicit about this.
