### ISSUE TITLE
Changing the locale outside of the component does not take effect

### ISSUE THREAD

**Issue by de-Formator** [intlify/vue-i18n-next#488]
Changing the locale outside of the component using `i18n.global.locale = %locale_name%`  won’t make it work.

Module versions:
 - `vue`: 3.x
 - `vue-i18n`: 9.x

Reproduction Link:
https://bsuxp.csb.app/

**Comment by averetennikov** [comment]
Agree. The same problem.

**Comment by kazupon** [comment]
Thank you for your reporting!

You need to use "i18n.global.locale.value =\`${locale_name}\`".
See the about docs:
https://vue-i18n.intlify.dev/api/general.html#global

Thanks!
