### ISSUE TITLE
Property 'install' is missing in type 'VueI18n'

### ISSUE THREAD

**Issue by sgClaudia98** [intlify/vue-i18n-next#491]
**Module versions (please complete the following information):**
 - `vue`: 3.0.5
 - `vue-i18n`: 8.24.3
Vue with typescript

**To Reproduce**
1. In the `main.ts` file 
```
import { createApp } from "vue";
import App from "./App.vue";
import VueI18n from "vue-i18n";
import { Locales } from "./locales";

import en from "./en.json";
import es from "./es.json";

const messages = {
    [Locales.EN]: en,
    [Locales.ES]: es
};
const defaultLocale = Locales.EN;

const i18n = new VueI18n({
    locale: defaultLocale, //if you need get the browser language use following "window.navigator.language"
    fallbackLocale: defaultLocale,
    messages,
    silentTranslationWarn: true
})

createApp(App)
    .use(i18n)
    .mount("#app");

```

2. Tipical `en.json` and `es.json`
3. new `locales.ts` file with
```
export enum Locales {
    EN = 'en',
    ES = 'es',
}

export const LOCALES = [
    { value: Locales.EN, caption: 'English' },
    { value: Locales.ES, caption: 'Español' }
]
```

4. See error on Visual Studio
`Argument of type 'VueI18n' is not assignable to parameter of type 'Plugin_2'.
  Property 'install' is missing in type 'VueI18n' but required in type '{ install: PluginInstallFunction; }'.ts(2345)`

5. Running de app see error on Browser console
`Uncaught TypeError: Cannot read property 'config' of undefined
    at VueI18n2._initVM (vue-i18n.esm.js:1332)
    at new VueI18n2 (vue-i18n.esm.js:1271)
    at index.ts:13`

**Expected behavior**
Successfully added VueI18n plugin to VUE

**Comment by kazupon** [comment]
Thank you for your reporting!
vue-i18n@v8.24.3 is for Vue 2.x
You need to use vue-i18n@v9.x

Please, read the docs
https://vue-i18n.intlify.dev/

thanks!
