### ISSUE TITLE
How to use Component Interpolation and Custom Directive in jsx

### ISSUE THREAD

**Issue by jiangmaniu** [intlify/vue-i18n-next#517]
I need to use [Component Interpolation](https://vue-i18n.intlify.dev/guide/advanced/component.html) in my project, but I don’t know how to use it. I don’t understand the content of the document very well.

I cannot import `I18nT` through `import` in the `jsx` file, and the following error will be reported:

```
'"vue-i18n"' has no exported member named 'I18nT'. Did you mean 'I18n'?ts(2724)
```

When I read the [document](https://vue-i18n.intlify.dev/guide/advanced/component.html#basic-usage), I found that the document is used directly, I don’t know whether `i18n-t` is registered globally.

But I cannot use `i18n-t` without introducing components in `jsx` file. The component cannot be used globally, because it will be output as it is and will not be compiled

``` vue
<i18n-t keypath="sys.login.registerlabel" tag="span" for="tos">
    <a href="url" target="_blank">{t('sys.login.registerLink')}</a>
</i18n-t>
```

In `jsx`, it is also not possible to use `v-t="'xxx'"` instructions in the [document](https://vue-i18n.intlify.dev/guide/advanced/directive.html#string-syntax).

Can I use `Component Interpolation` and `Custom Directive` in `jsx`, and if so, what should I do?

**Comment by kazupon** [comment]
I've just added an example.
https://github.com/intlify/vue-i18n-next/tree/master/examples/tsx

Please check it!

**Comment by jiangmaniu** [comment]
> I've just added an example.
> https://github.com/intlify/vue-i18n-next/tree/master/examples/tsx
> 
> Please check it!

Thank you very much for the example you submitted, it will be of great help to me~
