### ISSUE TITLE
Uncaught ReferenceError: __INTLIFY_PROD_DEVTOOLS__ is not defined in production mode.

### ISSUE THREAD

**Issue by HamzaShafiq** [intlify/vue-i18n-next#529]
**Description**
I have installed vue-i18n@next for vue 3 app. Locally it works fine but while deploying to production. After it is deployed, we see the console error saying 

**Module versions (please complete the following information):**
 - `vue`: "^3.0.0",
 - `vue-i18n`: "^9.1.6"
 
**Expected behavior**
The production build should be working correctly

**Screenshots**
<img width="1765" alt="console error" src="https://user-images.githubusercontent.com/18363127/121688779-44747c80-cadd-11eb-8dfc-714ade53266b.png">

Kindly let me know what I am doing wrong.

**Comment by kazupon** [comment]
Thank you for your reporting!
This is a bug

If you would like to avoid this issue, you need to specify `__INTLIFY_PROD_DEVTOOLS__` flag on bundler configuration
About this flag, see the below URL:
https://vue-i18n.intlify.dev/guide/advanced/optimization.html#reduce-bundle-size-with-feature-build-flags

By the way, This fix will be officially released in v9.2.
Currently, the alpha version of v9.2 has been released.
This version is not yet stable, but it can be used in much the same way as v9.1, except for the support for TypeScript, which is unaffected by the disruptive changes.

Thanks!

**Comment by micDropper** [comment]
@kazupon So v9.2 does not work with TypeScript yet? I have TypeScript errors when I attempt to build for production with v9.2.
