### ISSUE TITLE
Number formatting 'unit' style not working

### ISSUE THREAD

**Issue by yannbriancon** [intlify/vue-i18n-next#540]
I saw this issue https://github.com/intlify/vue-i18n-next/issues/481 but I do not manage to make it work with style 'unit'

**Module versions (please complete the following information):**
 - `vue`: 3.1.1
 - `vue-i18n`: 9.1.6

**Reproduction Link**
https://codesandbox.io/s/vue-i18n-9-number-formatting-bug-xluuc?file=/index.html

**To Reproduce**
1. Go to https://codesandbox.io/s/vue-i18n-9-number-formatting-bug-xluuc?file=/index.html
2. See the number 1 displayed without unit

**Expected behavior**
See the number 1 displayed with its unit 'year'

**Comment by yannbriancon** [comment]
So I managed to make it work with the fix proposed in the issue https://github.com/intlify/vue-i18n-next/issues/481 

Though, the typescript definitions look out of date because it throws an error:
![image](https://user-images.githubusercontent.com/18755947/122362401-64ca8e00-cf58-11eb-9538-a029182d8e2c.png)

**Comment by PeterAlfredLee** [comment]
@yannbriancon  try this: https://codesandbox.io/s/vue-i18n-9-number-formatting-bug-forked-1qrkv?file=/index.html

**Comment by yannbriancon** [comment]
Thanks @PeterAlfredLee, that was also how I made it work!

We could close the issue but I think the typing should be fixed, I will try to make a PR.
