### ISSUE TITLE
SSR: global messages from SFC not available outside the component

### ISSUE THREAD

**Issue by userquin** [intlify/vue-i18n-next#547]
**Reporting a bug?**
The messages loaded using `i18n` on SFC are not available on SSR outside the SFC but are there on client side.

I'm integrating `vue-i18n` with `vue-router` to add SSG on `vite-ssg`.

**Module versions (please complete the following information):**
 - `vue`: 3.1.1
 - `vue-i18n`: 9.1.6
 - `vite`: 2.3.7
 - `vue-router`: 4.0.9

**Reproduction Link**
https://github.com/userquin/vite-ssg/tree/feat/i18n-ssg-router

**To Reproduce**

1. from root folder run: `pnpm install && pnpm run build && pnpm run example:i18n:build-serve`
2. Go to dist folder on examples/dist and see `b.html` and `es/b.html` => missing title and description on head but below inside a paragraph the title is there `<p>{{ t('PageB.title') }}</p>`
3. open browser and go to `/b` link
4. the title and the description are there

**Expected behavior**

The messages should be available, seems to be loaded in an async fashion.

**Screenshots**

**Additional context**

**Comment by kazupon** [comment]
Thank you for your reporting!
I could not reproduce this issue.

Could you give us more info (e.g. screenshot and context), please?

**Comment by userquin** [comment]
@kazupon the problem here is that the setup method is called on `renderToString` and not in the normal lifecycle (`i18n` just set the reference to `i18n` stuff and pass this data to the setup method). This is not a problem of `vue-i18n`, sorry for the inconveniences.
