### ISSUE TITLE
assets in dist directory exists not compiled code '...'

### ISSUE THREAD

**Issue by YolandaQingniu** [intlify/vue-i18n-next#548]
Rest parameters '...' not be compiled

**Module versions (please complete the following information):**
 - `vue`: 3.x
 - `vue-i18n`: 9.x

![image](https://user-images.githubusercontent.com/23188780/123233391-9c16dd00-d50c-11eb-8bba-d75680a0179e.png)
![image](https://user-images.githubusercontent.com/23188780/123233458-ac2ebc80-d50c-11eb-9d15-2f1eece0d77c.png)

Now i resolve it in my project via add `transpileDependencies` field in vue.config.js to make babel to translate vue-i18n module

```js
  transpileDependencies: [
    /[/\\]node_modules[/\\](.+?)?vue-i18n[/\\]/,
  ],
```

**Comment by kazupon** [comment]
Thank you for your feedback!

As with Vue 3, vue-i18n-next does not support IE11.
https://github.com/vuejs/rfcs/discussions/296

If you really want to support IE11, you need the babel plugin as you have tried.
(vue-i18n-next does not support issues related to that.)

Thanks!
