### ISSUE TITLE
add docs for 2 new options  from vite-plugin-vue-i18n

### ISSUE THREAD

**Issue by kazupon** [intlify/vue-i18n-next#554]
from issue comment

-----
I need to add docs for these 2 new options (but first I'll wait for your feedback, once ok I can add docs) and also on the site (at least here: https://vue-i18n.intlify.dev/guide/advanced/sfc.html#bundling-with-vite, and here https://vue-i18n.intlify.dev/guide/advanced/sfc.html#bundling-with-rollup (for webpack I need to review options), but it is is another repo).

_Originally posted by @userquin in https://github.com/intlify/vite-plugin-vue-i18n/issues/109#issuecomment-871253865_

**Comment by userquin** [comment]
@kazupon I'll try to add options todas, I' also very busy at work...

I'm traying to align this library, its plugin, `vite-plugin-pages` and `vite-ssg` and so having  SSG with i18n router. 
You can see my fork and my i18n branch. 
You can also find a reference on vite ssg discusions.

**Comment by userquin** [comment]
Can I add `vitepress` to `dev dependencies` (what version have you installed globally). I'm not a fan of using global dependencies...
