### ISSUE TITLE
get localization fail when key ends with a point

### ISSUE THREAD

**Issue by snowchenlei** [intlify/vue-i18n-next#558]
```
Test:{
 IsRequired.:'IsRequired'
}
```
t('Test. IsRequired.') The value could not be obtained.
how to get?

**Comment by PeterAlfredLee** [comment]
Hi @snowchenlei 
Could you provide some detailed code to reproduce this problem?

I tested with a variable ends with point and got an error
> Uncaught SyntaxError: Unexpected token '.'

I'm wondering why you are trying to name a varibale that ends with a point?

**Comment by snowchenlei** [comment]
Defined in a referenced third-party package.
not me

**Comment by PeterAlfredLee** [comment]
> Defined in a referenced third-party package.
I see.

So could you provide some detailed code to reproduce this problem?

**Comment by snowchenlei** [comment]
api get local.result like this
![image](https://user-images.githubusercontent.com/26211283/124411077-654b8d00-dd7e-11eb-9da0-7c48436290cd.png)

**Comment by snowchenlei** [comment]
If It's not easy to solve, I will try TrimEnd to remove the end point

**Comment by PeterAlfredLee** [comment]
IMO defining a variable ends with point is a illegal in JavaScript.
I think this is a problem of third-party package.

**Comment by snowchenlei** [comment]
Third-party packages do not use js, use like c#
