### ISSUE TITLE
I'm sorry for sending an issues in a wrong place, please delete this if some admin see this.

### ISSUE THREAD

**Issue by KawaiiZapic** [intlify/vue-i18n-next#565]
I'm sorry to send an issues in a wrong place, please delete this if some admin see this.

**Comment by PeterAlfredLee** [comment]
Hi @KawaiiZapic 
Is this a vue-i18n related issue?

**Comment by PeterAlfredLee** [comment]
@kazupon 
Seems you can close this issue.

**Comment by kazupon** [comment]
Close because it does not follow the issue guideline.
