### ISSUE TITLE
vue-router.esm-bundler.js?6c02:3248 TypeError: _locales__WEBPACK_IMPORTED_MODULE_2__.default.te is not a function

### ISSUE THREAD

**Issue by dybxin** [intlify/vue-i18n-next#569]
### Reporting a bug?

vue-router.esm-bundler.js?6c02:3248 TypeError: _locales__WEBPACK_IMPORTED_MODULE_2__.default.te is not a function

### Expected behavior

success

### Reproduction

no

### System Info

```shell
kages vue,vue-i18n --binaries --browsers
npx: installed 1 in 1.769s

  System:
    OS: Linux 5.8 Ubuntu 20.04.2 LTS (Focal Fossa)
    CPU: (8) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
    Memory: 15.02 GB / 31.26 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 14.17.0 - ~/.nvm/versions/node/v14.17.0/bin/node
    Yarn: 1.22.10 - ~/.nvm/versions/node/v14.17.0/bin/yarn
    npm: 6.14.13 - ~/.nvm/versions/node/v14.17.0/bin/npm
  Browsers:
    Chrome: 91.0.4472.114
    Firefox: 89.0.2
  npmPackages:
    vue: ^3.0.0 => 3.1.2 
    vue-i18n: ^9.1.6 => 9.1.6
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/intlify/vue-i18n-next/blob/master/.github/CONTRIBUTING.md)
- [X] Read the [Documentation](https://vue-i18n.intlify.dev/)
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/intlify/vue-i18n-next/discussions)

**Comment by kazupon** [comment]
Thanks for filing the issue!

Could you provide the reproduction repo or minimum code, please?

It says the following in the notes to the issue form

>Please provide a link to a repo that can reproduce the problem you ran into. A reproduction is required unless you are absolutely sure that the issue is obvious and the provided information is enough to understand the problem. If a report is vague (e.g. just a generic error message) and has no reproduction, it will receive a "Status: Need More Info" label. If no reproduction is provided after 5 days, it will be closed.

Thanks!

**Comment by kazupon** [comment]
close, due to so it's had passed 5 days.
if you have anything more information, you can open the new issue.

Thanks.
