### ISSUE TITLE
loadlLocaleMessages() does not import json files correctly

### ISSUE THREAD

**Issue by bogannathan** [intlify/vue-i18n-next#597]
### Reporting a bug?

After adding vue i18n, a bootstrapped file "i18n.js" is added. There is a typo that prevents global messages loaded from the .json files in the locales folder from being loaded correctly. 

### Expected behavior

After adding globalInjection: true to the i18n file, I should be able to translate with $t anywhere.

### Reproduction

bootstrap a vue 3 project and run "vue add i18n"

### System Info

```shell
Windows 10
```

### Additional context

Changing "messages[locale] = locales(key)" to "messages[locale] = locales(key).default" fixes the issue. 

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/intlify/vue-i18n-next/blob/master/.github/CONTRIBUTING.md)
- [X] Read the [Documentation](https://vue-i18n.intlify.dev/)
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/intlify/vue-i18n-next/discussions)

**Comment by PeterAlfredLee** [comment]
Just tested: `loadlLocaleMessages()` should use `.default` with `vue3`, and should not use `.default` with `vue2`.
And I just opened [PR #217 in vue-cli-plugin-i18n](https://github.com/intlify/vue-cli-plugin-i18n/pull/217) to fix this.
WDYT @kazupon

**Comment by kazupon** [comment]
I've just released `vue-cli-plugin-i18n` latest version
https://github.com/intlify/vue-cli-plugin-i18n/releases/tag/v2.1.2
Please check it!

@PeterAlfredLee 
Thank you for your helping as always. :)

**Comment by PeterAlfredLee** [comment]
> Thank you for your helping as always. :)

You're welcome, this is a wonderful community and I'm happy to contribute :)

**Comment by kazupon** [comment]
@bogannathan 
Could you resolve it?
If you could resolve this, please you will close this issue.
