### ISSUE TITLE
Duplicate word in the doc  "Whether Whether"

### ISSUE THREAD

**Issue by dcyou** [intlify/vue-i18n-next#598]
### Reporting a bug?

sound like the word is twice

### Expected behavior

one word

### Reproduction

read the doc ^^

### System Info

```shell
all
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/intlify/vue-i18n-next/blob/master/.github/CONTRIBUTING.md)
- [X] Read the [Documentation](https://vue-i18n.intlify.dev/)
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/intlify/vue-i18n-next/discussions)

**Comment by kazupon** [comment]
Good catch!
I've just fixed it.
Thanks!
