### ISSUE TITLE
vue-i18n-next bundle includes new Function()

### ISSUE THREAD

**Issue by wuiyang** [intlify/vue-i18n-next#600]
### Reporting a bug?

This is similar to the issue [reported previously](https://github.com/intlify/vue-i18n-next/issues/543), where vue-i18n-next does not work without permitting `unsafe-eval` in CSP `script-src`.

The latest code in `@intlify/core-base` contains `new Function()`, which prevents `vue-i18n-next` from executing if the server has setup CSP.

### Expected behavior

`vue-i18n-next` should work as normal without providing `unsafe-eval` in CSP `script-src`.

### Reproduction

1. Setup a simple `vue@next` + `vue-i18n@next` project.
2. Set CSP header for `script-src`, it should not contain `unsafe-eval`.
3. Navigate to Vue website and check console log.

### System Info

```shell
System:
    OS: Windows 10 10.0.19042
    CPU: (8) x64 Intel(R) Core(TM) i5-8300H CPU @ 2.30GHz
    Memory: 4.91 GB / 15.85 GB
  Binaries:
    Node: 12.22.1 - D:\Program Files\nodejs\node.EXE
    npm: 6.14.12 - D:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1023.0), Chromium (92.0.902.55)
    Internet Explorer: 11.0.19041.1
  npmPackages:
    vue: ^3.0.0 => 3.1.4
    vue-i18n: ^9.1.6 => 9.1.6
```

### Screenshot

Content Security Policy: The page’s settings blocked the loading of a resource at inline (“style-src”). chunk-vendors.c61ed6e9.js:6:7578
EvalError: call to Function() blocked by CSP

### Additional context

The source code where it falls under `unsafe-eval` CSP rule.
https://github.com/intlify/vue-i18n-next/blob/master/packages/core-base/src/compile.ts#L62

### Validations

- [x] Read the [Contributing Guidelines](https://github.com/intlify/vue-i18n-next/blob/master/.github/CONTRIBUTING.md)
- [X] Read the [Documentation](https://vue-i18n.intlify.dev/)
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/intlify/vue-i18n-next/discussions)

**Comment by kazupon** [comment]
Thank you for your feedback!

About CSP, I mentioned at this issue
https://github.com/intlify/vue-i18n-next/issues/543#issuecomment-864348217

you need to use bundler, and you can solve it by using the runtime-only module, as described in the docs.
https://vue-i18n.intlify.dev/ja/guide/advanced/optimization.html#improve-performance-and-reduce-bundle-size-with-runtime-build-only

**Comment by wuiyang** [comment]
Hi, it works perfectly, previously it was not working for me, maybe I have did something wrong. Thank you!

**Comment by kazupon** [comment]
No worries.
Happy coding!

**Comment by ameinhardt** [comment]
@kazupon : does core-base also have a runtime version? The runtime-only module would still include a [new Function in compile.ts](https://github.com/intlify/vue-i18n-next/blob/dab6db19a1ef917425939275a41dfde9b6c61fe9/packages/core-base/src/compile.ts#L62), doesn't it?

**Comment by kazupon** [comment]
@ameinhardt 
There is the runtime version for core-base
https://github.com/intlify/vue-i18n-next/tree/master/packages/core

However, We do not offer this package to the public.
we will improve the API and make it framework agnostic in the future.
