### ISSUE TITLE
Typescript support about 'tm'.

### ISSUE THREAD

**Issue by LiuQixuan** [intlify/vue-i18n-next#604]
## Vue I18n V9 typescript support
1. when I used tm like that `<p>{{tm('content')['paragraph1']}}</p>`, vscode problems display that "**`Element implicitly has an 'any' type because expression of type 'string' can't be used to index type '{} | LocaleMessageValue<VueMessageType>'.
  No index signature with a parameter of type 'string' was found on type '{} | LocaleMessageValue<VueMessageType>'.`**". What should I do to solve this type safe problem?

Although VSCode won't report it wrong like this,`<p>{{t('content.paragraph1')}}</p>`, I still want to try to find a way to solve it.

2. I have another problem about "v-t",I need to use message of non-current languages , like this:
```HTML
<select id="locale-select" v-model="locale">
  <option value="en-US" v-t="{path:'language',locale:'en-US'}"></option>
  <option value="zh-CN" v-t="{path:'language',locale:'zh-CN'}"></option>
</select>
```
The code is work here.but I want to know to do without v-t,using t or tm?

3. I don't understand why Schema is used as Typescript support, but I encountered an error when running the examples in github in vscode.
[`vue-i18n-next\examples\type-safe\type-annotation\src\main.ts`](https://github.com/intlify/vue-i18n-next/blob/master/examples/type-safe/type-annotation/src/main.ts)
![code](https://i.bmp.ovh/imgs/2021/08/7a193a164fa4af65.png)
![error](https://i.bmp.ovh/imgs/2021/08/67d49d2631cdefee.png)

Maybe my problem is stupid, but I can't solve myself, I hope I can get help.Thanks.

### Expected behavior

I need to get TypeScript support when using Vuei18N V9.

### Reproduction

https://codesandbox.io/s/purple-http-rg4zy?file=/index.html:555-791
I made a simplification of the code so that code run well what separated from the entire project.
```
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <title>Page Test</title>
    <script src="https://unpkg.com/vue@next"></script>
    <script src="https://unpkg.com/vue-i18n@next"></script>
  </head>
  <body>
    <div id="app"></div>
    <script>
      const { createApp, defineComponent, ref, watchEffect } = Vue;
      const { createI18n, useI18n } = VueI18n;
      const App = defineComponent({
        name: "App",
        template: `
          <form>
            <label for="locale-select">{{t('selectLanguage') }}</label>
            <select id="locale-select" v-model="locale">
              <option value="en-US" v-t="{path:'language',locale:'en-US'}"></option>
              <option value="zh-CN" v-t="{path:'language',locale:'zh-CN'}"></option>
            </select>
          </form>
          <div class="title">{{t('title')}}</div>
          <div class="content">
            <p>{{tm('content')['paragraph1']}}</p>
            <p>{{tm('content')['paragraph2']}}</p>
          </div>
        `,
        setup() {
          const { tm, t, locale } = useI18n();
          return { tm, t, locale };
        }
      });

      const i18n = createI18n({
        locale: "en-US",
        legacy: false,
        messages: {
          "en-US": {
            selectLanguage: "switch language",
            language: "English",
            title: "I Have A Dream",
            content: {
              paragraph1:
                'I have a dream that one day this nation will rise up and live out the true meaning of its creed: "We hold these truths to be self-evident, that all men are created equal."',
              paragraph2:
                "I have a dream that one day on the red hills of Georgia, the sons of former slaves and the sons of former slave owners will be able to sit down together at the table of brotherhood.",
              paragraph3:
                "I have a dream that one day even the state of Mississippi, a state sweltering with the heat of injustice, sweltering with the heat of oppression, will be transformed into an oasis of freedom and justice.",
              paragraph4:
                "I have a dream that my four little children will one day live in a nation where they will not be judged by the color of their skin but by the content of their character."
            }
          },
          "zh-CN": {
            selectLanguage: "选择语言",
            language: "中文",
            title: "我有一个梦想",
            content: {
              paragraph1:
                "我梦想有一天，这个国家会站立起来，真正实现其信条的真谛：“我们认为这些真理是不言而喻的——人人生而平等。”",
              paragraph2:
                "我梦想有一天，在佐治亚的红山上，昔日奴隶的儿子将能够和昔日奴隶主的儿子坐在一起，共叙兄弟情谊。",
              paragraph3:
                "我梦想有一天，甚至连密西西比州这个正义匿迹，压迫成风的地方，也将变成自由和正义的绿洲。",
              paragraph4:
                "我梦想有一天，我的四个孩子将在一个不是以他们的肤色，而是以他们的品格优劣来评价他们的国度里生活。"
            }
          }
        }
      });
      createApp(App).use(i18n).mount("#app");
    </script>
  </body>
</html>
```

### System Info

```shell
System:
    OS: Windows 10 10.0.22000
    CPU: (8) x64 Intel(R) Core(TM) i7-4720HQ CPU @ 2.60GHz
    Memory: 8.10 GB / 15.89 GB
  Binaries:
    Node: 15.9.0 - E:\Program Files\nodejs\node.EXE
    Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 7.5.3 - E:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22000.1.0), Chromium (92.0.902.55)
    Internet Explorer: 11.0.22000.1
  npmPackages:
    vue: 3.0.11 => 3.0.11
    vue-i18n: ^9.1.7 => 9.1.7
```

### Screenshot

![screenshot](https://i.bmp.ovh/imgs/2021/07/37052c957c9fbf18.png)

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/intlify/vue-i18n-next/blob/master/.github/CONTRIBUTING.md)
- [X] Read the [Documentation](https://vue-i18n.intlify.dev/)
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/intlify/vue-i18n-next/discussions)

**Comment by kazupon** [comment]
Thank you for your reporting!

> npmPackages:
    vue: 3.0.11 => 3.0.11
    vue-i18n: ^9.1.7 => 9.1.7

Schema is next feature for v9.2
Could you try to v9.2, please?

**Comment by LiuQixuan** [comment]
Although I upgrade "vue-i18n" to "9.2.0-beta.1", there are many mistakes in the vscode.
 But never mind,I give up new feature.
```typescript
messages: {
          "en-US": {
            selectLanguage: "switch language",
            language: "English",
            title: "I Have A Dream",
          },
          "zh-CN": {
            selectLanguage: "选择语言",
            language: "中文",
            title: "我有一个梦想",          
          }
        }

```
```html
 <select id="locale-select" v-model="locale">
              <option value="en-US" v-t="{path:'language',locale:'en-US'}"></option>
              <option value="zh-CN" v-t="{path:'language',locale:'zh-CN'}"></option>
 </select>
```
how I use't' or'tm' to instead of'v-t' directive to achieve the same effect.

[All Code Here](https://codesandbox.io/s/purple-http-rg4zy?file=/index.html:555-791)

**Comment by PeterAlfredLee** [comment]
@LiuQixuan 
[See complete modified code here](https://codesandbox.io/s/modest-curran-65eh5?file=/index.html)

How about this, Use the `t` function everywhere:
1
```html
<p>{{t('content.paragraph1')}}</p>
<p>{{t('content.paragraph2')}}</p>
```

2
```html
<select id="locale-select" v-model="locale">
        <option value="en-US" >{{t('language', '', {locale:'en-US'})}}</option>
        <option value="zh-CN" >{{t('language', '', {locale:'zh-CN'})}}</option>
</select>
```

Hope this helps.

**Comment by LiuQixuan** [comment]
thanks,It's work for me.
