### ISSUE TITLE
Can't iterate over yaml array of strings 

### ISSUE THREAD

**Issue by aidar-kz** [intlify/vue-i18n-next#614]
### Reporting a bug?

I have an array of strings in en.yml file like this:
```js
strings:
  - String 1
  - String 2
  - String 3
```
And I'm trying to display the array in a component using `v-for`:
`<li v-for="string in t('strings')">{{ string }}</li>`

But instead of displaying the array elements it iterates over the key and displays:
s
t
r
i
n
g
s

### Expected behavior

`v-for="$t('arrayOfString')"` iterates over array of strings, not over the key

### Reproduction

The issue is obvious and the provided information is enough to understand the problem?

### System Info

```shell
"vue": "^3.1.5"
"vue-i18n": "^9.1.7"
```

### Screenshot
![image](https://user-images.githubusercontent.com/78292999/128372463-36edaceb-360d-4927-9ad2-07ef471296bc.png)

<img width="768" alt="Screen Shot 2021-08-05 at 8 47 28 PM" src="https://user-images.githubusercontent.com/78292999/128370582-4bb781fa-419b-4770-b98f-dcacd0e03f54.png">

![image](https://user-images.githubusercontent.com/78292999/128371768-3f3d42b0-4a4e-4679-a667-50edb6d6ee56.png)

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/intlify/vue-i18n-next/blob/master/.github/CONTRIBUTING.md)
- [X] Read the [Documentation](https://vue-i18n.intlify.dev/)
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [x] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/intlify/vue-i18n-next/discussions)

**Comment by PeterAlfredLee** [comment]
Hi, @aidar-kz 

Function `t` can only return a string. In your case, you should use function `tm` and `rt`, like this:
```html
<ul>
  <li v-for="string in tm('strings')">{{ rt(string) }}</li>
</ul>
```

I have tested it and this can work.

See also these docs: 
[t](https://vue-i18n.intlify.dev/ja/api/composition.html#t-key) 
[tm](https://vue-i18n.intlify.dev/ja/api/composition.html#tm-key) 
[rt](https://vue-i18n.intlify.dev/ja/api/composition.html#rt-message) 

Hope this helps.

**Comment by aidar-kz** [comment]
Hi, @PeterAlfredLee 

Thanks a lot for your help, it now works!

Best wishes!
