### ISSUE TITLE
`Linked messages` will have more spaces in Chinese

### ISSUE THREAD

**Issue by jiangmaniu** [intlify/vue-i18n-next#615]
### Reporting a bug?

The link message and the normal text need to be separated by a space, otherwise the normal text will be used as the key of the link, but after the space is separated, the space will be output to the page.

![image](https://user-images.githubusercontent.com/50100681/128456511-3d57b7fe-8728-4d76-9524-10cece6107a5.png)

render:

![image](https://user-images.githubusercontent.com/50100681/128457035-27c83254-5d9d-4566-a997-a70a0309845e.png)

Tips: Chinese grammar should not have spaces in paragraphs

### Expected behavior

/

### Reproduction

/

### System Info

```shell
/
```

### Screenshot

/

### Additional context

/

### Validations

- [X] Read the [Documentation](https://vue-i18n.intlify.dev/)
- [X] Read the [Contributing Guidelines](https://github.com/intlify/vue-i18n-next/blob/master/.github/CONTRIBUTING.md)
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/intlify/vue-i18n-next/discussions)

**Comment by PeterAlfredLee** [comment]
@jiangmaniu 
I think we can use [Literal interpolation](https://vue-i18n.intlify.dev/guide/essentials/syntax.html#list-interpolation) to avoid the space you don't want, try this:
```json
{
    "common": {
        "confirmTipPrefix": "您是否确定要"
    },
    "logoutTip": "@:common.confirmTipPrefix{''}退出登录"
}
```

It works in my test. Hope this helps.

**Comment by jiangmaniu** [comment]
@PeterAlfredLee 
I’m sorry, I tried your method, but it didn’t work

![image](https://user-images.githubusercontent.com/50100681/128470358-ea280594-52e1-49d6-9b22-47af294286ea.png)

![image](https://user-images.githubusercontent.com/50100681/128470821-62099e21-90eb-4c71-8d12-7115b0d1b546.png)


This is my system related environment:

```sh
  System:
    OS: Windows 10 10.0.19042
    CPU: (4) x64 Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz
    Memory: 2.38 GB / 15.92 GB
  Binaries:
    Node: 14.17.0 - D:\Program Files\nodejs\node.EXE
    Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.14.13 - D:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1023.0), Chromium (92.0.902.62)
    Internet Explorer: 11.0.19041.1
  npmPackages:
    vue: ^3.1.4 => 3.1.4
    vue-i18n: ^9.1.6 => 9.1.6
```

**Comment by PeterAlfredLee** [comment]
@jiangmaniu 
I see you use double quotation ({""}).
Please use single quotation({''}) instead of double quotation({""}).
See also this [doc](https://vue-i18n.intlify.dev/guide/essentials/syntax.html#literal-interpolation), it says:
>Literal interpolation allows you to specify string literal that is quoted with single quotation ’.

**Comment by jiangmaniu** [comment]
@PeterAlfredLee Oh, that's it, it can solve my problem, thank you very much!❤

**Comment by PeterAlfredLee** [comment]
@jiangmaniu 
I'm glad to help.  If everything is fine, please close this issue.
