### ISSUE TITLE
<i18n-t> in slot won't get component's local messages

### ISSUE THREAD

**Issue by i4nch1k** [intlify/vue-i18n-next#708]
### Reporting a bug?

I'm migrating my project to Vue 3 and have issues with `<i18n-t>` in slots (that I didn't have with Vue 2).
Here is a component C1 with `$t` and `<i18n-t>`:
```
<template>
    <span>C1:</span>
    <div>{{ $t("hello", { world: $t("world") }) }}</div>
    <i18n-t keypath="hello" tag="div">
      <template #world>
        <strong>{{ $t("world") }}</strong>
      </template>
    </i18n-t>
</template>

<script>
...
  i18n: {
    messages: {
      en: {
        hello: "Hello {world}",
        world: "world!",
      },
    },
  }
...
</script>
```

This outputs, as expected:

> C1:
> Hello world!
> Hello **world!**

Now, here is the component C2:
```
<template>
  <div>C2 slot: <slot></slot></div>
</template>
```
If I modify C1's template like this (aka just move previous code to C2's slot):
```
<template>
    <C2>
      <div>{{ $t("hello", { world: $t("world") }) }}</div>
      <i18n-t keypath="hello" tag="div">
        <template #world>
          <strong>{{ $t("world") }}</strong>
        </template>
      </i18n-t>
    </C2>
</template>
```

This outputs:

> C2 slot:
> Hello world!
> hello

As you can see, `$t` works as expected but not `<i18n-t>`, it behaves like it doesn't find the messages while `$t` does (like they do not have the same scopes).

### Expected behavior

Expected output:

> C2 slot:
> Hello world!
> Hello **world!**

I expected `<i18n-t>` to have the same scope as `$t`, find the messages and show them instead of falling back to displaying the keypath.
I do not have this issue with Vue 2.

### Reproduction

https://codesandbox.io/s/suspicious-sea-reu1e

### System Info

```shell
npmPackages:
  vue: ^3.2.14 => 3.2.14 
  vue-i18n: ^9.1.7 => 9.1.7
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/intlify/vue-i18n-next/blob/master/.github/CONTRIBUTING.md)
- [X] Read the [Documentation](https://vue-i18n.intlify.dev/)
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/intlify/vue-i18n-next/discussions)

**Comment by semiaddict** [comment]
I am also experiencing this issue while using the vue-i18n-loader.
Here's an example similar to @i4nch1k's:

```
<i18n>
{
  "en": {
    "hello: "Hello {world}",
     "world: "world!",
  },
}
</i18n>

<template>
    <C2>
      <div>{{ $t("hello", { world: $t("world") }) }}</div>
      <i18n-t keypath="hello" tag="div">
        <template #world>
          <strong>{{ $t("world") }}</strong>
        </template>
      </i18n-t>
    </C2>
</template>
```

I get the same exact output as described above:
> C2 slot:
> Hello world!
> hello

I guess it's the same exact issue, no?

**Comment by kazupon** [comment]
@semiaddict 
>I guess it's the same exact issue, no?

Yes, it's the same issue.

**Comment by semiaddict** [comment]
Thank you very much @kazupon.
Would it be possible to add the fix on the 9.1.x version as well ? I think it was only applied to the 9.2.x, which is still in beta.

**Comment by kazupon** [comment]
@semiaddict 
I've just released v9.1.8
Please check it!
https://github.com/intlify/vue-i18n-next/releases/tag/v9.1.8

Happy coding! :)

**Comment by i4nch1k** [comment]
Thank you very much @kazupon!

**Comment by semiaddict** [comment]
Thank you very much @kazupon.
This seems to work just fine now, but I'm encountering another, possibly related, issue with the i18n-t component, which I just filled under https://github.com/intlify/vue-i18n-next/issues/722.

**Comment by kazupon** [comment]
@semiaddict 
Thank you for the suggestion!
This is an issue with the locale messages scope resolve on the `i18n-t` component (Translation Component). This is another issue, so please create a separate issue.
