### ISSUE TITLE
Hot updates

### ISSUE THREAD

**Issue by wikin** [intlify/vue-i18n-next#74]
Hello, 
pls how should works this new version with hot reloades?

I'm trying to utilize this example https://kazupon.github.io/vue-i18n/guide/hot-reload.html#advanced-example for new API, but 
i18n.setLocaleMessage function do not propagate changed message into current view.

**Comment by Liwoj** [comment]
It works for me using v9. Just make sure to replace `i18n.setLocaleMessage` (from the example) with `i18n.global.setLocaleMessage` (using Legacy API mode)

**Comment by kazupon** [comment]
It works with Vue-i18n v9.0 (latest version).
so, close it. If you have any problems, please open a new issue.
