### ISSUE TITLE
Cannot read properties of undefined (reading 'locale')

### ISSUE THREAD

**Issue by jemkein** [intlify/vue-i18n-next#763]
### Reporting a bug?

I hope that this is a Bug and not just a dumb TypeScript Error by me.

Changing/Accessing "$i18n.locale" isn't possible.
Neither in my own Vue3+TypeScript+i18n Project. Nor in the example type-annotation Project.
I tried to access "$i18n.locale"  with v-model, with double Brackets, with and without "this".
Like shown on the Documentation "https://vue-i18n.intlify.dev/guide/essentials/scope.html#global-scope-1"
But everytime I get "Uncaught TypeError: Cannot read properties of undefined (reading 'locale')" in my Chrome Console.
I can't find a viable solution on google/Stackoverflow.

There are just some know Bugs with a specific Order in Vue2.
But with "CreateApp" this should've changed in Vue3.
Yet I can't change or even show "$i18.locale" or other properties.

Maybe I need to specify a Type to the i18n created in main.ts. But I just don't know which Type I need.

### Expected behavior

Access i18n.locale and see the current selected Language.

### Reproduction

Simply clone the newest Version from GitHub, use the" type-annotation" or any other TS Example.
And add {{ $i18n.locale }} to a component.

### System Info

```shell
System:
    OS: Windows 10 10.0.19042
    CPU: (16) x64 AMD Ryzen 7 3700X 8-Core Processor
    Memory: 10.23 GB / 31.95 GB
  Binaries:
    Node: 14.18.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.1.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 95.0.4638.54
    Edge: Spartan (44.19041.1266.0), Chromium (95.0.1020.40)
    Internet Explorer: 11.0.19041.1202
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/intlify/vue-i18n-next/blob/master/.github/CONTRIBUTING.md)
- [X] Read the [Documentation](https://vue-i18n.intlify.dev/)
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/intlify/vue-i18n-next/discussions)

**Comment by PeterAlfredLee** [comment]
Hi, @jemkein 

I guess you are using composition API by configuring option `legacy: false`.
In this case, if you want to use `$i18n`， you should also configure optipon `globalInjection: true`. Like:
```js
const i18n = createI18n({
  locale: 'en-US',
  legacy: false,
  globalInjection: true
})
```
See also this [doc implicit-with-injected-properties-and-functions](https://vue-i18n.intlify.dev/guide/advanced/composition.html#implicit-with-injected-properties-and-functions)

**Comment by kazupon** [comment]
close to in-activity
If you have still an issue, you can open it as a new issue.

Thanks!

**Comment by omerayo87** [comment]
![image](https://user-images.githubusercontent.com/91366118/155431201-26c8f7b1-e5f0-43de-964e-06a1106e569b.png)
Hello, I am using Nuxt2 and I have this problem.
If you could help me!
Greetings
