### ISSUE TITLE
Add support for nested namespaces

### ISSUE THREAD

**Issue by LifeIsStrange** [intlify/vue-i18n-next#766]
### Clear and concise description of the problem

so today I can express
``` json
{
"note": {
       "description": "I am a description"
  }
}
```
but **not**
``` json
{
"MobileVersion": {
   "note": {
    "description": "a note on Android/IOS"
   }
 },
"DesktopVersion": {
   "note": {
    "description": "a note on Windows/Linux"
   }
 }
}
```

### Suggested solution

allow us to write nested namespaces so that I can have different content not only based on the current locale but on the context (Smartphone or desktop, or common ? and so many other use cases, e.g load specific data for **integration tests**, etc)
A nested namespace also allow (with e.g the [intellij extension](https://github.com/nyavro/i18nPlugin)) to have autocompletion for all sub-namespaces, and therefore easy access and **discoverability**

I think support for this should be somewhat prioritarized as it allow much greater flexibility/modularity and support for it should be (in my mind) not too difficult :)

### Alternative

keep the limitations

### Additional context

Hi @kazupon I don't know if the work in issue [271](https://github.com/intlify/vue-i18n-next/issues/271#issuecomment-753021600) can help.
The link is now dead, where is the message resolver ?
 https://github.com/intlify/vue-i18n-next/tree/master/packages/message-resolver
has it been renamed to https://github.com/intlify/vue-i18n-next/tree/master/packages/message-compiler ?

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/intlify/vue-i18n-next/blob/master/.github/CONTRIBUTING.md)
- [X] Read the [Documentation](https://vue-i18n.intlify.dev/)
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by LifeIsStrange** [comment]
update: my bad, **the feature is already supported**, I must have tested it wrongly the first time, sorry for the noise!

**Comment by yannanna0920** [comment]
我也遇到这个问题请问是什么错误呢

**Comment by LifeIsStrange** [comment]
@yannanna0920 it worked for me, maybe there was some option to set, see the documentation, I don't remember
