### ISSUE TITLE
Error while building

### ISSUE THREAD

**Issue by arkanario** [intlify/vue-i18n-next#767]
### Reporting a bug?

Hi, I used i18n to work with two different languages in my vue app. I have 2 files, 'en.json' and 'de.json'

All works fine when I run with "npm run serve", but when I run "npm run build" for some reason I discovered that in the compiled files was added to the end of the translations keys "undefinedundefinedundefined", always after the last entry key of the translation json files. 
![undefined](https://user-images.githubusercontent.com/57564614/140189968-5497b029-fca5-4050-b3ad-55e6dbc8f0eb.png)

And that gives me a error
![undefined_error](https://user-images.githubusercontent.com/57564614/140189984-c6003ff1-4963-4ac4-b5d1-3a8d8d023064.png)

If I remove i18n from the project, all works fine. Here is how I configured it:

![configuration](https://user-images.githubusercontent.com/57564614/140190611-8eb9454c-ec38-4489-a0da-fdd88812e334.png)

Any ideas?

### Expected behavior

If all is fine it should not happen

### Reproduction

Configure like this on main:
![configuration](https://user-images.githubusercontent.com/57564614/140190718-a1d9e8a5-dc1b-4a0a-97c2-16cf14a4c45c.png)

Initialize like this in the component:
![usage](https://user-images.githubusercontent.com/57564614/140190917-299bee1b-b716-44df-9c55-902cfcae1025.png)

Use like this:
![image](https://user-images.githubusercontent.com/57564614/140191916-01c6c26c-712d-4e0e-a252-64f7013a683d.png)

### System Info

```shell
System:
    OS: Windows 10 10.0.19043
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz  
    Memory: 3.67 GB / 31.92 GB
  Binaries:
    Node: 14.18.1 - C:\Program Files\nodejs\node.EXE        
    Yarn: 1.22.17 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.14.15 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 95.0.4638.69
    Edge: Spartan (44.19041.1266.0), Chromium (95.0.1020.30)
    Internet Explorer: 11.0.19041.1202
  npmPackages:
    @intlify/vue-i18n-loader: ^2.0.3 => 2.0.3
    @vue/cli-plugin-babel: ~4.5.0 => 4.5.11
    @vue/cli-plugin-eslint: ~4.5.0 => 4.5.11
    @vue/cli-plugin-router: ~4.5.0 => 4.5.11
    @vue/cli-plugin-unit-jest: ^3.8.0 => 3.12.1
    @vue/cli-service: ~4.5.0 => 4.5.11
    @vue/compiler-sfc: ^3.0.0 => 3.0.5
    vue: 3.0.2 => 3.0.2
    vue-cli-plugin-i18n: ~2.0.2 => 2.0.2
    vue-i18n: ^9.0.0 => 9.0.0
    vue-router: ^4.0.0-0 => 4.0.3
    vue-template-compiler: ^2.6.12 => 2.6.12
    vuex: ^4.0.0 => 4.0.0
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/intlify/vue-i18n-next/blob/master/.github/CONTRIBUTING.md)
- [X] Read the [Documentation](https://vue-i18n.intlify.dev/)
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/intlify/vue-i18n-next/discussions)

**Comment by PeterAlfredLee** [comment]
Hi, @arkanario , this might caused by [vue-i18n-loader#32](https://github.com/intlify/bundle-tools/issues/32).
I think you can update your dependency, like:
```json
"vue-i18n": "^9.2.0-beta.17",
"@intlify/vue-i18n-loader": "^4.0.0"
```

**Comment by kazupon** [comment]
Close to in-activity.
If you have still an issue, please you can open it as a new issue.

Thanks!
