### ISSUE TITLE
Strict types for translations (t('something'))

### ISSUE THREAD

**Issue by gnuletik** [intlify/vue-i18n-next#771]
### Clear and concise description of the problem

When using `use18n` with schema like in the provided example : https://github.com/intlify/vue-i18n-next/blob/master/examples/type-safe/type-annotation/src/components/LocalScope.vue

We are still able to call the `t` function with a key parameter that does not exist in the schema.

```
interface Message {
  hello: string
}
const { t } = useI18n<{ message: Message }, 'en-US'>({
  messages: {
    'en-US': {
      hello: 'Hello!'
    }
  }
})

// work as expected
console.log(t('hello'))

// should throws a type error but work without issue
console.log(t('notInSchema'))
```

Is that something possible ?

### Suggested solution

When typing `t` as `t (key: keyof Message): string`, an error is thrown when the value does not exist.

Is it possible to implement such a behavior ?
Maybe I'm missing something.

### Additional context

Thanks!

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/intlify/vue-i18n-next/blob/master/.github/CONTRIBUTING.md)
- [X] Read the [Documentation](https://vue-i18n.intlify.dev/)
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by kazupon** [comment]
Thank you for your suggestion!

> When typing `t` as `t (key: keyof Message): string`, an error is thrown when the value does not exist.
> 
> Is it possible to implement such a behavior ? Maybe I'm missing something.

Unfortunately, it is not possible to make an error if a non-existent key is specified. vue-i18n-next needs to keep compatibility with the existing version v8.x.
In the existing version v8.x, if a non-existent key is specified, that key will be returned.
This is the expected behavior of vue-i18n-next to maintain compatibility.

Thanks!

**Comment by gnuletik** [comment]
Thanks for the feedback @kazupon :)
It makes sense to keep the compatibility with previous versions of vue-i18n.

For my usecase, I wrapped vue-i18n in a wrapper which redefines types to throw errors in case of missing translation keys.

Here's the types if anyone is interested : 
```ts
export type Locale = 'en' | 'it'

interface Options<T extends string = string> {
  messages: Record<Locale, Record<T, string>>
}

interface UseI18N<T> {
  locale: Locale
  t: (key: T, replace?: Record<string, string>) => string
}

export function useI18n<T extends string> (options: Options<T>): UseI18N<T>
```

Thanks!

**Comment by rathax** [comment]
is there are a way to redeclare types to globally add strict types for t()? 

strictly typed translations would make maintaining large projects a lot easier.
