### ISSUE TITLE
Locale has wrong TS type

### ISSUE THREAD

**Issue by chojnicki** [intlify/vue-i18n-next#785]
### Reporting a bug?

I was using v9.1.7 and recently updated to v9.1.18. Code works just fine, but I got TS warnings in IDE that are misleading. TS treats `global.locale` as String and not Ref as it should. It looks like it takes type from legacy mode. Of course when I remove `.value` code breaks because `locale` is reactive.
I also tried `petite-vue-i18n` which is composition only, but still getting same warnings.
It's documented for example in https://vue-i18n.intlify.dev/guide/advanced/lazy.html

### Expected behavior

When using composition API, it should use typing also from composition api instead legacy.

### Reproduction

_i18n.ts:_
```
import { createI18n } from 'vue-i18n'

export const i18n = createI18n({
  locale: 'en',
  legacy: false,
})

export const changeLocale = () => {
  i18n.global.locale.value = 'en' // warning
}

```

### System Info

```shell
System:
    OS: Linux 5.4 Alpine Linux
    CPU: (12) x64 Intel(R) Core(TM) i7-5820K CPU @ 3.30GHz
    Memory: 300.15 MB / 15.60 GB
    Container: Yes
    Shell: 1.32.1 - /bin/ash
  Binaries:
    Node: 16.13.0 - /usr/local/bin/node
    Yarn: 1.22.15 - /usr/local/bin/yarn
    npm: 8.1.0 - /usr/local/bin/npm
  npmPackages:
    @vitejs/plugin-vue: ^1.1.4 => 1.9.0 
    @vue/compiler-sfc: ^3.0.7 => 3.2.13 
    @vue/eslint-config-typescript: ^7.0.0 => 7.0.0 
    @vue/test-utils: ^2.0.0-rc.12 => 2.0.0-rc.14 
    vite: ^2.0.4 => 2.5.10 
    vite-plugin-vue-svg: ^0.1.0 => 0.1.0 
    vue: ^3.0.7 => 3.2.13 
    vue-i18n: ^9.2.0-beta.18 => 9.2.0-beta.18 
    vue-jest: ^5.0.0-alpha.10 => 5.0.0-alpha.10 
    vue-router: ^4.0.4 => 4.0.11
```

### Screenshot

![Screenshot_2021-11-12_19-16-34](https://user-images.githubusercontent.com/34774522/141515575-ae022150-0aa1-4b1b-9b32-b2762f136388.png)

`Property 'value' does not exist on type 'string'.ts(2339`

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/intlify/vue-i18n-next/blob/master/.github/CONTRIBUTING.md)
- [X] Read the [Documentation](https://vue-i18n.intlify.dev/)
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/intlify/vue-i18n-next/discussions)

**Comment by tracy2zhang** [comment]
+1

**Comment by kazupon** [comment]
Thank you for your reporting!

I've just updated the lazy-loading example, so it was old 😅 
https://github.com/intlify/vue-i18n-next/commit/504675dcfdbf3e87b30aecd90cf1b10effbc6527

`createI18n` is a function designed to support both styles of the Options API and the Composition API.
Therefore, the `global` property of the i18n instance returned by the function depends on the options specified in the function.

about the detail, you can see the below link:
https://vue-i18n.intlify.dev/api/general.html#global

You can resolve type resolution by type-annotating `createi18n` at vue-i18n-next@v9.2-beta and later.

See the API docs:
https://vue-i18n.intlify.dev/api/general.html#type-parameters

And, see the typescript supporting docs:
https://vue-i18n.intlify.dev/guide/advanced/typescript.html

Thanks!
