### ISSUE TITLE
TypeError: Cannot set properties of null (setting '__VUE_I18N__')

### ISSUE THREAD

**Issue by jakewhelan** [intlify/vue-i18n-next#793]
### Reporting a bug?

When loading a component tree which interacts with `vue-i18n` the library throws an error. I don't completely understand what conditions are necessary to reproduce this issue, it only happens in one place in our application.

We started noticing this after upgrading to `9.2.0-beta.17`

```
TypeError: Cannot set properties of null (setting '__VUE_I18N__')
    at Proxy.mounted (vue-i18n.esm-bundler.js:1930)
    at callWithErrorHandling (runtime-core.esm-bundler.js:154)
    at callWithAsyncErrorHandling (runtime-core.esm-bundler.js:163)
    at Array.hook.__weh.hook.__weh (runtime-core.esm-bundler.js:1953)
    at flushPostFlushCbs (runtime-core.esm-bundler.js:355)
    at flushJobs (runtime-core.esm-bundler.js:391)
```

The line of code is:
```
mounted() {
  /* istanbul ignore if */
  if (((process.env.NODE_ENV !== 'production') || __VUE_PROD_DEVTOOLS__) && !false) {
    this.$el.__VUE_I18N__ = this.$i18n.__composer; // HERE
```

`this.$el` is `null`

### Expected behavior

The library fails gracefully

### Reproduction

I don't understand how to reproduce this problem, it's an access error caused internally by the library

### System Info

```shell
System:
    OS: macOS 10.15.7
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 73.94 MB / 32.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.18.2 - ~/.nvm/versions/node/v12.18.2/bin/node
    Yarn: 1.22.4 - ~/.nvm/versions/node/v12.18.2/bin/yarn
    npm: 6.14.5 - ~/.nvm/versions/node/v12.18.2/bin/npm
  Browsers:
    Chrome: 95.0.4638.69
    Firefox: 89.0
    Safari: 15.0
  npmPackages:
    @vue/babel-preset-app: ^4.4.6 => 4.5.12 
    @vue/compiler-sfc: ^3.0.0-beta.18 => 3.0.11 
    @vue/test-utils: ^2.0.0-beta.0 => 2.0.0-rc.6 
    vue: ^3.0.0 => 3.0.11 
    vue-draggable-next: ^2.0.1 => 2.0.1 
    vue-i18n: ^9.2.0-beta.19 => 9.2.0-beta.19 
    vue-loader: ^16.0.0-beta.4 => 16.2.0
```

### Additional context

I've forked the library and fixed the problem like this, no idea what side effects this will have though

Before:
```
this.$el.__VUE_I18N__ = this.$i18n.__composer;
```

After:
```
if (!this || !this.$el) return
this.$el.__VUE_I18N__ = this.$i18n.__composer;
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/intlify/vue-i18n-next/blob/master/.github/CONTRIBUTING.md)
- [X] Read the [Documentation](https://vue-i18n.intlify.dev/)
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/intlify/vue-i18n-next/discussions)

**Comment by virgosoy** [comment]
when I used <script setup> + await, this bug production.

**Comment by miayang0513** [comment]
I'm also faced this problem when I used <script setup> + await.

**Comment by kazupon** [comment]
Sorry, late my reply
Thank you for your reporting!

I also tried to reproduce it based on the reporting information. 
Unfortunately, I could not reproduce it. 😞 

The best way to solve this problem is to provide a repo with the minimum reproduction code.
Could you please do this for us, please?

**Comment by mokone91** [comment]
Have same issue on 9.1.7, disappeared on 9.2.0-beta.20

**Comment by benkroeger** [comment]
I observed this behaviour when on one of my components as well (@9.2.0-beta.22). It's happening when using `script setup` in SFC and awaiting a promise in there. Weirdly enough, the error only happens when navigating to that component. If that component is on the initial page render (page refresh), error doesn't happen.
I assume, that this has something to do with being outside of the synchronous scope of the setup() lifecycle and thus `this.$el` is still null

**Comment by gvorster** [comment]
Get the same error also when using await inside `<script setup>`

Example:

```
<template>
  <div>test</div>
</template>

<script setup>
import useApi from 'src/composables/useApi';

const api = useApi();

let minWeight = await api.getAppSetting("AIRLINE_COMMERCIAL_OFFER_MIN_VOLUME")

</script>
```

```
vue-router.esm-bundler.js?f6c4:3295 TypeError: Cannot set properties of null (setting '__VUE_I18N__')
    at Proxy.mounted (vue-i18n.esm-bundler.js?b8e5:1755:1)
    at callWithErrorHandling (runtime-core.esm-bundler.js?9e79:6737:1)
    at callWithAsyncErrorHandling (runtime-core.esm-bundler.js?9e79:6746:1)
    at Array.hook.__weh.hook.__weh (runtime-core.esm-bundler.js?9e79:1970:1)
    at flushPostFlushCbs (runtime-core.esm-bundler.js?9e79:6938:1)
    at flushJobs (runtime-core.esm-bundler.js?9e79:6983:1)
triggerError @ vue-router.esm-bundler.js?f6c4:3295
eval @ vue-router.esm-bundler.js?f6c4:3334
Promise.catch (async)
handleScroll @ vue-router.esm-bundler.js?f6c4:3334
finalizeNavigation @ vue-router.esm-bundler.js?f6c4:3188
eval @ vue-router.esm-bundler.js?f6c4:3060
```

**Comment by zealot128** [comment]
I also ran into this issue, when using [Rollup/Vite's glob Import feature](https://vitejs.dev/guide/features.html#glob-import):

```javascript
const modules = import.meta.glob('./pages/**/*.vue')

createInertiaApp({
  resolve: name => modules[`./pages/${name}.vue`],
  setup({ el, app, props, plugin }) {
     createApp({ render: () => h(app, props) })
        .use(plugin)
        .use(i18n)
        .mount(el)
```

> Uncaught (in promise) TypeError: can't access property "__VUE_I18N__", this.$el is undefined



Importing dynamically works (but [with splitting each path components](https://github.com/vitejs/vite/issues/4945#issuecomment-951770052), which is a limitation of Vite/Rollup):

```javascript
createInertiaApp({
  // one level, if need multiple levels, then split by "/" and if/else
  resolve: name => import(`./pages/${name}.vue`)
// .... same as above -> no error
```

**Comment by kazupon** [comment]
close, due to I released v9.2.0-beta.28

**Comment by kolaente** [comment]
@kazupon  I'm hitting a slightly similar error with the latest version 9.2.0-beta.28:

![image](https://user-images.githubusercontent.com/13721712/150022546-bd6569ad-827a-4cf1-baec-26de53446cf9.png)

Should I open a new issue?

**Comment by kazupon** [comment]
I seem that is another issue.
you can open a new issue.

**Comment by kolaente** [comment]
Opened a new issue here: https://github.com/intlify/vue-i18n-next/issues/896
