### ISSUE TITLE
"vue-cli-service serve" is ok, "vue-cli-service build" is fail. __VUE_I18N__ undefined issue,  

### ISSUE THREAD

**Issue by heoyongun** [intlify/vue-i18n-next#815]
### Reporting a bug?

1. vue-cli-service build and nginx deploy
2. undefined error. __VUE_I18N__

        const messages = {
          required: app.__VUE_I18N__.global.t('validation.required', { field: ctx.field }),
          min: app.__VUE_I18N__.global.t('validation.min', { field: ctx.field }),
          max: app.__VUE_I18N__.global.t('validation.max', { field: ctx.field }),
          alpha_spaces: app.__VUE_I18N__.global.t('validation.alpha_spaces', { field: ctx.field }),
          email: app.__VUE_I18N__.global.t('validation.email', { field: ctx.field }),
          min_value: app.__VUE_I18N__.global.t('validation.min_value', { field: ctx.field }),
          max_value: app.__VUE_I18N__.global.t('validation.max_value', { field: ctx.field }),
          excluded: app.__VUE_I18N__.global.t('validation.excluded', { field: ctx.field }),
        }

### Expected behavior

**vue-cli-service serve**, **vue-cli-service build** same resule

### Reproduction

main.js 
![스크린샷, 2021-11-26 14-18-00](https://user-images.githubusercontent.com/6076067/143530720-02398f07-ac36-48bb-a966-c751571a2bff.png)

validation.js
![스크린샷, 2021-11-26 14-20-35](https://user-images.githubusercontent.com/6076067/143530848-7094b04a-56d1-449a-b02a-e68535f3963f.png)

i18n.js
![스크린샷, 2021-11-26 14-18-33](https://user-images.githubusercontent.com/6076067/143530781-dc75526e-f5cf-4d15-bb31-ac99daeacf2d.png)

### System Info

```shell
System:
    OS: Linux 5.11 Ubuntu 20.04.2 LTS (Focal Fossa)
    CPU: (16) x64 Intel(R) Core(TM) i7-10700F CPU @ 2.90GHz
    Memory: 2.79 GB / 31.28 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 16.3.0 - ~/.nvm/versions/node/v16.3.0/bin/node
    npm: 7.15.1 - ~/.nvm/versions/node/v16.3.0/bin/npm
  Browsers:
    Chrome: 96.0.4664.45
    Firefox: 94.0

  "scripts": {
    "serve": "vue-cli-service serve",
    "build": "vue-cli-service build",
    "lint": "vue-cli-service lint",
    "i18n:report": "vue-cli-service i18n:report --src \"./src/**/*.?(js|vue)\" --locales \"./src/undefined/**/*.json\""
  },
  "dependencies": {
    "@vee-validate/rules": "^4.5.3",
    "axios": "^0.24.0",
    "bootstrap": "^5.1.3",
    "core-js": "^3.6.5",
    "echarts": "^5.2.2",
    "jsencrypt": "^3.2.1",
    "vee-validate": "^4.5.5",
    "vue": "^3.0.0",
    "vue-echarts": "^6.0.0",
    "vue-i18n": "^9.2.0-beta.22",
    "vue-router": "^4.0.0-0",
    "vuex": "^4.0.0-0"
  },
  "devDependencies": {
    "@intlify/vue-i18n-loader": "^3.0.0",
    "@vue/cli-plugin-babel": "~4.5.0",
    "@vue/cli-plugin-eslint": "~4.5.0",
    "@vue/cli-plugin-router": "~4.5.0",
    "@vue/cli-plugin-vuex": "~4.5.0",
    "@vue/cli-service": "~4.5.0",
    "@vue/compiler-sfc": "^3.0.0",
    "@vue/eslint-config-prettier": "^6.0.0",
    "babel-eslint": "^10.1.0",
    "eslint": "^6.7.2",
    "eslint-plugin-prettier": "^3.3.1",
    "eslint-plugin-vue": "^7.0.0",
    "prettier": "^2.2.1",
    "sass": "^1.43.4",
    "sass-loader": "^10.2.0",
    "vue-cli-plugin-i18n": "^2.3.1"
  },
```

### Screenshot

"vue-cli-service serve" is ok, have __VUE_I18N__
![스크린샷, 2021-11-26 14-09-29](https://user-images.githubusercontent.com/6076067/143530432-abd19d7a-4255-4d5b-a9fc-116521b54105.png)

"vue-cli-service build" is fail, undefined __VUE_I18N__
![스크린샷, 2021-11-26 14-14-49](https://user-images.githubusercontent.com/6076067/143530501-dd945407-2fac-4532-a675-010cdc38b0c4.png)

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/intlify/vue-i18n-next/blob/master/.github/CONTRIBUTING.md)
- [X] Read the [Documentation](https://vue-i18n.intlify.dev/)
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [ ] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/intlify/vue-i18n-next/discussions)

**Comment by kazupon** [comment]
Thank you for your reporting.

`app.__VUE_I18N__` is used internally only...
You should use the i18n instance by `createI18n`

**Comment by heoyongun** [comment]
Thank you.
The code was changed.

![스크린샷, 2021-11-28 01-06-09](https://user-images.githubusercontent.com/6076067/143688557-fdbbe022-7927-42e7-8a06-d23bd8e617e7.png)
