### ISSUE TITLE
Define components in PascalCase

### ISSUE THREAD

**Issue by wopian** [intlify/vue-i18n-next#829]
### Clear and concise description of the problem

Currently vue-i18n@next only exposes components as kebab-case, which is in direct conflict with our [ESLint rules which forbid kebab-case component names](https://eslint.vuejs.org/rules/component-name-in-template-casing.html#kebab-case). 

PascalCase cannot be used if components are defined as kebab-case, so we're currently having to ignore this rule for  i18n's component names.

Related to https://github.com/kazupon/vue-i18n/issues/1196 in the Vue 2 repo

### Suggested solution

Define components as PascalCase. This allows consumers to use either PascalCase or kebab-case in their templates as PascalCase supports both usages and would not be a breaking change - see https://v3.vuejs.org/guide/component-registration.html#name-casing for details

### Additional context

```js
// .eslintrc.js
export default {
  ...,
  rules: {
	...,
    'vue/component-name-in-template-casing': [
      'error',
      'PascalCase',
      { registeredComponentsOnly: false, ignores: ['i18n-t'] }
    ],
  }
}
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/intlify/vue-i18n-next/blob/master/.github/CONTRIBUTING.md)
- [X] Read the [Documentation](https://vue-i18n.intlify.dev/)
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by santiagoarizti** [comment]
Hi, what about importing the component like this:

```
import {I18nT, useI18n} from 'vue-i18n';
```

This would allow you to use the pascal case name, plus you get intellisense/autocomplete,

I started this discussion [here](https://github.com/intlify/vue-i18n-next/discussions/872)

**Comment by Miguel-Bento-Github** [comment]
> Hi, what about importing the component like this:

> import {I18nT, useI18n} from 'vue-i18n';
This would allow you to use the pascal case name, plus you get intellisense/autocomplete,

> I started this discussion https://github.com/intlify/vue-i18n-next/discussions/872
  
Component registration can be global, it'd be better to have multiple `Translation` component names at   
https://github.com/intlify/vue-i18n-next/blob/master/packages/vue-i18n-core/src/components/Translation.ts

**Comment by kazupon** [comment]
close, already supported.
https://github.com/intlify/vue-i18n-next/blob/fea409da93bb9b367e5eb2f909afad23366507cc/packages/vue-i18n/src/vue.d.ts#L1275-L1277

**Comment by wopian** [comment]
Thank you for adding support for this! Fixed by https://github.com/intlify/vue-i18n-next/pull/1313
