### ISSUE TITLE
Usage with Vue 2 and @vue/composition-api

### ISSUE THREAD

**Issue by ivansieder** [intlify/vue-i18n-next#83]
As the code seems to import defineComponent and other props directly from the "vue" package, I was curious, if this is also usable with the Vue 2 composition-api plugin, as I couldn't find anything relating to that inside the docs till now. Thanks in advance for you time!

**Comment by kazupon** [comment]
@ivansieder 
sorry, late response.

Unfortunately, there are no plans for a back port from vue-i18n-next to vue-i18n@8.x at this time.
However, vue-i18n-next does offer a legacy mode that maintains compatibility with the vue-i18n@8.x API.

You can try it out.
I'd appreciate your feedback!

**Comment by ivansieder** [comment]
Thank you @kazupon for your time put into this. If I read the code right, the legacy mode just preserves the syntax but still requires Vue 3, is that correct?

**Comment by danieleades** [comment]
i have the same question. my issue is this-

- i'm using Qasuar components, which does not yet support V3
- i'm using the composition-api plugin
- I can't use vue-i18n with the composition API

i need either a workaround to use vue-i18n with the composition-api plugin, *or* a way to use vue-i18n with Vue2 + composition-api plugin

right now i'm in no-man's land

**Comment by danieleades** [comment]
found this nice little shim - https://github.com/intlify/vue-i18n-composable

works a treat

**Comment by kazupon** [comment]
We are offering vue-i18n-composable to make the migration to vue 3 supporting.
If there is anything missing we will add them.
