### ISSUE TITLE
te is undefined for composition api

### ISSUE THREAD

**Issue by haan123** [intlify/vue-i18n-next#833]
### Reporting a bug?

I'm using `"vue-i18n": "9.0.0-beta.6"` and `"vue": "^3.0.0"`.

Trying to access the `te` method from `const { t, te } = useI18n()` but the `te` is `undefined`

### Expected behavior

`te` should be available

### Reproduction

N/A

### System Info

```shell
Mac OS
Chrome
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/intlify/vue-i18n-next/blob/master/.github/CONTRIBUTING.md)
- [X] Read the [Documentation](https://vue-i18n.intlify.dev/)
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/intlify/vue-i18n-next/discussions)

**Comment by PeterAlfredLee** [comment]
Hi, @haan123 , 
API `te` was originally introduced by PR #200, so `"vue-i18n": "9.0.0-beta.6"` does not include it.
Please upgrade your `vue-i18n` version, hope this helps.

**Comment by haan123** [comment]
Ahh, i think it will work, thank you and have a nice day!
