### ISSUE TITLE
[intlify] Not found '[message]' key in 'en' locale messages.

### ISSUE THREAD

**Issue by Rolanddoda** [intlify/vue-i18n-next#849]
### Reporting a bug?

I have 2 routes:

```js
const routes = [
  {
    path: 'register',
    name,
    component: () => import(/* webpackChunkName: "register" */ './Register'),
    meta: {
      loadTranslation: (locale) => import(/* webpackChunkName: "lang-[request]" */ `./translations/${locale}.js`)
    }
  },

  {
    path: '',
    name,
    component: () => import(/* webpackChunkName: "home" */ './Home'),
    meta: {
      loadTranslation: (locale) => import(/* webpackChunkName: "lang-[request]" */ `./translations/${locale}.js`)
    }
  }
]
```

As you can see, they both have a `meta.loadTraslation` property.
Now in my router configuration I do:

```js
  Router.beforeEach(async (to, from, next) => {
    if (SUPPORTED_LOCALES.has(to.params.locale) && to.meta.loadTranslation) {
      const messages = await to.meta.loadTranslation(to.params.locale)
      await addMessages(to.params.locale, messages.default)
      setI18nLanguage(to.params.locale)
    }

    next()
  })
```

This simply means that if there is a translation to load, load it and add it to the i18n messages by using `setLocaleMessage`.
For instance, here is my i18n config:

```js
export const i18n = createI18n({
  globalInjection: true,
  legacy: false,
  locale: 'en',
  fallbackLocale: 'en',
  messages: {}
})

export function setI18nLanguage(locale) {
  if (i18n.global.locale.value !== locale) {
    i18n.global.locale.value = locale
    document.querySelector('html').setAttribute('lang', locale)
  }
}

export function addMessages(locale, messages) {
  i18n.global.setLocaleMessage(locale, messages)

  return nextTick()
}
```

Everything works as expected, but when I navigate between routes, I get `[intlify] Not found '[message]' key in 'en' locale messages.` warning.

### Expected behavior

No warning should be happening when navigating between routes.

### Reproduction

Github repo: https://github.com/Rolanddoda/vue-i18n-next-issue

### System Info

```shell
"vue-i18n": "^9.2.0-beta.25"
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/intlify/vue-i18n-next/blob/master/.github/CONTRIBUTING.md)
- [X] Read the [Documentation](https://vue-i18n.intlify.dev/)
- [X] Check that there isn't [already an issue](https://github.com/intlify/vue-i18n-next/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/intlify/vue-i18n-next/discussions)
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by kazupon** [comment]
Thank you for your feedback!

I check your reproduction code.
I noticed that `to.params.locale` is not used correctly

```js
Router.beforeEach(async (to, from, next) => {
    if (SUPPORTED_LOCALES.has(to.params.locale) && to.meta.loadTranslation) {
      const messages = await to.meta.loadTranslation(to.params.locale)
      await addMessages(to.params.locale, messages.default)
      setI18nLanguage(to.params.locale)
    }

    next()
  })
```

you need to specify param to route path:

```js
const routes = [
  {
    path: '/:locale/register',
    name,
    component: () => import(/* webpackChunkName: "register" */ './Register'),
    meta: {
      loadTranslation: (locale) => import(/* webpackChunkName: "lang-[request]" */ `./translations/${locale}.js`)
    }
  },

  {
    path: ''/:locale/",
    name,
    component: () => import(/* webpackChunkName: "home" */ './Home'),
    meta: {
      loadTranslation: (locale) => import(/* webpackChunkName: "lang-[request]" */ `./translations/${locale}.js`)
    }
  }
]
```

**Comment by Rolanddoda** [comment]
@kazupon thanks for the answer.

You are right about `to.params.locale` but it was just left there when I copied and pasted code from the real app to the repo that I created specifically for this issue.

I have updated now the repo and the issue is still there.
Please check it out.

**Comment by kazupon** [comment]
I think `to.params.locale` still is used.
https://github.com/Rolanddoda/vue-i18n-next-issue/blob/d9437458442329f7e9c813b2344c6d58e8fb6292/src/router/index.js#L42-L43

**Comment by Rolanddoda** [comment]
@kazupon I fixed the issue in my app, it was related to Vue-Router when switching pages, so I am going to close this issue.
