### ISSUE TITLE
Documentation incosistency  globalMsg.en.messages.myKey or gobalMsg.en.myKey ? 

### ISSUE THREAD

**Issue by Doogiemuc** [intlify/vue-i18n-next#852]
### Reporting a bug?

There is an inconsistency in the documentation:

What is the format of the configuration parameter `messages` for the `createI18n()` constructor?

The documentation writes here https://vue-i18n.intlify.dev/guide/#javascript
````
const messages = {
  en: {
    message: {                        // <===== there is an in between "message" attribute
      hello: 'hello world'
    }
  },
  ja: {
    message: {
      hello: 'こんにちは、世界'
    }
  }
}
````

But on this page https://vue-i18n.intlify.dev/guide/essentials/fallback.html#explicit-fallback-with-one-locale it sais:
````
const messages = {
  en: {                                        // <============= no in between "message" attribute
    hello: 'Hello, world!'
  },
  ja: {
  }
}
````

Which one is correct?

### Expected behavior

Documentation should be consistent

### Reproduction

This is just about documentation

### System Info

```shell
docu
```

### Screenshot

See links above

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/intlify/vue-i18n-next/blob/master/.github/CONTRIBUTING.md)
- [X] Read the [Documentation](https://vue-i18n.intlify.dev/)
- [X] Check that there isn't [already an issue](https://github.com/intlify/vue-i18n-next/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/intlify/vue-i18n-next/discussions)
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by kazupon** [comment]
Thank you for your feedback.

You are right that it is preferable to have consistent docs.
However, I don't think it should be done for everything, because if it is all consistent, then if you need to modify it, you have to update everything.

So I will keep the docs as it is.

Thanks!

**Comment by Doogiemuc** [comment]
I think you misunderstood the issue.

What is the correct syntax? Only one of these two alternatives is correct. I assume the one without the "message: " attribute "in between" is the correct one. At least that works for me.   I think the first place is the docs is just simply wrong.

**Comment by Doogiemuc** [comment]
I'll try to reformulate my question.   Which of these two alternatives is correct?

# Alternative A

````
const globalTranslations = {
	en: {
                // <===== mind: No "message:" attribute here!
		HelloWorld: "Hello world!"
	},
	de: {
		HelloWorld: "Hallo Welt!"
        }
}
const i18n = new createI18n({
	locale: "de",
	messages: globalTranslations
})
````

# Alternative B

or is this second alternative correct?


````
const globalTranslations = {
	en: {
                messages: {    // <===== mind: Now with an additional "message:" attribute here!
		     HelloWorld: "Hello world!"
              }
	},
	de: {
                messages: {
		      HelloWorld: "Hallo Welt!"
               }
        }
}
const i18n = new createI18n({
	locale: "de",
	messages: globalTranslations
})
````

I think Alternative B is correct. But the documentation still mentions the (old?) Alternative A here: https://vue-i18n.intlify.dev/guide/#javascript

**Comment by kazupon** [comment]
Both are correct.
Here is the type (TypeScript) you can specify for the `messages` options.
https://vue-i18n.intlify.dev/api/general.html#localemessage

`messages` option can put an object with the locale (e.g. `en`) as key.
