### ISSUE TITLE
Never install the latest alpha version by npm

### ISSUE THREAD

**Issue by screets** [intlify/vue-i18n-next#86]
vue: 3.0.0-rc.5

Trying `npm install --save vue-i18n@next` command, it installs **9.0.0-alpha.1** instead of 9.0.0-alpha.13. 

When I do:

* Update package.json file manually as `"vue-i18n": "^9.0.0-alpha.13",`
* And run `npm update`
* Then my Vue project doesn't recognize `import { useI18n } from 'vue-i18n'` anymore and asks me to install vue-i18n package although it is already installed (I mean alpha version)

How can I fix it?

Thank you in advance.

**Comment by screets** [comment]
Fixed when I remove package.lock.json file and node_modules folder, and then re-run `npm install`. It seems working now.

**Comment by kazupon** [comment]
Thanks! 
I've `npm dist-tag add`.
You can install latest version with `npm install vue-i18n@next`

**Comment by screets** [comment]
Hey Intlify/vue-I18n-Next,

We got your help request!
One of our agents will respond to you, asap (usually in *1 business day*).

Note that we don't work on weekends.
However, if we release a major update recently, we are following the
issues.

For support questions, please also email us *s**creets API key* which is
required for support questions.
If you already included in your message, you don't need to do anything else.

Best,
screets
{#HS:1248279444-6775#}
