### ISSUE TITLE
TypeError: Cannot set properties of null (setting '__VUE_I18N__')

### ISSUE THREAD

**Issue by mirkofisic** [intlify/vue-i18n-next#873]
### Reporting a bug?

The router works properly until the moment if I want the component to render automatically. To automatically render the renderer component in `<router-view/>` node I bind key, as follows: `<router-view :key="$route.fullPath"/> `the component renders successfully but I get an error:
TypeError: Cannot set properties of null (setting '__VUE_I18N__')
    at Proxy.mounted (vue-i18n.esm-bundler.js?b8e5:1998)
    at callWithErrorHandling (runtime-core.esm-bundler.js?9e79:6737)
    at callWithAsyncErrorHandling (runtime-core.esm-bundler.js?9e79:6746)
    at Array.hook.__weh.hook.__weh (runtime-core.esm-bundler.js?9e79:1970)
    at flushPostFlushCbs (runtime-core.esm-bundler.js?9e79:6938)
    at flushJobs (runtime-core.esm-bundler.js?9e79:6983)

![image](https://user-images.githubusercontent.com/6698925/148824126-9ce11786-a1ef-463f-bea2-30c072a6ca9f.png)

### Expected behavior

No error

### Reproduction

No reproduction

### System Info

```shell
Windows 10 

  "dependencies": {
    "@quasar/extras": "^1.12.2",
    "axios": "^0.21.1",
    "connect-mongo": "^4.6.0",
    "core-js": "^3.6.5",
    "date-fns": "^2.25.0",
    "express-session": "^1.17.2",
    "mongodb": "^4.1.4",
    "music-metadata": "^7.11.4",
    "quasar": "^2.4.4",
    "stream-title": "^1.0.7",
    "tiny-emitter": "^2.1.0",
    "url-parse": "^1.5.4",
    "vue-i18n": "^9.2.0-beta.26",
    "vuex": "^4.0.1"
  },

Node version v16.13.0
Chrome Version 96.0.4664.110 (Official Build) (64-bit)
```

### Screenshot

![image](https://user-images.githubusercontent.com/6698925/148824585-45ea0884-48bd-4dfe-9e1c-b0fb1691e25c.png)

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/intlify/vue-i18n-next/blob/master/.github/CONTRIBUTING.md)
- [X] Read the [Documentation](https://vue-i18n.intlify.dev/)
- [X] Check that there isn't [already an issue](https://github.com/intlify/vue-i18n-next/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/intlify/vue-i18n-next/discussions)
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by gvorster** [comment]
I have the same error when I use `await` inside `<script setup>`

```
<template>
 <div>test</div>
</template>

<script setup>
import useApi from 'src/composables/useApi';

const api = useApi();

let minWeight = await api.getAppSetting("AIRLINE_COMMERCIAL_OFFER_MIN_VOLUME")

</script>
```

**Comment by kazupon** [comment]
I've just released v9.2.0-beta.27
Please try it.

**Comment by zealot128** [comment]
> I've just released v9.2.0-beta.27
> Please try it.

@kazupon tried it, unfortunately, the if condition gets replaced by a mere ``if (true)`` during your build step somehow:


![Bildschirmfoto 2022-01-13 um 08 56 29](https://user-images.githubusercontent.com/147175/149289277-8e35d28a-d549-4581-b755-8d7e3c53c01d.png)

Thus, the error is unchanged.

**Comment by kazupon** [comment]
Hmm, 🤔  I seem that it's built with development building.
What do you use the bundler + intlify/bundle-tools? webpack + @intlify/vue-i18n-loader?
I have checked with vite + `@intlify/vite-plugin-vue-i18n` on the project that is created with`create-vue` and it does not have that condition.

**Comment by zealot128** [comment]
> 

I don't use create-vue app, but Vite directly.  No Webpack.

When I scan the raw files in ``node_modules/vue-i18n/dist``, if seems the the "*esm-browser.js" files have no "if (...)" around, only the comment "istanbul ignore" remains. So it will always be executed. And even the other 2 files, you can see that the if condition is somehow changed with a "&& !false" at the end, which is redundant:

![Bildschirmfoto 2022-01-13 um 10 13 51](https://user-images.githubusercontent.com/147175/149301081-ae24cb73-9384-4405-94c6-b0a9daf17726.png)

Could this be a problem? I am sorry, I don't know to much about the js module system + bundling to tell, which file gets loaded in my setup.

<details>
<summary>Vite config + versions</summary>
```javascript
  import { defineConfig } from 'vite'
  import RubyPlugin from 'vite-plugin-ruby'
  import FullReload from "vite-plugin-full-reload"
  import vue from '@vitejs/plugin-vue'
  import vueJsx from '@vitejs/plugin-vue-jsx'

  export default defineConfig({
    server: {
      hmr: {
        host: process.env.VITE_WSS_HOST,
        port: 443,
        protocol: 'wss',
      },
    },
    plugins: [
      RubyPlugin(),
      vue({ ssr: false, isProduction: false}),
      vueJsx({}),
      FullReload(["config/routes.rb", "app/views/**/*", "app/controllers/**/*"], {
        delay: 200,
      }),
    ],
  })
  ```

 ```
    "@vitejs/plugin-vue": "^1.9.3",
    "@vitejs/plugin-vue-jsx": "^1.2.0",
    "@vue/server-renderer": "^3.2.19",
    "vite": "^2.5.0",
    "vite-plugin-full-reload": "^0.2.2",
    "vite-plugin-ruby": "^3.0.0",
    "vue": "^3.2.19",
    "vue-i18n": "9.2.0-beta.27",
 ```
</details>

**Comment by kazupon** [comment]
Thank you for your information!

For bundler, we should use the `vue-i18n.esm-bundler.js`.

About vue-i18n dist files, You can read them here:
https://vue-i18n.intlify.dev/installation.html#explanation-of-different-builds

And for optimizations using the libraries provided by bundler and intlify/bundle-tools, see here:
https://vue-i18n.intlify.dev/guide/advanced/optimization.html


BTW, I've just released v9.2.0-beta.28
Please try it.

**Comment by kazupon** [comment]
> i18n + using vite's meta.glob import no works! 

I think that is another issue, so you can new issue.

I believe this issue is resolved.
I will close.

Thanks!

**Comment by zealot128** [comment]
That was a Typo, i meant, it "now" works :) 

Thank you for your time.
