### ISSUE TITLE
breaking change: Can't use nested arrays or arrays of objects needed for Page content or Language list

### ISSUE THREAD

**Issue by tohagan** [intlify/vue-i18n-next#885]
### Reporting a bug?

In vue-i18n v8.0.0, I was able use nested arrays of objects to manage translatable content for "About" or "FAQ" pages.
Just tried using in `vue-i18n: 9.2.0-beta.26` and found this very important feature appears to be missing. I realise this is known limitation documented in your Migration guide. 

This is a bit of a show stopper for porting from v2 Vue.  I'll have to resort to some awful data transformations to get this feature back or toss this library and find/build an alternative. IMHO arrays are essential for translatable content. I use them for things like the list of Languages to select from (so language names are translated).

Someone else mentioned this in #75 .

Examples:  

```vue
...
<script lang="ts" setup>
  import { useI18n } from 'vue-i18n';
  const { t } = useI18n();

  interface Section {
    heading: string;
    body: string[]
  }

  const names = t('heroPage.names')   //  is undefined
  const content = t('heroPage.content')  as unknown as Section[];  // is undefined
</script>
```

`i18n/en-US/index.ts` ...

```ts
export default {
  heroPage: {
    title: Super Hero Powers",
    names: ["Clark Kent", "Peter Parker"],
    content: [
      {
        heading: "Superman can ...",
        body: [
         "Flight. 'You will believe a man can fly,' the 1978 movie promised, and they were right.",
         "Super Strength. Superman's other most famous power is that he's strong.",
         "Invulnerability.",
         "Super Speed.",
         "Super Hearing.",
         "Solar Flare.",
         "Turning Diamonds Into Coal.",
         "Super Disco Dancer!"
        ]
      },
      {
        heading: "Spiderman powers ...",
        body: [
          "Superhuman Strength.",
          "Superhuman Speed.",
          "Superhuman Reflexes.",
          "Superhuman Durability.",
          "Healing Factor.",
          "'Spider-Sense' Alert.",
          "Heightened Senses.",
          "Wallcrawling. "       
        ]
      }
    ]
  }
}
```

### Expected behavior

(1) Return nested arrays or strings or objects and (2) Permit typecasting of translatable content:

const names = t<string[]>('heroPage.names')
const content = t<Section[]>('heroPage.content') ;

### Reproduction

I think the example above should be sufficient to reproduce it. 
Buzz me if you disagree. 

### System Info

```shell
I'm using YARN not NPM. 


  "dependencies": {
    "@quasar/extras": "^1.0.0",
    "axios": "^0.21.1",
    "core-js": "^3.6.5",
    "firebase": "^9.6.3",
    "firebaseui": "^0.600.0",
    "pinia": "^2.0.9",
    "quasar": "^2.0.0",
    "vue-i18n": "^9.2.0-beta.26"
  },
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/intlify/vue-i18n-next/blob/master/.github/CONTRIBUTING.md)
- [X] Read the [Documentation](https://vue-i18n.intlify.dev/)
- [X] Check that there isn't [already an issue](https://github.com/intlify/vue-i18n-next/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/intlify/vue-i18n-next/discussions)
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by kazupon** [comment]
Thank you for your feedback.

docs said, the translation API like `$t` and `t` function  (and, composition API too) that return string only. Object and array values are no longer returned.
You can workaround with using `tm` or `$tm`
Please check docs!
https://vue-i18n.intlify.dev/guide/migration/breaking.html#translation-api-return-value

Thanks!

**Comment by PeterAlfredLee** [comment]
@tohagan here is a example:

```js
<template>
  <p v-for="name in tm('heroPage.names')" :key="name">
    {{ rt(name) }}
  </p>
</template>

<script>
import { useI18n } from 'vue-i18n'

export default {
  setup() {
    const { tm, rt } = useI18n();
    return { rt, tm }
  }
}
</script>
```

**Comment by tohagan** [comment]
const { t, tm, rt } = useI18n();

Reports that `tm` is undefined for  "vue-i18n": "^9.2.0-beta.26"

**Comment by PeterAlfredLee** [comment]
@tohagan  

> Reports that tm is undefined for "vue-i18n": "^9.2.0-beta.26"

Unfortunately, I could not reproduce it. 
Could you give us the reproduction repo ?

**Comment by tohagan** [comment]
My apologies ... I misread the TS error ... I just needed to use ...
// eslint-disable-next-line @typescript-eslint/unbound-method

**Comment by tohagan** [comment]
```vue
<template>
  <div v-for="(section, index) in tm('info.content')" :key="index">
    <div class="row text-bold q-pt-xs info-heading">
      {{ rt(section.heading) }}
    </div>
    <div class="row">
      <ul>
        <li v-for="(item, index) in rt(section.body)" :key="index" v-html="item" />
      </ul>
    </div>
  </div>
 </template>
```

`tm('heroPage.content')` TS reports ...

- The right-hand side of a 'for...in' statement must be of type 'any', an object type or a type parameter, but here has type 'never'.ts(2407)
- Type instantiation is excessively deep and possibly infinite.ts(2589)

`rt(section.heading)` and `rt(section.body)`TS reports 

- Property 'heading' does not exist on type 'never'.ts(2339)

I think this is most because we've not given it the actual type which something like this would do ...
  - `const content = t<Section[]>('heroPage.content') ;`

**Comment by tohagan** [comment]
Ok I it now runs - just has TS Warnings about `never` type.

**Comment by DarkLite1** [comment]
We're having the same issue. If I understood it all correctly we have to use `$tm` and `$rt`, which works but throws an TS error:
![image](https://github.com/intlify/vue-i18n-next/assets/10828570/9ace68cf-9e2a-45ba-904c-6361238264fc)

### Translation file
```json
  "contacts": [
        { "title": "Health & safety" },
        { "title": "IT Support" }
      ],
```
![image](https://github.com/intlify/vue-i18n-next/assets/10828570/380703a4-9b07-43b2-992e-c17cf85a411e)

Are we still doing something wrong here?
