### ISSUE TITLE
[typescript] I18n.global incorrect type when in "composition" mode (should be Composer, is VueI18n)

### ISSUE THREAD

**Issue by sullyD64** [intlify/vue-i18n-next#889]
### Reporting a bug?

This is a TypeScript-related bug.

From the docs https://vue-i18n.intlify.dev/api/general.html#global it is said that "If the I18n#mode is 'legacy', then `I18n.global` can access to a global VueI18n instance, else then I18n#mode is 'composition' , you can access to the global Composer instance.". 

I've found this to be true at runtime, but the inferred TypeScript type is always `VueI18n` even when in "composition" mode. This throws errors at compile time and in the editor when I try to access Composer properties which are differently typed or absent from VueI18n (according to the mapping found at https://vue-i18n.intlify.dev/guide/advanced/composition.html#mapping-between-vuei18n-instance-and-composer-instance). More on that, this breaks typing on functions that return `useI18n() | i18n.global`.

### Expected behavior

The following code should not throw a typescript error on the last line 

```ts
import { createI18n } from "vue-i18n";

const testI18n = createI18n({
  legacy: false,
  locale: "ja",
  fallbackLocale: "en",
  messages: {
    en: {
      message: {
        hello: "hello world",
      },
    },
    ja: {
      message: {
        hello: "こんにちは、世界",
      },
    },
  },
});

const globalComposerInstance = testI18n.global;
console.log(globalComposerInstance.formatter); // this should be absent in Composer instance!
console.log(globalComposerInstance.getMissingHandler); // this should be present is Composer instance!
```

Instead it throws the following error:
```
Property 'getMissingHandler' does not exist on type 'VueI18n<{ en: { message: { hello: string; }; }; ja: { message: { hello: string; }; }; }, {}, {}, string, \"ja\" | \"en\", \"ja\" | \"en\", Composer<{ en: { message: { hello: string; }; }; ja: { message: { hello: string; }; }; }, ... 4 more ..., \"ja\" | \"en\">>'.
```

### Reproduction

Use the above snippet anywhere in a project with `vue-i18n@9.2.0-beta.28` and `typescript@4.5.4`. Hope it is enough, if not i will provide a repro.

### System Info

```shell
System:
    OS: Linux 5.11 Linux Mint 20.2 (Uma)
    CPU: (12) x64 Intel(R) Core(TM) i7-10710U CPU @ 1.10GHz
    Memory: 843.50 MB / 15.47 GB
    Container: Yes
    Shell: 5.8 - /usr/bin/zsh
  Binaries:
    Node: 14.15.0 - ~/.nvm/versions/node/v14.15.0/bin/node
    Yarn: 1.22.17 - ~/.nvm/versions/node/v14.15.0/bin/yarn
    npm: 8.1.0 - ~/.nvm/versions/node/v14.15.0/bin/npm
  Browsers:
    Brave Browser: 97.1.34.80
    Chrome: 97.0.4692.71
    Firefox: 95.0.1
  npmPackages:
    vue-i18n: ^9.2.0-beta.28 => 9.2.0-beta.28
```

### Screenshot

![immagine](https://user-images.githubusercontent.com/26333714/150174896-09a51c5c-704e-4c78-ada9-1b64d20475d1.png)

### Additional context

The actual value of `testI18n.global` is in fact a Composer instance. The following code:

```ts
console.log("testI18n.global", testI18n.global);
console.log("testI18n.global.formatter", testI18n.global.formatter);
```

logs the following: 

![immagine](https://user-images.githubusercontent.com/26333714/150174431-33419e17-f148-4018-9431-6771be85da7d.png)

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/intlify/vue-i18n-next/blob/master/.github/CONTRIBUTING.md)
- [X] Read the [Documentation](https://vue-i18n.intlify.dev/)
- [X] Check that there isn't [already an issue](https://github.com/intlify/vue-i18n-next/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/intlify/vue-i18n-next/discussions)
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by PeterAlfredLee** [comment]
Hi, @sullyD64  , try this:

```ts
import { createI18n } from "vue-i18n";

const i18n = createI18n<false>({
    legacy: false,
    locale: "ja",
    fallbackLocale: "en",
    messages: {
        en: {
            message: {
                hello: "hello world",
            },
        },
        ja: {
            message: {
                hello: "こんにちは、世界",
            },
        },
    },
});

const globalComposerInstance = i18n.global;
console.log(globalComposerInstance.formatter); // this should be absent in Composer instance!
console.log(globalComposerInstance.getMissingHandler); // this should be present is Composer instance!
```

**Comment by sullyD64** [comment]
Hi @PeterAlfredLee , thanks for replying. 
With the type parameter `<false>` it actually works. Thank you. 

I still think there is window for improvement since the docs mention the type inference for `I18n.global` to depend solely on `I18n.mode`, which is correctly reporting "composition" since i've set `legacy.false`, and don't mention needing to force the type parameter on `createI18n`.

Leaving this issue open so that either the docs or the typings can be fixed.

**Comment by sullyD64** [comment]
Also, sorry for breaking this up, but I've noticed that by casting `<false>`, the Composer instance doesn't infer types from the schema, I actually lose the type suggestions for the translation keys when using `t()` and other APIs. So this fixes the typings but defeats the purpose of having them correct anywyay.

**Comment by PeterAlfredLee** [comment]
> but I've noticed that by casting <false>, the Composer instance doesn't infer types from the schema

You can pass `schema` and `false` at the same time, see also this [example](https://github.com/intlify/vue-i18n-next/blob/6a693a4cad9e3c3f01be3ec3218034ae73a0bab4/examples/type-safe/type-annotation/src/main.ts).
Hope this helps.

**Comment by sullyD64** [comment]
Thank you for sticking around!

> You can pass schema and false at the same time, see also this example.

I've tried this without success:
```ts
const messages = {
  en: {
    message: {
      hello: "hello world",
    },
  },
  ja: {
    message: {
      hello: "こんにちは、世界",
    },
  },
};

const i18n = createI18n<{ message: typeof messages["en"] }, "en" | "ja", false>({
  legacy: false,
  locale: "ja",
  fallbackLocale: "en",
  messages,
});

const globalComposerInstance = i18n.global;
// console.log(globalComposerInstance.formatter); // this should be absent in Composer instance!
// console.log(globalComposerInstance.getMissingHandler); // this should be present is Composer instance!

globalComposerInstance.t("message.hello"); // no autocompletion!

```

This can be simplified by commenting the `ja` block and casting `<{ message: typeof messages}, "en", false>`) with the same results. 

As you can see in the screenshot,  `globalComposerInstance = i18n.global` is of type Composer but loses types :
![immagine](https://user-images.githubusercontent.com/26333714/150317427-2cb55686-d5b7-4e97-bba0-67100be4ad7f.png)

Thus `globalComposerInstance.t("message.hello")` doesn't give suggestions unfortunately.

**Comment by PeterAlfredLee** [comment]
Hi, @sullyD64 ,seems `Resource Keys completion supporting` only work with `useI18n`, so maybe you can try this:
```ts
const { t } = useI18n<{ message: typeof messages["en"] }, "en" | "ja">()
t('message.hello')
```
![image](https://user-images.githubusercontent.com/55973914/150338139-bf2ab2a4-1053-4aca-b5a9-e13dfa493c25.png)

See also [Resource Keys completion supporting](https://vue-i18n.intlify.dev/guide/advanced/typescript.html#resource-keys-completion-supporting)

**Comment by sullyD64** [comment]
I understand that. I thought that `I18n.global` and the returned Composer instance from `useI18n()` would be the same.

For anyone interested, i've found a workaround to my use case by casting `I18n.global` as follows:
```
return coreI18n.global as unknown as Composer<{ message: typeof messages["en"] }, "en" | "ja">;
```

Problem is solved for me, but I still think that either the docs or the typings should be fixed to work as advised in https://vue-i18n.intlify.dev/api/general.html#global, so I'm leaving this open.

Quoting myself:
> the docs mention the type inference for I18n.global to depend solely on I18n.mode, which is correctly reporting "composition" since i've set legacy.false, and don't mention needing to force the type parameter on createI18n.

Thank you @PeterAlfredLee for your kind patience!
