### ISSUE TITLE
Error when trying to translate in the missing handler

### ISSUE THREAD

**Issue by weevood** [intlify/vue-i18n-next#890]
### Reporting a bug?

I try to translate a key through the MissingHandler with vuei18n, but I get the following error: vm.$t is not a function. My goal is to ensure that a key is replaced, with a parent key, if it is not found.

### Expected behavior

The expected behavior is to have the $t function in vm object to use it in the MissingHandler.

### Reproduction

```javascript
export const i18n = createI18n({
    messages,
    legacy: false,
    locale: 'en',
    missing: (locale: Locale, key: Path, vm: Vue, values) => {
        if (key.includes('.')) {
            const newKey = /\.(.+)/.exec(key)[1]
            return vm.$t(newKey) as string
        }
        return key
    },
})

export const install: UserModule = ({ app }) => {
    app.use(i18n)
}
```

### System Info

```shell
System:
    OS: macOS 12.1
    CPU: (8) x64 Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz
    Memory: 360.68 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.18.1 - /usr/local/bin/node
    npm: 8.3.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 96.0.4664.110
    Safari: 15.2
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/intlify/vue-i18n-next/blob/master/.github/CONTRIBUTING.md)
- [X] Read the [Documentation](https://vue-i18n.intlify.dev/)
- [X] Check that there isn't [already an issue](https://github.com/intlify/vue-i18n-next/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/intlify/vue-i18n-next/discussions)
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by PeterAlfredLee** [comment]
Hi @weevood, 
Seem the signature of your missinghandler is not fit.  The type of `MissingHandler` is:
```ts
export declare type MissingHandler = (locale: Locale, key: Path, insttance?: ComponentInternalInstance, type?: string) => string | void;
```
see also [MissingHandler](https://vue-i18n.intlify.dev/api/composition.html#missinghandler).

And if you want to use the `t` function in your `missinghandler`, this might be a workaround:
```ts
const i18n = createI18n({
    legacy: false,
    locale: 'en',
    missing: (locale: Locale, key: Path) => {
        console.log(i18n)
        return i18n.global.t('miss')
    },
    messages: {
        en: {
            miss: 'missKey'
        }
    }
})
```
Please make sure the new key exists when you pass it to the `t` function inside the `missinghandler`, otherwise it may cause a loop.
Hope this helps.

**Comment by weevood** [comment]
Hi @PeterAlfredLee,

I've been stuck on this error for months, but with your solutions it works!

Thank you very much for your help and your code example.
