### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading '__composer')

### ISSUE THREAD

**Issue by Quasarman** [intlify/vue-i18n-next#892]
### Reporting a bug?

I get the following error message constantly logged to my console when something in the vue context changes:
```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading '__composer')
    at eval (vue-i18n.esm-bundler.js?b8e5:2002:1)
```

Releated section inside the code:
```
nextTick(() => {
    /* istanbul ignore if */
    if (((process.env.NODE_ENV !== 'production') || __VUE_PROD_DEVTOOLS__) &&
        !false &&
        this.$el) {
        this.$el.__VUE_I18N__ = this.$i18n.__composer;
        const emitter = (this.__v_emitter =
            createEmitter());
        const _vueI18n = this.$i18n;
        _vueI18n.__enableEmitter && _vueI18n.__enableEmitter(emitter);
        emitter.on('*', addTimelineEvent);
    }
});
```

### Expected behavior

No error messages being triggered.

### Reproduction

Just install the latest version.

### System Info

```shell
System:
    OS: Windows 10 10.0.19043
    CPU: (16) x64 AMD Ryzen 7 2700X Eight-Core Processor
    Memory: 10.31 GB / 31.92 GB
  Binaries:
    Node: 14.17.0 - C:\Program Files\nodejs\node.EXE
    npm: 6.14.13 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 97.0.4692.71
    Edge: Spartan (44.19041.1266.0), Chromium (97.0.1072.62)
    Internet Explorer: 11.0.19041.1202
  npmPackages:
    vue-advanced-cropper: ^2.7.1 => 2.7.1
    vue-i18n: ^9.2.0-beta.28 => 9.2.0-beta.28
    vue-mention: 2.0.0-alpha.2 => 2.0.0-alpha.2
    vue-observe-visibility: ^2.0.0-alpha.1 => 2.0.0-alpha.1
    vue-plugin-load-script: ^2.1.0 => 2.1.0
    vue-resize: ^2.0.0-alpha.1 => 2.0.0-alpha.1
    vue-showdown: ^3.1.0 => 3.1.0
    vuedraggable: ^4.1.0 => 4.1.0
    vuese: ^1.4.7 => 1.4.7
    vuex: ^4.0.2 => 4.0.2
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/intlify/vue-i18n-next/blob/master/.github/CONTRIBUTING.md)
- [X] Read the [Documentation](https://vue-i18n.intlify.dev/)
- [X] Check that there isn't [already an issue](https://github.com/intlify/vue-i18n-next/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/intlify/vue-i18n-next/discussions)
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by kazupon** [comment]
Thank you for your reporting!

This issue is the same with #896 
So, close

Thank!
