### ISSUE TITLE
Cannot use Component Interpolation together with HTML message

### ISSUE THREAD

**Issue by Suxsem** [intlify/vue-i18n-next#895]
### Reporting a bug?

I'm trying to get something like
`Hello <b>dear</b> user, press the <img src="icon.png"> button to login`

As you can see we have html formatting tags (`<b>`) that I could get using
`<span v-html="$t('message')"></span>`
as well as component interpolation that I could get using the template component:
```
<i18n-t keypath="message" tag="span">
        <template v-slot:icon>
          <img src="icon.png">
        </template>
      </i18n-t>
```
but in this case I loose the ability to format the `<b>` tag.

How can we use both features together? thank you!

### Expected behavior

-

### Reproduction

-

### System Info

```shell
-
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/intlify/vue-i18n-next/blob/master/.github/CONTRIBUTING.md)
- [X] Read the [Documentation](https://vue-i18n.intlify.dev/)
- [X] Check that there isn't [already an issue](https://github.com/intlify/vue-i18n-next/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/intlify/vue-i18n-next/discussions)
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by kazupon** [comment]
You can use the below for your case.
the below composition API example:

```vue
<script setup lang="ts">
import { useI18n } from 'vue-i18n'

const { t } = useI18n({
  locale: 'en',
  messages: {
    en: {
      message: 'Hello {dear} user, press the {icon} button to login',
      dear: 'dear'
    }
  }
})
</script>

<template>
  <i18n-t keypath="message">
    <template #dear>
      <b>{{ t('dear') }}</b>
    </template>
    <template #icon>
      <img src="icon.png" />
    </template>
  </i18n-t>
</template>

```

Please see the here docs:
https://vue-i18n.intlify.dev/guide/advanced/component.html

Thanks!

**Comment by Suxsem** [comment]
@kazupon Thank you for replying, but I already saw it. The problem is that with this approach we could get long multiple-segments messages that are hard to be translated by third parties. Cannot we use component interpolation with plain html messages? Thank you!

**Comment by kazupon** [comment]
>Cannot we use component interpolation with plain html messages?

Yes, We cannot use it.
If you would like to use it, you need to wrap it with components.
https://vue-i18n.intlify.dev/guide/essentials/syntax.html#html-message
