### ISSUE TITLE
pnpm workspace bug

### ISSUE THREAD

**Issue by littleboarx** [intlify/vue-i18n-next#902]
### Reporting a bug?

in pnpm, the workspace packages are not shredded, and the peerDependencies will not install automatically. which make some problems in the project.
https://github.com/pnpm/pnpm/issues/3558

### Expected behavior

there should be no dependency resolve problem in the projects
found now:

### Reproduction

"peerDependencies": {
    "vue": "^3.0.0"
  },
in package vue-i18n-core
parser: 'vue-eslint-parser',
in .eslintrc.js

### System Info

```shell
System:
    OS: Windows 10 10.0.18362
    CPU: (12) x64 Intel(R) Core(TM) i5-10400 CPU @ 2.90GHz
    Memory: 14.53 GB / 31.84 GB
  Binaries:
    Node: 16.3.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.11 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 7.15.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.18362.1.0)
    Internet Explorer: 11.0.18362.1
  npmPackages:
    @intlify/core-base: workspace:* => 9.2.0-beta.28
    @intlify/message-compiler: workspace:* => 9.2.0-beta.28
    @vue/server-renderer: ^3.2.4 => 3.2.20
    vitepress: ^0.21.0 => 0.21.4
    vue: ^3.2.29 => 3.2.29
    vue-i18n: workspace:* => 9.2.0-beta.28
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/intlify/vue-i18n-next/blob/master/.github/CONTRIBUTING.md)
- [X] Read the [Documentation](https://vue-i18n.intlify.dev/)
- [X] Check that there isn't [already an issue](https://github.com/intlify/vue-i18n-next/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/intlify/vue-i18n-next/discussions)
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by kazupon** [comment]
close in-activity
