### ISSUE TITLE
TypeError: 'getOwnPropertyDescriptor' on proxy: trap reported non-configurability for property '__v_emitter'

### ISSUE THREAD

**Issue by elboukhari** [intlify/vue-i18n-next#906]
### Reporting a bug?

I'm facing this bug with **9.2.0-beta.29** : 
```
shared.esm-bundler.js:493 Uncaught (in promise) TypeError: 'getOwnPropertyDescriptor' on proxy: trap reported non-configurability for property '__v_emitter' which is either non-existent or configurable in the proxy target
    at Proxy.hasOwnProperty (<anonymous>)
    at hasOwn (shared.esm-bundler.js:493:45)
    at Object.set (runtime-core.esm-bundler.js:6762:41)
    at vue-i18n.esm-bundler.js:2003:43
```

Especially with text-fields (like with vuetify v-text-field) but not with textarea for example.

Even if I try with a simple one like :
<v-text-field label="test"></v-text-field>

It seems to be related to the usage with Vuetify (next branch). This pure html one works fine :
 <input type="text" id="fname" name="fname"><br><br>

### Expected behavior

This error should not appear 

### Reproduction

Use version :  **9.2.0-beta.29** 
Try with this : <v-text-field label="test"></v-text-field>

### System Info

```shell
System:
    OS: Windows 10 10.0.18363
    CPU: (12) x64 Intel(R) Core(TM) i7-10710U CPU @ 1.10GHz
    Memory: 16.22 GB / 31.34 GB
  Binaries:
    Node: 14.18.1 - C:\Program Files\nodejs\node.EXE
    npm: 8.3.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 97.0.4692.99
    Edge: Spartan (44.18362.1593.0)
    Internet Explorer: 11.0.18362.1766
  npmPackages:
    @vitejs/plugin-vue: ^1.9.0 => 1.10.2
    @vue/cli-plugin-babel: 5.0.0-beta.7 => 5.0.0-beta.7
    @vue/cli-service: 5.0.0-beta.7 => 5.0.0-beta.7
    @vue/eslint-config-prettier: 6.0.0 => 6.0.0
    @vue/eslint-config-typescript: 9.1.0 => 9.1.0
    @vuetify/nightly:  3.0.0-next-20220114.0
    vite: ^2.5.10 => 2.7.13
    vue: ^3.2.29 => 3.2.29
    vue-i18n: ^9.2.0-beta.29 => 9.2.0-beta.29
    vue-router: ^4.0.12 => 4.0.12
```

### Screenshot

![image](https://user-images.githubusercontent.com/36670922/151321953-8819541d-4aaf-4480-a7ce-4f2a0e71c333.png)

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/intlify/vue-i18n-next/blob/master/.github/CONTRIBUTING.md)
- [X] Read the [Documentation](https://vue-i18n.intlify.dev/)
- [X] Check that there isn't [already an issue](https://github.com/intlify/vue-i18n-next/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/intlify/vue-i18n-next/discussions)
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by kazupon** [comment]
Thank you for your reporting!

We need a reproduction repo to solve this issue, or need more detail info (e.g. app operation info)

Could you give us to minimum reproduction repo, please?

**Comment by elboukhari** [comment]
Dupplicate
