### ISSUE TITLE
Global availability of i18n instance methods

### ISSUE THREAD

**Issue by Korijn** [intlify/vue-i18n-next#91]
In Vue3 it is possible to globally install instance methods such as `$t` with `app.config.globalProperties`, is that already supported or is support coming?

**Comment by kazupon** [comment]
Thank you for your feedback!

vue-i18n-next don't globally inject with using `app.config.globalProperties`.
The legacy mode that  vue-i18n's API is nearly v8.x compatible, each vue instance is injected by mixins.

Th composable mode (new API style from v9) is optimized for the composition API. The composable mode is the style that uses `useI18n` to return `setup` function such as `t` as the render context.

The problem with the style of injecting globals become to be tight coupling to components.
Implicitly injecting APIs means that the component won't work without the plugin.

This is why we don't inject globally from `vue-i18n@v9`.

**Comment by Korijn** [comment]
OK, thanks for clarifying!
