### ISSUE TITLE
i18n.global.locale is not working after update legacy to be false.

### ISSUE THREAD

**Issue by MomenYasser** [intlify/vue-i18n-next#925]
### Reporting a bug?

After update legacy to be false i'm trying to change **i18n.global.locale** from inside Vuex action but it's not working.

### Expected behavior

After changing **i18n.global.locale** it should update all strings in the app.

### Reproduction

Please check line 44 here:
https://codesandbox.io/embed/vue-i18n-9-template-forked-nwkns?fontsize=14&hidenavigation=1&theme=dark

### System Info

```shell
System:
    OS: macOS 12.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 1.63 GB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.17.4 - ~/.nvm/versions/node/v14.17.4/bin/node
    Yarn: 1.22.17 - ~/.nvm/versions/node/v14.17.4/bin/yarn
    npm: 7.20.5 - ~/.nvm/versions/node/v14.17.4/bin/npm
  Browsers:
    Chrome: 98.0.4758.80
    Firefox: 95.0.2
    Safari: 15.2
  npmPackages:
    vue: ^3.0.0 => 3.2.29 
    vue-i18n: ^9.2.0-beta.30 => 9.2.0-beta.30 
    vue-router: ^4.0.0 => 4.0.12 
    vuex: ^4.0.1 => 4.0.2 
    vuex-composition-helpers: ^2.0.1 => 2.0.1
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/intlify/vue-i18n-next/blob/master/.github/CONTRIBUTING.md)
- [X] Read the [Documentation](https://vue-i18n.intlify.dev/)
- [X] Check that there isn't [already an issue](https://github.com/intlify/vue-i18n-next/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/intlify/vue-i18n-next/discussions)
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by PeterAlfredLee** [comment]
Hi， @MomenYasser  I think you should use `i18n.global.locale.value = "ja";`
try this:
```
setTimeout(() => {
        // WORKING <============
        i18n.global.locale.value = "ja";
      }, 5000);
```
https://codesandbox.io/s/vue-i18n-9-template-forked-g2r5t?file=/index.html:980-1092

**Comment by MomenYasser** [comment]
Thanks a lot it worked fine! 🙏
But it’s better to mention that in official docs.
