### ISSUE TITLE
When the key contains special symbolsm, ex:  ':., the $te function is always return false

### ISSUE THREAD

**Issue by liulei92** [intlify/vue-i18n-next#928]
### Reporting a bug?

const translationKey = "name: '123'";
const hasKey = this.$te(translationKey); // is always false
if (hasKey) {
    return this.$t(translationKey);
}
return translationKey; 

1.Have a translation setup (something like this):
"name: '123'":"name: '123'"
Use $te("name: '123'") to check for the key
It returns false

### Expected behavior

It should return true, because there is a 'Test translation' key. 

### Reproduction

"version": "9.2.0-beta.30",

### System Info

```shell
"version": "9.2.0-beta.30",
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/intlify/vue-i18n-next/blob/master/.github/CONTRIBUTING.md)
- [X] Read the [Documentation](https://vue-i18n.intlify.dev/)
- [X] Check that there isn't [already an issue](https://github.com/intlify/vue-i18n-next/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/intlify/vue-i18n-next/discussions)
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by PeterAlfredLee** [comment]
Hi, @liulei92 I think it was intentional. See the following test [cases](https://github.com/intlify/vue-i18n-next/blob/ede3da6faded4f6a990bf14c5e28f78147154eb7/packages/core-base/test/resolver.test.ts#L18) in vue-i18n-next repo.
> expect(parse('"')).toBeUndefined()
>expect(parse("'")).toBeUndefined()
>expect(parse('.')).toBeUndefined()

**Comment by kazupon** [comment]
As metion @PeterAlfredLee, we cannot use the key that is included in the double quotation. so for this reason, $te function returns false.

Thanks!
