### ISSUE TITLE
<i18n> tag not resolved

### ISSUE THREAD

**Issue by Quasarman** [intlify/vue-i18n-next#932]
### Reporting a bug?

Hello,

I wanted to use Component Interpolation as described here: https://vue-i18n.intlify.dev/guide/advanced/component.html
When trying to use the <i18n> tag inside by .vue files <template> section the tag does not seem to get resolved at all.

```
<template>
...
<i18n path="layouts.noInternetConnection" tag="span">
    <span class="text-secondary">{{ $t('common.labels.internet') }}</span>...
</i18n>
...
<template>
```
Becomes;
![image](https://user-images.githubusercontent.com/30523269/154810007-c26c232c-3ed7-42f0-a05f-4f03ca466bd7.png)

In browser:
![image](https://user-images.githubusercontent.com/30523269/154810270-a2e4929f-86c1-408d-bfc9-c4f9facb9257.png)

I am using quasar CLI and have tried following these guides: https://vue-i18n.intlify.dev/guide/advanced/sfc.html#quasar-cli
but after adding the described npm module and the sections to my quasar.conf chainWebpack section no translations work at all. Event the `$t('some.label')` will no longer perform a translation which worked before.

### Expected behavior

That the i18n tag gets resolved correctly into a span tag.

### Reproduction

Hope Ill find time to provide a reproduction repo.

### System Info

```shell
System:
    OS: Windows 10 10.0.19043
    CPU: (16) x64 AMD Ryzen 7 2700X Eight-Core Processor
    Memory: 15.10 GB / 31.92 GB
  Binaries:
    Node: 14.17.0 - C:\Program Files\nodejs\node.EXE
    npm: 6.14.13 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 98.0.4758.102
    Edge: Spartan (44.19041.1266.0), Chromium (98.0.1108.55)
    Internet Explorer: 11.0.19041.1202
  npmPackages:
    @intlify/vue-i18n-loader: ^4.1.0 => 4.1.0
    vue-advanced-cropper: ^2.7.1 => 2.7.1
    vue-i18n: ^9.2.0-beta.30 => 9.2.0-beta.30
    vue-observe-visibility: ^2.0.0-alpha.1 => 2.0.0-alpha.1
    vue-plugin-load-script: ^2.1.0 => 2.1.0
    vue-resize: ^2.0.0-alpha.1 => 2.0.0-alpha.1
    vue-showdown: ^3.1.0 => 3.1.0
    vuedraggable: ^4.1.0 => 4.1.0
    vuese: ^1.4.7 => 1.4.7
    vuex: ^4.0.2 => 4.0.2
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/intlify/vue-i18n-next/blob/master/.github/CONTRIBUTING.md)
- [X] Read the [Documentation](https://vue-i18n.intlify.dev/)
- [X] Check that there isn't [already an issue](https://github.com/intlify/vue-i18n-next/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/intlify/vue-i18n-next/discussions)
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Bob-Jung** [comment]
https://vue-i18n.intlify.dev/guide/migration/breaking.html#rename-to-i18n-tfrom-i18n

**Comment by Quasarman** [comment]
Darn...It seems like i have:
* Looked at the v8 config and just saw the `<i18n>` tag
* Not double checked the writing inside the v9 doc again...

Sorry about that and thanks for the help.
