### ISSUE TITLE
Global scope vs local scope and ts error

### ISSUE THREAD

**Issue by volarname** [intlify/vue-i18n-next#937]
### Clear and concise description of the problem

- add possibility to disable warning about global scope 'Not found parent scope. use the global scope'. its really annoying on bigger projects
- add posiibility to set i18n to use always global scope, so its not needed in each use of composable like this: `const { t } = useI18n({ useScope: 'global' })`
- fix ts error: `TS2589: Type instantiation is excessively deep and possibly infinite.` when this is used (usage outside of vue components in custom composables): `const { t } = i18n.global || i18n`

### Suggested solution

- add options to global config and fix

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/intlify/vue-i18n-next/blob/master/.github/CONTRIBUTING.md)
- [X] Read the [Documentation](https://vue-i18n.intlify.dev/)
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by kazupon** [comment]
Please make sure to read the [Issue Reporting Guidelines](https://github.com/intlify/vue-i18n-next/blob/master/.github/CONTRIBUTING.md#general-guidelines) before opening new issues. 

Thanks.
