### ISSUE TITLE
error: Not available in legacy mode

### ISSUE THREAD

**Issue by Ambince** [intlify/vue-i18n-next#953]
### Reporting a bug?

version:9.2.0-beta.31

example： const { t } = useI18n();    or     const { t } = useI18n({ useScope: 'global'})

error info:
message-compiler.esm-bundler.js:54 Uncaught (in promise) SyntaxError: Not available in legacy mode
    at createCompileError (message-compiler.esm-bundler.js:54:1)
    at createI18nError (vue-i18n.esm-bundler.js:100:30)
    at useI18n (vue-i18n.esm-bundler.js:2210:1)

### Expected behavior

use example is normal

### Reproduction

1

### System Info

```shell
nothing
```

### Screenshot

nothing

### Additional context

nothing

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/intlify/vue-i18n-next/blob/master/.github/CONTRIBUTING.md)
- [X] Read the [Documentation](https://vue-i18n.intlify.dev/)
- [X] Check that there isn't [already an issue](https://github.com/intlify/vue-i18n-next/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/intlify/vue-i18n-next/discussions)
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by XyoloJR** [comment]
If I understood correctly when you create i18n instance,  
it's now mandatory to set legacy option to false, if you want to use [composition API](https://vue-i18n.intlify.dev/guide/advanced/composition.html#basic-usage)

But if you still want have [legacy injection](https://vue-i18n.intlify.dev/guide/advanced/composition.html#implicit-with-injected-properties-and-functions), for instance to use $t in your templates
you have to specify this with `globalInjection: true` in the createI18n() options

**Comment by kazupon** [comment]
FYI:
vue-i18n v9.2-beta.32, `useI18n` is supported in legacy mode
https://vue-i18n.intlify.dev/guide/migration/vue3.html

Note that is limited, as noted in the documentation.

**Comment by Shinigami92** [comment]
@kazupon Is it expected that all usages of
```ts
const { t } = useI18n();
```
with `allowCompositoin: true` are now lazy?

Previously I needed just e.g.
```ts
console.log(t('mykey'))
```
Now I need at least
```ts
onBeforeMount(()=> {
  console.log(t('mykey'))
})
``` 

after `9.2.0-beta.31`+ many stuff broke in comparison to `9.2.0-beta.30` 😕

**Comment by kazupon** [comment]
@Shinigami92 
Yeah.
Unfortunately 😞 , `useI18n` on legacy mode is lazy because the legacy mode is implemented using of `beforeCreate` mixin. vue core cannot `setup` in mixin.
If we want to use `t` in the `setup` function directly not template, we need to wait on `nextTick` etc.
I'll add it to the docs as a limitation.

**Comment by Shinigami92** [comment]
I would like to say that I will stay on `9.2.0-beta.30` for now due to the breaking behavior
I will see how it will taken by the community and if they accept that breaking change when it arrives in `9.2.0`
