### ISSUE TITLE
Support fetching locales from api

### ISSUE THREAD

**Issue by SassNinja** [intlify/vue-i18n-next#957]
### Clear and concise description of the problem

If I understand the docs correctly, it's only possible to lazy load other locales via dynamic import: https://vue-i18n.intlify.dev/guide/advanced/lazy.html

This doesn't work for me because I don't have any json files but rely on getting the translations from an api. Furthermore I've got a lot of translations any don't wanna import everything for a given language but only load specific namespaces.

### Suggested solution

Support namespaces to avoid loading all translations (similar to i18next) and support fetching via http request (similar to https://github.com/i18next/i18next-http-backend)

### Alternative

Only alternative I can image (without using another framework) is downloading all data from the api in the (webpack) build process and emit it as json files though this would feel quite hacky and doesn't solve the namespace issue.

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/intlify/vue-i18n-next/blob/master/.github/CONTRIBUTING.md)
- [X] Read the [Documentation](https://vue-i18n.intlify.dev/)
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by adrai** [comment]
Something similar to [this](https://locize.com/blog/give-vue-i18n-more-superpowers/#superpowers)?

**Comment by Eddie344** [comment]
Need to add support for promises, it's block my nuxt3 migration

**Comment by kazupon** [comment]
From v9.3.0-beta.20, vue-i18n can be compile like JIT style.
so you can integrate back-end that has locale messages.
https://vue-i18n.intlify.dev/guide/advanced/optimization.html#jit-compilation

example is here
https://github.com/intlify/vue-i18n-next/tree/master/examples/backend

so close.
