### ISSUE TITLE
[BUG REPORT] feature flags only check type, but vite define is always string

### ISSUE THREAD

**Issue by YunYouJun** [intlify/vue-i18n-next#961]
### Reporting a bug?

In vite, `__DEFINE_VAR__` always be `string`.

https://github.com/vitejs/vite/blob/fde0f3c0e6e74a02e45ee0c0beb0ea774608e9a9/packages/vite/src/node/plugins/define.ts#L27

But `vue-i18n` use `typeof __FEATURE_FULL_INSTALL__ !== 'boolean'` to judge.

https://github.com/intlify/vue-i18n-next/blob/dab6db19a1ef917425939275a41dfde9b6c61fe9/packages/vue-i18n-core/src/misc.ts#L20

> @intlify/vite-plugin-vue-i18n can not solve this, so i report here.

### Expected behavior

Add `__FEATURE_FULL_INSTALL__ !== 'false'`

So i can use vite `define` to disable warnings.

<img width="633" alt="image" src="https://user-images.githubusercontent.com/25154432/158808159-cb8c5ac9-3503-4f5e-8ab1-13d93d96529c.png">

### Reproduction

The code is obvious.

### System Info

```shell
Vite v2.8.6
@intlify/vite-plugin-vue-i18n v3.3.1
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/intlify/vue-i18n-next/blob/master/.github/CONTRIBUTING.md)
- [X] Read the [Documentation](https://vue-i18n.intlify.dev/)
- [X] Check that there isn't [already an issue](https://github.com/intlify/vue-i18n-next/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/intlify/vue-i18n-next/discussions)
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by kazupon** [comment]
Thank you for reporting!
This issus is resolved v9.2.0 or later
If you would avoid this issue, you can use v9.2.0 latest version
(Note that v9.2 is currently beta)

Thanks!
