### ISSUE TITLE
is there a way to custom messageCompiler

### ISSUE THREAD

**Issue by moonRider** [intlify/vue-i18n-next#979]
### Clear and concise description of the problem

i have found `new Function` in code to compiler message, it's a dangerous method for my platform.

### Suggested solution

if i can define messageCompiler like follow code, it will solve my problem
```
createI18n({
   ...,
   messageCompiler,
})
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/intlify/vue-i18n-next/blob/master/.github/CONTRIBUTING.md)
- [X] Read the [Documentation](https://vue-i18n.intlify.dev/)
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by kazupon** [comment]
Thank you for your feedback :)

You should be able to resolve your issue by trying the following link
https://vue-i18n.intlify.dev/guide/advanced/optimization.html#improve-performance-and-reduce-bundle-size-with-runtime-build-only

so, you can use a bundler such as vite to resolve alias

If this does not solve your issue, please provide your minimal reproduction repo.
Then, please open another issue.

Thanks!

**Comment by moonRider** [comment]
thank you, it help me
