### ISSUE TITLE
Local scope does not work with Composition API

### ISSUE THREAD

**Issue by LasyIsLazy** [intlify/vue-i18n-next#986]
### Reporting a bug?

I used `useI18n({ locale: 'en' })` and set a `locale` option, but it doesn't work. The spread `locale` variable is still equals to the global one which is `ja`.

### Expected behavior

Local scope locale should be `en`

### Reproduction

https://github.com/LasyIsLazy/vue-i18n-local-locale-bug-demo

main.ts
```
import { createApp } from 'vue'
import { createI18n } from 'vue-i18n'
import App from './App.vue'

const messages = {
    ja: {},
    en: {}
}

const i18n = createI18n({
  legacy: false, // you must set `false`, to use Composition API
  locale: 'ja', // set locale
  fallbackLocale: 'en', // set fallback locale
  messages, // set locale messages
  // If you need to specify other options, you can set other options
  // ...
})


createApp(App).use(i18n).mount('#app')

```

App.vue
```
<template>
  global locale: {{locale}}
  <HelloWorld/>
</template>

<script lang="ts">
import { defineComponent } from 'vue';
import { useI18n } from 'vue-i18n';
import HelloWorld from './components/HelloWorld.vue';

export default defineComponent({
  name: 'App',
  components: {
    HelloWorld
  },
  setup() {
    const { locale } = useI18n()
    return { locale }
  }
});
</script>

```

HelloWorld.vue
```
<template>
  <div class="hello">
    local locale: {{locale}}
  </div>
</template>

<script lang="ts">
import { defineComponent } from 'vue';
import { useI18n } from 'vue-i18n';

export default defineComponent({
  name: 'HelloWorld',
  props: {
    msg: String,
  },
  setup() {
    const { locale } = useI18n({
      locale: 'en',
      messages: {
        en: {
          msg: 'hello',
          named: '{msg} world!',
          list: '{0} world!',
          literal: "{'hello'} world!",
          the_world: 'the world',
          dio: 'DIO:',
          linked: '@:dio @:the_world !!!!'
        },
        ja: {
          msg: 'こんにちは',
          named: '{msg} 世界！',
          list: '{0} 世界！',
          literal: "{'こんにちは'} 世界！",
          the_world: 'ザ・ワールド！',
          dio: 'ディオ:',
          linked: '@:dio @:the_world ！！！！'
        }
      }
    })


    return { locale }
  }
});
</script>

```

App.vue use global scope and HelloWorld.vue use local scope.

Result:
![image](https://user-images.githubusercontent.com/18400251/163552203-fcb2a530-8fb4-4580-a56e-3f8e9a26f679.png)

### System Info

```shell
System:
    OS: macOS 12.3.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 453.52 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.16.1 - ~/.nvm/versions/node/v14.16.1/bin/node
    npm: 8.5.5 - ~/.nvm/versions/node/v14.16.1/bin/npm
  Browsers:
    Chrome: 100.0.4896.88
    Chrome Canary: 102.0.5004.2
    Edge: 100.0.1185.39
    Firefox: 86.0.1
    Safari: 15.4
  npmPackages:
    @vue/cli-plugin-babel: ~4.5.13 => 4.5.17 
    @vue/cli-plugin-typescript: ~4.5.13 => 4.5.17 
    @vue/cli-service: ~4.5.13 => 4.5.17 
    @vue/compiler-sfc: ^3.0.0 => 3.2.33 
    vue: ^3.0.0 => 3.2.33 
    vue-i18n: ^9.1.9 => 9.1.9
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/intlify/vue-i18n-next/blob/master/.github/CONTRIBUTING.md)
- [X] Read the [Documentation](https://vue-i18n.intlify.dev/)
- [X] Check that there isn't [already an issue](https://github.com/intlify/vue-i18n-next/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/intlify/vue-i18n-next/discussions)
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by LasyIsLazy** [comment]
I found the reason: I forgot to add `inheritLocale: false` to `useI18n` options. After add that, local scope locale worked. This option just like `sync: false` in legacy  API.

**Comment by GhotiFish1078** [comment]
> I found the reason: I forgot to add `inheritLocale: false` to `useI18n` options. After add that, local scope locale worked. This option just like `sync: false` in legacy API.

😢 tysm kind stranger, I was bashing my head trying to figure out why my component was not using the right translation. Outside of the API reference, does the guide even mention to set ```inheritLocale: false```??
