### ISSUE TITLE
Fallback and empty strings in JSON-File

### ISSUE THREAD

**Issue by dspangenberg** [intlify/vue-i18n-next#995]
### Reporting a bug?

If a value in a JSON-file is empty, the fallback doesn't work and shows an empty String.

**main.js**
```js
const i18n = createI18n({
  locale: 'en',
  fallbackLocale: 'de',
  fallbackFormat: true,
  messages
})
```

**en.json**
```json
{
  "welcome": ""
}
```

**de.json**
```json
{
  "welcome": "Willkommen"
}
```

### Expected behavior

I excepted a fallback to the German JSON-File (Willkommen).

### Reproduction

https://github.com/dspangenberg/reproduction-i11n

### System Info

```shell
System:
    OS: macOS 12.3.1
    CPU: (8) arm64 Apple M1
    Memory: 80.83 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 18.0.0 - ~/.nvm/versions/node/v18.0.0/bin/node
    Yarn: 1.22.18 - ~/.nvm/versions/node/v18.0.0/bin/yarn
    npm: 8.6.0 - ~/.nvm/versions/node/v18.0.0/bin/npm
  Browsers:
    Chrome: 100.0.4896.127
    Safari: 15.4
  npmPackages:
    @intlify/vite-plugin-vue-i18n: ^3.4.0 => 3.4.0
    @vitejs/plugin-vue: ^2.3.1 => 2.3.1
    @vue/eslint-config-standard: ^6.1.0 => 6.1.0
    vite: ^2.9.6 => 2.9.6
    vue: ^3.2.33 => 3.2.33
    vue-i18n: ^9.1.9 => 9.1.9
```

### Screenshot

![image](https://user-images.githubusercontent.com/166466/165841112-6154db9d-9987-4468-b9ee-d98f353349c1.png)
![image](https://user-images.githubusercontent.com/166466/165842606-3d5b5999-b607-4e63-b35e-150c9cc4c956.png)

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/intlify/vue-i18n-next/blob/master/.github/CONTRIBUTING.md)
- [X] Read the [Documentation](https://vue-i18n.intlify.dev/)
- [X] Check that there isn't [already an issue](https://github.com/intlify/vue-i18n-next/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/intlify/vue-i18n-next/discussions)
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by dspangenberg** [comment]
Sorry, the screenshot are from the real project, and I've forgotten to remove them.

![image](https://user-images.githubusercontent.com/166466/165845611-b2393fff-2334-412f-87ad-f00cc68f1349.png)

**Comment by dspangenberg** [comment]
Sorry, wrong screenshots.
![image](https://user-images.githubusercontent.com/166466/165845754-f0d8d1f2-7ad8-4931-ae4e-71f427d015e6.png)

**Comment by kazupon** [comment]
Thank you for your feedback!

This is expected behavior.
vue-i18n v8 is the same behavior.
if vue-i18n v9 will be changed, it is a breaking change.
Generally, that is not good what empty string is set in i18n resources in localization workflow because the translator doesn't understand.

Thanks!
